### ISSUE TITLE
The wave probe shouldn't read lattice values in water side view.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#103]
The wave probe shouldn't read lattice values in water side view.

![image](https://user-images.githubusercontent.com/679486/44623334-1704a880-a888-11e8-8d48-eb45b4da31ec.png)

@arouinfar how do you want to address this?

**Comment by arouinfar** [comment]
@samreid in Java, the probe is restricted to the center line where the graph values are pulled from.  Could we do something similar here? 

![image](https://user-images.githubusercontent.com/8419308/44682354-5f46d680-aa00-11e8-9298-aeaf1abb0344.png)

**Comment by samreid** [comment]
Good find, that seems like a reasonable user experience.  I'm not convinced that this reaches one of our learning goals, but it would seem awkward if we hid the meter in side view, or something like that.    I'll give it a try.

**Comment by samreid** [comment]
Here's a few lines of code that can help me on this, to be added in WaveMeterNode.js

```js
      const initializeSeries = ( color, wireColor, dx, dy, connectionProperty ) => {
        const centerProbe = () => {
          probeNode.y = view.waveAreaNode.centerY + 38; // TODO: can this offset be eliminated?  Why is it necessary?
        };
        const probeNode = new WaveMeterProbeNode( {
          color,
          drag: centerProbe
        } );
```

However, before I go any further, I'd like to hear the recommended approach for dealing with the probes when the water view is already in the side view and the wave sensor meter is dragged out of the toolbox.  Should the probes travel with the probe until it is released?  Until it reaches the wave area?  Should the probes jump to the y=0 line as soon as the meter is dragged out of the toolbox?

@arouinfar what do you recommend?

**Comment by arouinfar** [comment]
Great questions @samreid. In general, I think the probes should jump to the center line (x-coordinate stays the same) when switching to Side View. I can think of two basic scenarios.

1. Wave Detector is already in the play area, and the user switches to Side View. The probes should change their y-coordinate and “jump” vertically to the horizontal line.

![image](https://user-images.githubusercontent.com/8419308/44933682-9d5d3680-ad2f-11e8-8f05-5a357f809c24.png)
![image](https://user-images.githubusercontent.com/8419308/44933695-a3ebae00-ad2f-11e8-8589-f674b3a68869.png)

2. In Side View, the user pulls out the Wave Detector. Once the tool is released, the probes jump up to the center line.

![image](https://user-images.githubusercontent.com/8419308/44933720-ba920500-ad2f-11e8-8c85-017f4b08373d.png)
![image](https://user-images.githubusercontent.com/8419308/44933726-c1b91300-ad2f-11e8-8b08-86af61d23a82.png)

**Comment by samreid** [comment]
I added the behavior described in the preceding comment.  While working on this, I noted new problem  https://github.com/phetsims/wave-interference/issues/122 (not sure if caused by this or unrelated).  @arouinfar can you please review and close if all is good for this issue?

**Comment by arouinfar** [comment]
@samreid this is looking really nice! Everything looks good, so closing.
