### ISSUE TITLE
What color should the sound particle view background be?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#106]
I chose #4c4c4c which looks like:

![image](https://user-images.githubusercontent.com/679486/44675973-30743480-a9ef-11e8-96d5-ddcedc498b4c.png)

@arouinfar do you think we should change that background color?  If so, can you recommend a color value?

**Comment by arouinfar** [comment]
@samreid I like the background color, but I would change the gray particles to white (or a lighter gray such as `rgb(240, 240, 240)` if white is too stark) to improve the contrast.

**Comment by arouinfar** [comment]
Hold that thought... I should also think about the contrast against the wave-view.
![image](https://user-images.githubusercontent.com/8419308/44682920-f4969a80-aa01-11e8-8da9-0cf232df8411.png)

@samreid I'll play with the colors a bit more and get back to you.

**Comment by arouinfar** [comment]
@samreid can we try lightening up the particles a bit? Let’s use the gray I suggested earlier, `rgb(240, 240, 240)` and add a thin black stroke around the particles. The lighter gray should have better contrast against the darker grays used for the minimas and Particle View background, while the black stroke should maintain decent contrast against the brigher wave minimas.

**Comment by samreid** [comment]
I made the recommended changes.  In my opinion, it's a bit difficult to see the gradient shading on the particles with such a bright rgb.  I like the stroke though.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
@samreid, I really like the stroke!! The gradient is indeed a bit hard to see, so perhaps we should darken the gray a smidge more, say `rgb(210,210,210)`?

**Comment by samreid** [comment]
I added the new color, please review on phettest.

**Comment by arouinfar** [comment]
Looks good, thanks!

**Comment by arouinfar** [comment]
Seems like @kathy-phet may have some thoughts about the colors, so I'll reopen and tag for design meeting.

**Comment by kathy-phet** [comment]
I like it, but thanks for checking! I think its nice that it sort of matches the wave peak color, and I agree the high contrast is good.

**Comment by arouinfar** [comment]
Great, thanks @kathy-phet!
