### ISSUE TITLE
Deal with particles on slits screen

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#109]
On the slits screen we need to either (a) make sure they don't pass through walls or (b) don't allow showing particles on the slits screen.  (b) would be much easier, but then you cannot see the plane waves as particles, which looks pretty neat (not a learning goal though).

**Comment by samreid** [comment]
I estimate implementing hard-sphere collisions or a forcing function for the wall would take 2-8 hours for the initial version.  Then there would be some added complexity for maintenance, and making sure particles look good elsewhere on the slits screen.  It would take around 15 minutes to hide the sound particles on the sound scene, plus additional time to decide how the control panel should look, see https://github.com/phetsims/wave-interference/issues/113#issuecomment-416878740

I'd prefer to hear from the design team before starting on either of these approaches.

**Comment by samreid** [comment]
Design meeting: ok to try bouncing off or repelling from the wall.

**Comment by samreid** [comment]
I added this code to BarriersNode to get the model coordinates for the barrier rectangles:

```js
// TODO: move the rects to the model
if (scene===this.model.soundScene){
  window.rects = [

    this.modelViewTransform.viewToModelBounds( new dotRectangle( this.x, this.waveAreaViewBounds.top, this.cellWidth, y1 - this.waveAreaViewBounds.top ) ),
    this.modelViewTransform.viewToModelBounds( new dotRectangle( this.x, y2, this.cellWidth, this.waveAreaViewBounds.bottom - y2 ) )
  ];
}
```

Then in SoundParticle.js I added this code for bouncing the particles away from the barrier:

```js
// if the particle entered or crossed the barrier, bounce it back out
if ( window.rects ) {
  for ( let i = 0; i < window.rects.length; i++ ) {
    var rect = window.rects[ i ];
    rect = rect.dilated( 3 );
    if ( rect.containsPoint( new Vector2( this.x, this.y ) ) ) {
      this.vx = -this.vx;
      this.vy = -this.vy;
      this.x += this.vx * dt;
      this.y += this.vy * dt;
      this.x += this.vx * dt;
      this.y += this.vy * dt;
    }
  }
}
```

The quick hack above detects if the center of a particle is in the wall, then reverses its velocity and steps it again.  This leads to a lot of jittery behavior around the wall and this won't work for a final solution.

The problems I ran into are:
(a) there is no model representation of the barrier regions
(b) there is no model representation of the particle radius

Once those are added, I do not see a trivial way to add a forcing function that will bounce the particles off the wall (say with a new potential term).  We would likely need to detect collision and reflect the appropriate component of the velocity vector (probably with some coefficient of restitution).  Also, we would need to detect the case where a particle passes the wall in one time step.  So this could be more like 1-2 days to complete a first draft.  We will need to discuss if this is where we want to spend our time.

**Comment by samreid** [comment]
We decided to only show particles in screen 1 and 2.

**Comment by samreid** [comment]
Commit pushed and this is ready for review.  @arouinfar can you please check through the first three screens and make sure particles and associated controls appear nicely on "Waves" and "Interference" but not "Slits"?

**Comment by arouinfar** [comment]
👍
