### ISSUE TITLE
Move ScrollingChartNode to griddle

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#111]
From https://github.com/phetsims/wave-interference/issues/24.

On Thursday, we decided this can move as ES6.  I should also create a griddle example.

**Comment by samreid** [comment]
I've moved ScrollingChartNode to griddle and added an example demo for it.  Next steps are (a) reuse it for bending light and (b) code review.  I'm inclined to exercise it in bending light before the code review so that we can be more sure that it has the right feature set or so it can be generalized as appropriate.

**Comment by pixelzoom** [comment]
The griddle BarChart demo looks like an excellent opportunity to use VSlider, since the sliders control bar height.   Currently:

![screenshot_746](https://user-images.githubusercontent.com/3046552/45060207-3c4d9f80-b05c-11e8-9a4d-e390a6fc87e9.png)

**Comment by samreid** [comment]
The HSliders were introduced in https://github.com/phetsims/griddle/commit/6f1477b5831fae95996ffa7c0d4b26df76c0c5d1, I'll create a griddle issue.
