### ISSUE TITLE
Checkbox and aqua radio button hit areas should extend to the right

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#112]
Checkbox and aqua radio button hit areas should extend to the right, as they do with Vertical*Group

**Comment by samreid** [comment]
Simply using `VerticalCheckBoxGroup` did not solve this problem, because those touch areas only extend as far as the longest aqua radio button text--not across the entire panel.  That being said, there's a good chance this problem will be eliminated/alleviated by design changes like https://github.com/phetsims/wave-interference/issues/113#issuecomment-416878740.  Placing on hold until #113 is discussed.

**Comment by samreid** [comment]
VerticalAquaRadioButtonGroup does not give control over the touch area of the items--I may need to just create my own AquaRadioButtons.

**Comment by arouinfar** [comment]
> I may need to just create my own AquaRadioButtons

@samreid wouldn't it be better to add touch area control to `VerticalAquaRadioButtonGroup`? They are ubiquitous in sims, as is the desire to extend the touch areas.

**Comment by arouinfar** [comment]
> is this something critical for 1.0 of Wave Interference?

Probably not @samreid. So long as the radio button are useable for touch, I don't think we need to be worried about this particular issue in sun.
