### ISSUE TITLE
Is there a better way to cue that some options only apply to some scenes?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#113]
Now that we are moving towards a set of 3 radio buttons for the "Sound" scene (see #108) and we already have two checkboxes that only apply to the "Light" scene, I'm wondering if there is a better user interface convention to signal that the "waves/particles/both" radio buttons only apply to Sound and "Screen/Intensity" only applies to light.  It will help to move the "Graph" checkbox to the top since it applies to all scenes (I'll make a new issue for that), but I'm wondering if there's a better UI approach we can take for this.  For example, the scene radio buttons could stack vertically, and the relevant options could be next to the scene radio button.  Or maybe it is already clear enough, and graying out/ungraying is sufficient.  One possibility would be to interview on the graying out, and see if that is working OK.  I'm not sure how much a precedent we have for this in other simulations.

@arouinfar what do you think?

**Comment by samreid** [comment]
After completing the two issues linked above, the control panel looks pretty bad ("checkbox and radio button soup"):

![image](https://user-images.githubusercontent.com/679486/44776097-80104880-ab34-11e8-8d94-74418ecd3f16.png)

I suspect, but am not sure, that this issue could be part of better segmenting those controls.  Also, note that after converting to use VerticalAquaRadioButtonGroup, the sound radio buttons no longer support enabled/disabled.  This aspect will be addressed in https://github.com/phetsims/wave-interference/issues/117

**Comment by samreid** [comment]
I put together a quick redesign of this component, to try to pair the scene-specific options with the scene:

![image](https://user-images.githubusercontent.com/679486/44776933-7f78b180-ab36-11e8-963a-4e87e80462ef.png)

Note that the water "side view" and "top view" should be grayed out because that scene is not selected.  (It's just a quick sketch to test the overall layout).

What works well about this: it makes it clear which controls go with which scene.  It also provides a natural place for the water side/top view, which would correspondingly be removed from the play area.

What doesn't work well, or would need improvements in this design: First, the water "top" view is not available in the 2nd and 3rd screens, and the space to the right of the water radio button could look odd if it was just blank.  Second, there is less horizontal space to accommodate strings for longer languages (though it seems there is still some space to grow).  Assigned to @arouinfar for discussion, though I imagine this may be a good issue to discuss at design meeting this week.

**Comment by samreid** [comment]
@arouinfar is going to mock up an idea for this.

**Comment by arouinfar** [comment]
In yesterday’s design meeting we decided that only the relevant options would appear for each scene. 

Water: Graph checkbox
Sound: Graph checkbox, radio button group for waves/particles/both
Light: Graph, Screen, and Intensity checkboxes

![image](https://user-images.githubusercontent.com/8419308/44933773-f0cf8480-ad2f-11e8-8645-1ec23e040e06.png)

**Comment by samreid** [comment]
@arouinfar those mockups look great.  I wonder if it will also work well for screen-readers or accessibility in general?  Will we need to make special considerations for that, like keeping the non-visible UI components in the scene graph?  Should we check in with an a11y designer or developer before getting started?

**Comment by terracoda** [comment]
@samreid and @arouinfar my sense if they are visually no there then they can also be completely hidden in the PDOM. If they are visually greyed-out (i.e., disabled and visually still on the screen) they should be findable/navigable in the PDOM, but communicated as disabled.

Generally speaking, we try to achieve a similar experience both visually and non-visually.

**Comment by samreid** [comment]
Thanks @terracoda.  Assigning to myself to start working on these controls as designed in https://github.com/phetsims/wave-interference/issues/113#issuecomment-417776557 (though not starting on the a11y specific parts yet).

**Comment by samreid** [comment]
Changes pushed, @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
Thanks @terracoda! 

Everything is looking good to me @samreid. Thanks!
