### ISSUE TITLE
Show some slight random motion even there is no wave, since we are not at absolute zero.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#115]
From #39, 

> [we should be] showing some slight random motion even there is no wave, since we are not at absolute zero.

**Comment by samreid** [comment]
This commit referenced the wrong issue:

https://github.com/phetsims/wave-interference/commit/0cf2fe2ffac1efa0c1bb6be2e5cc37c43f90474e

> Added random motion to the sound particles

**Comment by samreid** [comment]
@arouinfar I added a random force at each time step.  I tuned the random force magnitude low enough that the random motion did not wash out the wavefronts, but high enough that the random motion wasn't too slow.  Can you please review on phettest and let me know your thoughts?  Close if everything seems OK.  Or let me know if you want me to change the algorithm or random force magnitude.

**Comment by arouinfar** [comment]
@samreid overall, it's looking pretty good. I do wonder if the oscillations are just a tad too large or fast. That's said, let's discuss with the team on Thursday before spending any more time on this.

**Comment by samreid** [comment]
We agreed this looks good, closing.  If we need to turn down the randomness to get a crisp wave, we will do so, but we'll aim for something like this.
