### ISSUE TITLE
Pulse sends out many sound particle wavefronts

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#116]
Pulse currently looks like this:

![image](https://user-images.githubusercontent.com/679486/44749204-1742b500-aacf-11e8-8e2a-5ff106dfe1de.png)

It's kind of difficult to see in the picture, but there are many smaller waves after the initial wave crest.  This effect may be reduced once #115 is addressed.

**Comment by samreid** [comment]
Placing on hold until #115 is addressed, in case it resolves this issue.

**Comment by samreid** [comment]
Removed hold since there is a proposed solution for #115.

**Comment by samreid** [comment]
This is still problematic after adding the random motion.  I wonder if we need to have a smoother pulse function, one that asymptotes toward zero (instead of a pure sine wave)?  Labeled for design meeting to decide how to proceed.

**Comment by samreid** [comment]
This could be a phase problem, I'll check if that's the problem.

**Comment by samreid** [comment]
According to this comment, we had adjusted the phase so that water drops wouldn't appear while the water was very high:
```js
      // The phase was adjusted so that when the water is turned on under default circumstances, a drop doesn't appear
      // right above the water.
```

However, it seems much more important that the wave begin and end at a=0 instead of starting partway through the phase, so I'll revert that.

**Comment by samreid** [comment]
Even after this change, there is still some "ringing" in the wave values.

**Comment by samreid** [comment]
After fixing the initial phase, I also zeroed out the pulse for an additional 1/2 period, and that seems to have reduced the ringing significantly.  This is dev.26:

![image](https://user-images.githubusercontent.com/679486/45568332-91866f80-b819-11e8-813d-3249857258ab.png)

This is current master:
![image](https://user-images.githubusercontent.com/679486/45568341-9b0fd780-b819-11e8-994d-4c524c7ab912.png)

@arouinfar can you please review this on phettest?

**Comment by samreid** [comment]
On the other hand, you can still see a few "echoes" in the sound view pulse.

![image](https://user-images.githubusercontent.com/679486/45568438-e4602700-b819-11e8-98c2-f803b498dc8f.png)

This is not easy to test now because there is interference from in-progress work in the water model.  Assigning to myself until easier to test.

**Comment by samreid** [comment]
OK, ready for testing.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
The pulses are looking waaaaay smoother, thanks @samreid!
