### ISSUE TITLE
Slow motion ruins the waves on the right hand side of the slits

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#120]

**Comment by samreid** [comment]
The problem is that the lattice wave propagation step is discrete, and running every time the model updates (independent of dt).  I foresee solutions like these:

1. track an "elapsed time since last lattice step" in WavesScreenModel, and only update it when it should be updated.   This may be accomplished manually or with another EventTimer (though stacking EventTimers sounds "tricky")
2. change the `EVENT_RATE` so the `ConstantEventModel` only calls `advanceTime` every so often.  This would be very simple and guaranteed to be correct physics.  But would lose some fidelity in the non-lattice measurements.

**Comment by samreid** [comment]
It would be best to consult with @jonathanolson about how to proceed.  @jonathanolson is there a way to change the event rate for `EventTimer.ConstantEventModel`?  What approach do you recommend?

**Comment by jonathanolson** [comment]
Maybe just create your own "event model" that returns whatever the period should be?

**Comment by samreid** [comment]
Thanks @jonathanolson that is working great.  After fixing the event model, I changed the event rate from 1/3 to 1/2 and it looked much better in my opinion.  @arouinfar can you please review slow motion on phettest?  Close if all is well.

**Comment by arouinfar** [comment]
Slow motion is looking good @samreid.
