### ISSUE TITLE
A sim to potentially leverage if we make a wave addition sim

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/wave-interference#121]
A google user wrote:    

> Would PhET be interested in hosting/having this HTML5 wave superposition simulation?
> 
>     Download it from: 
> 
>        https://sites.google.com/a/kirbyx.com/waveadd/
>     It adds two waves and shows the result. The wavelength, frequency, speed, and shape (transverse or longitudinal) can be changed on the fly, and the sim has presets (beat, constructive, destructive, standing wave). There are no library dependencies, adverts, cookies; it's one small HTML file (about 170k).
>     It's had very good feedback so far.

This sim has some elements we have considered for a future sim, but it would certainly need lots of redesign to follow PhET conventions and such. Something to keep in mind for future.

**Comment by samreid** [comment]
@arouinfar @ariel-phet or @oliver-phet, is there a more appropriate place to keep this idea?  Do we have a brainstorming list of ideas for new sims, or something like that?

**Comment by arouinfar** [comment]
I think @oliver-phet has a Google sheet to keep track of new sim ideas.

**Comment by oliver-phet** [comment]
This has been recorded in our sim suggestions spreadsheet.
