### ISSUE TITLE
Sometimes the wave meter node pops out of the toolbox at an odd location

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#122]
Discovered during https://github.com/phetsims/wave-interference/issues/103, dragging it out of the toolbox multiple times causes it to pop out at odd offsets.

**Comment by samreid** [comment]
I haven't been able to reproduce this problem again.  @arouinfar can you please test it out on phettest and see if you see anything odd?

**Comment by arouinfar** [comment]
@samreid I didn't run into this issue while testing #103. Let's go ahead and close it, and if we run into this issue again, we can re-open.
