### ISSUE TITLE
Disable Intensity checkbox when Screen is off

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#125]
In reviewing #113, I realized that it's possible to view the Intensity graph without also having the Screen on. A did a quick search of this repo and didn't find a related issue, though I did find this in the April 12 meeting notes:

> Intensity graph by itself doesn’t make a lot of sense. It needs mapping to the pattern

@samreid do you remember any previous discussion of this issue?

It seems natural that the Intensity checkbox should be deactivated (grayed out) if Screen is off. A similar approach has been taken in other sims for parent/child checkboxes. For example, the Electric Field/Direction Only checkboxes in CAF.

![image](https://user-images.githubusercontent.com/8419308/45117561-2fd84e00-b113-11e8-8380-5af062e1e44b.png)
![image](https://user-images.githubusercontent.com/8419308/45117575-3961b600-b113-11e8-9a97-0b08295e9ff8.png)

**Comment by samreid** [comment]
Proposed fix is above, @arouinfar can you please review it on screens 2-3 on phettest?

**Comment by arouinfar** [comment]
👍
