### ISSUE TITLE
Prevent crashing on iPad 2

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#128]
The simulation shouldn't crash on iPad 2.  I'll investigate how frequently it crashes and whether there is a way to crash less.

**Comment by samreid** [comment]
@jessegreenberg has been investigating Energy Skate Park: Basics crashing on iPad 2 in this issue: https://github.com/phetsims/energy-skate-park-basics/issues/435

**Comment by samreid** [comment]
Launching built version on iPad2: 
opens without crashing after about 15 seconds.
Stay on homescreen without crashing for 10 seconds.
Click into waves screen 1 and run waves for 10 seconds.
Switch to interference screen and run waves for 10 seconds
Switch to slits screen and run waves for 10 seconds
Switch to diffraction screen and scrub sliders for 10 seconds
No crash yet.

Launching built version on iPad2 with ?fuzzMouse
Crash at 48 seconds after launch

Launching built version on iPad2 with ?fuzzMouse (2nd run)
Crash at 90 seconds after launch

(3rd run)
Crash at 130 seconds after launch

**Comment by samreid** [comment]
Several minutes of fuzz testing on Mac Chrome does not reveal a memory leak:
![image](https://user-images.githubusercontent.com/679486/45695251-483a6680-bb1e-11e8-9b8e-d86d907bd7fa.png)

**Comment by samreid** [comment]
I investigated crashing on Energy Skate Park: Basics in https://github.com/phetsims/energy-skate-park-basics/issues/435#issuecomment-422424628 to see if I could find out what the crashing correlates with.  But it is very difficult to discern correlations or how we could reduce the problem.  Is the behavior acceptable for now?  I also have asked a question in https://github.com/phetsims/energy-skate-park-basics/issues/435#issuecomment-422446774 about whether the crashing pattern is the same in the app as it is in mobile safari.

**Comment by samreid** [comment]
In the aforementioned issue, we switched from hundreds of shaded sphere nodes to using one canvas. It likely impacts the memory usage, so I should run more crash tests.

**Comment by samreid** [comment]
On hold until dev testing.

**Comment by samreid** [comment]
Launching a built version with `?fuzz` on iPad air is still showing no problems after 3 minutes.  That seems good enough to close this issue.  We can reopen or create supplemental issues if related problems are discovered during dev or RC testing.

**Comment by samreid** [comment]
Oops, after closing I realized this issue is about iPad 2, not iPad air.  Leaving open for further investigation.

**Comment by samreid** [comment]
More than 5 minutes of fuzzing on a built version on iPad 2 with no issues (except the fuzzing is notably sluggish).  This may have been helped by recent PhET-iO IO type memory fixes, or omitting the fourth screen.  In either case, this seems good enough to close this issue, and we can reopen if other problems are found in subsequent dev or RC testing.

**Comment by samreid** [comment]
Testing dev.51 on iPad2 today I observed a crash.  I subsequently restarted safari, cleared other apps and was able to tap through every screen and every scene and use the simulation for >3 minutes with no crashing.  But this sim uses around 60MB of memory, so it could be susceptible to crashing on iPad2.  I'll see how far fuzzing goes at the moment.

**Comment by samreid** [comment]
I can shave off 2.4MB (from 59.5MB to 57.1MB) in requirejs mode with assertions disabled by only declaring PhetioObject properties if PHET_IO_ENABLED.  This is pretty hackish though because some of the properties such as tandem and linkedElements, need to be defined anyways, so the solution looks haphazard.

**Comment by samreid** [comment]
Some thoughts:

1. I don't want to send this sim to dev testing if we think we are going to redo a lot of the implementation focusing around memory savings.
2. On the other hand, requesting QA dev testing focused on iPad 2 memory and crashing may be good to help us determine whether the sim is acceptable or better understand the nature of the crashing.
3. Let's say we determine that the sim is crashing too frequently on iPad 2 and we cannot publish.  Then we need to do one of the following:

a) reduce general memory usage without changing functionality--maybe we can find parts of common code or the sim heap that are too bulky and can be reduced.  However, it would be unfortunate if this pushes us toward implementing things in less maintainable ways.
b) reduce feature set.  It would be unfortunate if we had to start dropping features in order to stay below a memory threshold.  For instance, commenting out the WaveMeterNode saves 5MB total.  Another option we could pursue is to somehow figure out a way to publish each screen as its own sim and use those on iPad 2 (I have no idea how we could do that in practice and it would be an inferior user experience).

I fuzz tested Graphing Quadratics 1.0 on this same iPad2 to test for crashing profile, as a comparison.
First crash at 15 seconds
Second test, still no crashes fuzzing after 15 minutes
For reference, Graphing Quadratics weighs about 40MB and Wave Interference weighs about 60MB.

One last point--if we add a fourth screen to Wave Interference, the memory usage is just going to increase.  For instance, right now each screen weighs around 20MB.  If we can get this to around 15MB per sim, we would have around the same memory footprint as graphing quadratics.  Then if we add another screen, this will just push us back where we started.

Another possibility--that the crash is due more to memory thrashing (allocation and deallocation) than it is to static size.  If that proves to be the case, we could work toward reducing allocations during the runtime of the sim, but this would generally entail changing toward less maintainable code.

@ariel-phet what do you think and how do you recommend to proceed?

**Comment by samreid** [comment]
Another possibility: even though the allocated canvas sizes don't show up on the heap, they may still contribute to iPad 2 crashing.  It would lead to very hackish code but we could try creating only one LatticeCanvasNode and passing it to each screen.  I'm not sure how layering would work or if scenery still allocates multiple `<canvas>` elements in that case.  It could take a few hours to test this out and may or may not work.

**Comment by samreid** [comment]
Notes from discussion with @ariel-phet:

* dev.51 ran on Ariel's iPad 2 for >5 minutes under normal usage with no crashing.
* We will be dropping support for iPad 2 soon, probably before Wave Interference 2.0 is released
* Equality Explorer weighs in at 70MB
* We will give to the QA team and ask to keep an eye out for crashing.
* If the sim happens to crash sometimes (but not all the time) on iPad 2, this wouldn't prevent publication of 1.0.

**Comment by samreid** [comment]
@KatieWoe were there any iPad 2 tests run during the dev test?  Here is a note from the dev request:

> In addition to the general QA Dev testing, please test crashing conditions on iPad 2. How long can you use the sim before it crashes? Does any particular conditions lead to crashing? Please test multiple trials and report results at phetsims/wave-interference#128. Per @ariel-phet's direction, take a little bit of time exploring this, but not too long.

**Comment by KatieWoe** [comment]
I did some testing for about 7 - 10 minutes and did not see any crashes. @samreid

**Comment by samreid** [comment]
Sounds good, thanks for testing, closing.
