### ISSUE TITLE
Arrange red particles in a grid

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#129]
@ariel-phet pointed out that the random layout of the red particles looks haphazard, and it could be more helpful if they were arranged more carefully.  I'll create a dev version with this change for us to evaluate.

**Comment by samreid** [comment]
I tried a grid with `( soundParticle.i % 5 === 0 || soundParticle.k % 5 === 0 )` and it looked like this:

![image](https://user-images.githubusercontent.com/679486/45398836-f74cde80-b602-11e8-88ea-c72cd8f43ab4.png)

Should I try stripes instead of a grid?  Or a more or less dense grid?

**Comment by ariel-phet** [comment]
@samreid I think a less dense grid. Something closer to the corner of each of those squares

**Comment by samreid** [comment]
Of course, that makes much more sense.  Something like this?

![image](https://user-images.githubusercontent.com/679486/45398976-907bf500-b603-11e8-8553-db9d3f9aac6a.png)

**Comment by ariel-phet** [comment]
@samreid yes, something more like that. However, it would be good to pull the red particles in a bit from the edges. So for instance, in the screen shot above the red particles are very close to the edge on the bottom and right sides (most obviously). I think basically just reduce the grid spacing a bit, so there is some more negative space between the edges of the viewing window and the red particles.

**Comment by samreid** [comment]
I changed it from "every 5th particle starting at the 0th particle" to "every 6th particle starting at the 1st particle" and it looked like this:

![image](https://user-images.githubusercontent.com/679486/45569256-3bff9200-b81c-11e8-95c7-c38d5dd79c95.png)

I noted the preceding comment suggested to reduce the spacing, so I tried "every 4th particle, starting at the 2nd particle" and it looked like this:

![image](https://user-images.githubusercontent.com/679486/45569352-854fe180-b81c-11e8-95be-2bddfd80e609.png)

Either of these looks fine to me, I'll commit the latter.  This is difficult to test right now since there is interference from the water drop model--leaving self assigned to address that.

**Comment by samreid** [comment]
After https://github.com/phetsims/wave-interference/commit/b239eb2fbf62524a46e6aec20001aae387cf2a4f this is ready for testing, @ariel-phet and @arouinfar can you please take a look on phettest?

**Comment by ariel-phet** [comment]
@samreid I toook a look at master, and I think this current implementation looks quite good. I think this change is a nice upgrade and definitely feels more "purposeful" in my opinion than the random arrangement of red particles.

@arouinfar can make the final call, but looks fully polished to me.

**Comment by arouinfar** [comment]
Looks great @samreid!
