### ISSUE TITLE
Barriers should be absorbing instead of reflecting.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#13]
The barriers in the model currently force the lattice values to constant value of 0, this has the effect of reflecting the waves.  Instead we would prefer that the barriers (say, for the double slit) absorb the wave instead of reflect it--this will help students focus on the interference on the opposite side of the slits instead of the complex reflective pattern on the incident side of the slits.

I've implemented a dampening algorithm on the perimeter of the wave area (offscreen), but it takes many rows and columns and still creates artifacts.

@ariel-phet and @kathy-phet suggested that @veillette may have ideas about how to implement absorption.  What do you think @veillette?

**Comment by samreid** [comment]
Brainstorming: perhaps at lattice cells near the barrier we could use asymmetrical neighborhoods for updating the wave.  For instance, lattice cells just to the left of the barrier would not use values in the barrier as part of their neighborhood sum.  Perhaps this would prevent the reflection?

**Comment by samreid** [comment]
@jonathanolson or @ariel-phet how is the open boundary condition implemented in Wave on a String?

**Comment by jonathanolson** [comment]
WOAS uses step[ n - 1 ] and step[ n ] to compute step[ n + 1]. It modifies some of the boundary values before/after the step, seen in WOASModel (anything referring to typeEndProperty).

**Comment by veillette** [comment]
In physics and electric engineering, impedance matching is used to minimize reflection of signals. 
https://en.wikipedia.org/wiki/Reflections_of_signals_on_conducting_lines

This is used in coax cable to prevent the reflection of a signal. The end of the line is terminated with a resistor.  One might think that you would like a high resistance, but it turns out that the resistance of the terminal resistor must match the impedance of coax cable. It shouldn't be too high or too low.

Because the sim is simulating the propagation of wave (even if it is discretizing it)  the same physics, should apply.  

I need to think more about it to go beyond ideas and toward a workable implementation.

**Comment by samreid** [comment]
Here's the relevant code from Wave on a String:

```js
      switch( this.typeEndProperty.get() ) {
        case'looseEnd':
          this.yNow[ this.nSegs - 1 ] = this.yNow[ this.nSegs - 2 ];
          break;
        case'noEnd':
          this.yNow[ this.nSegs - 1 ] = this.yLast[ this.nSegs - 2 ];
          break;
        default: //'fixedEnd'
          this.yNow[ this.nSegs - 1 ] = 0;
      }
```

I can see the difference in the code but I don't understand the conceptual difference between `noEnd` and `looseEnd`.

**Comment by jonathanolson** [comment]
Also this at the end of the step:
```js
      switch( this.typeEndProperty.get() ) {
        case'looseEnd':
          this.yLast[ this.nSegs - 1 ] = this.yNow[ this.nSegs - 1 ];
          this.yNow[ this.nSegs - 1 ] = this.yNow[ this.nSegs - 2 ];
          break;
        case'noEnd':
          this.yLast[ this.nSegs - 1 ] = this.yNow[ this.nSegs - 1 ];
          this.yNow[ this.nSegs - 1 ] = this.yLast[ this.nSegs - 2 ]; // from a comment in the old model code?
          // from the Flash model: this.yNow[this.nSegs - 1] = this.yNow[this.nSegs - 1];//this.yLast[this.nSegs - 2];
          break;
        default: //'fixedEnd'
          this.yLast[ this.nSegs - 1 ] = 0;
          this.yNow[ this.nSegs - 1 ] = 0;
      }
```
Off the bat I also don't know the exact concepts being used, I'd have to sort through it a bit.

**Comment by samreid** [comment]
Since we can use the strategy from #11 to simulate the incoming wave, we will not need to implement absorbing barriers, closing.
