### ISSUE TITLE
Use spread operator for augmenting children array

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#131]
Discussed during https://github.com/phetsims/phet-info/issues/82

**Comment by samreid** [comment]
@jonathanolson can you please skim the preceding commit and confirm if that is the recommended approach?

**Comment by jonathanolson** [comment]
Yes, looks good, although I would combine
```js
          ...( options.showAmplitudeSlider ? [ amplitudeTitle ] : [] ),
          ...( options.showAmplitudeSlider ? [ amplitudeSlider ] : [] ),
```
into
```js
          ...( options.showAmplitudeSlider ? [
            amplitudeTitle
            amplitudeSlider
          ] : [] ),
```

**Comment by samreid** [comment]
Good call, thanks!  I tried the formatting you recommended but it looked odd in context, so I went with a single line instead.  Closing.
