### ISSUE TITLE
Use rasterization for creating icons

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#132]
Discovered while working on https://github.com/phetsims/capacitor-lab-basics/issues/242, may be a simpler way of creating icons.

**Comment by samreid** [comment]
Working great after above commits.  The change to MeasuringTapeNode should code reviewed as part of the code review of the simulation.  Labeling for review and hold until then.

**Comment by samreid** [comment]
@jonathanolson: I was surprised that `rasterized` included the bounds of invisible children.  Is that as expected?  My workaround is to remove the children, then rasterize, then re-add the children.

**Comment by jonathanolson** [comment]
It's expected, but this could be changed to include only visible bounds. It will cost a bit more CPU up front, but since the rasterization is probably slower than the bounds computation (and we usually don't do that in inner loops) I think it's generally worth it.

I'll plan to make this change.

**Comment by samreid** [comment]
Sounds great, thanks!  Keep me posted and when it's ready I'll use it to simplify Wave Interference toolbox icon creation.

**Comment by jonathanolson** [comment]
Should be handled with the above changes. Can you verify the behavior?

**Comment by samreid** [comment]
This change did not appear to work, or I am misunderstanding something.  With current master, I see this for the rasterized measuring tape node bounds:

![image](https://user-images.githubusercontent.com/679486/45568755-afa09f80-b81a-11e8-9605-7ad983b10fd7.png)

After changing MeasuringTapeNode.setTextVisible from

```js
this.valueContainer.children = visible ? [ this.valueBackgroundNode, this.valueNode ] : [];
```
to
```js
this.valueContainer.visible = visible;
```
I see this behavior:
![image](https://user-images.githubusercontent.com/679486/45568797-d232b880-b81a-11e8-9b67-ebdeb0684fdc.png)

It appears it is still using the bounds of the invisible nodes, or I am misunderstanding something.  @jonathanolson can you please take a look?

**Comment by jonathanolson** [comment]
Oops, need to patch one more part of it.

<img width="1071" alt="screen shot 2018-09-20 at 11 49 23 am" src="https://user-images.githubusercontent.com/480878/45836961-685b5880-bccb-11e8-8c2e-f7c89a9577a9.png">

Can you test now?

**Comment by samreid** [comment]
Looks great, I'm now getting the same behavior through `children=` and `visibility=`.  Leaving self-assigned to fine-tune the layout.

**Comment by samreid** [comment]
I created a new issue for that part, closing.
