### ISSUE TITLE
Check the single slit equation with an query parameter overlay.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#134]
From https://github.com/phetsims/wave-interference/issues/74

**Comment by samreid** [comment]
@arouinfar can you please review and test this on phettest, using the `?theory` query parameter?

**Comment by arouinfar** [comment]
@samreid the physics appears correct to me.

I had other worries concerning the graph scaling and screen saturation, but those issues are being discussed elsewhere, so I will close this issue.
