### ISSUE TITLE
Add spatial averaging for the chart overlay

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#137]
We would like to try spatial averaging for the chart in order to wash out the extrema near the source, see https://github.com/phetsims/wave-interference/issues/58

**Comment by samreid** [comment]
I changed the value read like so:
```
const value = i > 0 && i < array.length - 1 ? ( array[ i ] + array[ i - 1 ] + array[ i + 1 ] ) / 3 : array[ i ];
```
and it looked like this:

![image](https://user-images.githubusercontent.com/679486/45426774-60ac0c00-b65a-11e8-9615-f615a1dde8a9.png)

It's kind of pointy at the source because we are only averaging over the lattice cells, not over the graph coordinates.  Not sure if this is a good stopping point or if we should investigate further.  

Tagging for design meeting to see if this is good or if it requires further investigation.

**Comment by samreid** [comment]
We would like to suppress the wave source without averaging or altering the other points.

**Comment by samreid** [comment]
Here's a 5-point average over the 3 points nearest the source:

![image](https://user-images.githubusercontent.com/679486/45703594-0b786a80-bb32-11e8-9311-f49e1d4d1222.png)

```js
      for ( let i = 0; i < array.length; i++ ) {
        const isSourcePoint = i === WaveInterferenceConstants.POINT_SOURCE_HORIZONTAL_COORDINATE - WaveInterferenceConstants.LATTICE_PADDING;
        const isSourcePointL = i === WaveInterferenceConstants.POINT_SOURCE_HORIZONTAL_COORDINATE - WaveInterferenceConstants.LATTICE_PADDING - 1;
        const isSourcePointR = i === WaveInterferenceConstants.POINT_SOURCE_HORIZONTAL_COORDINATE - WaveInterferenceConstants.LATTICE_PADDING + 1;
        const value = isSourcePoint ? ( array[ i ] + array[ i - 1 ] + array[ i + 1 ] + array[ i - 2 ] + array[ i + 2 ] ) / 5 :
                      isSourcePointL ? ( array[ i ] + array[ i - 1 ] + array[ i + 1 ] + array[ i - 2 ] + array[ i + 2 ] ) / 5 :
                      isSourcePointR ? ( array[ i ] + array[ i - 1 ] + array[ i + 1 ] + array[ i - 2 ] + array[ i + 2 ] ) / 5 :
                      array[ i ];
        const x = Util.linear( 0, array.length - 1, waveAreaBounds.left, waveAreaBounds.right, i ) + dx;
        const y = WaveInterferenceUtils.getWaterSideY( waveAreaBounds, value ) + dy;
        shape.lineTo( x, y );
      }
```

I'd like to compare this to a 3-point average directly on the source (no neighbors).

**Comment by samreid** [comment]
Here's a 3-point average only on the source:

![image](https://user-images.githubusercontent.com/679486/45723281-c40fcf80-bb6d-11e8-9ee7-fc08771719b8.png)

Here's a 3-point average on the source combined with 2 point averages for the source's neighbors:

![image](https://user-images.githubusercontent.com/679486/45723360-1bae3b00-bb6e-11e8-9de0-9aa01d820257.png)

**Comment by samreid** [comment]
I pushed a commit that uses single-point averaging at the source.  @arouinfar can you please pull and test it out?

**Comment by arouinfar** [comment]
Looks great @samreid!
