### ISSUE TITLE
Will the amplitude/frequency controls and toolbox be on the left?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#14]
Will the amplitude/frequency controls and toolbox be on the left?  I thought we decided to move them to the left to make room for the screen on the right, but I don't see that documented in today's notes.

**Comment by arouinfar** [comment]
@samreid my impression was that we would try moving the wave source and viewing window to the left, but wouldn't necessarily move amplitude and frequency controls. I have a meeting with KP and AP this afternoon, so I'll double check with them and report back.

**Comment by arouinfar** [comment]
@samreid I don't think we'll be able to move the amplitude/frequency controls to the left. On the Interference screen, there will be two sources with variable separation, which will require a column of space reserved for just the sources.

![image](https://user-images.githubusercontent.com/8419308/37066628-8eb59bb6-2163-11e8-9926-f8b18dbc07ef.png)

I am, however, working on shifting the wave viewing window further left to accommodate the screen/intensity graph for the light scene.

**Comment by arouinfar** [comment]
@samreid please feel free to close if you don't have any further concerns.
