### ISSUE TITLE
Try Canvas for showing the SoundParticleLayer

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#145]
This is a good candidate for canvas because the particles cannot be interacted with individually.  This will help with iPad performance.

**Comment by samreid** [comment]
Maybe double check that this is essential by testing performance on iPad air before converting it.

**Comment by samreid** [comment]
iPad Air is hitting 60fps for the sound scene, but it drops to 3-4fps when showing the particles.

**Comment by samreid** [comment]
CanvasNode looks great and Waves Screen/Speaker/Particles is running at 60fps on iPad Air.  @arouinfar can you please check that the particle layout and rendering still looks as good as before?

Also, this change likely affects the memory usage of the sim, so iPad 2 crashing may be more or less likely now.  It will need testing.  See #128.

**Comment by arouinfar** [comment]
@samreid I compared master to dev.28 on the iPad Air, and things are running so much smoother on master!! I am noticing a bit more aliasing of the particles in master, however. Is there anything that can be done to sharpen them a bit? 

master:
![img_0181](https://user-images.githubusercontent.com/8419308/45779347-00980580-bc18-11e8-8516-88b375713d6a.PNG)

dev.28:
![img_0182](https://user-images.githubusercontent.com/8419308/45779346-00980580-bc18-11e8-84de-e6993a6a6350.PNG)

**Comment by samreid** [comment]
I increased the sound particles resolution in the preceding commit, and it seems crisper on my Mac Chrome.  @arouinfar can you please test on the same platform you reported above?

**Comment by arouinfar** [comment]
Looking much crisper @samreid! The performance on iPad Air seems pretty comparable to before, too. 

![image](https://user-images.githubusercontent.com/8419308/45787468-c9831d80-bc32-11e8-850b-df23a4c5e914.png)

Not sure if anything else needs to be done for this issue, so I'll kick it back to you @samreid.

**Comment by samreid** [comment]
Thanks, nothing else for this issue, closing.
