### ISSUE TITLE
Speaker separation range and default is too small

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#146]
After we increased the wave area size in https://github.com/phetsims/wave-interference/issues/39 we did not correspondingly adjust the position of the dual speakers.  Perhaps I should put this on hold until #39 is decided.

**Comment by samreid** [comment]
For example, here is the default:

![image](https://user-images.githubusercontent.com/679486/45587179-871eb100-b8bf-11e8-8e4c-5c7e3aa034e6.png)

**Comment by samreid** [comment]
I pushed a proposed fix, would be good for @arouinfar to review default values and ranges for each of the emitter types.

**Comment by arouinfar** [comment]
@samreid the separation ranges and defaults look good to me!
