### ISSUE TITLE
Prepare a stable, somewhat polished version by Friday afternoon

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#148]
@ariel-phet said we will be demoing a version on Monday Sept 24, and added:

> It would be good to have a stable dev version at the end of this week to demo (and let me know any known bugs).
> 
> I think it might be worth doing a quick pixel polish session to make things look a bit more tidy (I know there are some very large slider thumbs and such), although not a big deal.

I think we'll be meeting on Thursday Sept 20, so perhaps we can polish pixels then.  After our meeting we'll determine what else should be done before creating a dev version, and what level of testing we would like to do for it.

**Comment by arouinfar** [comment]
Here's a screenshot of the preliminary pixel-polishing. I'll enumerate the changes tonight/first thing tomorrow @samreid.

![image](https://user-images.githubusercontent.com/8419308/45851589-f8fc5d80-bcf8-11e8-9e43-5af7425b1c55.png)

**Comment by samreid** [comment]
@arouinfar your proposed mock-up looks great, thanks.  I captured many of the changes, not sure if I got them all.  I'll commit and can you please review and make recommendations?

**Comment by samreid** [comment]
Also, I'm not sure if I have icons for the scene radio buttons, can you check if they have been shared, particularly for the speaker?  Perhaps we should leave the hose icon as a hose to match with the play area since we won't have time to change that by end of business.

**Comment by arouinfar** [comment]
@samreid that was fast! The scene buttons in my mockups are old, and were just meant to communicate size/colors, so no need to change those any further. For the purpose of the site visit, I think the pixels have been sufficiently polished. :)

@ariel-phet can you take a look at master?

**Comment by samreid** [comment]
Maybe it would be best for me to publish a dev version, then it if checks out we can use it without having to re-test it.

**Comment by samreid** [comment]
Here's a dev version: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.30/phet/wave-interference_en_phet.html

**Comment by samreid** [comment]
@ariel-phet and I worked together to fine tune other layout issues and published a new dev version:
https://github.com/phetsims/wave-interference/issues/148

Known issues:
1. On the diffraction screen, we would like the left panel to show the aperture rather than showing the gaussian.  This is a more complex change and I indicated about a 10% chance I can get to this in time.
2. On the diffraction screen, the 3rd scene "lines" does not have the correct behavior.  I could remove this option for Monday if desired.
3. On the slits screen, there is a flickering in the leading edge of the plane wave.
4. The water drops model is fairly new and I'd be surprised if there are no bugs in it.  For instance, turning on the water drops, then switching scenes, then turning off the source (or other sequences like that) may not have the intended behavior.

I recommend thoroughly testing this dev version before using it for a presentation.  Please also be aware of other open issues.  Also, thanks both @arouinfar and @ariel-phet for helping to pixel polish, the sim feels much nicer now!

**Comment by samreid** [comment]
From slack:

Sam Reid [1:15 PM]
Should I remove the “lines” option from the diffraction screen?  I think right now it’s only showing numerical artifacts and not showing any physics.


Ariel Paul [1:45 PM]
That seems reasonable for the moment

**Comment by samreid** [comment]
I pushed a new dev version that omits the "lines" option from the diffraction screen: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.33/phet/wave-interference_en_phet.html

**Comment by arouinfar** [comment]
@samreid dev.33 looks good to me!  

A few more caveats/reminders for @ariel-phet's demo
* The particle view of sound is still in progress. The wavefronts are particularly weak at low-frequencies, and we still need to tune the model parameters to ensure better coordination between particle/wave views, but for the most part, things look about right.
* There's a slight misalignment between the wave in the lattice and the wave in the graph, though not particularly noticeable unless you're looking for it. See #143.
* Play with single-slit diffraction to find  a good case to demo. A wider slit width of 2-3x wavelength tends to look a bit better, particularly with blue and violet frequencies.
