### ISSUE TITLE
Measuring Tape looks off-center

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#150]
![image](https://user-images.githubusercontent.com/679486/45858115-16d9ba80-bd19-11e8-9869-63c5def29af5.png)

From #132.

**Comment by samreid** [comment]
I swapped out the Measuring Tape icon with a blue rectangle with the same dimensions and it came out like this:

![image](https://user-images.githubusercontent.com/679486/46024461-14be8580-c0a4-11e8-8305-41580b992e72.png)

Perhaps the problem lies elsewhere?

**Comment by samreid** [comment]
align:top came out like this:

![image](https://user-images.githubusercontent.com/679486/46024544-45062400-c0a4-11e8-8047-9865b7413c1a.png)

So it seems the other nodes have incorrect bounds.

**Comment by samreid** [comment]
@jonathanolson can you please help me figure out what's causing the incorrect dimensions for these icons?  The code is in wave-interference/js/common/view/ToolboxPanel.js

**Comment by jonathanolson** [comment]
Commit is https://github.com/phetsims/scenery/commit/710ecf689ae8aa03a356737d017fdfaf123db009 (forgot to tag).

**Comment by samreid** [comment]
Looks great @jonathanolson, thanks!  Closing.
