### ISSUE TITLE
Particles lag behind wave crests

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#153]
https://github.com/phetsims/wave-interference/issues/39

![image](https://user-images.githubusercontent.com/679486/46172111-cb1a9a00-c25f-11e8-80e0-2e2468111a9c.png)

**Comment by samreid** [comment]
We may be able to address this with the controls introduced in https://github.com/phetsims/wave-interference/issues/157 for parent issue https://github.com/phetsims/wave-interference/issues/39

**Comment by samreid** [comment]
This is on hold pending tuning in #158

**Comment by samreid** [comment]
Tuning in #158 is complete, @arouinfar can you please double check specifically regarding particles lagging the wave crests?  If all is well, please close.

**Comment by arouinfar** [comment]
The particles and waves are now well-matched. Thanks @samreid!
