### ISSUE TITLE
Bug when changing frequency when paused

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#154]
During yesterday's design meeting, we saw a problem that was created like so:

1. set frequency to max
2. pause
3. set frequency to min
4. Press step many times

This led to a buggy behavior in the water drops and wave area.

**Comment by samreid** [comment]
Proposed fix committed above, and the instructions in the issue description work nicely now.  The flip side of this coin is that when changing from low frequency to high frequency, the simulation waits until one wave cycle is complete before sending the next drop.  @arouinfar can you please test the water drop frequency in a variety of contexts and see if there is any other incorrect behavior related to these changes?

**Comment by arouinfar** [comment]
@samreid thanks for the explanation. That makes more sense to me now, and I agree that it's an improvement. 

The behavior actually seems pretty natural if you switch between min/max frequency while the sim is not paused.
