### ISSUE TITLE
Update water drop artwork

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#155]
In yesterday's design meeting, @kathy-phet suggested darkening the water drop artwork (originally discussed in #15) so it's a bit easier to see against the gray background in the side-view. 

<img src="https://user-images.githubusercontent.com/8419308/46220854-ac241280-c308-11e8-81c8-e9e48fdb45ad.png" width=200>

@samreid here are the updated the assets. I'll delete the .ai file from Drive once it's committed.

[water_drop.ai](https://drive.google.com/file/d/1kuNBLIIy-F5BnrUq49SXTciTQHMu41hX/view)
[water_drop.png](https://user-images.githubusercontent.com/8419308/46220797-7f6ffb00-c308-11e8-8c29-de72077d9065.png)

**Comment by samreid** [comment]
Committed and pushed, can you please review on phettest?

**Comment by arouinfar** [comment]
I think the updated drop (left) has better contrast against the wave/gray than the original drop (right). Thanks @samreid!

![image](https://user-images.githubusercontent.com/8419308/46492847-f9eac000-c7cb-11e8-845a-3e8558bb57c6.png) ![image](https://user-images.githubusercontent.com/8419308/46492863-066f1880-c7cc-11e8-9dec-e87a8e8b189e.png)

![image](https://user-images.githubusercontent.com/8419308/46492920-2f8fa900-c7cc-11e8-9694-8d3b7e374200.png) ![image](https://user-images.githubusercontent.com/8419308/46492929-34545d00-c7cc-11e8-94cc-88be776feb01.png)
