### ISSUE TITLE
Tune the sound particle physics

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#158]
In #39 we moved to a new sound particle physics model which computes a local gradient on the lattice to use as the force on the sound particle.  In #157 we added controls to explore the parameter space.  The next step is for Wave Interference design team members @kathy-phet @ariel-phet @samreid @arouinfar @KatieWoe to experiment with a dev version to find good combinations of free parameters:
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.34/phet/wave-interference_en_phet.html?dev

Please write back if I need to change the range on any of the control (UPDATE: or if I forgot to add a control).  Also, keep in mind we would like the particles to "keep up" uniformly with the wave as described in #153.  Furthermore, keep in mind that we have the option to choose different sets of parameters as a function of frequency and then to interpolate between them.  Using this tool, I proposed new initial values that seem reasonable for mid + max frequency.  In my brief exploration, I found it important to turn down the "home force" to 2.0 or less for the min frequency.  But please don't let my initial investigation dissuade you from your own search.

**Comment by KatieWoe** [comment]
Preliminary findings for me.  It looks like the best results come from decreasing gradient force and increasing home force a frequency gets higher.  Haven't found any numbers that look exactly right yet, but it might be a good place to start.

**Comment by KatieWoe** [comment]
My suggestions for now, though they could definitely still use some tweaking.
Randomness = 12 and Friction = .85 for all.
Low Frequency: Home Force = 2 and Gradient Force = 130
Medium Frequency: Home Force = 4 and Gradient Force = 99.5
High Frequency: Home Force = 6.5 and Gradient Force = 63

**Comment by arouinfar** [comment]
@KatieWoe these values have been a big help, thank you!

Since @KatieWoe's recommendations for medium frequency were nearly at the midpoint of the high/low values, I decided to test the exact midpoints, and found now appreciable difference. I think a linear scaling would work just fine.

For high frequency, I found the gradient force to be a bit too low (wavefronts generally looked pretty faint in particle-only view), so I bumped it up a bit. I found that 76 looked about right.

@samreid I would recommend

|Frequency|Randomness|Home Force|Friction|Gradient Force|
|---|---|---|---|---|
|Low|12|2|0.85|130|
|High|12|6.5|0.85|76|

The midpoint of these values looks good for medium frequency, so I think we can use a linear mapping.

**Comment by samreid** [comment]
In the preceding commit, I applied the linear scaling described in the preceding comment.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
Looks great @samreid!

**Comment by arouinfar** [comment]
In light of #182, we need to re-tune to particle parameters.

**Comment by arouinfar** [comment]
@samreid have you published a dev version since #182 was addressed? If not, can you publish one for the parameter re-tuning?

**Comment by samreid** [comment]
I published https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.41/phet/wave-interference_en_phet.html.  Before taking time to tune the sound particle physics, we should verify that we are happy with the min/max/default wavelengths of sound--were they disturbed when https://github.com/phetsims/wave-interference/issues/182 was fixed?

**Comment by samreid** [comment]
After changing the range of sound frequencies in https://github.com/phetsims/wave-interference/issues/182#issuecomment-436457162

I published a new dev version here: 
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.42/phet/wave-interference_en_phet.html

**Comment by arouinfar** [comment]
@samreid the ranges in the ?dev controls look a bit off. In particular the max values for the home force and gradient force are far too low. I'm also not sure what (if anything) to do with the CUTOFF value.

dev.34
<img src="https://user-images.githubusercontent.com/8419308/48221550-a67e0b80-e34f-11e8-8802-77802fe80711.png" width=200>

dev.42
<img src="https://user-images.githubusercontent.com/8419308/48221579-b1d13700-e34f-11e8-822b-5be1217c13f9.png" width=200>

**Comment by samreid** [comment]
Based on a cursory inspection, @arouinfar and I agreed on these starting values.  I'll publish a dev version with these and @arouinfar can fine tune:

high frequency
14.75
0.8
0.725
1.01

min frequency
14.75
1.05
0.740
1.12

**Comment by samreid** [comment]
I added the values above and made some additional adjustments (so values in the preceding comment won't match exactly with new controls), and I expanded the slider ranges for further tuning.  Here's a dev version: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.43/phet/wave-interference_en_phet.html

@arouinfar can you please take a look and adjust further as necessary?

**Comment by arouinfar** [comment]
@samreid here are my recommendations. The wavefronts still aren't as crisp as they were before, but the particle/wave views are well-aligned.

|Frequency|Randomness|Home Force|Friction|Gradient Force|
|---|---|---|---|---|
|Low|10|1.00|0.70|1.15|
|High|10|0.70|0.70|0.85|

**Comment by samreid** [comment]
Thanks @arouinfar.  Before going ahead and making changes to accommodate the newly recommended values, I wanted to compare to the values proposed in https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.43/phet/wave-interference_en_phet.html and make sure the changes are desirable.

Here's a gif that shows the max frequency case.  On the left are the values proposed in dev.43 and on the right are the values proposed in https://github.com/phetsims/wave-interference/issues/158#issuecomment-437979819.  

This shows the wave fronts from from dev.43 (on the left) are more crisp than the proposed values (on the right), which have broader wave crests.
![crisp2](https://user-images.githubusercontent.com/679486/48367700-bf97fc80-e66e-11e8-9240-0004d7d9e906.gif)

I'll post another gif in the next comment that shows correspondence between particles/wave view.

**Comment by samreid** [comment]
This image shows the "both" view so we can check the correspondence between the particles and the lattice.  On the left are the values proposed in dev.43 and on the right are the values proposed in https://github.com/phetsims/wave-interference/issues/158#issuecomment-437979819 (high frequency case only)

![waves](https://user-images.githubusercontent.com/679486/48367894-55338c00-e66f-11e8-87bf-8db5818a26fd.gif)

In my opinion, both have a good correspondence between particles and lattice canvas.  The one on the left has the advantage of crisper wave fronts.  Please review and advise.

**Comment by arouinfar** [comment]
@samreid the .gifs for dev.43 certainly do have a crisper wavefront. When running dev.43 with `?dev`, the values didn't quite match https://github.com/phetsims/wave-interference/issues/158#issuecomment-437366575, which is why I probably (unnecessarily) tinkered with the values. 

I reviewed dev.43 again, and the particle view is looking pretty good to me, and certainly better than https://github.com/phetsims/wave-interference/issues/158#issuecomment-437979819. 

Let's go with the dev.43 values @samreid. Not sure if that's what's in master, so reassigning to you.

**Comment by samreid** [comment]
There were refactorings, but no other intentional physics changes in SoundParticle.js since dev.43.  Closing for now.
