### ISSUE TITLE
The light screen shouldn't saturate so early.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#161]
See #152 

![image](https://user-images.githubusercontent.com/679486/46501147-e0547300-c7e1-11e8-9eb2-83cdcf3dd689.png)

We would like to turn down the scale factor in the light screen so it doesn't saturate too early.  It will not be coupled to the intensity chart scale.

**Comment by samreid** [comment]
Here is the default configuration on the interference screen:

![image](https://user-images.githubusercontent.com/679486/46551603-6f6e9300-c895-11e8-8091-7fed3acf2fe3.png)

That does seem oversaturated as well, though not as bad as the case @arouinfar described.  Perhaps the problem is partly that the plane wave magnitude is too high?

**Comment by samreid** [comment]
The previous scaling value was 7, I reduced it to 1 and found it was too low for this default case (nothing reached max).  A level of 2 seemed OK, though it reveals some artifacts at the edges that we were previous "wallpapering" over.

![image](https://user-images.githubusercontent.com/679486/46552023-9a0d1b80-c896-11e8-98e0-3d11151e5841.png)

I'll test this for plane waves.

**Comment by samreid** [comment]
Changing this saturation point also has the effect of increasing the width of the minima on the screen.

**Comment by samreid** [comment]
The scaling factor of 2 yields a yellow pattern like this:

![image](https://user-images.githubusercontent.com/679486/46552170-1c95db00-c897-11e8-9dba-3841d24e0c42.png)

@arouinfar can you please comment?  Is this better? Do you recommend a different scaling factor?  Or a query parameter so you can experiment with different values yourself?

I'll commit the change from 7 => 2 to master so you can review on phettest.

**Comment by arouinfar** [comment]
@samreid I think a scale factor of 5 is looking pretty good!

In general the secondary maxima are visible, but appropriately dim.
<img src="https://user-images.githubusercontent.com/8419308/46696299-183b2c00-cbcf-11e8-9df8-757d9b27fa5c.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/46696346-2ee18300-cbcf-11e8-8185-cce372e718ad.png" width=300>

There's still a bit of over-saturation going on here, but I think it's an improvement over https://github.com/phetsims/wave-interference/issues/161#issue-366957705.
<img src="https://user-images.githubusercontent.com/8419308/46696465-67815c80-cbcf-11e8-813c-6969ac2c4b10.png" width=300>

The range of brightnesses also seem pretty good for double-slit.
<img src="https://user-images.githubusercontent.com/8419308/46697157-40c42580-cbd1-11e8-8678-dd6495ffacee.png" width=300>

What's not so great is the saturation for a single source. I'm also seeing some apparent maxima and minima on the screen, which I've moved to #171.
<img src="https://user-images.githubusercontent.com/8419308/46697235-6a7d4c80-cbd1-11e8-9a0c-bc14d4ac6495.png" width=300>

Currently, I find the brightness on the Waves screen to be a bit too dim. In Java, the screen brightness was on par with the wave maxima, which I'd like to maintain, if possible.
![image](https://user-images.githubusercontent.com/8419308/46697754-94833e80-cbd2-11e8-8091-a19e6af34f79.png)

Some options would include:
1. separate mapping on the Waves screen
2. logarithmic brightness scaling

Option (1) seems preferable, as the brightness is looking good for the interference cases. I'll tag for further discussion at design meeting.

**Comment by samreid** [comment]
Another possibility would be to remove the Light Intensity Screen from the first screen of the sim.

**Comment by arouinfar** [comment]
>  Another possibility would be to remove the Light Intensity Screen from the first screen of the sim.

Yes, that too. Actually @ariel-phet and I had briefly discussed that option, but it slipped my mind when replying. I actually would prefer to remove the screen altogether, as I'm not sure what pedagogical purpose it serves on the Waves screen.

**Comment by samreid** [comment]
Yesterday, we decided we would like to keep the Light Intensity Screen on the first screen of the sim.  We may need a multiplier on that intensity screen, or larger intensity waves so they will match the rest of the sim.

**Comment by arouinfar** [comment]
@samreid do you want to defer this issue until #171 is addressed, or is this separate enough?

**Comment by samreid** [comment]
It seems we can decide on this separately.  The artifacts we see on #171 shouldn't change the magnitudes (unless we opt for a wave damping solution which changes the overall magnitude at the right hand side).

**Comment by arouinfar** [comment]
Sound good @samreid. Given that the screen saturation is looking really good for interference, I'm hesitant to completely change things and go with a logarithmic mapping. I think it would make more sense to come up with a separate solution for the Waves screen, such as the intensity multiplier. I'll defer to @samreid's judgement on this, though.

**Comment by samreid** [comment]
I'd like to experiment with both (a) changing the source amplitude and (b) changing the screen multiplier.

**Comment by arouinfar** [comment]
Sounds good @samreid.

**Comment by samreid** [comment]
To clarify on the problem, the maximum amplitude of the oscillator on the "Waves" screen is 10, the same as the amplitude of the oscillators on the other screens.  The light intensity screen gradient was fine tuned for constructive interference of two 10-amplitude oscillators.  So perhaps that means we need to increase the amplitude on the 1st screen to compensate (or reduce amplitude on the interference and plane wave screen).

I tried changing the range from 0-10 to be 0-16 and put the initial value at 80% (same percent as before), and the light intensity screen fills up OK (note there is still the model artifact problem noted in https://github.com/phetsims/wave-interference/issues/171 )

![image](https://user-images.githubusercontent.com/679486/47313612-97335a00-d5fc-11e8-8f4a-8c925945283e.png)

Note that this change by itself un-calibrates other things, such as the size of water drops, here is the default size with the change above and no other corresponding changes:

![image](https://user-images.githubusercontent.com/679486/47313652-b4682880-d5fc-11e8-9171-9c05d87cb96d.png)

So I'd like to check in with @arouinfar.  It seems the right thing to do is to recalibrate the amplitude of the source emitters, but I wanted to coordinate with you about whether to increase the Waves screen oscillation amplitude or decrease the Slits and Interference oscillation amplitude, and what other parts of the simulation should be re-calibrated to compensate.

**Comment by arouinfar** [comment]
I'd like to experiment with this locally so I can see things in action. 

Over Slack, @samreid said:
> Easiest is to change the "max" on this line: https://github.com/phetsims/wave-interference/blob/70b76742b9c90dba6faaf572a96cf0f81affb953/js/waves/model/WavesScreenModel.js#L204

**Comment by arouinfar** [comment]
Changing the amplitude range does improve the screen saturation, but it also has some other effects that's we'll need to address. The color mapping will look a bit different, and the graph will need to be rescaled. Here's an initial test I did:

| max=10 (current) | max=13 | max=16 |
|---|---|---|
|<img src="https://user-images.githubusercontent.com/8419308/47468538-0c4b8e80-d7b9-11e8-8d7d-d38ff5938da5.png" width=200>|<img src="https://user-images.githubusercontent.com/8419308/47468592-559bde00-d7b9-11e8-9849-31bf56bceccb.png" width=200>|<img src="https://user-images.githubusercontent.com/8419308/47468545-1a011400-d7b9-11e8-99fd-bf4af6d5ff09.png" width=200>|

After further conversation with @samreid, I've decided to wait until he has the chance to talk with Mike Dubson about #171. There might not be a clear solution to #171, so we may live with the interference in the chart. If that's the case, we can consider a Hollywooded screen for the Waves screen.

**Comment by samreid** [comment]
Perhaps we should continue with #171 before deciding on this

**Comment by samreid** [comment]
I was able to make some incremental improvements in #171, and now the default one-source red light case looks like this:

![image](https://user-images.githubusercontent.com/679486/49019791-01837100-f14c-11e8-8c99-57f572e4d7aa.png)

@arouinfar can you please advise?

**Comment by arouinfar** [comment]
@samreid I think the screen on Waves is far too dark. I'd recommend bumping up the max to 13, as shown in https://github.com/phetsims/wave-interference/issues/161#issuecomment-433144883. I'd experiment locally, but it looks like the code's undergone some restructuring.

**Comment by samreid** [comment]
You can now experiment by changing the range on this line:

https://github.com/phetsims/wave-interference/blob/32024a437466e638985214dad1d1aa8cc69d1f7a/js/common/model/Scene.js#L158

However, do we want to just change the scaling on the screen, or change the true amplitude of the oscillator?  I was unclear whether we were just tinkering with the amplitude to determine what the screen should look like, so that we could apply a screen-specific scaling later.

If you do prefer to change the range of oscillation from (0,10) to (0,13), then what should the new initialAmplitude be?  Current initialAmplitude is 8 as defined here:

https://github.com/phetsims/wave-interference/blob/29fcbf1393069a4277f656933804d5311ddc4e71/js/waves/model/WavesScreenModel.js#L68-L72

Please advise.

**Comment by arouinfar** [comment]
>  I was unclear whether we were just tinkering with the amplitude to determine what the screen should look like, so that we could apply a screen-specific scaling later.

Good point @samreid. I think an intensity multiplier on Waves would be preferable. I'm pretty happy with how the current amplitude range looks in the lattice, as well as on the screens for Interference and Slits. Some other side effects of changing the amplitude values:
* Water drop size would end up larger
* There would be an odd mapping of tick marks to actual values in the amplitude slider
* The majority of amplitude values would still map to a really dark screen on Waves

That said, I can still experiment with the amplitude range locally, but I'm not sure how helpful it would be if we end up going down the multiplier route.

**Comment by samreid** [comment]
Proposed fix increases scaling on screen 1 to 1.85.  Default light looks like this, other screens unaffected. 

![image](https://user-images.githubusercontent.com/679486/49129815-74950080-f28e-11e8-8117-4195d3df6f26.png)

 @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
@samreid I think that's definitely an improvement. Unfortunately, brightening up the screen makes the interference pattern on the screen more apparent.  I'm also a bit worried that the screen is SO much dimmer than the plane wave source. In both cases, the wavelength is the same, but the color in the lattice also looks very different. Can you take a look @samreid?


<img width="500" alt="screen shot 2018-11-28 at 11 26 39 am" src="https://user-images.githubusercontent.com/8419308/49181346-5d98f180-f314-11e8-83bf-9868f706c1b0.png">
<img width="500" alt="screen shot 2018-11-28 at 11 26 33 am" src="https://user-images.githubusercontent.com/8419308/49181345-5d98f180-f314-11e8-8960-ed7716f879a7.png">

**Comment by samreid** [comment]
> Unfortunately, brightening up the screen makes the interference pattern on the screen more apparent.

As part of https://github.com/phetsims/wave-interference/issues/197 I've averaged over some of that noise and it is looking cleaner.

> I'm also a bit worried that the screen is SO much dimmer than the plane wave source. In both cases, the wavelength is the same, but the color in the lattice also looks very different. Can you take a look @samreid?

The amplitude of the point source and the amplitude of the plane waves have been set independently to reach different goals for those screens.  Should we take efforts to redesign that and try to unify them?  If not, then maybe its OK for the screens to show different brightnesses since the accumulated intensities really are different?

![image](https://user-images.githubusercontent.com/679486/49188116-d4d78100-f326-11e8-9fdb-64410f8942d6.png)

**Comment by arouinfar** [comment]
> The amplitude of the point source and the amplitude of the plane waves have been set independently to reach different goals for those screens.

Agreed. I had forgotten about the amplitude attenuation, so the differences in screen intensity make perfect sense. 

I think the screenshot in https://github.com/phetsims/wave-interference/issues/161#issuecomment-442638812 looks a bit smoother. Given the significant improvement on the Waves screen, I think we can go ahead and close this issue.

| Before  | After |
|---|---|
| <img width="145" alt="screen shot 2018-11-28 at 4 53 54 pm" src="https://user-images.githubusercontent.com/8419308/49190160-70202480-f32e-11e8-929b-f89aff11456b.png"> | <img width="140" alt="screen shot 2018-11-28 at 4 54 12 pm" src="https://user-images.githubusercontent.com/8419308/49190161-70202480-f32e-11e8-8085-1adb0a6179a1.png"> |
