### ISSUE TITLE
Why is the interference graph so noisy?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#163]
See:

![image](https://user-images.githubusercontent.com/679486/46501553-15ad9080-c7e3-11e8-86ae-5be07bc90ffe.png)

@kathy-phet says to consult with @jonathanolson as necessary.

This was not a problem in Java.

**Comment by samreid** [comment]
If there was postprocessing smoothing in the Java version, we should try it.

**Comment by samreid** [comment]
It could be a back-reflection?

**Comment by samreid** [comment]
Note that some curves are not too noisy, even after allowing time for back-reflection:

![image](https://user-images.githubusercontent.com/679486/46552600-6d5a0380-c898-11e8-8587-069f0567e92c.png)

**Comment by samreid** [comment]
Java was compacting values into the light screen, then reading color values off that and taking their magnitude to get the chart values.

**Comment by samreid** [comment]
If I add 3-point vertical smoothing, the result from the top comment looks like this:

![image](https://user-images.githubusercontent.com/679486/46554681-41418100-c89e-11e8-84ae-f27875bd76e6.png)

Adding 2-point horizontal average at the sampling site gives this:

![image](https://user-images.githubusercontent.com/679486/46554836-bca33280-c89e-11e8-980b-5e0733531f86.png)

I found the Java version was using a 5-point vertical average:
```java
intensityColorMap.setColorMap( new IndexColorMap( waveModel.getLattice(), colorMap.getRootColor(), new WaveValueReader.AverageAbs( 2 ) ) );
```

Using 5-point average in the HTML5 lifts the bottom of the graph too far off of 0, so maybe we should stick with 3 or so?

**Comment by samreid** [comment]
I also increased the temporal window from 120 to 180 and that helps it stabilize the temporal jitter.

**Comment by samreid** [comment]
After the commit, it looks like this:

![image](https://user-images.githubusercontent.com/679486/46555363-43a4da80-c8a0-11e8-8e25-a23e7873dc7c.png)

@arouinfar can you please test on phettest and let me know your recommendations?

**Comment by arouinfar** [comment]
@samreid the curve looks marginally smoother, but it's still quite noisy. I haven't noticed much difference in the temporal jittering, and if anything, master is a bit worse than before.

Unfortunately, I don't have any particularly clever ideas. @ariel-phet can you review and advise? I'll also tag this for follow-up in design meeting.

![image](https://user-images.githubusercontent.com/8419308/46561334-69d47580-c8b4-11e8-9093-2137621dd59d.png) ![image](https://user-images.githubusercontent.com/8419308/46561344-72c54700-c8b4-11e8-818e-c81c767dcd0c.png)

**Comment by kathy-phet** [comment]
I think it might need investigation of the modeling approach. I still think a discussion with JO or Mike around the model and the filtering/approach that is going on there might provide some possible causes.

**Comment by samreid** [comment]
See also #167 regarding asymmetry in particular.

**Comment by samreid** [comment]
In #167 we identified two sources of asymmetry and resolved them.  Now the graph for two sources/max frequency/max separation looks like this:

![image](https://user-images.githubusercontent.com/679486/46572754-68ed2380-c948-11e8-9ecd-1e247d75704d.png)

Switching to a 5-point vertical intensity average like in the Java, looks like this:
![image](https://user-images.githubusercontent.com/679486/46573153-334b3900-c94e-11e8-8b0d-44dee7ac9b0a.png)

@arouinfar you can test the more symmetrical version with 3-point smoothing on phettest/master.  I could also commit the 5-point smoothing if you wish.  Can you please review and advise?

**Comment by arouinfar** [comment]
@samreid I think this is looking better. The graph looks symmetric about the midline, but the curves themselves are bit distorted. I'd still like for @ariel-phet to take a look and see what he thinks/recommends.

![image](https://user-images.githubusercontent.com/8419308/46698049-50446e00-cbd3-11e8-9389-f5471ff97edf.png)

**Comment by samreid** [comment]
Let's put this issue on hold until https://github.com/phetsims/wave-interference/issues/171 is addressed in case that solves the remainder of the problem.

**Comment by samreid** [comment]
I was able to improve absorption at the boundary somewhat--now the curve may look something like this:

![image](https://user-images.githubusercontent.com/679486/49019634-9d60ad00-f14b-11e8-81ba-443b7b22fc7b.png)

Is this acceptable for 1.0?

**Comment by arouinfar** [comment]
@samreid I think that's a huge improvement! I'm seeing some slight deformities near the outside edges of the curve, but overall it looks so much cleaner. I'd say this is definitely acceptable for 1.0, so closing.

![image](https://user-images.githubusercontent.com/8419308/49040622-50e39480-f180-11e8-87c4-a195cb7e77f5.png)
