### ISSUE TITLE
Add zoom to intensity graph

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#164]
From discussion in #151, we decided to add zoom buttons to the intensity graph. Heres' a mockup:

![image](https://user-images.githubusercontent.com/8419308/46507776-73e46e80-c7f7-11e8-9172-2bd81d05eafd.png)

General behavior:
* Default zoom level should match current scaling in the sim.
* Allow 2-3 steps of zooming in and out
* When zoomed all the way in or out, the corresponding zoom button will be inactive.
* Match the color of the zoom buttons used in Masses and Springs and Pendulum Lab

**Comment by arouinfar** [comment]
Looks awesome @samreid! 

I'm on the fence about zoom level 1. In preliminary testing, I haven't found a case were it was particularly useful, though it doesn't hurt to leave it in.

Let's review with the team at the next design meeting.

**Comment by samreid** [comment]
One possibility would be to keep 5 levels, so it remains symmetrical, but make level 1 equal to what level 2 is now.

**Comment by samreid** [comment]
It sounded like the team approved of the existing zoom levels-- @arouinfar was that your impression, or should we revisit in another meeting?  If this is good, please close.

**Comment by arouinfar** [comment]
Correct @samreid. The team liked it team liked the zoom feature, and the current zoom levels looked appropriate. No need to make any further tweaks. Closing.
