### ISSUE TITLE
Difficult to distinguish light wave area from intensity screen when wave is off.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#166]
When the wave is off, the intensity screen and wave area are the same color, with no boundary:

![image](https://user-images.githubusercontent.com/679486/46551461-13a40a00-c895-11e8-834e-72a1c3edf522.png)

Should we add a stroked edge or dotted line so it is clearer what is happening at that boundary?

**Comment by arouinfar** [comment]
It is a bit hard to differentiate the two. @samreid can you try adding a thin white stroke around the lattice viewing window?

**Comment by arouinfar** [comment]
@samreid it seems okay, but it's hard to tell because the screen is broken in master. 

![image](https://user-images.githubusercontent.com/8419308/46693617-97c4fd00-cbc7-11e8-9e1c-3ed3258fdd06.png)

**Comment by ariel-phet** [comment]
Looks good to me!
