### ISSUE TITLE
Apparent interference pattern on screen for single source

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#171]
Discovered in #161 

For a single source, I'm seeing some apparent maxima and minima on the screen, which makes me think that there are some reflections in the system. 
![image](https://user-images.githubusercontent.com/8419308/46697235-6a7d4c80-cbd1-11e8-9a0c-bc14d4ac6495.png)

This is also apparent in dev.38, which has a larger saturation scale factor of 7.
![image](https://user-images.githubusercontent.com/8419308/46697330-a0223580-cbd1-11e8-8c06-757815b1b524.png)

**Comment by samreid** [comment]
At yesterday's design meeting, we decided to investigate and try to understand this problem better.  We would like to keep the light screen on the waves screen.  @samreid will reach out to MD as needed for assistance.

**Comment by arouinfar** [comment]
To add to @samreid's comments:

When measuring the E-field at the edge of the lattice, regions next to the apparent maxima in the screen have a larger amplitude (even though the lighter probe is farther from the source).
![image](https://user-images.githubusercontent.com/8419308/47241661-2ac51a80-d3b2-11e8-8185-2e98916a6155.png)




While the screen doesn’t necessarily have great pedagogical value on Waves, it does have “sim use” value. Users will get introduced to the feature, and have a point of contrast when looking at the screen on Interference and Slits. (Removing the screen because there’s something funky going on in the model isn’t the most robust solution, either.)

**Comment by samreid** [comment]
Here's a conversation on absorbing boundary conditions and a discussion about using a masking function on the boundary: https://scicomp.stackexchange.com/questions/26725/discrete-wave-simulation-absorbing-boundaries

**Comment by samreid** [comment]
Note that we cannot simply apply damping across the entire wave area because we already like the existing behavior for the wave attenuation.  Adding a global damping term may eliminate the artifacts, but would disturb the attenuation.

**Comment by samreid** [comment]
Here is the behavior with no damping terms:
![image](https://user-images.githubusercontent.com/679486/47370892-ec767680-d6a3-11e8-97b0-f18df84c6ec1.png)

**Comment by samreid** [comment]
Here is a uniform exponential damping:

```js
      for ( let i = 1; i < width - 1; i++ ) {
        for ( let j = 1; j < height - 1; j++ ) {
          const neighborSum = matrix1.get( i + 1, j ) + matrix1.get( i - 1, j ) + matrix1.get( i, j + 1 ) + matrix1.get( i, j - 1 );
          const m1ij = matrix1.get( i, j );
          const value = m1ij * 2 - matrix2.get( i, j ) + WAVE_SPEED_SQUARED * ( neighborSum + m1ij * -4 );
          const depth = this.visibleBounds.minimumDistanceToPointSquared( new Vector2( i, j ) );
          Math.random() < 0.0001 && console.log( i, j, depth );
          matrix0.set( i, j, value * Math.exp( -depth / 2000 ) );

          if ( Math.abs( value ) > LIGHT_VISIT_THRESHOLD ) {
            this.visitedMatrix.set( i, j, 1 );
          }
        }
      }
```

![image](https://user-images.githubusercontent.com/679486/47372863-e4b8d100-d6a7-11e8-8451-6d216de86300.png)

**Comment by samreid** [comment]
I experimented with a damping scale factor of 0.99 everywhere on the lattice, with the idea that this would subtract off artifacts as quickly as they are being added--maybe it helped a little but there was still diffraction on the screen.

**Comment by samreid** [comment]
Here's a radial mask for reference:

```js
      // Main loop, doesn't update cells on the edges
      for ( let i = 1; i < width - 1; i++ ) {
        for ( let j = 1; j < height - 1; j++ ) {
          const neighborSum = matrix1.get( i + 1, j ) + matrix1.get( i - 1, j ) + matrix1.get( i, j + 1 ) + matrix1.get( i, j - 1 );
          const m1ij = matrix1.get( i, j );
          const value = m1ij * 2 - matrix2.get( i, j ) + WAVE_SPEED_SQUARED * ( neighborSum + m1ij * -4 );
          const depth = Math.sqrt( this.visibleBounds.minimumDistanceToPointSquared( new Vector2( i, j ) ) );
          // Math.random() < 0.0001 && console.log( i, j, depth );

          const origin = new Vector2( WaveInterferenceConstants.POINT_SOURCE_HORIZONTAL_COORDINATE, this.height / 2 );
          const dist2 = origin.distance( new Vector2( i, j ) );
          matrix0.set( i, j, value * Math.exp( -depth / 250 ) * Math.exp( -dist2 / 2000 ) );

          if ( Math.abs( value ) > LIGHT_VISIT_THRESHOLD ) {
            this.visitedMatrix.set( i, j, 1 );
          }
        }
      }
```

**Comment by samreid** [comment]
I've scheduled a meeting with MD and putting this issue on hold until then.

**Comment by samreid** [comment]
MD and I met to discuss the problem once, but haven't no solution yet. I wrote to him two subsequent times but have not heard back.  I also reached out to MV:

Greetings from Colorado!  PhET is working on porting our 2D Wave Interference simulation and running into an issue we were hoping you could help with.  Full details are in https://github.com/phetsims/wave-interference/issues/171. The gist is that we are using this numerical solution for the 2d wave propagation: http://www.mtnmath.com/whatth/node47.html and we are trying to simulate absorbing boundary conditions (so it appears the wave can propagate out of the visible window), but we are seeing minor internal reflections that add up and show an interference pattern on the screen.  The three parts we have already implemented in attempt to solve this are:
1. Make a larger lattice than what is shown
2. We have a "temporal" damping term on the edges, like so: matrix0.set( i, j, matrix2.get( i, j + dj ) );  matrix0 is current value, matrix2 is value from 2 steps ago.
3. We have a "masking function" where the wave amplitude is multiplied by a value <=1 closer to the boundaries, but in experimentation, it doesn't seem this term is helping too much.

Here's the latest dev version: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.43/phet/wave-interference_en_phet.html
To see the problem, choose "light" and select "screen", then turn on the wave source and wait until a pattern appears on the screen.

Any ideas?

Best Regards,
Sam

**Comment by samreid** [comment]
In the preceding commit, I eliminated temporal damping and improved the masking function.  Here are the results:

![after](https://user-images.githubusercontent.com/679486/48799058-7164a800-ecc3-11e8-8147-3bb9945bfba2.png)

**Comment by samreid** [comment]
I tried these masking functions as a function of depth, the orange one is shown on the right above.  The blue one is surprisingly much morse than before:

![image](https://user-images.githubusercontent.com/679486/48800254-7f67f800-ecc6-11e8-8211-30d4b7fe6875.png)

**Comment by samreid** [comment]
I experimented with a few linear functions but couldn't improve upon the preceding sigmoid.  @arouinfar can you please test on phettest and see if that curve will be acceptable?

**Comment by arouinfar** [comment]
I'm definitely noticing less interference in master @samreid! This looks like a reasonable solution to me, so I'll go ahead and close this issue.

Master (left) vs. dev.43 (right)
<img width="105" alt="screen shot 2018-11-26 at 1 13 29 pm" src="https://user-images.githubusercontent.com/8419308/49039622-8935a380-f17d-11e8-877d-0dd4f141b7b6.png"> <img width="114" alt="screen shot 2018-11-26 at 1 13 46 pm" src="https://user-images.githubusercontent.com/8419308/49039626-8935a380-f17d-11e8-9aee-dab2a6db3cc3.png">

**Comment by samreid** [comment]
The proposed solution was not wavelength-independent and failed for broad water waves--we will need a more general solution.  I'm continuing in https://github.com/phetsims/wave-interference/issues/197
