### ISSUE TITLE
Update scene selection icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#172]
Now that the water source has been finalized (#104), the scene icons should be updated.

By design, the water source is pretty generic looking. I don't think it does a great job of cueing the context of the scene, but that might be okay since it's the default scene. An alternative choice would be the water drop. Since the water drop is what initiates the wave, I don't think it's thematically different from the other icons.

<img width="316" alt="screen shot 2018-10-16 at 9 10 24 am" src="https://user-images.githubusercontent.com/8419308/47026740-5c748200-d123-11e8-9aed-4ced1759402c.png">

**Comment by arouinfar** [comment]
@samreid  see https://github.com/phetsims/wave-interference/issues/104#issuecomment-431394209. I've updated the water source on Drive (in Wave Interference design folder). I included an iconic version for the scene button, but clipping the source artwork would also work.

**Comment by samreid** [comment]
In the preceding commit, I switched to the new speaker icon and faucet icon, @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
Looks great @samreid!
