### ISSUE TITLE
The sound particles origin may not be quite right

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#174]
From https://github.com/phetsims/wave-interference/issues/52

Note the particles aren't aggregating exactly at the center of the oscillator:

![image](https://user-images.githubusercontent.com/679486/47257934-94e0cc80-d451-11e8-8a95-cbf1e211edc5.png)

**Comment by samreid** [comment]
I don't have a good understanding of the mismatch in coordinates, but the above change seems to align the physical and lattice coordinates better.

**Comment by samreid** [comment]
This is out of alignment as identified in https://github.com/phetsims/wave-interference/issues/242, will need adjusting.

**Comment by samreid** [comment]
There was indeed a bug here, I'll report further in #242 and leave this open for verification of the Sound Particle positions in particular.

**Comment by samreid** [comment]
Please see comments in https://github.com/phetsims/wave-interference/issues/242#issuecomment-447233239 and be apprised of particle position issues (like the one in the screenshot at the top of this file) during testing.

**Comment by KatieWoe** [comment]
Looks ok.  I'm not seeing this issue in master.
