### ISSUE TITLE
When barrier is added, clear lattice to right of barrier

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#176]
If the plane wave has fully propagated in the lattice, adding a barrier creates some interesting phenomena to the right of the barrier.

![barrier_reflections](https://user-images.githubusercontent.com/8419308/47533874-a58aab80-d872-11e8-87af-c87f47ddb100.gif)

@samreid if a barrier is added to the play area, please clear the lattice to the right of the barrier. This would be similar to how we currently handle dragging a barrier.

**Comment by samreid** [comment]
@kathy-phet also indicated that this errant behavior may indicate deeper problems in the model.  I surmised that the analytical model on left doesn't change the wave "history", so there is no momentum in the wave.  I should check on this as part of this issue.

**Comment by samreid** [comment]
The model is setting the `currentValue` like a forcing function as part of Lattice.step, therefore those values should be propagating to the history properly, so I don't know what explains the behavior in https://github.com/phetsims/wave-interference/issues/176#issue-374158010.  Still, I've added a commit that clears the waves to the right when the barrier is added.

@arouinfar can you check this is OK?

Also, I noticed that removing a barrier instantly shows the plane wave everywhere to the right of the slit (even if it hadn't propagated that far yet). Should we create an issue to address it, or is this acceptable?

**Comment by arouinfar** [comment]
The behavior when adding a barrier looks great @samreid.

I'm not particularly bothered by the plane wave taking up the entire lattice when removing the barrier. Perhaps a more consistent alternative would be to clear the portion of the lattice that was to the right of the barrier, and then allow the plane wave to propagate the rest of the way across. If  you agree, and think that it'd be a relatively simple tweak, please open an issue. Otherwise, feel free to veto the change, and close this issue.

**Comment by kathy-phet** [comment]
@samreid - I agree with the change to fix this issue, but still think it would be good to understand why the model was displaying this behavior as it may help us understand some of the artifacts seen in various cases?

**Comment by samreid** [comment]
Thanks @arouinfar and @kathy-phet. I'll open up separate issues to continue discussion/investigation.

**Comment by arouinfar** [comment]
Sure thing @samreid. Closing.

**Comment by samreid** [comment]
Now that the root of the problem has been solved in #185, we have the option to remove or keep the "clear to the right of the barrier" code added in this issue.  Here is the behavior with the the "clear" removed now:

![wave-barrier](https://user-images.githubusercontent.com/679486/47730608-24dbfe80-dc28-11e8-9097-2dc4e26071cc.gif)

I don't feel strongly one way or the other, let me know what you recommend.

**Comment by arouinfar** [comment]
@samreid since we clear the wave when dragging the barrier, I think the current behavior feels a bit more consistent. I'm inclined to leave things as the are, but glad to know you chased down the root of the problem.
