### ISSUE TITLE
Find suitable ranges, defaults, and constrainValue for sliders

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#177]
Stemming from today's design discussion, I should find appropriate ranges/defaults for the Source Separation, Slit Width, and Slit Separation sliders.

Slider thumbs should also be snappy to allow for easier-to-reproduce experiments, so I'll also recommend values for `constrainValue`.

Currently, Slit Width is current shared for One Slit and Two Slit cases, but @samreid has said that they can be separated.

**Comment by samreid** [comment]
We will also need to decide "rounding" for each of the sliders, for example rounding water to nearest 0.5cm and light to nearest 10nm.

**Comment by arouinfar** [comment]
@samreid  here are my recommendations for the Separation slider on Interference. I'll report back with Slit Width and Slit Separation shortly.

| Scene | Min | Max | Default | tweaker increment | thumb increment (constrainValue) |
| --- | --- | --- | --- | --- | --- |
| Water | 1.0 cm | 5.0 cm | 3.0 cm | 0.1 cm | 0.5 cm |
| Sound | 100 cm | 400 cm | 200 cm | 1 cm | 10 cm |
| Light | 500 nm | 4000 nm | 1500 nm | 10 nm | 100 nm |

**Comment by arouinfar** [comment]
@samreid here are the rest of the values.

### Slit Width

| Scene | Min | Max | Default | tweaker increment | thumb increment (constrainValue) |
| --- | --- | --- | --- | --- | --- |
| Water | 0.5 cm | 2.5 cm |  1.5 cm | 0.1 cm | -- |
| Sound | 20 cm | 160 cm | 90 cm | 1 cm | 10 cm |
| Light | 200 nm | 1600 nm | 900 nm | 10 nm | 50 nm |

### Slit Separation

| Scene | Min | Max | Default | tweaker increment | thumb increment (constrainValue) |
| --- | --- | --- | --- | --- | --- |
| Water | 1.0 cm | 5.0 cm | 3.0 cm | 0.1 cm | -- |
| Sound | 40 cm | 320 cm | 180 cm | 1 cm | 10 cm |
| Light | 400 nm | 3200 nm | 1800 nm | 10 nm | 50 nm |

**Comment by samreid** [comment]
Why is thumb increment (constrainValue) specified for Water source separation but not Water slit separation or Water slit width?

**Comment by samreid** [comment]
In the preceding commits I matched the values for the bottom table (aside from the different slit separation defaults for sound and light), reassigned to @arouinfar to discuss the two preceding comments.

**Comment by arouinfar** [comment]
The behavior on master is looking to me @samreid!

> Why is thumb increment (constrainValue) specified for Water source separation but not Water slit separation or Water slit width?

The range is pretty small, so it didn't make much sense to me to snap the thumb in increments greater than the tweaker increment.

> Also, in #87 we decided that the initial source separation values (interference screen) would match the initial slit separation values (slit screen).

I had forgotten about that detail! I had simply chosen the midpoint as the default, but matching the defaults to the source separation on Interference is fine by me.
