### ISSUE TITLE
Is the dotted line only shown when the "graph" is selected?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#18]
The mock-up shows the graph selected, but I can't tell if the dotted line should be there when the graph is not shown (I suspect it should not be, but wanted to double check).

**Comment by arouinfar** [comment]
Great question @samreid! The dotted white line should only be visible when the graph is on.

Reassigning to @samreid so he'll see this before closing.

**Comment by samreid** [comment]
Got it, thanks! Closing.
