### ISSUE TITLE
Sound waves look like they change wavelength when going through the slits

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#182]
Or through a single slit.

**Comment by samreid** [comment]
There was an incorrect value for the sound scene time scale factor, which I corrected in the preceding commit.  Now the wavelengths match up as expected.  Unfortunately, the min/max frequencies and sound particle features were calibrated against the buggy time scale factor, so we will need to revisit that.

**Comment by samreid** [comment]
If I change the frequency range from the current range of 440Hz-880Hz to the proposed range of 220Hz-440Hz, then it's much closer to the values we calibrated against.  These are the lines of code that determine the min and max frequencies for sound:

https://github.com/phetsims/wave-interference/blob/ff83584541e5dddc8d20bb3bf615dbb61e5c8a94/js/waves/model/WavesScreenModel.js#L137-L138

@arouinfar would you mind pulling master and tinkering with those values to see the proposed range seems reasonable?  Or if we may need to do a different range or further corrections to the sound particle physics calibration or other recalibrations?

**Comment by arouinfar** [comment]
If we ever decide to add actual sound to the sim, a range of A3-A4 would sound more pleasing.
A3 (220 Hz): https://www.youtube.com/watch?v=N5k0Ar3bgvM
A4 (440 Hz): https://www.youtube.com/watch?v=SsGhuUm_3-8
A5 (880 Hz): https://www.youtube.com/watch?v=C8nlAqr5KBY

I'll test out 220-440 Hz, and get back to you @samreid.

**Comment by arouinfar** [comment]
@samreid, in principle, I'm fine with 220-440 Hz. It has a more pleasing sound, and the wave view looks better at the chosen scale.

However, when I tested 220-440 out locally, I noticed the particle view of was quite jittery. It's especially noticeable near the source. The wavefronts also lose some of their crispness. Unfortunately, I think we're going to need to re-tune the particle parameters.

| f | Local Test (220-440 Hz) | dev.40 |
|---|---|---|
| min | ![220](https://user-images.githubusercontent.com/8419308/47818696-15d77800-dd1e-11e8-9634-e4be2c06f8fd.gif) | ![dev40_min](https://user-images.githubusercontent.com/8419308/47818711-22f46700-dd1e-11e8-8603-aaee274113a4.gif) |
| max | ![440](https://user-images.githubusercontent.com/8419308/47818729-36073700-dd1e-11e8-85f3-56f2aa30bb6d.gif)|  ![dev40_max](https://user-images.githubusercontent.com/8419308/47818984-cc3b5d00-dd1e-11e8-925d-6682b40dec29.gif)|

**Comment by samreid** [comment]
@arouinfar would you like to re-tune the parameters using the `?dev` controls?

**Comment by arouinfar** [comment]
Sure @samreid. Can you open a new issue for re-tuning (or re-open the original)?

**Comment by arouinfar** [comment]
Since the only remaining work is re-tuning the particle physics, I reopened #158. I think we can close this issue.

**Comment by arouinfar** [comment]
@samreid not sure where my head was last week, but I should not have closed this issue.

I think we should update the frequency range to 220-440 Hz, and the default can be at 330 Hz.

**Comment by samreid** [comment]
Range changed in commit, can you please review and test on phettest?

**Comment by arouinfar** [comment]
The updated range and scaling all looks good @samreid. Can you publish a new dev version for the particle re-calibration?

**Comment by samreid** [comment]
Commented in https://github.com/phetsims/wave-interference/issues/158#issuecomment-436682429 and published a new dev version for recalibration.  Can this issue be closed?

**Comment by arouinfar** [comment]
Perfect, thanks @samreid! There's nothing left for this issue.
