### ISSUE TITLE
Reset all not resetting "two slits" back to "one slit"

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#183]

**Comment by samreid** [comment]
Proposed fix pushed, @arouinfar can you please test?

**Comment by arouinfar** [comment]
Looks good @samreid.

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/238.  This issue is occurring.  It also does not turn No Barrier into one slit.  This applies to all scenes on the screen and all browsers tested so far.  It does reset any size changes made. @samreid

**Comment by samreid** [comment]
Proposed fix pushed, @KatieWoe can you please verify on phettest?

**Comment by KatieWoe** [comment]
Looks good on master
