### ISSUE TITLE
dev.39 and dev.40 seem to have a shift.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#184]
They are supposed to only differ in the wave rendering cutoff, but they seem to show a phase offset.

**Comment by arouinfar** [comment]
@samreid I am also reasonably convinced that the apparent phase shift is an optical illusion. 

Here's another comparison of dev.40 (top) and dev.39 (bottom)
![image](https://user-images.githubusercontent.com/8419308/47820036-ddd23400-dd21-11e8-9af4-1674239f9fe0.png)
