### ISSUE TITLE
When removing the barrier and clearing the wave, can it fill in gradually instead of immediately?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#186]
From https://github.com/phetsims/wave-interference/issues/176#issuecomment-433464508

I said:

> Also, I noticed that removing a barrier instantly shows the plane wave everywhere to the right of the slit (even if it hadn't propagated that far yet). Should we create an issue to address it, or is this acceptable?

@arouinfar replied:

> I'm not particularly bothered by the plane wave taking up the entire lattice when removing the barrier. Perhaps a more consistent alternative would be to clear the portion of the lattice that was to the right of the barrier, and then allow the plane wave to propagate the rest of the way across. If you agree, and think that it'd be a relatively simple tweak, please open an issue. Otherwise, feel free to veto the change, and close this issue.

I'm not sure whether this is an easy change or not, self-assigning to investigate.

**Comment by samreid** [comment]
Proposed fix is committed, @arouinfar can you please test?

**Comment by arouinfar** [comment]
Looks good @samreid
