### ISSUE TITLE
Move pulse/continuous buttons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#189]
I should create some mockups.

**Comment by arouinfar** [comment]
@samreid here's a mockup.

I vertically stacked the pulse/continuous buttons, but put continuous on top since it's the default state. I also moved the top/side radio group a bit to the left so it's left-aligned with the lattice.

![image](https://user-images.githubusercontent.com/8419308/49190651-87f8a800-f330-11e8-9164-b82c71cc6eae.png)

**Comment by samreid** [comment]
Completed in the preceding commit,  But I am seeing an overlap with the graph--not sure how to proceed:

![image](https://user-images.githubusercontent.com/679486/49191616-6ef1f600-f334-11e8-8ec6-e7bf6cb3293c.png)

**Comment by samreid** [comment]
Also, would you like to move the top/side play/pause normal/slow buttons up to be centered between wave area and navbar?  Right now there is some awkward trapped space above them.

![image](https://user-images.githubusercontent.com/679486/49191635-87faa700-f334-11e8-804e-b8bb3925298e.png)

**Comment by samreid** [comment]
This shows the pulse/continuous buttons centered between the edge of the wave and the dev bounds:

![image](https://user-images.githubusercontent.com/679486/49191716-e6278a00-f334-11e8-88c5-970c9375eb31.png)
