### ISSUE TITLE
stringTest=long needs work

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#194]
See https://github.com/phetsims/wave-interference/issues/193

Currently looks like: 
![image](https://user-images.githubusercontent.com/679486/49036408-e7aa5400-f174-11e8-9a93-5587bcbf6c85.png)

**Comment by arouinfar** [comment]
Looking much better @samreid, but I'm still noticing a few things in https://github.com/phetsims/wave-interference/issues/194#issuecomment-442323708.
* "Intensity" doesn't appear to be translatable (wasn't replaced with the stringTest)
* The toolbox and panel on the right should be given an appropriate maxWidth to prevent them from spilling over the Intensity graph.
* The time scale factor should be given a maxWidth so it doesn't overlap the spatial scale factor.

**Comment by samreid** [comment]
Nice catch @arouinfar, thanks!

**Comment by samreid** [comment]
Proposed fixes are committed.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
Getting close @samreid. 

* The barriers panel on Slits is escaping `?dev`
<img width="278" alt="screen shot 2018-11-28 at 10 30 39 am" src="https://user-images.githubusercontent.com/8419308/49170628-cd4db300-f2f9-11e8-9c76-75b98461a3ed.png">

* The title and tick labels on the Frequency slider all overlap. There should be some vertical separation between the title and ticks. The tick marks also need a maxWidth so they don't overlap one another.
<img width="193" alt="screen shot 2018-11-28 at 10 38 12 am" src="https://user-images.githubusercontent.com/8419308/49170637-d179d080-f2f9-11e8-8a04-5863d974bb12.png">

* There's a lot of unused white space to the right of these checkboxes, so their maxWidth could be larger

<img width="193" alt="screen shot 2018-11-28 at 10 43 41 am" src="https://user-images.githubusercontent.com/8419308/49170915-7c8a8a00-f2fa-11e8-99ab-a23eab0dda14.png">

* Numeric tick mark labels do not need to be translatable.
<img width="192" alt="screen shot 2018-11-28 at 10 52 15 am" src="https://user-images.githubusercontent.com/8419308/49171414-b1e3a780-f2fb-11e8-80db-7996709a9f3c.png">

**Comment by arouinfar** [comment]
@samreid I was ready to close this issue, but then I tested `?stringTest=double` and it became clear that the numberControl titles were getting obscured by the readouts.
![image](https://user-images.githubusercontent.com/8419308/49259614-53035880-f3f7-11e8-840e-9ed5625c13fb.png)
![image](https://user-images.githubusercontent.com/8419308/49259620-5bf42a00-f3f7-11e8-82cd-94a671a11e19.png)

The same issue is probably happening for `?stringTest=long`, but this issue just wasn't as apparent with tiny/nonsensical strings.
![image](https://user-images.githubusercontent.com/8419308/49259692-abd2f100-f3f7-11e8-940d-1898a3fe2067.png)

**Comment by samreid** [comment]
Proposed fix committed, can you please review on phettest?

**Comment by arouinfar** [comment]
👍
