### ISSUE TITLE
Ensure credits are correct before publication

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#195]
From #191 

> Does a GitHub issue exist for tracking credits, to ensure that they are correct before publication?

**Comment by arouinfar** [comment]
@samreid we should also credit the legacy design team. Please add Wendy Adams to the team, and Noah Podolefsky to leadDesign. You can also remove me from graphicArts, since I'm already credited in leadDesign.

**Comment by KatieWoe** [comment]
@samreid, so far for qa.

**Comment by samreid** [comment]
Credits now read:

```js
  const simOptions = {
    credits: {
      leadDesign: 'Amy Rouinfar, Noah Podolefsky',
      softwareDevelopment: 'Sam Reid',
      team: 'Diana López, Ariel Paul, Kathy Perkins, Katie Woessner, Wendy Adams',
      qualityAssurance: 'Katie Woessner, Laura Rea, Steele Dalton, Liam Mulhall',
      graphicArts: 'Cheryl McCutchan'
    },
    showSmallHomeScreenIconFrame: true
  };
```

Close if all is well.

**Comment by arouinfar** [comment]
👍

**Comment by phet-steele** [comment]
I alphabetized SOME credits in the above commit.
