### ISSUE TITLE
Should the ?theory lines show on the "Interference" screen?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#196]
From #191 and https://github.com/phetsims/wave-interference/issues/136, the `?theory` query parameter only shows for the "Slits" screen.  Would we like it to show fo the "Interference" screen as well?

**Comment by arouinfar** [comment]
Good question @samreid. I think `?theory` is particularly useful for slit interference because it can be a bit trickier to get the interference pattern to converge on the screen. It's much easier to set up two-source interference examples that converge on the screen. I also think it would also be a bit odd to see the `?theory` lines on Interference, because the origin would be at the midpoint of the sources. I'd prefer to pass on adding `?theory` support to Interference.

If you agree, feel free to close @samreid. Otherwise, please tag this issue for further consideration at design meeting.

**Comment by samreid** [comment]
> I also think it would also be a bit odd to see the ?theory lines on Interference, because the origin would be at the midpoint of the sources.

That part doesn't bother me at all, for the same reason it is acceptable showing the origin at the center of the barrier on the slits screen.

I agree this feature will be very helpful to teachers that want to leverage it for the slits screen, but it could be confusing to teachers that want to draw correspondence between the slits screen and the interference screen.  That being said, I don't think this query parameter will be used by a large fraction of teachers and it also doesn't seem essential for 1.0.  If it was a more important feature, I'd suggest we add a user interface control for it in the simulation, but we decided against that in a design meeting.  I estimate it would take a couple of hours to add it to the Interference screen.  I won't work on it until we discuss it further.

**Comment by arouinfar** [comment]
@samreid I think we could defer `?theory` on Interference for 1.1+. Given the tight timeline, it doesn't seem worth it for 1.0.

**Comment by samreid** [comment]
Agreed, I'll self-assign for now to document accordingly, then we can decide how best to address for 1.1+.

**Comment by samreid** [comment]
In my opinion, the value of this feature would not exceed its cost and I recommend to close without fixing.  Assigning for design meeting to discuss.

**Comment by arouinfar** [comment]
I don't think `?theory` is essential for the Interference screen, so I'd be fine with closing.

**Comment by samreid** [comment]
@kathy-phet says it would be nice to make sure the empirical result matches the theoretical result, and it could potentially be something to share with teachers as well.  @samreid gave a time estimate of 2-3 hours.

**Comment by samreid** [comment]
I adapted the existing `?theory` code to show for the interference screen, with the assumption that 2 sources are oscillating.  Testing the default value for water:

![image](https://user-images.githubusercontent.com/679486/56142131-5be66800-5f5b-11e9-9845-9a279aeb5282.png)

Testing the max frequency for sound:

![image](https://user-images.githubusercontent.com/679486/56142175-6ef93800-5f5b-11e9-9412-ba144980dffb.png)

Testing the min frequency for light:

![image](https://user-images.githubusercontent.com/679486/56142226-8506f880-5f5b-11e9-9803-db2e7b4dd0c2.png)

Correspondence seems reasonable.  Reassigning to @arouinfar to take a closer look, let me know if there's more to do for this issue.

**Comment by arouinfar** [comment]
@samreid the correspondence in the screenshots you've posted looks fine to me. However, the lines don't appear to shift when the separation changes. I'm also seeing a pretty big delay between changing the frequency and the shift in the `?theory` lines for the water scene.

**Comment by samreid** [comment]
Thanks @arouinfar, in the preceding commit, the theory lines update when the source separation changes.  

Regarding the delay in the water scene, I was surprised to see this behavior as well.  Looking into it, I realized changing the separation or frequency via the user interface doesn't immediately change the oscillatory behavior of the model.  Instead, it schedules the new frequency/separation for when the next droplets hit the surface of the water.  The theory overlay is observing the model frequency/separation, not the values specified in the user interface and scheduled for upcoming/falling droplets.  

Should I investigate wiring up the theory overlay for water to the values set in the user interface?  It could take 30-60 minutes up-front effort and would introduce a bit more complexity for this feature that would need to be maintained.

**Comment by arouinfar** [comment]
> Thanks @arouinfar, in the preceding commit, the theory lines update when the source separation changes.

Looks good @samreid.

> Regarding the delay in the water scene, I was surprised to see this behavior as well. Looking into it, I realized changing the separation or frequency via the user interface doesn't immediately change the oscillatory behavior of the model. Instead, it schedules the new frequency/separation for when the next droplets hit the surface of the water. 

That makes a lot of sense, thanks @samreid. However, while the sources are off, I'm still noticing a pretty big delay which still seems odd.

**Comment by samreid** [comment]
There are actually "invisible drops" that send a signal to the lattice to stop oscillating.   They fall at the same rate as the visible drops, so it should have the same delay pattern.  Is this acceptable for this use case, or want me to investigate wiring things up to the "desired" instead of "actual" for the water drops?

**Comment by arouinfar** [comment]
> There are actually "invisible drops" that send a signal to the lattice to stop oscillating.

Ah, got it. Thanks for the clarification. 

> Is this acceptable for this use case, or want me to investigate wiring things up to the "desired" instead of "actual" for the water drops?

Since I was fine with limiting `?theory` to only the Slits screen, I would lean towards not spending any more time on this issue. However, I think it's best to defer to @kathy-phet on this one.

**Comment by arouinfar** [comment]
@kathy-phet can you review the behavior of `?theory` on the Interference screen? There is good correspondence between the `?theory` overlay and the lattice. However, the overlay is quite slow to update on water because as @samreid  described:

> changing the separation or frequency via the user interface doesn't immediately change the oscillatory behavior of the model. Instead, it schedules the new frequency/separation for when the next droplets hit the surface of the water. 

@kathy-phet is this acceptable? @samreid also proposed this alternative:

> Should I investigate wiring up the theory overlay for water to the values set in the user interface? It could take 30-60 minutes up-front effort and would introduce a bit more complexity for this feature that would need to be maintained.

**Comment by samreid** [comment]
@ariel-phet can you please help move this issue forward?

**Comment by arouinfar** [comment]
> Should I investigate wiring up the theory overlay for water to the values set in the user interface? It could take 30-60 minutes up-front effort and would introduce a bit more complexity for this feature that would need to be maintained.

Discussed at the 6/20/19 design meeting, and we decided that @samreid should proceed with this.

**Comment by samreid** [comment]
In the commit, I made it so the theory lines update immediately for water.  @arouinfar can you please fully test the `?theory` query parameter, including but not limited to this new change and let me know if everything is OK?  Close if all is well.

**Comment by arouinfar** [comment]
@samreid `?theory` is looking good on the Interference screen for all scenes. However, I'm noticing things look a bit off for water on the Slits screen (sound and light are ok). Comparing to latest reveals that things are indeed different for water.

In latest (1.0.4) there is good agreement between `?theory` and the lattice.
![WI-1 0](https://user-images.githubusercontent.com/8419308/60356128-624a8480-998d-11e9-84b6-3471c102c8d9.png)

Recreating the same situation in master, the `?theory` lines are clearly different, and do not align with the pattern seen in the lattice (red lines look centered between two minima).
![WI-2 0](https://user-images.githubusercontent.com/8419308/60356129-624a8480-998d-11e9-9f8f-04de0ef53541.png)

**Comment by samreid** [comment]
Good discovery @arouinfar, I'll look into it.

**Comment by samreid** [comment]
Proposed fix is committed, @arouinfar please review.

**Comment by arouinfar** [comment]
Looking good in master @samreid!
