### ISSUE TITLE
Low frequency water shows significant reflection artifacts

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#197]
I tested water at lowest frequency and saw significant reflection artifacts:

![image](https://user-images.githubusercontent.com/679486/49058455-53b2a980-f1c1-11e8-9dcc-6531a8257607.png)

I fine tuned the absorption profile in #171 mainly for red light--I wonder if different characteristics are needed for different frequencies/wavelengths.

**Comment by samreid** [comment]
I tried damping the wave to eliminate interference effects, but this had many undesirable effects and did not solve the problem 100%.

**Comment by samreid** [comment]
I tested the absorbing boundary conditions listed at https://www.phy.ornl.gov/csep/sw/node22.html

![image](https://user-images.githubusercontent.com/679486/49181023-840a5d00-f313-11e8-82ab-253dae4ef06b.png)

```
The left side boundary condition loop is

          do 140 j=2,nzd-1
          u3(1,j) = u2(1,j)+u2(2,j)-u1(2,j)+
     x   cb(1,j)*(u2(2,j)-u2(1,j)-u1(3,j)+u1(2,j))
 140      continue
Code Fragment I
The  wave field arrays are for the , ,  time steps respectively. The  array contains the spatial coefficient, .

The right side boundary condition loop is

          do 160 j=2,nzd-1
          u3(nxd,j) = u2(nxd,j)+u2(nxd-1,j)-u1(nxd-1,j)-
     x    cb(nxd,j)*(u2(nxd,j)-u2(nxd-1,j)-
     x    u1(nxd-1,j)+u1(nxd-2,j))
 160      continue
Code Fragment II
The top side boundary condition loop is

          do 150 i=2,nxd-1
          u3(i,nzd) = u2(i,nzd)+u2(i,nzd-1)-u1(i,nzd-1)-
     x   cb(i,nzd)*(u2(i,nzd)-u2(i,nzd-1)-
     x      u1(i,nzd-1)+u1(i,nzd-2))         
150       continue
Code Fragment III
The bottom side boundary condition loop is

          do 130 i=2,nxd-1
          u3(i,nzd) = u2(i,nzd)+u2(i,nzd-1)-u1(i,nzd-1)-
     x   cb(i,nzd)*(u2(i,nzd)-u2(i,nzd-1)-
     x      u1(i,nzd-1)+u1(i,nzd-2))         
130       continue
```

Note there is a bug in the bottom fortran code.  I did got reasonable behavior (not perfect) for the red light condition:

![image](https://user-images.githubusercontent.com/679486/49181061-9edcd180-f313-11e8-989a-f49a7e1a3442.png)

and this handled low frequency water OK

![image](https://user-images.githubusercontent.com/679486/49181094-b3b96500-f313-11e8-8bc5-95fdd3534c23.png)

**Comment by samreid** [comment]
I should have mentioned: every now and then the entire wave goes negative--not sure why.

**Comment by samreid** [comment]
@arouinfar this is a large change to the model physics near the boundaries, can you please test it out and make sure it seems reasonable?

**Comment by arouinfar** [comment]
@samreid I tested all three screens, and things look reasonable to me.
