### ISSUE TITLE
Pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#202]
@samreid here are my recommended tweaks to [dev.44](https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.44/phet/wave-interference_en_phet.html)

- [x] Distance and time scale indicators should have the same font size, let's try 14 pt
- [x] Center-align playback controls with lattice, and bottom-align with resetAllButton. This will still leave enough room for the barrier arrow, as well as the top/side view controls
![image](https://user-images.githubusercontent.com/8419308/49541267-8b8bb200-f88f-11e8-8186-7d63f79fd757.png)
- [x] Panel corners look a bit too rounded, reduce corner radii a few steps
- [x] Left-align checkboxes/radio buttons with sliders 
![image](https://user-images.githubusercontent.com/8419308/49541301-a52cf980-f88f-11e8-992e-2ca4efae96db.png)
- [x] Frequency/Amplitude slider titles and tick labels are too close. Shift slider down a few pixels from the titles, but maintain relative vertical spacing of everything else in this panel.
- [x] Similar to the above request, increase padding between numberControl titles and slider
- [x] Slightly increase font size of all slider tick labels and numberControl readouts
- [x] Increase vertical padding between all Slit Width/Slit Separation numberControls. Try to match the padding between the Frequency/Amplitude sliders on Waves.

**Comment by samreid** [comment]
> time controls should be bottom-align with resetAllButton.

That was already implemented, let me know if it looked incorrect or if I need to adjust it.

**Comment by samreid** [comment]
> Left-align checkboxes/radio buttons with sliders

I presume you mean the aqua radio buttons and not the scene radio buttons.

**Comment by samreid** [comment]
I addressed each of the checkboxes, with a few notes and questions in my preceding comments.  @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
@samreid everything's looking nice!

> time controls should be bottom-align with resetAllButton.

I had remembered in #189 that the playback controls weren't bottom-aligned with resetAllButton, but didn't confirm that in dev.44.  The current alignment looks great!

> I presume you mean the aqua radio buttons and not the scene radio buttons.

Correct! I could have been clearer in my original request. :)

I am noticing that there's some shifting in the numberControls between the scenes. It's particularly noticeable for the Slit Separation numberControl. It looks a bit odd, so I'm wondering if there's anything that can be done to clean things up. My guess is that the varying string sizes shifts things around. Ideally, "Separation" and the tweakers wouldn't shift, but not sure if anything can be done here @samreid.

![numbercontrol](https://user-images.githubusercontent.com/8419308/49676286-51a8e000-fa36-11e8-9558-6086f3abd452.gif)

**Comment by samreid** [comment]
Thanks @arouinfar, I'll move that last point to a new issue.  Can this one be closed?
