### ISSUE TITLE
Anything else to complete before initial dev testing?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#203]
All of the critical issues I'm aware of have been addressed.  The main outstanding issues are:

https://github.com/phetsims/wave-interference/issues/202
https://github.com/phetsims/wave-interference/issues/142
https://github.com/phetsims/wave-interference/issues/54

It would be nice to solve these before initial dev testing, but they appear limited in scope, such as tweaking an independent value for the wave coloring, changing icons, or pixel polishing.  It would be nice if they were complete before first dev testing, but not essential.

However, it would be good to have either (a) a design team meeting to look through the sim and make sure there are no other issues and/or (b) to have @arouinfar spend 1-2 hours with the sim to make sure there's nothing else to address before dev testing.  That latter part may overlap somewhat with #202 "pixel polishing".

@ariel-phet and @arouinfar can you discuss how you would like to proceed and when we should schedule initial dev testing?

**Comment by arouinfar** [comment]
@samreid I've commented on #54 and #142, and I can take care of #202 by the early afternoon.

**Comment by ariel-phet** [comment]
@samreid nothing else comes to mind for me in terms of an initial dev test.

**Comment by arouinfar** [comment]
@samreid I recommended some pixel polishes in #202. I also spent quite a bit of time with the sim today, and the only other issue I ran into was #205.

**Comment by samreid** [comment]
We decided to aim for Friday December 14 to begin dev testing.

**Comment by samreid** [comment]
All known work tracked in other issues, closing.
