### ISSUE TITLE
Create a dev version for @arouinfar

### ISSUE THREAD

**Issue by zepumph** [phetsims/wave-interference#204]
@samreid posted on slack:

```
Sam Reid [09:23]
I’m out of the office for the moment, can someone publish a phet brand dev version of wave interference and notify @arouinfar ? Thanks!
```

I'm on it!

**Comment by zepumph** [comment]
Here you are @arouinfar. 

https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.44/phet/wave-interference_all_phet.html

**Comment by arouinfar** [comment]
Excellent, thanks @zepumph!
