### ISSUE TITLE
Constrain tools to visible bounds

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#205]
@samreid it's currently possible to completely lose the tools by dragging them out of the window bounds.

For an example of the desired behavior, test the ruler, stopwatch, and period timer on the [Lab Screen](https://phet.colorado.edu/sims/html/pendulum-lab/latest/pendulum-lab_en.html?screens=3) of Pendulum Lab.

**Comment by arouinfar** [comment]
If this is a quick fix, it would be nice to address before #203.

**Comment by samreid** [comment]
Measuring tape doesn't currently support the "edge-based" drag constraint--it is constrained based on the measuring tape body cross-hairs.  Should we open an issue to change this in scenery-phet?

**Comment by samreid** [comment]
I've constrained all objects to the visible bounds and made them stay in bounds as the window reshapes.  There are two oddities, both regarding the Measuring Tape common code component.  It does not keep its full bounds in the play area--only its cross-hairs.  Also, when the window reshapes, the measuring tape cross-hairs stays in the play area, but it can rotate if its draggable tip goes further out of bounds.

Should we work on this before dev testing or 1.0?  The primary cost would be adding this feature, possibly upgrading drag listeners for the MeasuringTapeNode.  The secondary cost (may exceed the primary cost) would be making sure the half-a-dozen or so sims that already use MeasuringTapeNode remain in working and acceptable condition.

**Comment by arouinfar** [comment]
@samreid the MeasuringTapeNode is master is still retrievable (by dragging the crosshairs attached to the body), so I don't think it's a problem that the body goes off-screen. In some sims, that may actually be advantageous.
![image](https://user-images.githubusercontent.com/8419308/49677944-afd9c100-fa3e-11e8-9358-da780ef29523.png)

> Also, when the window reshapes, the measuring tape cross-hairs stays in the play area, but it can rotate if its draggable tip goes further out of bounds.
> Should we work on this before dev testing or 1.0?

The rotating also seems fine to me @samreid. The goal is to keep the tool in-bounds so that users don't have to reset the sim to get the tool back. I don't think we need to tweak the common code for 1.0.  However, it might be better to limit MeasuringTapeNode to `?dev` rather than the visible bounds. Realistically, users won't need to measure anything beyond the lattice, anyway.

The probes on the Wave Detector tool can still be lost out-of-bounds, though. It looks like you had a method for handling this in Bending Light, and I think the same logic could be applied here.

**Comment by samreid** [comment]
I used the same behavior from bending light to keep the probes in bounds when their corresponding body is being dragged.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
The Wave Detector looks good, @samreid.

Can you update the bounds of the MeasuringTapeNode to `?dev` rather than the visible bounds?

**Comment by samreid** [comment]
Will it be inconsistent for some of the tools to be limited by `?dev` and some to be limited by the visible bounds?  It seems you are recommending this to help keep the measuring tape closer to the area where it will be useful, but I were a student seeing the measuring tape hitting an invisible wall I would probably suspect it was a bug.

**Comment by arouinfar** [comment]
I think the nature of the MeasuringTapeNode is a bit different, as the tool body needs to be on top of the area it is measuring. This is not the case for the TimerNode or the body of the Wave Detector. Allowing the TimerNode or Wave Detector to be dragged out of `?dev` allows these tools to be placed somewhere where they they won't occlude other UI components (for most users, at least).

For consistency, I'd be fine with letting MeasuringTapeNode be restricted to the visible bounds, since it'd still be retrievable. Aside from consistency, I don't think there is any particular advantage to allowing it outside of `?dev` though.

@samreid I'll let you make the call.

**Comment by samreid** [comment]
I agree the measuring tape can only be useful for measuring things in the wave area, but it seems like a non-productive constraint to limit it to the dev bounds--I expect it would be perceived as buggy and inconsistent.

> Allowing the TimerNode or Wave Detector to be dragged out of ?dev allows these tools to be placed somewhere where they they won't occlude other UI components (for most users, at least).

The same argument could be made about the measuring tape--it could be used over the wave area for a measurement, then moved out of the dev bounds (out of the way) temporarily while the user focuses on other aspects.

> @samreid I'll let you make the call.

I recommend to close for now, but I'm happy to discuss further if desired.
