### ISSUE TITLE
Low amplitude light looks really problematic

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#206]
First observed by @phet-steele, in what I assume was dev.44. (Screenshots below are from dev.44.)

If the amplitude is below the first tick mark, the light wave looks pretty awful, and it does not propagate across the lattice. While this looks buggy, I'm not particularly sure that this is actually a bug, but rather a consequence of choosing black to represent an empty light lattice. For Water and Sound, an empty lattice is represented by the color for zero amplitude (mid-blue or mid-gray, respectively). For Light, we chose to use black to represent an empty lattice, which is actually the color representing -1 amplitude. 

| Amplitude | Water | Sound | Light |
|---|---|---|---|
| ![image](https://user-images.githubusercontent.com/8419308/49600343-365ba900-f940-11e8-909f-b80a7bc9fc76.png) | ![image](https://user-images.githubusercontent.com/8419308/49600367-483d4c00-f940-11e8-8525-66041571cc03.png) | ![image](https://user-images.githubusercontent.com/8419308/49600477-889cca00-f940-11e8-8543-0f6821af7a5a.png) |![image](https://user-images.githubusercontent.com/8419308/49600827-622b5e80-f941-11e8-9e77-8f597a6360cd.png)|
| ![image](https://user-images.githubusercontent.com/8419308/49600601-cf8abf80-f940-11e8-8fd9-af19a282031b.png) | ![image](https://user-images.githubusercontent.com/8419308/49600632-e29d8f80-f940-11e8-8e42-09df7b116dec.png) | ![image](https://user-images.githubusercontent.com/8419308/49600710-0fea3d80-f941-11e8-9419-1d07402c1cbc.png) |  ![image](https://user-images.githubusercontent.com/8419308/49600787-40ca7280-f941-11e8-969b-b567269c463a.png)
| ![image](https://user-images.githubusercontent.com/8419308/49600973-d1a14e00-f941-11e8-98a1-c16800e2b911.png)| ![image](https://user-images.githubusercontent.com/8419308/49600870-86873b00-f941-11e8-8011-d58905a80a94.png) | ![image](https://user-images.githubusercontent.com/8419308/49601032-f8f81b00-f941-11e8-9cff-e660bf0fb279.png) | ![image](https://user-images.githubusercontent.com/8419308/49601078-10cf9f00-f942-11e8-91e9-d8f78b7eb903.png)|
| ![image](https://user-images.githubusercontent.com/8419308/49601125-352b7b80-f942-11e8-9b04-7d10e9f1dcd3.png) | ![image](https://user-images.githubusercontent.com/8419308/49601135-3eb4e380-f942-11e8-8a65-afbd666304b3.png) |  ![image](https://user-images.githubusercontent.com/8419308/49601152-4a080f00-f942-11e8-9dec-dac7a4f8ecb5.png) | ![image](https://user-images.githubusercontent.com/8419308/49601174-54c2a400-f942-11e8-821a-adbef425de04.png)|

A strange side effect of this issue is that reducing the amplitude leaves the strange silhouette.

Letting the wave propagate from startup, with an amplitude just below the 1st tick, the wave gets stuck here:
![image](https://user-images.githubusercontent.com/8419308/49601776-fdbdce80-f943-11e8-9c52-875a56ce7551.png)

Reducing the amplitude to just above zero, the wave will be visible throughout the silhouette, which is a bigger portion of the lattice than in the table above.
![image](https://user-images.githubusercontent.com/8419308/49601745-eb439500-f943-11e8-9ec2-526126df9dfd.png)

**Comment by arouinfar** [comment]
Looks like this was present in Java too.

![light_java](https://user-images.githubusercontent.com/8419308/49602473-c9e3a880-f945-11e8-8ab4-a176c2ccb89d.gif)

**Comment by samreid** [comment]
I changed the threshold, back to @arouinfar and @phet-steele

**Comment by samreid** [comment]
Also self-assigning in case I want to tinker with the threshold to avoid diamonding.

**Comment by samreid** [comment]
I found a better threshold that avoids diamonds while still having the desired behavior at extremely low amplitude.  Leaving assigned to @arouinfar and @phet-steele to test.

**Comment by arouinfar** [comment]
@samreid 10^-3 is definitely looking nicer than 10^-6. A tradeoff of reducing the threshold is that lattice cells will illuminate a bit earlier, creating a less-clean looking halo around the initial wavefront. However, I think this is a reasonable compromise.

Here's what 10^-3 looks like:
<img src="https://user-images.githubusercontent.com/8419308/49669064-58772900-fa1d-11e8-9c49-7382e9aa6ecf.png" width=200>

**Comment by samreid** [comment]
@arouinfar said:

> Amy Rouinfar [5:14 PM]
Steele said he was waiting for a dev test to confirm 206

**Comment by samreid** [comment]
@phet-steele the dev test version has been available for several weeks.  Can you please take a look?

**Comment by phet-steele** [comment]
It's goooood! ( I checked 1.0.0-dev.56)
