### ISSUE TITLE
Plane wave edge sometimes has leading edge flicker

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#207]
Figure out leading edge flicker on plane wave
 - should not delay dev testing, may publish 1.0 with this flicker

**Comment by samreid** [comment]
It can be instructive to set to Light (red wavelength) and use pause/step.

**Comment by samreid** [comment]
There was a flaw in the phase calculation, and also a leakage in the numerical integration.  Looks much better now on my side, @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
Looks beautiful @samreid!
