### ISSUE TITLE
Reduce initial slit width so that the light intensity screen doesn't wash out in initial conditions

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#209]
From today's meeting, we saw that the default slit aperture was so wide that the light screen washed out.  We want to reduce that value so the default conditions are more sensible.  In another issue we will also be adding an amplitude slider to this screen.

**Comment by samreid** [comment]
Committed proposed value.  Note: I applied a change only to the light scene (not water or sound) and this changes the initial value for both single slit and double slits.  Works well in my testing, @arouinfar can you please take a look and advise?

**Comment by arouinfar** [comment]
@samreid looks good!
