### ISSUE TITLE
Can/should we remove the graph title?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#21]
From https://github.com/phetsims/wave-interference/issues/20#issuecomment-370949324

It's unclear why we need to repeat "Water Height" twice.  Why not remove the top label?  It seems "Water Height" is redundant, and "at Center" is already covered by the dotted line (or we could include "at center" on the vertical axis).

![image](https://user-images.githubusercontent.com/679486/37061850-fb481306-2151-11e8-9cab-035d1136eac8.png)

**Comment by arouinfar** [comment]
@samreid I agree that "Water Height at Center" is redundant, but we wanted to make the connection between the two white dashed lines explicitly clear. I think we'll need interviews to determine if the title is overkill, or is truly helpful. I would be okay with removing the title for now, and seeing how it's interpreted in interviews. Let's discuss in design meeting.

> or we could include "at center" on the vertical axis

I see what you're getting at, but I think it may muddy the waters a bit. The curve represents displacement <i>about</i> the center line, not <i>at</i> the center line.

**Comment by samreid** [comment]
Water: 

title: Water Level at Center
axis label: Water Level

Sound: check Java, then add "at Center" for the title.

**Comment by samreid** [comment]
Implemented, closing.
