### ISSUE TITLE
On interference screen and slits screen, add "amplitude" slider directly under the frequency slider.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#210]
On interference screen and slits screen, add "amplitude" slider directly under the frequency slider.  Make sure it affects both sources on the interference screen.

**Comment by samreid** [comment]
Due to the nature of the model, changing the amplitude of the plane wave changes it everywhere to the left of the slits.  Perhaps this is one of the reasons we originally omitted the amplitude control on this screen.  Our options:

(a) add the amplitude slider to the slits screen, and let it change the amplitude everywhere (0 hours)
(b) omit the amplitude slider from the slits screen (0 hours)
(c) write a new part of the slits screen model that keeps track of the amplitudes as a function of time so the amplitude applies to the place where the wave is generated (2-4 hours?)

@arouinfar how would you like to proceed?

**Comment by samreid** [comment]
This is committed so you can review and test (a), but note that it is not wired up for water--only wired up for sound and light.  If we keep (a), then I'll need to spend 20 minutes or so wiring it up to the WaterScene.desiredAmplitudeProperty.

**Comment by arouinfar** [comment]
@samreid I think option (a) is perfectly fine, and is looking nice in master. I'll make a note to add this to the teacher tips, though.

**Comment by samreid** [comment]
I wired this up to water as well, @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
Looks good!
