### ISSUE TITLE
Set the default light frequency to green

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#211]
Set the default light frequency to green, in the middle of the available spectrum.

@arouinfar can you please confirm this is a desired feature?  I recalled we discussed about it but I hadn't written it down and just wanted to double check.

Will we need to re-tune values around the new defaults?

**Comment by arouinfar** [comment]
@samreid the motivation for changing the color to green was that it has a nicer pop against the black background. I tested to new defaults in #209 with the frequency at ~50%  (green) and things still look nice to me.

Please change the initial light frequency to 50%.

**Comment by samreid** [comment]
Proposed fix in preceding commits, @arouinfar can you please double check on phettest?

**Comment by arouinfar** [comment]
👍
