### ISSUE TITLE
MeasuringTapeNode's state is saved when retrieved from toolbox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#215]
When reviewing #205, I noticed that the MeasuringTapeNode remembers how it was returned to the toolbox. The next time it is pulled out of the toolbox, it will have the same configuration.
![mtn](https://user-images.githubusercontent.com/8419308/49677703-73599580-fa3d-11e8-81f9-85fa27422e97.gif)

I do not find this to be particularly useful, and is contrary to how MeasuringTapeNode has behaved elsewhere (such as Projectile Motion).  The TimerNode and Wave Detector tool both reset when returned to the toolbox, so I think the MeasuringTapeNode should also return to its default configuration.

**Comment by samreid** [comment]
Proposed fix committed, @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
@samreid I pulled all, and the measuring tape still behaves like the .gif in https://github.com/phetsims/wave-interference/issues/215#issue-388850870.

**Comment by arouinfar** [comment]
Thanks @samreid! Looks good on reset all and when retrieving from the toolbox.
