### ISSUE TITLE
New dev version for interviews

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#216]
@samreid my first interview is scheduled for 10AM on Monday (the 2nd is at 2PM). I can use dev.44 for interviews, but there have been some great improvements made since then, so it would be nice to publish a new dev version when time allows.

The issues that would be nice to wrap up before a new dev version would be:
- [x] #208
- [x] #210 
- [x] #211

**Comment by samreid** [comment]
Here's a dev version that has proposed (but unverified) fixed for the aforementioned issues: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.45/phet/wave-interference_en_phet.html

**Comment by arouinfar** [comment]
dev.46 has been behaving nicely for me @samreid, thanks!!

**Comment by samreid** [comment]
We fixed a number of other issues in the last few commits, I'll send a new dev version in case you want to use that instead.

**Comment by arouinfar** [comment]
Great, thanks!

**Comment by arouinfar** [comment]
Thanks!
