### ISSUE TITLE
Reduce maxWidth of Top/Side View radio buttons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#217]
@samreid now that the playback controls have shifted a bit to the left, the maxWidth of the Top View/Side View strings should be a bit shorter.
![image](https://user-images.githubusercontent.com/8419308/49709785-49e26a80-fbf3-11e8-951e-a4c2730a6d69.png)

**Comment by samreid** [comment]
Proposed fix committed, @arouinfar please review.

**Comment by arouinfar** [comment]
👍
