### ISSUE TITLE
Oscillator button pressed but no waves coming out.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#219]
Sometimes when switching scenes and turning things on and off, you can get into a scenario with the oscillator button pressed but no waves coming out.  I saw this several months ago but could not reproduce the problem.  @arouinfar saw it in an interview today.

Here's our slack chat:

> Amy Rouinfar [5:12 PM] I did run into a weird bug (that I haven’t since been able to reproduce, so no issue yet) where the lasers would be on, but wouldn’t emit any light. For example, a student might be experimenting with Water or Sound, and then switch to Light and turn on the laser, but nothing would come out.
> 
> I think it’s some sort of strange edge case, though, because students switched between scenes many, many times and didn’t encounter this issue more than once or twice.
> 
> Sam Reid [5:12 PM]
Oh no, I saw something like that weeks ago but haven’t been able to reproduce it.
Maybe QA dev test will help us narrow down how to create that case?
> 
> Amy Rouinfar [5:13 PM]
I hope so!
I still need to review the screencaptures for the interview notes, so I’ll see if I find any clues there

Self assigning for testing and to remind me to put this on QA team radar during dev testing.  Assigning to @arouinfar to look for clues in the screen captures.

**Comment by samreid** [comment]
Fuzzing and pausing again reveals a similar error case:

![image](https://user-images.githubusercontent.com/679486/49777324-487d7480-fcbd-11e8-8428-aaf56fb0bf0d.png)

Note the waves are nonzero even though they cannot be seen, and the light screen is visible beneath the wave area.

**Comment by samreid** [comment]
Steps to reproduce the problem:

1. Go to sound scene and select "particles"
2. Go to any other scene and start the wave.

Not shown due to faulty logic in WavesScreenView.js

**Comment by arouinfar** [comment]
@samreid I tested the steps in https://github.com/phetsims/wave-interference/issues/219#issuecomment-446066301 in dev.47 (version used in interviews) and could reliably reproduce the bug, but it no longer appears to be on master. Reviewing the screen capture footage, I think this was the same bug, because the student had switched to light after looking at the particle view of sound.
