### ISSUE TITLE
Color coding for the probe sensor

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#22]
The mockup shows the probe sensor like this:

![image](https://user-images.githubusercontent.com/679486/37076383-9a6c8a20-2193-11e8-8857-f33ff6c05df8.png)

I wonder if we should colorize the probes/wires and the lines on the chart to indicate which is which (or some other way to distinguish them).

**Comment by samreid** [comment]
I noticed the other icon shows the probes as different colors:

![image](https://user-images.githubusercontent.com/679486/37076591-8a0a5710-2194-11e8-8236-b4745d22b2ba.png)

**Comment by arouinfar** [comment]
@samreid the mockup is very much a wireframe. I reused a common .ai asset for the probe, which is why it's green and doesn't have the proper crosshairs.

Please use the probe color/style used in the wave detector in Bending Light.

**Comment by arouinfar** [comment]
The probes, wires, and associated curve are all color-coordinated -- one darker gray, and one lighter gray.

![image](https://user-images.githubusercontent.com/8419308/37111962-66c40610-21fe-11e8-9bc4-0e2bf3928eba.png)

**Comment by samreid** [comment]
I made the probes gray in the above commit, we'll close for now and create a new issue if fine-tuning is needed.
