### ISSUE TITLE
Sometimes the RoundStickyPushButton highlights wrong

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#228]
Discovered during https://github.com/phetsims/wave-interference/issues/227.  Sometimes the highlight looks like "pressed" instead of "shiny"

![button-highlight](https://user-images.githubusercontent.com/679486/49834040-a90dbf80-fd58-11e8-9669-80ce5e333044.gif)

**Comment by samreid** [comment]
It seems that `StickyToggleButtonInteractionStateProperty.buttonModel.looksPressedProperty` is somehow true for this case, will require further investigation.

**Comment by samreid** [comment]
Here's the docs for `looksPressedProperty`

```js
    // @public - This Property was added for a11y. It tracks whether or not the button should "look" down. This
    // will be true if downProperty is true or if an a11y click is in progress. For an a11y click, the listeners
    // are fired right away but the button will look down for as long as PressListener.a11yLooksPressedInterval.
    // See PressListener.click for more details.
    this.looksPressedProperty = new BooleanProperty( false );
```

Assigning @jessegreenberg for investigation.

**Comment by jessegreenberg** [comment]
This should be fixed in master, @samreid can you please confirm?

**Comment by samreid** [comment]
I can't seem to break it any more, thanks for the fix!
