### ISSUE TITLE
TimerNode button not working on iPad2

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#23]

**Comment by samreid** [comment]
This problem can be replicated by using the device toolbar in chrome dev tools.

If you comment out this line in WaveInterferenceTimerNode.js, the problem goes away:

```js
this.addInputListener( this.timerNodeDragListener );
```

But then, the Node doesn't drag any longer after you move it from the toolbox to the play area and release it.  @jonathanolson can you please review and advise?

**Comment by jonathanolson** [comment]
Hmm, it isn't well documented that it's needed, but wave-on-a-string uses the dragTarget instead, so things work when you replace the mentioned code with:

```js
this.dragTarget.addInputListener( this.timerNodeDragListener );
```

Thoughts?

**Comment by samreid** [comment]
After the above commit, I'm using dragTarget.addInputListener and it's working fine.  At a minimum, I'd like to understand why this pattern is used here to help understand where else it may be effective/necessary.  I'll create a scenery-phet issue for that discussion.  Closing.
