### ISSUE TITLE
Timer resets when scene changes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#231]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/238
On the wave screen, when switch from one type of wave to another, and then back, the timer will have reset itself.  This may be intended or unavoidable.  If so, please close.
**Steps to reproduce:**
1. Go to wave screen and start timer.  Note the type of wave (water, light, sound)
2. While timer is still running, go to another type of wave
3. Go back to the type of wave from step 1.  While the wave from earlier will still be going, the timer will be back at zero.

**Screenshots:**
![resetingthetimer](https://user-images.githubusercontent.com/41024075/49889126-f7c16500-fdfd-11e8-94ca-171a6172c3bb.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.51/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.51 2018-12-12 03:47:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"73e761ec","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"61bc739b","branch":"master"},"dot":{"sha":"b45eafe8","branch":"master"},"griddle":{"sha":"914c9215","branch":"master"},"joist":{"sha":"5a013a46","branch":"master"},"kite":{"sha":"f3e96e5b","branch":"master"},"phet-core":{"sha":"86dec8cc","branch":"master"},"phet-io":{"sha":"a267fdb1","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"d5b42848","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"e4f9e8e8","branch":"master"},"scenery":{"sha":"a18ce7f1","branch":"master"},"scenery-phet":{"sha":"56df5b6d","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"38ed71af","branch":"master"},"tambo":{"sha":"746fbd32","branch":"master"},"tandem":{"sha":"c7a56e2e","branch":"master"},"twixt":{"sha":"e38c70ed","branch":"master"},"wave-interference":{"sha":"bfce593d","branch":"master"}}

</details>

**Comment by phet-steele** [comment]
> @samreid is it possible to reset the timer when the scene changes?

Since I was confused by this question, maybe other people will be too! I asked @arouinfar on slack, and what she wants is a cleared, paused timer on a scene change, as if the u-shaped reset button were pressed.

**Comment by samreid** [comment]
Proposed fix pushed, @KatieWoe can you please test on phettest?

**Comment by KatieWoe** [comment]
Seems to behave well on master

**Comment by samreid** [comment]
Closing so this will show red on the QA issue.  We can verify in the next dev test or RC if necessary.
