### ISSUE TITLE
Possible for drop to be above faucet

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#232]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/238
It is possible to have a drop of water falling above the faucet it came from.  Due to the nature of how this is achieved, it may be acceptable or unavoidable.
**Steps to reproduce:**
1. Go to the Interference screen and the water scene
2. Separate the faucets as much as possible and start the water
3. Pause the sim (not necessary but makes observation and set up easier)
4. Advance sim until a drop is visible after falling from the top faucet
5. Bring the faucets as close together as possible, observe the drop
6. Press play on the sim

**Screenshots:**
![dropabove](https://user-images.githubusercontent.com/41024075/49892352-03b12500-fe06-11e8-9608-51f752ce2eef.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.51/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.51 2018-12-12 03:47:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"73e761ec","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"61bc739b","branch":"master"},"dot":{"sha":"b45eafe8","branch":"master"},"griddle":{"sha":"914c9215","branch":"master"},"joist":{"sha":"5a013a46","branch":"master"},"kite":{"sha":"f3e96e5b","branch":"master"},"phet-core":{"sha":"86dec8cc","branch":"master"},"phet-io":{"sha":"a267fdb1","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"d5b42848","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"e4f9e8e8","branch":"master"},"scenery":{"sha":"a18ce7f1","branch":"master"},"scenery-phet":{"sha":"56df5b6d","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"38ed71af","branch":"master"},"tambo":{"sha":"746fbd32","branch":"master"},"tandem":{"sha":"c7a56e2e","branch":"master"},"twixt":{"sha":"e38c70ed","branch":"master"},"wave-interference":{"sha":"bfce593d","branch":"master"}}

</details>

**Comment by arouinfar** [comment]
@KatieWoe thanks for reporting, but I do not actually think this is a problem. The drop in your screenshot originated from the source that was further up. The next drop will originate from the sources's new location. The user had to take an action to move the water source down, so I don't think it will be strange to temporarily see a water drop above the source. 

If we wanted to address this sort of issue, then we would need to change an already-emitted water drop's location, speed, or size based on some other condition in the sim being changed. To me, that's unintuitive and would look buggy, so closing.
