### ISSUE TITLE
Jagged curves on graph when frequency is high

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#234]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/238
The graph of a wave down the center can be rather jabbed, particularly when the frequency is high as with the blue colors of light.  @arouinfar asked for an issue to see if it could be cleaned up, but it may not have enough points and so it may not be possible.
**Steps to reproduce:**
1. Go to the Slits screen (waves stay larger for longer, so its easier to see)
2. Go to the light scene and set the frequency as either a blue or a violet
3. Start the wave and turn on the graph

**Screenshots:**
![pointy](https://user-images.githubusercontent.com/41024075/49900967-46cac280-fe1d-11e8-9a17-8752c182d641.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.51/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.51 2018-12-12 03:47:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"73e761ec","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"61bc739b","branch":"master"},"dot":{"sha":"b45eafe8","branch":"master"},"griddle":{"sha":"914c9215","branch":"master"},"joist":{"sha":"5a013a46","branch":"master"},"kite":{"sha":"f3e96e5b","branch":"master"},"phet-core":{"sha":"86dec8cc","branch":"master"},"phet-io":{"sha":"a267fdb1","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"d5b42848","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"e4f9e8e8","branch":"master"},"scenery":{"sha":"a18ce7f1","branch":"master"},"scenery-phet":{"sha":"56df5b6d","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"38ed71af","branch":"master"},"tambo":{"sha":"746fbd32","branch":"master"},"tandem":{"sha":"c7a56e2e","branch":"master"},"twixt":{"sha":"e38c70ed","branch":"master"},"wave-interference":{"sha":"bfce593d","branch":"master"}}

</details>

**Comment by samreid** [comment]
If I recall correctly, we experimented with different smoothing strategies and found this was preferable.  There is a very small number of cells in the lattice that is used to generate the curve--I'm not sure what else we can do with this.  @arouinfar any thoughts?

**Comment by arouinfar** [comment]
I asked @KatieWoe to open this issue so I could hear @samreid's thoughts on the issue. Thanks for jogging my memory @samreid. Light suffers more than the other scenes because the wavefronts are more closely spaced, but I agree that there isn't anything else we can do here.
