### ISSUE TITLE
Two lines on intensity graph

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#235]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/238
When there is no barrier on the Slits screen when using light, the intensity graph can show two lines that move and shift around.
**Steps to reproduce:**
1. Go to the Slits screen
2. Go to the Light scene
3. Select the No Barrier option
4. Turn on the screen and the intensity
5. Start the wave
6. When the line leaves the graph, adjust the graphs size with the + and - buttons.  The effect will be visible
7. This phenomenon seems to come and go at different zooms, so it may be helpful to pause the sim and zoom in and out until you see it.

**Screenshots:**
![toointense](https://user-images.githubusercontent.com/41024075/49905701-fb6be080-fe2b-11e8-83ae-6ac2d1ef4cd9.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.51/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.51 2018-12-12 03:47:24 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"73e761ec","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"61bc739b","branch":"master"},"dot":{"sha":"b45eafe8","branch":"master"},"griddle":{"sha":"914c9215","branch":"master"},"joist":{"sha":"5a013a46","branch":"master"},"kite":{"sha":"f3e96e5b","branch":"master"},"phet-core":{"sha":"86dec8cc","branch":"master"},"phet-io":{"sha":"a267fdb1","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"d5b42848","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"e4f9e8e8","branch":"master"},"scenery":{"sha":"a18ce7f1","branch":"master"},"scenery-phet":{"sha":"56df5b6d","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"38ed71af","branch":"master"},"tambo":{"sha":"746fbd32","branch":"master"},"tandem":{"sha":"c7a56e2e","branch":"master"},"twixt":{"sha":"e38c70ed","branch":"master"},"wave-interference":{"sha":"bfce593d","branch":"master"}}

</details>

**Comment by KatieWoe** [comment]
Note: These lines stay around if you add a barrier restart the the light generator, etc.  One can even stay as a new graph is being formed until the new graph reaches the height of that line.

**Comment by samreid** [comment]
Does this occur on other platforms?  I'm unable to see the problem on Mac/Chrome or Mac/Firefox.

**Comment by samreid** [comment]
I was able to reproduce the problem on Win/Firefox.  I even got up to 3 lines!!!  And it appeared that only one of the lines was animated at a time.

**Comment by KatieWoe** [comment]
Just checked on Win 10 firefox in master and this seems to be fixed.

**Comment by samreid** [comment]
Thanks @KatieWoe, closing.
