### ISSUE TITLE
Water drop doesn't create a wave when switching continuous to pulse

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#236]
From https://github.com/phetsims/wave-interference/issues/230 and may be related, 

Waves screen
Pulse mode
Press faucet button
While drop is falling, switch to continuous mode.

Why does this trigger a wave?  Should the water drop keep falling?

**Comment by samreid** [comment]
In slow motion, I can see this is the desired behavior--the drop continues falling and creates the wave.  However, now I'm seeing the opposite problem:

Waves Screen
Continuous Mode
Press faucet button
While drop is falling, switch to continuous mode

Why doesn't this trigger a wave?

**Comment by samreid** [comment]
I thought it would be simplest and clear enough to consistently clear falling drops when switching between pulse and continuous.  @arouinfar can you please test this and make sure nothing else was disturbed?

**Comment by arouinfar** [comment]
Seems to be working nicely @samreid.
