### ISSUE TITLE
Cut off dots on wave examiner

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#238]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
firefox (not seen in chrome or edge)
**Problem description:**
For https://github.com/phetsims/QA/issues/238.  May be related to https://github.com/phetsims/wave-interference/issues/235 but it isn't fixed in master.
The dark and light grey dots on the wave examiner tool get cut in half at the last vertical line.  This leaves half of the dot behaving normally and the other half remaining in place.  This is not effected by screen or scene.  The frozen half dot moves up or down to a new frozen position when the target tools are moved.
**Steps to reproduce:**
1. Open the sim on firefox and go to any screen and scene
2. Pull out the wave examiner tool
3. Start a wave and make sure the targets are in position to pick it up
4. Move one of the targets to a new location

**Screenshots:**
![halfdot](https://user-images.githubusercontent.com/41024075/49951969-682cbc80-feb8-11e8-95a2-d9b9222ac2b6.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.51/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.51 2018-12-12 03:47:24 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"73e761ec","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"61bc739b","branch":"master"},"dot":{"sha":"b45eafe8","branch":"master"},"griddle":{"sha":"914c9215","branch":"master"},"joist":{"sha":"5a013a46","branch":"master"},"kite":{"sha":"f3e96e5b","branch":"master"},"phet-core":{"sha":"86dec8cc","branch":"master"},"phet-io":{"sha":"a267fdb1","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"d5b42848","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"e4f9e8e8","branch":"master"},"scenery":{"sha":"a18ce7f1","branch":"master"},"scenery-phet":{"sha":"56df5b6d","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"38ed71af","branch":"master"},"tambo":{"sha":"746fbd32","branch":"master"},"tandem":{"sha":"c7a56e2e","branch":"master"},"twixt":{"sha":"e38c70ed","branch":"master"},"wave-interference":{"sha":"bfce593d","branch":"master"}}

</details>

**Comment by samreid** [comment]
Does this happen on Mac Firefox?

**Comment by KatieWoe** [comment]
Just checked 10.14 Firefox and it did not.

**Comment by KatieWoe** [comment]
@samreid it _is_ on Mac.  I just realized that the Mac I had tested on was not up to date.  Version it worked on = 63.0.3.  After update (64.0) it is broken.

**Comment by samreid** [comment]
Same for me:

Working in Mac Firefox 63.0.3 (64-bit)
Broken on Mac Firefox 64.0 (64-bit)

**Comment by samreid** [comment]
![waves-ok](https://user-images.githubusercontent.com/679486/49976930-58859600-ff01-11e8-956a-f2ce4a0df23a.gif)

**Comment by samreid** [comment]
![waves-broken](https://user-images.githubusercontent.com/679486/49976938-6509ee80-ff01-11e8-87ba-72d2743011a0.gif)

**Comment by samreid** [comment]
Proposed workaround committed, @KatieWoe can you please test?

**Comment by KatieWoe** [comment]
I am now see this happening at the top of the graph.  Not fixed
![uptop](https://user-images.githubusercontent.com/41024075/50012999-434e4d00-ff7d-11e8-97ae-ab1e7fb14f6f.PNG)

**Comment by samreid** [comment]
@jonathanolson can we schedule a time to investigate this?

**Comment by kathy-phet** [comment]
@samreid - Since Firefox introduced this bug, lets not prioritize it for v1. We can fix it if firefox doesn't fix it by v2 perhaps.

**Comment by kathy-phet** [comment]
But perhaps undo the last commit, because it made it worse.

**Comment by samreid** [comment]
Reverted, putting on hold until 2.0.

**Comment by KatieWoe** [comment]
@samreid @ariel-phet  I saw something new in https://github.com/phetsims/QA/issues/264 on firefox.  Sometimes it appears as above, but I have also seen the dots remain intact but appear to be passing behind some object at certain points.  This was seen on the Waves screen, light scene, when the graph is selected.  I believe the graph is the determining factor.  I doubt this changes the priority at all.
![connectedweirdness](https://user-images.githubusercontent.com/41024075/51560569-145fac80-1e42-11e9-954c-9bbe69f338d1.jpg)

**Comment by KatieWoe** [comment]
@samreid @ariel-phet 
Firefox 65 was just released and I checked this issue out of curiosity.  It does seem to have resolved itself (I only looked for a few seconds).  Would you like this issue closed?

**Comment by samreid** [comment]
I tested on Mac/Firefox 65 and I also don't see the problem.  I think it would be OK to close this issue, but let's double check with @ariel-phet first.

**Comment by ariel-phet** [comment]
Agreed, closing
