### ISSUE TITLE
Move the probe sensor tool to common code

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#24]
This tool is used in Bending Light and now Wave Interference.  It would be good to generalize and move to common code.

@ariel-phet and @arouinfar can you think of any other existing or upcoming sims with this kind of measuring tool?

![image](https://user-images.githubusercontent.com/679486/37220245-456c0ea0-2383-11e8-9801-16fe1a4db047.png)

In the common code, should I make it:
1. Always have 2 probes
2. Optionally have 1-2 probes
3. Have any number of probes

Any other features to consider as I'm commonizing it?  I'll probably move this to scenery-phet.  We'll need to re-test Bending Light to get this working.  Please reassign to me after responding.

Any suggestions for a name? Currently it is called ChartToolNode in Wave Interference and IntensityMeterNode in Bending Light.

**Comment by ariel-phet** [comment]
@samreid I think you mean a probe that includes a graph readout. So I think the title should be indicative of that. I think optionally having 1-2 probes makes sense. More than 2 would be cumbersome and likely 3 graphs on such a small window of the tool would be overload anyhow.

But I could imagine such a tool as a "non contact" oscilloscope or such in other future sims. It seems best suited to graphical readouts of an oscillatory nature, although it is not a full oscilloscope.

**Comment by arouinfar** [comment]
@samreid I think the wave detector tool is a good start, but would need extra features such as optional vertical axis and grid labels.

I agree with @ariel-phet. I think the tool should have 1-2 probes, but not more.  The only sim that I can think of that would need a similar tool would be CCK: AC. The ammeter would need one probe, and the voltmeter would need two probes which work together to produce a single curve.

![image](https://user-images.githubusercontent.com/8419308/37221499-7b18a8ac-2387-11e8-9776-74f2c1e891f9.png)

**Comment by samreid** [comment]
I'm wondering if we should split up the responsibilities into two separate things:

a) the part that combines the probe node, the wire, and a generic meter body
b) meter body content that shows the dynamic graph

The former part could be used in contexts like Beer's Law Lab or CCK, the latter would be an add-on that is used in sims like Bending Light and Wave Interference.

Or even if we decide not to reuse (a) for BLL/CCK, it could still be a good way to split up the code.

**Comment by samreid** [comment]
Here are the sims using ProbeNode, thanks binder!

![image](https://user-images.githubusercontent.com/679486/40284583-7c164868-5c4e-11e8-8ba1-65d751d9e182.png)

**Comment by samreid** [comment]
The wave sensor in Wave Interference currently looks like this:

![image](https://user-images.githubusercontent.com/679486/43755036-2f357f36-99cb-11e8-868a-dcf35d45c4d8.png)

The dots remain at the right like pens on a seismograph, and the paper scrolls to the left underneath it. This sim has a custom time scale indicator, which we may want to reuse in other sims.

I'd love some discussion/guidance about what should go in common code.  Should the scrolling graph component go into griddle?  If so, should it support axis labels, scale indicators, tick labels, the works?  Or just the graph part and subclasses would be responsible for axes/ticks/zoom buttons or decorations like that?

Or should common code have the entire component, including options for where the wires connect to the body, and options for the probes and everything?

The implementation for Wave Interference is currently in https://github.com/phetsims/wave-interference/blob/master/js/common/view/WaveDetectorToolNode.js and contains some custom logic for reading values out of the wave lattice.

**Comment by jonathanolson** [comment]
Without going into detail, I don't know exactly what should be in common code. Generally I'd imagine we'd have griddle common components that support scrolling graphs. We might also have a general "thing with probes" component, which can have different shapes/content.

**Comment by samreid** [comment]
@pixelzoom suggested a module for the body + probes + wires.  Content would be separate.

**Comment by arouinfar** [comment]
I know I commented on this issue a few days ago, just after @samreid's https://github.com/phetsims/wave-interference/issues/24#issuecomment-410933472. However, it looks like it didn't go through...

@samreid here's the quick summary I what I had commented:
* For Wave Detector-like tool, the dots at the end of the curve seem pretty integral to the purpose of the tool.
* Time Scale seems like a feature that could be useful elsewhere
* It would be nice to customize the probe connection point, or at least the side of the body which the probes connect on. In Wave Interference, it would be more convenient to connect the probes to the left side of the body to minimize occlusion. 

![image](https://user-images.githubusercontent.com/8419308/43918812-619d8556-9bd1-11e8-809a-84dd123aa0f0.png)

**Comment by samreid** [comment]
Would it be distracting for the connection point to adjust depending on the position of the probe?  That seems like a good general solution that could allow us to get away from having to specify defaults for every case, then have situations where the defaults don't work so well.

**Comment by arouinfar** [comment]
> Would it be distracting for the connection point to adjust depending on the position of the probe? 

I like that idea! If other devs are on board with such behavior, I'd be in favor.

**Comment by pixelzoom** [comment]
> Would it be distracting for the connection point to adjust depending on the position of the probe? 

OK, but optionally.

**Comment by samreid** [comment]
> Would it be distracting for the connection point to adjust depending on the position of the probe?

@arouinfar and I reviewed a prototype where the connection point circumnavigated the perimeter, and it was really odd and distracting.  We also tried having it flip sides, and that was also distracting.  Here's a movie of the latter:

![out](https://user-images.githubusercontent.com/679486/44118965-f4398d0e-9fd4-11e8-89b3-e4e8b3ae2db2.gif)

We decided to hardcode the connection point to be the bottom left.

**Comment by samreid** [comment]
Here's code for the flipping prototype, in case we change our minds.
```js
      const attachmentPoint = new Property( Vector2.ZERO );
      const boundsProperty = new NodeProperty( backgroundNode, 'bounds', 'bounds' );
      const normalProperty = new Property( Vector2.ZERO );

      // @private {Node}
      this.probe1Node = createProbeAndWire( SERIES_1_COLOR, WIRE_1_COLOR, 5, 10, attachmentPoint, normalProperty );
      var updateFromBounds = bounds => {
        var rightAttachmentPoint = rightBottomProperty.value.plusXY( 0, -10 );
        var leftAttachmentPoint = leftBottomProperty.value.plusXY( 0, -10 );
        var point = this.probe1Node.centerBottom;
        var d1 = point.distance( rightAttachmentPoint );
        var d2 = point.distance( leftAttachmentPoint );
        if ( d1 < d2 ) {
          attachmentPoint.value = rightAttachmentPoint;
        }
        else {
          attachmentPoint.value = leftAttachmentPoint;
        }
      };
      boundsProperty.link( updateFromBounds );
      attachmentPoint.link( attachment => {
        var bounds = boundsProperty.value;
        normalProperty.value = attachment.y === bounds.maxY ? new Vector2( 0, NORMAL_DISTANCE ) :
                               attachment.y === bounds.minY ? new Vector2( 0, -NORMAL_DISTANCE ) :
                               attachment.x === bounds.minX ? new Vector2( -NORMAL_DISTANCE, 0 ) :
                               attachment.y === bounds.maxX ? new Vector2( NORMAL_DISTANCE, 0 ) : Vector2.ZERO;

      } );

      setInterval( () => updateFromBounds( boundsProperty.value ), 10 );

      // @private {Node}
      this.probe2Node = createProbeAndWire( SERIES_2_COLOR, WIRE_2_COLOR, 36, 54,
        new DerivedProperty( [ rightBottomProperty ], position => position.plusXY( 0, -10 ) ),
        new Property( new Vector2( NORMAL_DISTANCE, 0 ) )
      );
```

**Comment by samreid** [comment]
I generalized the following common code components:

1. WireNode (currently in scenery-phet): View that typically connects a sensor (like a ProbeNode) to its body (where the readout value or chart appears).
2. MeterNode (still in Wave Interference): Depicts a draggable meter node with an arbitrary number of probes which can optionally travel with the meter. This type is also set up for usage in a toolbox, including dragging out of a toolbox and dropping back in a toolbox.
3. ScrollingChartNode (still in Wave Interference):  The scrolling graph component which can be shown in the MeterNode or used alone.  Like a seismograph, it has pens on the right hand side that record data, and the paper scrolls to the left.

The MeterNode is purposefully general/sparse, so that subclasses have full flexibility in attaching probes.  ScrollingChartNode has placeholders for titles, and several constants hard-coded for this use case, but they could be moved to options if/when we need flexibility.

In the case of WaveInterference, WaveMeterNode brings them together, providing the simulation-specific data capture, and creating the probes/wires.

I'd like to request a code review for WireNode, MeterNode and ScrollingChartNode before we move them to another repo or try to reuse them in Bending Light or other simulations.  @ariel-phet can you please recommend a reviewer?

**Comment by pixelzoom** [comment]
Maybe I missed it, but I didn't see anything related to this added to scenery-phet's demo application. (I looked in the "Components" screen.) If it's not there, recommended to add it before doing a review.

**Comment by samreid** [comment]
> Maybe I missed it, but I didn't see anything related to this added to scenery-phet's demo application. (I looked in the "Components" screen.) If it's not there, recommended to add it before doing a review.

Good idea.  As mentioned in https://github.com/phetsims/wave-interference/issues/24#issuecomment-413085022 MeterNode and ScrollingChartNode are still in wave-interference.  I could use help picking a repo for ScrollingChartNode--not sure if it should go in scenery-phet where it seems MeterNode should go (so they can stick together) or griddle which currently has a few other chart-related things.

**Comment by pixelzoom** [comment]
I'm also not sure about ScrollingChartNode. Rather than use ScrollingChartNode in the scenery-phet demo, how about something simpler, like displaying the (x,y) coordinates of a pair of probes?

**Comment by samreid** [comment]
I added a MeterNode example to http://localhost/scenery-phet/scenery-phet_en.html?brand=phet&ea&screens=3&component=MeterNode

This shows a draggable MeterNode with one draggable ProbeNode attached via a WireNode.  On the first drag of the meter body, the ProbeNode travels with the MeterNode body (as it would when dragging out of a toolbox).  On subsequent drags, the ProbeNode travels independently of the MeterNode body.  This example does not exercise the dragging out of toolbox/dropping into toolbox functionality--it seems out of scope or too complex for this example and just includes a few lines of code that aren't tested here (but are exercised in Wave Interference).

I'll create separate issues for code reviewing MeterNode and WireNode, then in this issue I'll move ScrollingChartNode to griddle.

**Comment by pixelzoom** [comment]
@samreid said:
> ... This example does not exercise the dragging out of toolbox/dropping into toolbox functionality ...

After a quick peek at MeterNode, it's not obvious to me what part of the implementation supports dragging in/out of toolbox.  I'm also wondering whether the pattern for dragging things in/out of toolboxes (creator pattern?) is sufficiently standardized to be able to provide common-code support for it.  And if it is, whether that support should really be in things like MeterNode.

**Comment by samreid** [comment]
> After a quick peek at MeterNode, it's not obvious to me what part of the implementation supports dragging in/out of toolbox.  

Here are the 3 sites that mention "toolbox":

```js
    options = _.extend( {

      // This function is called when the a wave detector drag ends.  
      // It can be used to drop it back into a toolbox.
      end: function() {}
    }, options );
```

```js
    /**
     * Gets the region of the background in global coordinates.  This can be used to determine if the MeterNode should
     * be dropped back in a toolbox.
     * @returns {Bounds2}
     */
    getBackgroundNodeGlobalBounds: function() {
      return this.localToGlobalBounds( this.backgroundNode.bounds );
    },

    /**
     * Forward an event from the toolbox to start dragging the node in the play area.
     * @param {Object} event
     */
    startDrag: function( event ) {
      this.synchronizeProbeLocations = true;
      this.backgroundDragListener.press( event, this.backgroundNode );
    }
```

We already have a precedent for using `startDrag` in scenery-phet, see for example `MeasuringTapeNode.startBaseDrag` and its usages.

> I'm also wondering whether the pattern for dragging things in/out of toolboxes (creator pattern?) is sufficiently standardized to be able to provide common-code support for it

MeterNode doesn't need to know anything about the creator pattern, it only provides:
(a) a callback for when its drag is ended (which can be used to drop it into a toolbox),
(b) knowledge of its own bounds (which can be used to determine if its is over a toolbox)
(c) a `startDrag` function which can be used with createForwardingListener to drag from an icon in a toolbox.

**Comment by pixelzoom** [comment]
Why should that functionality be in MeterNode? Shouldn't it be in a base class (or mixin) that can be used for other Node subclasses that need toolbox support?

**Comment by samreid** [comment]
I consider it to be akin to implementing an interface.  For instance, if we had an interface like `interface ToolboxItem`, it might have methods like `endDrag`, `getGlobalBounds` and `startDrag`, but the class that implements that interface would have to provide the implementations of those methods.

**Comment by samreid** [comment]
On hold pending review in https://github.com/phetsims/scenery-phet/issues/395

**Comment by samreid** [comment]
From https://github.com/phetsims/wave-interference/issues/111#issuecomment-418518156

> I've moved ScrollingChartNode to griddle and added an example demo for it. Next steps are (a) reuse it for bending light and (b) code review. I'm inclined to exercise it in bending light before the code review so that we can be more sure that it has the right feature set or so it can be generalized as appropriate.

**Comment by samreid** [comment]
The ball is in my court for the review issue, so I'll un-hold this issue to put it on my to-do list.

**Comment by samreid** [comment]
Review in https://github.com/phetsims/scenery-phet/issues/395 is complete, and ScrollingChartNode has been moved to griddle.  Next I need to get a review for ScrollingChartNode, I'll create a separate issue for that.

**Comment by samreid** [comment]
I created a new issue in griddle for reviewing the ScrollingChartNode.  On hold until that is complete.

**Comment by samreid** [comment]
Removed hold to put https://github.com/phetsims/griddle/issues/30 on my Wave Interference "todo" list.

**Comment by samreid** [comment]
On hold for review.

**Comment by samreid** [comment]
Will continue in #124 and phetsims/griddle#30, closing.
