### ISSUE TITLE
Shadow in front of barrier

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#242]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
chrome and edge
**Problem description:**
For https://github.com/phetsims/QA/issues/238
When the barrier is moved it creates a large shadow line in front of it.  A smaller such line can be seen before any movement, but it becomes more pronounced after.
**Steps to reproduce:**
1. Go to the slits screen and set up a barrier
2. Start a wave and observe behavior in front of barrier
3. Move barrier back and forth and examine behavior

**Screenshots:**
![largeline](https://user-images.githubusercontent.com/41024075/49965614-ee59fa80-feda-11e8-961b-45e0a1d6fd90.PNG)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.51/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.51 2018-12-12 03:47:24 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"73e761ec","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"61bc739b","branch":"master"},"dot":{"sha":"b45eafe8","branch":"master"},"griddle":{"sha":"914c9215","branch":"master"},"joist":{"sha":"5a013a46","branch":"master"},"kite":{"sha":"f3e96e5b","branch":"master"},"phet-core":{"sha":"86dec8cc","branch":"master"},"phet-io":{"sha":"a267fdb1","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"d5b42848","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"e4f9e8e8","branch":"master"},"scenery":{"sha":"a18ce7f1","branch":"master"},"scenery-phet":{"sha":"56df5b6d","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"38ed71af","branch":"master"},"tambo":{"sha":"746fbd32","branch":"master"},"tandem":{"sha":"c7a56e2e","branch":"master"},"twixt":{"sha":"e38c70ed","branch":"master"},"wave-interference":{"sha":"bfce593d","branch":"master"}}

</details>

**Comment by samreid** [comment]
This issue was previously discovered and worked on in https://github.com/phetsims/wave-interference/issues/188 but looks like it wasn't solved completely.  I'll continue here, thanks for the report.

**Comment by samreid** [comment]
It should snap to cells.  Wouldn't block publication.

**Comment by samreid** [comment]
I pushed a commit to align the barrier coordinates with the lattice cells, @KatieWoe can you please test?

**Comment by samreid** [comment]
On second thought, I have an "off by one" error somewhere, would like more time to investigate before turning over for review.

**Comment by samreid** [comment]
There was a bug in the SoundParticleLayer that caused other bugs to compensate.  The SoundParticleLayer had a `RESOLUTION` scale factor to prevent pixellation of particles, but it didn't scale the particles properly.  Unfortunately, I changed the bounds to compensate.  This bounds adjustment showed a symptom that the barrier was not centered or dragging at the right quantized interval.

In my working copy, I've removed the workarounds from the bounds and visited each of the sites that were compensating for this error.  On my side things look like they are working well and the code is simpler and there are less workarounds, but this has been the largest change since dev testing began and we will need to be careful to test features particularly about coordinate frames, scaling, etc in the wave area.

**Comment by KatieWoe** [comment]
Water and light seem better with this issue, but not sound.  Behavior of the waves also seems rather off while dragging the barrier.  Everything disappears with light (which may be intended) and everything starts flashing with the other two.

**Comment by samreid** [comment]
> Behavior of the waves also seems rather off while dragging the barrier. Everything disappears with light (which may be intended) and everything starts flashing with the other two.

Perhaps this is the same problem as identified in https://github.com/phetsims/wave-interference/issues/246?

**Comment by samreid** [comment]
> Water and light seem better with this issue, but not sound.

On the sound scene, I can see some values where the barrier has a front-shadow and some where it does not.  It suggests a different calculation is being used for where to show the barrier vs where the barrier appears in the model.  I thought I switched all of these to use `Math.floor` but perhaps I missed one or perhaps there is another factor at play.

**Comment by samreid** [comment]
I added quantization in the view layer and it seems to have fixed the problem for sound.  However, now for the sound scene, when you initially grab the barrier, it jumps a cell or two to the left, and I'm not sure why.

**Comment by samreid** [comment]
I moved the barrier location into lattice coordinates.  All tests seem good except the lattice jumps a bit when starting a drag in the light scene.

**Comment by samreid** [comment]
I was able to fix that problem by switching to rounding instead of flooring.  All tests seem OK on my side, but all things with coordinate frames will need to be rechecked.  This includes wave area, barrier locations, oscillator locations, emitter locations, wave detector node, etc.

**Comment by KatieWoe** [comment]
Looks good on master
