### ISSUE TITLE
Drag measure tape and barrier with same touch input

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#243]
**Device**
iPad (2018)
**OS**
iOS 12
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/238
It is possible to accidentally "pick up" the barrier while dragging the measuring tape across.  This can be replicated with the touch screen on Win 10, but much less reliably.  It does not occur every time.
**Steps to Reproduce**
1. Go to the sim on an iPad
2. Go to the slits screen
3. Pick up the measure tape and drag it back and forth over the divider without picking up your finger

**Screenshot**
https://drive.google.com/file/d/1p4pRxbdvg2cSjI97412BbreWKvcinM9W/view?usp=sharing

**Comment by samreid** [comment]
This should be solved, but does not block publication.

**Comment by KatieWoe** [comment]
Note for @ariel-phet.  Letting go drops both objects

**Comment by samreid** [comment]
I can also use the measuring tape to pick up the timer.

**Comment by samreid** [comment]
I've proposed a fix in https://github.com/phetsims/scenery/issues/910 but it would be best for @jonathanolson to take a look before we proceed.  On hold until then.

**Comment by samreid** [comment]
Proposed fix is pushed, @KatieWoe can you please test and verify?

**Comment by KatieWoe** [comment]
This seems fixed on master

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/264 I noticed this when dragging the end of the measure, rather than the measure itself.  It also catches the timer and wave examiner.

**Comment by samreid** [comment]
Good catch @KatieWoe, fix is pushed, can you please verify on phettest/master?

**Comment by KatieWoe** [comment]
Looks good on master @samreid
