### ISSUE TITLE
Graph and wave generator label overlap

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/wave-interference#244]
For https://github.com/phetsims/QA/issues/238.

![screen shot 2018-12-13 at 4 49 50 pm](https://user-images.githubusercontent.com/31285590/49974550-2cfdae00-fef7-11e8-9375-b7a35d389f98.png)

In this screencap, you can see the bottom part of the 'g' in light overlapping with the graph.

**Comment by samreid** [comment]
@arouinfar how would you prefer this be addressed?

**Comment by arouinfar** [comment]
What a catch @lmulhall-phet! Unfortunately, I don't have an elegant solution to recommend @samreid. Perhaps move the label so it's above the button? That feels a bit heavy, so I don't particularly like that option. Maybe @ariel-phet will have a good idea for this one.

**Comment by samreid** [comment]
What about moving the label to the left?

**Comment by samreid** [comment]
Some other possibilities:

a) Leave the "Water wave Generator" text centered as it is now, then hide it when the graph is showing.
b) Always show the "Water Wave Generator" text to the left of the wave generator (in the white area)
c) Show the text in the top part of the wave generator.

@amanda-phet just described today how it is preferable to not have things jump around to compensate for layout. Perhaps that's also an argument against (a).  I guess I'm now leaning toward (c).

**Comment by samreid** [comment]
I pushed (c) for discussion, you can see it in action on master.  Let me know your thoughts.

**Comment by ariel-phet** [comment]
My vote would be to the left, in the whitespace, centered vertically on the button.

**Comment by samreid** [comment]
I'll take a picture of master for the record, then I'll try @ariel-phet's recommendation.

**Comment by samreid** [comment]
Here's master:

![image](https://user-images.githubusercontent.com/679486/50021581-cc25b280-ff96-11e8-85eb-866f5dfe1275.png)

![image](https://user-images.githubusercontent.com/679486/50021591-d2b42a00-ff96-11e8-971a-62b3484aaca2.png)

**Comment by samreid** [comment]
Here's the text off to the left:

![image](https://user-images.githubusercontent.com/679486/50021681-1c047980-ff97-11e8-9db9-82519e3a5ead.png)

![image](https://user-images.githubusercontent.com/679486/50021732-3ccccf00-ff97-11e8-84a9-42c7514a0816.png)

**Comment by samreid** [comment]
Here's a patch that gives https://github.com/phetsims/wave-interference/issues/244#issuecomment-447420525.  However I think https://github.com/phetsims/wave-interference/issues/244#issuecomment-447419637 is preferable because the label is on the wave generator.  When the text is to the left, it gives the impression that it is labeling the entire wave area instead of just the generator.

```
Index: js/slits/view/PlaneWaveGeneratorNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/slits/view/PlaneWaveGeneratorNode.js	(revision fa0ba18fc5d3c8bf1768e9bb0ea120c95ad4dafd)
+++ js/slits/view/PlaneWaveGeneratorNode.js	(date 1544813661000)
@@ -50,7 +50,7 @@
 
       this.mutate( options );
 
-      // Show descriptive text label at the bottom of the cylinder
+      // Show descriptive text label
       this.addChild( new SceneToggleNode( model, scene => {
         const textNode = new WaveInterferenceText( scene.planeWaveGeneratorNodeText, {
           rotation: -Math.PI / 2,
@@ -66,8 +66,8 @@
           children: [ backgroundNode, textNode ]
         } );
       }, {
-        centerX: this.centerX,
-        top: verticalCylinderImageNode.top + 42,
+        right: verticalCylinderImageNode.left - 10,
+        centerY: verticalCylinderImageNode.centerY,
         alignChildren: ToggleNode.BOTTOM
       } ) );
     }
```

**Comment by ariel-phet** [comment]
Huh, on top looks much better than I thought it would. Lets go with that @samreid

**Comment by samreid** [comment]
Text on top is committed to master, I double checked the ?stringTest=double and ?stringTest=long and it seemed a good fit.  @arouinfar do you want to do any other double checks on this?  Close if all is well.

**Comment by arouinfar** [comment]
Text on top looks nice @samreid! Thanks for iterating on this with @ariel-phet.
