### ISSUE TITLE
In Pulse mode, make wave source button green with pulse icon

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#245]
While not technically for https://github.com/phetsims/QA/issues/238, this should be addressed before the next round of dev testing.

When switching from continuous to pulse, it was not clear to interviewees that they would need to press the button on the wave source to release a pulse (since the source had already been on in continuous mode). WOAS uses a green button with a pulse icon, so we'd like to do the same here.

Here's what it looks like in WOAS. We can use the same green, though the pulse should match the Gaussian on the radio button.
![image](https://user-images.githubusercontent.com/8419308/49987525-c9907200-ff30-11e8-91e2-21284de2c959.png)

@samreid can you make these changes?

**Comment by samreid** [comment]
I made the button green and used the same icon as on the radio button.  @arouinfar can you please pull and review?

**Comment by samreid** [comment]
OK, all set.

**Comment by arouinfar** [comment]
@samreid looking pretty good. 

A few pixel polishing suggestions:
* The icon could pop a bit more. Let's add a white stroke around the pulse icon, similar to WOAS.
* The pulse tails are a bit too close to the button edge. Try reducing the tail length slightly  and/or slightly reducing the icon size so there's a bit of padding between the icon and button edge.

**Comment by samreid** [comment]
Proposed fix is pushed, @arouinfar can you please review on phettest and close if all is well?

**Comment by arouinfar** [comment]
Looks great!
