### ISSUE TITLE
Dilate Pointer Areas Around Wave button? 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#252]
I noticed that, when using an iPad, it seemed like pushing the button to start the wave didn't always work.  I looked at the touch pointer areas from those button and they look pretty small.  I think it might be useful if they are a bit bigger.  We'd have to be careful that they don't overlap when separation between two sources is as small as possible, but even a slightly larger target might be useful.
For https://github.com/phetsims/QA/issues/238

**Comment by arouinfar** [comment]
Great suggestion @KatieWoe! This is the worst case scenario for the Interference screen, which should still leave ample room for dilation of the touch area around the on/off button.
![image](https://user-images.githubusercontent.com/8419308/50038436-277e9180-ffe5-11e8-87e5-5900cb7afd4a.png)

@samreid seems like we could make the touch areas pretty generous here. Let's try something like this:
<img src="https://user-images.githubusercontent.com/8419308/50038447-86440b00-ffe5-11e8-86d8-fd2e6617cc8d.png" width=200>

This touch area would apply to the source on/off button for all scenes/screens.

**Comment by samreid** [comment]
Here's a dilation of 8 view coordinates:

![image](https://user-images.githubusercontent.com/679486/50038825-a96dbb00-ffe3-11e8-906e-c04074e7a04d.png)

Pushed and ready for review, @arouinfar can you please take a look?

**Comment by KatieWoe** [comment]
Looks good on the Waves and Interference screen.  Not implemented on the Slits screen.  Do we want it to be @arouinfar?

**Comment by samreid** [comment]
That was not intentional, self-assigning to fix that up.

**Comment by samreid** [comment]
Proposed fix pushed, @KatieWoe can you please double check and close if all is well?

**Comment by KatieWoe** [comment]
Looks good in master.

**Comment by arouinfar** [comment]
> Not implemented on the Slits screen. Do we want it to be @arouinfar?

Good catch @KatieWoe! Thanks for taking care of it @samreid.
