### ISSUE TITLE
Dev Query Parameter Has Additional Slider Options Not Seen Elsewhere

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/wave-interference#253]
For https://github.com/phetsims/QA/issues/238 when using the ?dev query parameter a box with four slider options appears on the waves and interference screens. The sliders adjust randomness, home force, friction, and gradient force. This slider box does not appear on the standalone sim, or with any other query parameters. This might be a non-issue as users will most likely not apply this query parameter, but it was odd to me that this box appeared when a query parameter was implemented.

**Comment by samreid** [comment]
Those are developer controls-- @arouinfar is appropriate to show those with `?dev` or should I put them in some other query parameter?

**Comment by arouinfar** [comment]
@samreid these controls are a bit in the way when using `?dev`. Since we've finished tuning the sound particle physics, it seems appropriate to retire them.

**Comment by arouinfar** [comment]
Looks good to me @samreid.
