### ISSUE TITLE
Behavior of wave different when moving step by step

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#254]
For https://github.com/phetsims/QA/issues/238
When a sim is paused, moving step by step produces different waves than when played normally.
1. Go to the wave screen and go to the light scene (easier to see)
2. Play the wave for a bit
3. Pause the sim
4. Step by step, advance the sim and note change in wave

![stepdif](https://user-images.githubusercontent.com/41024075/50024183-ce8c0a80-ff9e-11e8-9213-e63797bc7d60.PNG)

**Comment by KatieWoe** [comment]
Seems to be a light and sound problem.  Don't see it as much on water it seems.

**Comment by samreid** [comment]
I wonder if this was broken by the fix in https://github.com/phetsims/wave-interference/issues/226

**Comment by samreid** [comment]
I reverted #254 and commented why it doesn't seem possible.  @KatieWoe can you please verify that this issue is resolved?

**Comment by KatieWoe** [comment]
This looks good on master.
