### ISSUE TITLE
Jittery leading wave when barrier is removed

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/wave-interference#255]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.14

<b>Browser</b>

Chrome 71.0.3578.98

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/238. Related to https://github.com/phetsims/wave-interference/issues/207. See title and gif.

<b>Steps to Reproduce</b>

1. Slits screen.
2. Generate wave.
3. Remove barrier.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/31285590/50026918-c08eb780-ffa7-11e8-995c-7a6dfda58815.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.51/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.51 2018-12-12 03:47:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"73e761ec","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"61bc739b","branch":"master"},"dot":{"sha":"b45eafe8","branch":"master"},"griddle":{"sha":"914c9215","branch":"master"},"joist":{"sha":"5a013a46","branch":"master"},"kite":{"sha":"f3e96e5b","branch":"master"},"phet-core":{"sha":"86dec8cc","branch":"master"},"phet-io":{"sha":"a267fdb1","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"master"},"phet-io-wrappers":{"sha":"d5b42848","branch":"master"},"phetcommon":{"sha":"869b2561","branch":"master"},"query-string-machine":{"sha":"e4f9e8e8","branch":"master"},"scenery":{"sha":"a18ce7f1","branch":"master"},"scenery-phet":{"sha":"56df5b6d","branch":"master"},"sherpa":{"sha":"a1f5e867","branch":"master"},"sun":{"sha":"38ed71af","branch":"master"},"tambo":{"sha":"746fbd32","branch":"master"},"tandem":{"sha":"c7a56e2e","branch":"master"},"twixt":{"sha":"e38c70ed","branch":"master"},"wave-interference":{"sha":"bfce593d","branch":"master"}}

</details>

**Comment by samreid** [comment]
I struggled with this in https://github.com/phetsims/wave-interference/issues/207 and still do not understand the underlying problem.  https://github.com/phetsims/wave-interference/issues/207 was solved by carefully choosing the phase of the plane wave so it is not a problematic value, but we cannot control the phase of the wave when the user chooses when to remove the barrier.  This doesn't seem like something that would block publication (the leading edge flicker doesn't seem pedagogically harmful), but maybe it would be a good idea to request @pixelzoom to help investigate this once he is more familiar with the sim after code review.  @ariel-phet thoughts?

Also leaving self-assigned in case I figure it out sooner.

**Comment by pixelzoom** [comment]
I'll be happy to take a look at this after I've become familiar with the sim (via code review).  But this is most likely something in @jonathanolson's wheelhouse.

**Comment by ariel-phet** [comment]
@samreid @lmulhall-phet definitely should not block publication of 1.0 and could be deferred to 2.0 for the following reasons:

1. As @samreid pointed out, not really pedagogically problematic

2. "no barrier" is sort of very uninteresting, just a plane wave, so unlikely for students/teachers to remain on that setting long. Slits is where it is at

However, the plane wave on https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.56/phet/wave-interference_all_phet.html (tested on chrome) looks fairly jittery even before the barrier, perhaps that is a separate issue (removing the barrier does seem to make it worse).

@samreid worth investigating if you can get the waves in general (even on the first screen) being a bit less jittery, but this would not be a show stopper. Marking medium priority but could be deferred to 2.0

**Comment by samreid** [comment]
@ariel-phet are you referring to the leading edge of the plane wave, or generally the wave depiction in the entire wave area?

**Comment by ariel-phet** [comment]
@samreid generally the wave depiction in the entire wave area. Perceptually more noticeable with the plane wave before it his the barrier.

**Comment by samreid** [comment]
Pixellation of the wave area is discussed in https://github.com/phetsims/wave-interference/issues/256 and marked as deferred to 2.0+.  Let's leave this issue about the particular case of the leading edge of the plane wave as depicted in https://github.com/phetsims/wave-interference/issues/255#issue-391275776.  It sounds like this can also be deferred to 2.0+.  @ariel-phet does this all sound correct to you?

**Comment by samreid** [comment]
> However, the plane wave on https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.56/phet/wave-interference_all_phet.html (tested on chrome) looks fairly jittery even before the barrier, perhaps that is a separate issue (removing the barrier does seem to make it worse).

It does sound like a separate issue.  I'll leave this issue about the *leading edge of the advancing wave" and open a new issue about the issue you are describing.

**Comment by samreid** [comment]
@ariel-phet now that I have opened https://github.com/phetsims/wave-interference/issues/297 how would you like to proceed with this issue, about the leading edge of the advancing wave?  Some possibilities:

* Leave this issue open and deferred, and do not address before 1.0
* Schedule me more time to investigate.  I have already looked into it in https://github.com/phetsims/wave-interference/issues/207 and am having difficulty making progress, but could spend more time on it.
* Assign help from @pixelzoom or @jonathanolson in case they have ideas about what is causing the leading edge flicker or suggestions how to proceed.

**Comment by ariel-phet** [comment]
@samreid I will mark this one deferred, the general smoothness is far more important to me, as removing the barrier and watching a plane wave a fairly uninteresting from a pedagogical standpoint.

**Comment by samreid** [comment]
Since this problem was reported, the lattice size was increased in https://github.com/phetsims/wave-interference/issues/315 and the leading edge jitter is gone or significantly reduced.  Can this issue be closed?

**Comment by arouinfar** [comment]
This seems like the same underlying issue as #297. I think the increased lattice size sufficiently addressed this issue, and I am seeing very little jitter in master, though I'll leave this one up to @ariel-phet for final sign-off.

**Comment by ariel-phet** [comment]
Looking pretty good on my laptop on master, and the no barrier case is by far the least interesting/pedagogically important, so I agree, sufficiently addressed. Closing.
