### ISSUE TITLE
Pixelated wave

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#256]
For https://github.com/phetsims/QA/issues/238
Under some circumstances the waves can look rather pixelated.  This seems to occur more when frequency is high and separation is small, but is noticeable in other circumstances as well.
![image](https://user-images.githubusercontent.com/41024075/50027386-3d6e6100-ffa9-11e8-89a8-6c33ac5610f7.png)

**Comment by samreid** [comment]
We use an optimization in LatticeCanvasNode that accelerates performance and makes iPad 2 usage possible (though not great) and gives great performance on iPad 4.  The optimization is that the entire lattice is rendered as one cell = one pixel, then that is blown up.  

Perhaps changing to a WebGL renderer could offer more resolution without increasing CPU demands.  It could take 4-12 hours to get a version ready for testing, but would be quicker to run a feasibility test.  Note: we would not change the physics or increase the resolution of the lattice at all, but we would interpolate cell values in the rendering phase on the GPU.  I'm interested to see what this looks like, but will not spend a significant amount of time on it until discussing with @arouinfar @ariel-phet or @kathy-phet.

**Comment by ariel-phet** [comment]
@samreid that sounds worth of investigation for 2.0, not for 1.0. Lets defer for the moment.

**Comment by arouinfar** [comment]
@samreid @ariel-phet I haven't noticed too many pixelated situations like the one in https://github.com/phetsims/wave-interference/issues/256#issue-391278476, so it definitely seems reasonable to defer.

**Comment by kathy-phet** [comment]
I've noticed pixelation occuring sometimes too. It seems somewhat unpredictable, and I've seen it create some odd readings on the charting tool too. 

I think its worth investigating WebGL as an alternative, but agree it can be deferred to 2.0.

**Comment by samreid** [comment]
> It seems somewhat unpredictable, and I've seen it create some odd readings on the charting tool too.

The proposed usage of WebGL would only apply in the view layer--would not change the underlying model values or what is shown on the charts.  Should we open another issue to investigate odd readings on the charting tool?

**Comment by samreid** [comment]
Here's how the same scene looks after we increased the lattice size:

![image](https://user-images.githubusercontent.com/679486/52351453-06845c80-29e8-11e9-8213-3c66c8e27d6f.png)

@arouinfar does this look OK to you?  Can this issue be closed?

**Comment by arouinfar** [comment]
@samreid I think the increased lattice size adequately addresses the original issue. However, there should probably be a separate issue for WebGL investigation for 2.0, since I know it's come up a few times now.

**Comment by samreid** [comment]
I reopened https://github.com/phetsims/wave-interference/issues/66 and will close this particular issue.
