### ISSUE TITLE
Turning on the lower speaker resets the phase of the upper speaker

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#257]
Screen 2.
Turn on Top speaker
Turn on Bottom Speaker

Notice the phase of the top speaker is reset (top has a truncated wave)

![image](https://user-images.githubusercontent.com/679486/50099046-6aee2100-01da-11e9-997d-861d2e7d3aa0.png)

**Comment by arouinfar** [comment]
Looks good in master @samreid
