### ISSUE TITLE
z-ordering for the graph and slits

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#26]
I noticed this in the mock-up

![image](https://user-images.githubusercontent.com/679486/37258588-b5da469e-253f-11e8-9880-6ecfe90e6531.png)

@arouinfar do you really want the z-order to be:
chart background
barriers
chart curve

That is, that the barriers are layered between the chart background and foreground?

**Comment by arouinfar** [comment]
@samreid the z-order should be: wave, barrier, chart background, chart curve (top). I remember re-ordering the barrier on Friday, so I checked the .ai file, and z-order was correct there. Looks like the updated mockup didn't make it into the design doc, so I updated the doc.
![image](https://user-images.githubusercontent.com/8419308/37290618-5835ded4-25d2-11e8-8ff3-74a089cdc31d.png)

**Comment by arouinfar** [comment]
@samreid that should be it! Master appears to be broken, so I'll wait for the dev version to verify.

**Comment by arouinfar** [comment]
@samreid please reassign me when you publish a new dev version.

**Comment by samreid** [comment]
I tested phettest and saw this error:

![image](https://user-images.githubusercontent.com/679486/43114232-3a1b95b8-8ebb-11e8-8117-3df51c476ea6.png)

This revealed an unpushed change in sun.  I've pushed the change and phettest seems to be launching now, thanks for pointing out this problem @arouinfar.  I'll also publish a new dev version when I get to a good checkpoint.

**Comment by arouinfar** [comment]
@samreid I should have pulled all! My bad. I'll check master tomorrow.

**Comment by arouinfar** [comment]
Master looks great @samreid!

**Comment by samreid** [comment]
Thanks, closing.
