### ISSUE TITLE
add more vertical space between checkboxes and radio buttons?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#261]
Related to code review #259, pointer areas.

There's plenty of vertical space, why is there so little spacing between vertically stacked radio buttons and checkboxes? 

![screenshot_943](https://user-images.githubusercontent.com/3046552/50170064-46627980-02ac-11e9-850c-13bf37f994dc.png)

**Comment by arouinfar** [comment]
Thanks for the suggestion @pixelzoom. I agree the checkboxes and aqua radio buttons are a bit tighter than necessary.  @samreid can you add a px or two of padding between these components?

**Comment by arouinfar** [comment]
Looks nice @samreid, thanks!
