### ISSUE TITLE
odd grouping of UI components

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#262]
Related to #259 code review, noticed in #261.

In the Waves screen, when the speaker radio button is selected, the control panel looks like this:

![screenshot_944](https://user-images.githubusercontent.com/3046552/50170221-9b05f480-02ac-11e9-9093-8fadce1b81e0.png)

Having the bottom 4 UI components (1 checkbox, 3 radio buttons) grouped together makes them look related, when in fact the Graphs checkbox is unrelated.   Consider adjusting the spacing, or add a separator, to make the grouping clear.

**Comment by pixelzoom** [comment]
Note that decisions made here may impact https://github.com/phetsims/wave-interference/issues/283.

**Comment by samreid** [comment]
Spacing was adjusted in another issue, it looks like this now:

![image](https://user-images.githubusercontent.com/679486/50363665-dbbe7180-0529-11e9-9a5a-3ac080102ad1.png)

@arouinfar do you recommend further changes to segregate the radio button group from the checkbox?

**Comment by arouinfar** [comment]
@samreid I like the added negative space. I don't have any further UI changes to recommend, so closing.
