### ISSUE TITLE
model.md issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#263]
Related to code review #259, where @samreid said:

> I recommend to start with the documentation:
wave-interference/doc/implementation-notes.md
wave-interference/doc/model.md

Formatting of model.md is jacked, and it's unclear whether it was reviewed by @arouinfar.

**Comment by samreid** [comment]
Formatting changes look good, self-unassigning but leaving @arouinfar assigned to make sure the content is complete and correct.

**Comment by arouinfar** [comment]
Looks good to me. Thanks @pixelzoom @samreid!
