### ISSUE TITLE
replace Math.round with Util.roundSymmetric

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#267]
From code review checklist in #259:

> Check that `dot.Util.roundSymmetric` is used instead of `Math.round`. `Math.round` does not treat positive and negative numbers symmetrically, see phetsims/dot#35 (comment).

This sims has 12 occurrences of `Math.round`.   If there are any exceptions where `Math.round` is required, document them.  Otherwise replace with `Util.roundSymmetric`.

**Comment by samreid** [comment]
I converted several Math.round to Util.roundSymmetric.  The remaining cases are documented as:

```js
// ImageData.data is Uint8ClampedArray.  Use Math.round instead of Util.roundSymmetric
// because performance is critical and all numbers are non-negative.
const offset = 4 * m;
data[ offset ] = Math.round( r );
data[ offset + 1 ] = Math.round( g );
data[ offset + 2 ] = Math.round( b );
data[ offset + 3 ] = 255; // Fully opaque
m++;
```

Ready for review.

**Comment by pixelzoom** [comment]
👍 Closing.
