### ISSUE TITLE
Make it easier to visualize the minima in the wave area

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#27]
In the original simulation, the value for amplitude=0 in the wave is the center of the lattice coloring.  For red, it is this "medium red":

![image](https://user-images.githubusercontent.com/679486/37572176-e2489bf8-2acc-11e8-8687-0b8a16bdd6b6.png)

For experienced users, it is easy to see how the "grayish red" matches up with the minima in the graph.  But for novices, or when the pattern isn't as clear, it is harder to see what's happening in the play area:

![image](https://user-images.githubusercontent.com/679486/37572208-56a13f46-2acd-11e8-80bc-5a638aeab4be.png)

The coloring strategy is currently amplitude -1 => black, amplitude 0 => grayish color, amplitude = 1 => full color.

I'm wondering if we should choose a coloring strategy where amplitude 0 should be black.  As a quick test, I tried -1=>red, 0=>black and +1=>blue and it looked like this:

![image](https://user-images.githubusercontent.com/679486/37572232-b016b2f4-2acd-11e8-9218-9368c94222a0.png)

In this case, it is clear where the minima are.  However, now it looks like the wave has twice the frequency that it really does.  I wonder if we should choose another color scheme which has amplitude 0 as black?

**Comment by samreid** [comment]
Here's a paintCanvas implementation that shows the behavior in the preceding screenshot:

```js
    /**
     * Draws into the canvas
     * @param {CanvasRenderingContext2D} context
     */
    paintCanvas: function( context ) {
      for ( var i = this.lattice.dampX; i < this.lattice.width - this.lattice.dampX; i++ ) {
        for ( var k = this.lattice.dampY; k < this.lattice.height - this.lattice.dampY; k++ ) {
          var value = this.lattice.getCurrentValue( i, k );
          if(value>0){
            var shading = Util.linear( 0, 2, 0, 255, value );
            shading = Math.floor( Util.clamp( shading, 0, 255 ) );
            context.fillStyle = 'rgb(0,0,' + shading + ')';
            context.fillRect( ( i - this.lattice.dampX ) * CELL_WIDTH, ( k - this.lattice.dampY ) * CELL_WIDTH, CELL_WIDTH + 1, CELL_WIDTH + 1 ); // +1 is to eliminate seams // TODO: x-offset?
          }else{
            var shading = Util.linear(0, -2, 0, 255, value );
            shading = Math.floor( Util.clamp( shading, 0, 255 ) );
            context.fillStyle = 'rgb('+shading+',0,0)';
            context.fillRect( ( i - this.lattice.dampX ) * CELL_WIDTH, ( k - this.lattice.dampY ) * CELL_WIDTH, CELL_WIDTH + 1, CELL_WIDTH + 1 ); // +1 is to eliminate seams // TODO: x-offset?
          }

        }
      }
    }
```

**Comment by samreid** [comment]
Another problem is that the representation in https://github.com/phetsims/wave-interference/issues/27#issue-306293583 is that the coloring in the wave area has a different meaning than the coloring in the intensity panel.

**Comment by samreid** [comment]
To clarify, I'm not advocating for red/blue color scheme, but wanted to discuss the meaning of black in the wave area vs black in the intensity panel and wondering if we can unify them.  Before I revert the trial code above, here's another depiction that shows how black in the area can align with black in the intensity panel:

![image](https://user-images.githubusercontent.com/679486/37604484-b3dbca6c-2b56-11e8-8e4f-14cf60e3386f.png)

**Comment by samreid** [comment]
Also, this overlaps with the issue of the "dark wave" in light mode.  If we chose black = 0 amplitude, then we wouldn't need a special model for wave propagation in the light scene.

**Comment by arouinfar** [comment]
Thanks for doing this investigation @samreid! I think this is something that we should definitely discuss with the rest of the team during the next design meeting.

In general, I think black=-1 works really well for interpreting a single propagating wave. It's easy to see the wave maxima and minima, though I will concede that it is a bit tricker to pinpoint which color represents the node.

Comparing these two examples from @samreid, black=0 (top) lines up with the interference minima really nicely. Using black to represent a node makes conceptual sense as well. In the case of black=-1 (bottom) the medium red stripes running through the waves to the interference pattern on the screen are harder to interpret as nodes, but I think it's rather telling that there isn't any apparent oscillation in those regions.
> ![image](https://user-images.githubusercontent.com/8419308/37923892-8ad2d0a6-30ed-11e8-8eb0-0f9b5230124e.png)
 ![image](https://user-images.githubusercontent.com/8419308/37923881-831882d4-30ed-11e8-9735-ff93e0ddeb5e.png)


A big downside of using black=0, is that the wave's frequency will apparently double. Compare black=-1 (top) to black=0 (bottom). In the absence of interference, I find black=0 to be more confusing than helpful.
![image](https://user-images.githubusercontent.com/8419308/37923538-98cdd800-30ec-11e8-92a1-18604f70c759.png)

**Comment by arouinfar** [comment]
@samreid brings up an excellent point.
> Also, this overlaps with the issue of the "dark wave" in light mode. If we chose black = 0 amplitude, then we wouldn't need a special model for wave propagation in the light scene.

In Java, the water and sound viewing windows displays the node color in the absence of a wave. For light, the node color would be the "medium red" (by default), but we instead chose to use black. On one hand, this makes sense -- the absence of light would be black. However, this contradicts the other contexts, and requires special-case code.

**Comment by samreid** [comment]
From my notes:
SR will try out flattening the color mapping range for zero amplitude. AR/SR will meet to tune

**Comment by samreid** [comment]
Now that the WebGL lattice renderer has been implemented, this will need to be implemented in the fragment shader as well.  Also, Is the main point of this recommendation to "widen" the 0-amplitude regions?

**Comment by samreid** [comment]
I committed 80c4973a4b80e66b6eb666e600cca9e36c650ce0 and 51afbcfa65eb2caf119b0a4431b10aea1ed46650 which use the mapping as described in https://github.com/phetsims/wave-interference/issues/27#issuecomment-377383722 with a minor adjustment.  @arouinfar do we need to refine this further?

**Comment by samreid** [comment]
Also note this issue overlaps with https://github.com/phetsims/wave-interference/issues/89, if we color map the minima to be even broader, it could be more difficult to pinpoint the node with the wave detector tool.

**Comment by arouinfar** [comment]
@samreid I think the color mapping looks great, so I think we can go ahead and close.
