### ISSUE TITLE
nonstandard names for model classes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#271]
Related to code review #259.

The screen names in this sim are Waves, Interference, Slits, and Diffraction.  So based on other sims that I've reviewed, I'd expect to find top-level model classes `WavesModel`, `InterferenceModel`, `SlitsModel`, and `DiffractionModel` respectively.  `DiffractionModel` is as expected. But  the others are `WavesScreenModel`, `InterferenceScreenModel`, `SlitsScreenModel`.

Searching for "ScreenModel" shows that this naming scheme is also used in circuit-construction-kit-dc and circuit-construction-kit-black-box-study.   The naming convention used in all other sims has served us well, and I see no benefit to deviating or changing.  So unless there's a really good reason to spend time in a dev meeting discussing a different naming convention, I recommend to rename the model classes in this sim, circuit-construction-kit-dc, and circuit-construction-kit-black-box-study

**Comment by samreid** [comment]
Proposed fixes pushed for Wave Interference and Circuit Construction Kit, ready for review.

**Comment by pixelzoom** [comment]
👍 Closing.
