### ISSUE TITLE
inconsistent naming of Enumerations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#273]
Related to code review #259.

There are currently 2 patterns used to name Enumerations:

(1) 'Enum' suffix: `BarrierTypeEnum, PlaySpeedEnum`

(2) 'Type' suffix: `ApertureType, SoundViewType, SceneType, ViewType, WaveSpatialType, WaveTemporalType`

I don't have a preference on which pattern is used, but it would be nice to pick one.

**Comment by pixelzoom** [comment]
And I don't think we need to necessarily be consist across _all_ sims, just within a sim.

**Comment by samreid** [comment]
It seems it would be best for this sim to change:

BarrierTypeEnum => BarrierType
PlaySpeedEnum => PlaySpeedType

**Comment by pixelzoom** [comment]
I guess I do have a preference.  'Type' is misleading. These are not types, they are enumerations.  So I think 'Enum' is the appropriate suffix.

**Comment by samreid** [comment]
So will several of these end with `TypeEnum`?  For instance, `ApertureEnum` sounds incorrect because it doesn't enumerate apertures, it enumerates aperture types.

**Comment by pixelzoom** [comment]
If it makes life easier, I'm OK with 'Type' suffix.

**Comment by samreid** [comment]
Do you prefer `ApertureType` or `ApertureTypeEnum`?

**Comment by samreid** [comment]
Enum suffix added, please review.

**Comment by pixelzoom** [comment]
👍 Closing.
