### ISSUE TITLE
duplicated code in LatticeCanvasNode and LightScreenNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#277]
For code review #259, identified by grunt find-duplicates.

The code below is duplicated in LatticeCanvasNode.js (lines 51-68) and LightScreenNode.js (lines 59-76).

```
      const height = this.lattice.height - this.lattice.dampY * 2;

      // @private
      this.directCanvas = document.createElement( 'canvas' );
      this.directCanvas.width = width;
      this.directCanvas.height = height;

      // @private
      this.directContext = this.directCanvas.getContext( '2d' );

      // @private
      this.imageData = this.directContext.createImageData( width, height );

      // Invalidate paint when model indicates changes
      const invalidateSelfListener = this.invalidatePaint.bind( this );
      lattice.changedEmitter.addListener( invalidateSelfListener );
```

**Comment by samreid** [comment]
Proposed fix pushed, please review.

**Comment by pixelzoom** [comment]
`ImageDataRenderer` looks very nice, could be useful in common code someday (maybe even in Gas Properties).  With that in mind...

The first 2 lines of the constructor are:

```js
constructor( lattice, width ) {
 const height = lattice.height - lattice.dampY * 2;
```

... and the `lattice` is never used again.  How about changing to:

```js
constructor( width, height ) {
```

... with call sites like:

```js
  this.imageDataRenderer = new ImageDataRenderer( width, this.lattice.height - this.lattice.dampY * 2 );
```

And perhaps move the `this.lattice.height - this.lattice.dampY * 2` computation into method of `Lattice`.

**Comment by samreid** [comment]
Nice recommendation, thanks!  I pushed one commit, please review.

**Comment by samreid** [comment]
Oops, previous commit had bad jsdoc params, fixed in an additional commit.

**Comment by pixelzoom** [comment]
👍 Closing.
