### ISSUE TITLE
nonstandard pattern for static constants

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#281]
Related to code review #259.

This was originally a REVIEW comment, but I'm promoting it to an issue.

During a recent ES6 discussion (led by @jonathanolson, if I recall correctly) we discussed the lack of static constants in JS, and the alternatives.  And I believe that we concluded that this pattern was the most straightforward:

```js
class SomeClass {
  ...
}

SomeClass.SOME_STATIC_CONSTANT = 5;

return someNamespace.register( 'SomeClass', SomeClass );
```

@samreid is using a different pattern in Wave Interference. For example, in `WaveScreensModel`:

```js
class WavesScreenModel {
...
  static get EVENT_RATE() {
    return EVENT_RATE;
  }
}

return waveInterference.register( 'WavesScreenModel', WavesScreenModel );
```

This pattern is also used for: 
`LightWaveGeneratorNode.DEFAULT_OPTIONS` 
`WavesScreenModel.EVENT_RATE`
`WavesScreenView.SPACING`

A couple of potential issues with this pattern:

(1) It obfuscates what is really happening - it's a function masquerading as a constant.  
(2) It violates the naming convention for functions. 

This might be something that we need to discuss at dev meeting, so labeling accordingly.

**Comment by jonathanolson** [comment]
I have a few cases of that pattern (from before the decision was made) in fractions-common. I'm happy to refactor to the "new" style (assigning myself).

**Comment by samreid** [comment]
Proposed fix committed, @pixelzoom can you please review this change for Wave Interference?  I'll create a separate issue for @jonathanolson for fractions common.  If this issue looks good for wave-interference, it can be closed.

**Comment by pixelzoom** [comment]
👍 Closing.
