### ISSUE TITLE
use better names for Ranges in SlitsControlPanel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#284]
Related to code review #259, and #279.

`SlitsControlPanel` has some inadequate names for Ranges.

These are Ranges for slit width, and should be renamed to indicate that, e.g. `waterSlitWidthRange`.
```js
const waterRange = new Range( 0.5, 2.5 ); // cm
const soundRange = new Range( 20, 160 );
const lightRange = new Range( 200, 1600 );
```

These are Ranges for slit separation. Consider renaming to (e.g) `waterSlitSeparationRange`. 
```js
const waterSeparationRange = new Range( 1, 5 );
const soundSeparationRange = new Range( 40, 320 ); // cm
const soundSeparationRange = new Range( 40, 320 ); // cm
const lightSeparationRange = new Range( 400, 3200 );
```

**Comment by samreid** [comment]
In https://github.com/phetsims/wave-interference/issues/279 the slit width ranges were moved to the model, and now appear like this (e.g.,):

```js
slitWidthRange: new Range( 0.5, 2.5 ), // cm
```
and

```js
sourceSeparationRange: new Range( 1, 5 ), // cm
```

Please review.

**Comment by pixelzoom** [comment]
👍 Closing.
