### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#285]
Finalize the credits in wave-interference-main.js.

**Comment by arouinfar** [comment]
The credits are currently up-to-date, but @KatieWoe will need to finalize the QA credits when this sim is in the last round of rc testing.

@DianaTavares you are currently credited as Diana López. Is this how you would like to be credited, or would you prefer Diana López Tavares?

**Comment by DianaTavares** [comment]
I prefer Diana López Tavares, thanks!

**Comment by pixelzoom** [comment]
Hmm... Diana's credits seem to be a little inconsistent across sims.  In Equality Explorer, she is "Diana Berenice López Tavares".   In Area Model suite and Interaction Dashboard, she is "Diana Lopez Tavares" (López incorrect).

**Comment by DianaTavares** [comment]
I suggest  always use Diana López Tavares

**Comment by arouinfar** [comment]
Thanks @DianaTavares. I've updated the sim credits to always use Diana López Tavares.

Assigning to @KatieWoe to finalize the QA credits when this sim is in rc testing.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I was unaware of such a convention. @samreid (I presume) used `ó` in [wave-interference-main.js](https://github.com/phetsims/wave-interference/blob/master/js/wave-interference-main.js), which is the pattern I followed.

I have seen non-ASCII characters in sim credits before, including [hookes-law-main.js](https://github.com/phetsims/hookes-law/blob/master/js/hookes-law-main.js), which has a `ç`.

If this is a convention, then I will make the dozen-or-so commits to change the `ó` it to \u00f3, but perhaps this should be an item on the code review checklist.

**Comment by samreid** [comment]
@jonathanolson can you please comment pros and cons for ascii vs unicode in credits?  What do you recommend?

**Comment by pixelzoom** [comment]
https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/#3unicodeinjavascript says:
> I recommend to keep the source code text with characters from Basic Latin Unicode block (or ASCII). Characters outside ASCII should be escaped. This will ensure less problems when comes to encoding.

While UTF-16 is used internally, JavaScript source code is usually not stored in that format. Unless you specify the encoding, you'll get a default encoding (based on a complicated set of rules), and that's where problems can arise.  So http://speakingjs.com/es5/ch24.html recommend:
> It is highly recommended that you always specify an encoding. If you don’t, a locale-specific default encoding is used. In other words, people will see the file differently in different countries. Only the lowest 7 bits are relatively stable across locales. 
...
> My recommendations can be summarized as follows:
> * For your own application, you can use Unicode. But you must specify the encoding of the app’s HTML page as UTF-8.
> * For libraries, it’s safest to release code that is ASCII (7 bit).

**Comment by samreid** [comment]
Thanks @jonathanolson. @arouinfar can you convert credits to use ascii and escapes?

**Comment by arouinfar** [comment]
I have replaced `ó` with `\u00f3` and `ç` with `\u00e7` in sim credits. 

@pixelzoom @samreid @jonathanolson I would recommend adding something to the code review checklist to check for non-ASCII characters in .js files. @DianaTavares will be credited in several more sims, so we are likely to run into `ó` showing up in sim credits again.

**Comment by samreid** [comment]
Here's a lint rule that would prevent that:

```js
// Copyright 2018, University of Colorado Boulder

/**
 * Lint detector for invalid text based on regex search.  Checks the entire file and does not correctly report line number.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
module.exports = function( context ) {
  'use strict';

  var badRegexes = [
    /[^\u0000-\u007F]+/
  ];

  return {
    Program: function( node ) {
      var sourceCode = context.getSourceCode();
      var text = sourceCode.text;
      badRegexes.forEach( function( badRegex ) {
        if ( badRegex.test( text ) ) {
          context.report( {
            node: node,
            message: 'File contains bad regex: \'' + badRegex + '\''
          } );
        }
      } );
    }
  };
};

module.exports.schema = [
  // JSON Schema for rule options goes here
];
```

**Comment by samreid** [comment]
@pixelzoom I opened https://github.com/phetsims/chipper/issues/732 and @arouinfar used escape codes in Wave Interference credits, can this issue be closed?

**Comment by pixelzoom** [comment]
Nothing else that I'm aware of.

**Comment by KatieWoe** [comment]
Kathryn Woessner, Liam Mulhal, Jacob Romero, Kelly Wurtz, Luara Rea, and Megan Lai

**Comment by samreid** [comment]
Credits updated in the preceding commit.  @KatieWoe can you please double check?  If all is well, please close.

**Comment by KatieWoe** [comment]
Looks good
