### ISSUE TITLE
WaveGeneratorNode API is too broad

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#286]
Related to code review #259:

>  - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

The constructor API for `WaveGeneratorNode` and its subclasses is too broad.  Notes:

* `WaveGeneratorNode` does not use `@param {WavesScreenModel} model`, that parameter can be deleted.
* `LighterGeneratorNode` does not require the entire model, only `model.lightScene`.
* `SoundGeneratorNode` does not require the entire model, only `model.soundScene`
* `WaterGeneratorNode` does not require the entire model, only `model.waterScene`

**Comment by samreid** [comment]
Proposed fix committed, please review.

**Comment by pixelzoom** [comment]
👍 Closing.
