### ISSUE TITLE
ToolboxPanel API is too broad

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#287]
Related to code review #259:

>  - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

ToolboxPanel does not need the entire model, it needs 4 Properties: isMeasuringTapeInPlayAreaProperty, measuringTapeTipPositionProperty, isTimerInPlayAreaProperty, isWaveMeterInPlayAreaProperty.

**Comment by samreid** [comment]
Proposed fix committed, please review.

**Comment by pixelzoom** [comment]
👍 Closing.
