### ISSUE TITLE
WaterSideViewNode API is too broad

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#288]
Related to code review #259:

>  - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

WaterSideViewNode does not need the entire model.  It needs model.waterScene.

**Comment by samreid** [comment]
Proposed fix pushed, please review.

**Comment by pixelzoom** [comment]
👍 Closing.
