### ISSUE TITLE
TheoryInterferenceOverlay API is too broad

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#289]
Related to code review #259:

>  - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

TheoryInterferenceOverlay does not need the entire model. It needs model.scenes and model.sceneProperty.

**Comment by samreid** [comment]
Proposed fix is pushed, please review.

**Comment by pixelzoom** [comment]
👍 Closing.
