### ISSUE TITLE
SlitsControlPanel API is too broad

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#290]
Related to code review #259:

>  - [ ] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

SlitsControlPanel does not need the entire model. It needs scenePropery, waterScene, soundScene, and lightScene.

**Comment by samreid** [comment]
Proposed fix committed, please review.

**Comment by pixelzoom** [comment]
👍 Closing.
