### ISSUE TITLE
Should TheoryInterferenceOverlay use red or colorblind red shade?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#291]
We currently show the minima in red and maxima in yellow.  During code review #259 @pixelzoom asked if we should use our shade of colorblind red instead of pure red.  @arouinfar what do you think?

**Comment by pixelzoom** [comment]
I brought this up in code review because 'red' on 'black' has historically been a bad combination for some types of colorblindness.

**Comment by arouinfar** [comment]
Thanks for the suggestion @pixelzoom! Let's use `RED_COLORBLIND` instead of pure red @samreid.

**Comment by arouinfar** [comment]
👍
