### ISSUE TITLE
ModelViewTransform2.create* is called 10 times in this simulation

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#292]
Inspired by https://github.com/phetsims/wave-interference/issues/264, I observed that `ModelViewTransform2.create*` is called 10 times in this simulation.  Many of these are duplicates and it would be good to isolate them.  It seems the appropriate place to track them is in each Scene.  But the problem is at the moment Scene is "model only".  Once the view is constructed and we know the wave area bounds, we could create the transforms and set them to the Scenes.  This seems a plausible approach but I'm not sure whether it is optimal.  @pixelzoom what do you recommend?

**Comment by pixelzoom** [comment]
These 2 calls to `ModelViewTransform2.createRectangleMapping` look suspicious to me:

BarrierNode:
```js
      // @private - View width for one cell
      this.cellWidth = ModelViewTransform2.createRectangleMapping( scene.lattice.visibleBounds, viewBounds )
        .modelToViewDeltaX( 1 );
```

TheoryInterferenceOverlay:
```js
          const cellWidth = ModelViewTransform2.createRectangleMapping( scene.lattice.visibleBounds, viewBounds )
            .modelToViewDeltaX( 1 );
```

Should/could these be using one the 3 transforms identified in implementation-notes.md?

The call in `TheoryInterferenceOverlay` occurs inside of `{function} updateLines` -- can it be moved outside this function so that it's computed once, or does it really need to be recomputed each time `updateLines` is called?

**Comment by pixelzoom** [comment]
implementation-notes.md says:

> There are 3 coordinate frames:
> 
> * view coordinates
> * lattice coordinates (integer), with damping regions
> * Scene-specific physical coordinates (such as cm or nm)

There are 3 coordinate frames.  What are the transform relationships?  The names used in the code aren't very helpful -- I see  `transform`, `modelViewTransform`, `modelToLatticeTransform`, and `latticeToViewTransform`.   The last 2 are the only ones that I can easily correlate to the 3 coordinate frames identified in implementation-notes.md.  And the ones identified above for `cellWidth` are never given names.

**Comment by samreid** [comment]
Should I take a first pass at factoring these out, storing them in Scene.js after the view is created, then reassigning to you for review?

**Comment by pixelzoom** [comment]
`Scene` sounds like an appropriate place to store these transforms. In most of my sims, I've stored `ModelViewTransform2` instances in the model, typically in the model container's constructor.  The exception to that would be when creating the transform has to occur after ScreenView creation.

**Comment by samreid** [comment]
Proposed fix committed, please review.

**Comment by pixelzoom** [comment]
Looks great, much clearer. Closing.
