### ISSUE TITLE
The theory rays don't reach the right side of the wave area.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#296]
Discovered in #289, the rays don't all reach the right side of the wave area:

![image](https://user-images.githubusercontent.com/679486/50570198-dee10b00-0d3c-11e9-947b-f7af20845545.png)

Is that by design, or should the rays be lengthened?

**Comment by samreid** [comment]
I made the rays longer, @arouinfar can you please review on phettest?  Close if all is well.

**Comment by arouinfar** [comment]
@samreid I just realized the issue -- the source point should be at the barrier. It looks like `?theory` is originating from the lattice origin for the previous screens.

**Comment by samreid** [comment]
Thanks @arouinfar, a bug was introduced when working on the barrier coordinate frame.  Should be repaired now, please review on phettest and close if all is well.

**Comment by arouinfar** [comment]
Looks good!
