### ISSUE TITLE
Enum improvements

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#305]
Let's follow the proposal in https://github.com/phetsims/phet-core/issues/53 and reassign to @pixelzoom when ready.

**Comment by samreid** [comment]
I moved to this pattern for DisturbanceType in this commit https://github.com/phetsims/wave-interference/commit/d538c9d2b66154b094a5f6b5866d30514859a3e8, @pixelzoom would you mind doing a micro-review before I continue?

Also, I noted that unfortunately WebStorm doesn't know how to highlight this too well and is showing a lot of gray underlines:

![image](https://user-images.githubusercontent.com/679486/50854987-d93e8300-1343-11e9-93ef-7d711338132e.png)

**Comment by pixelzoom** [comment]
Looks good to me.

**Comment by samreid** [comment]
I fixed up the other enums, @pixelzoom can you please review?  Close if all is well.

**Comment by samreid** [comment]
I fixed up the other enums, @pixelzoom can you please review? Close if all is well.

**Comment by pixelzoom** [comment]
Enumerations look great.  Questions about a few related fields:

Should this field in Scene be documented as "read-only"?

```js
// @public {WaveSpatialType}
this.waveSpatialType = ...
```

I wonder if this Property in SoundScene might be better named `soundViewTypeProperty`, since it's value is of type `SoundViewType`.

```js
      // @public - indicates the selected view for sound
      this.viewSelectionProperty = new Property( SoundScene.SoundViewType.WAVES, {
        validValues: SoundScene.SoundViewType.VALUES
      } );
```

Similarly in DiffractionModel, I wonder if this Property might be better named `apertureTypeProperty`:

```js
      // @public - selected scene
      this.sceneProperty = new Property( DiffractionModel.ApertureType.CIRCLE, {
        validValues: DiffractionModel.ApertureType.VALUES
      } );
```

**Comment by samreid** [comment]
Thanks, I followed your recommendations, ready for review.

**Comment by pixelzoom** [comment]
👍 Closing.
