### ISSUE TITLE
Plane wave amplitude boosted when emerging from slit

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#310]
While testing https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.61/phet/wave-interference_en_phet.html I noticed that when the wave emerges from the slit, it gets a ~ 5% amplitude boost.  I don't know why this is happening.  @arouinfar can you please test and advise?

![boost](https://user-images.githubusercontent.com/679486/51048029-2a8a8480-1587-11e9-98e6-20cc59ca67d4.gif)

**Comment by arouinfar** [comment]
@samreid I would imagine you have amplitude matching at the boundary, so I don't know what else to suggest. 

I think the amplitude boost is pretty subtle, and I wonder if the low graph sampling rate makes it looks worse than it is.

**Comment by samreid** [comment]
Yes, the wave values from the plane are the same values in the lattice going forward.  Want to close as will not fix?

**Comment by arouinfar** [comment]
👍
