### ISSUE TITLE
Why is the default "One Slit" and should the default be "Two Slits"?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#311]
From slack:

Sam Reid [2:03 PM]
Why is the default “one slit” instead of “two slits”?

Amy Rouinfar [2:04 PM]
Probably because 1 < 2, but that’s not a particularly compelling reason.
Two slits would be a better comparison to the Interference screen.

Sam Reid [2:05 PM]
Would be nice to discuss before 1.0, but could easily be changed even after RC1.  Should I create an issue for discussion? (edited) 

Amy Rouinfar [2:06 PM]
Yes, please open the issue. My vote would be for two slits.

**Comment by kathy-phet** [comment]
I have mixed feelings here. One slit is the starting point to understanding slits ... that a slit acts as a point source and you can treat it like that. Interference adds onto this concept. I think we could keep the default as is for the start up, and the screen icon points people to the fact that you can also investigate 2 slits.

**Comment by ariel-phet** [comment]
The Java sim in essence scaffolds slits the same way. One slit interference is a bit more complex to understand than two slit interference, but I agree with @kathy-phet that there are plenty of cues to suggest moving toward two slits (the icon and the fact that slit separation is disabled until two slits are chosen)

I would leave as is. Back to @arouinfar

**Comment by ariel-phet** [comment]
@arouinfar I do think the combo box is a little odd though, it lists 

No barrier
One Slit
Two Slits

I would change it to 

One Slit
Two Slits
No Barrier

So that when you open it the default of "One Slit" is up top, where the default normally sits. No Barrier is also pedagogically very uninteresting so seems like it belongs last.

**Comment by arouinfar** [comment]
Looks like we'll leave one slit the default @samreid, but let's reorder the combobox items as @ariel-phet suggested.

**Comment by samreid** [comment]
I reordered them and pushed, @arouinfar can you please test on phettest?

**Comment by arouinfar** [comment]
👍
