### ISSUE TITLE
Design team testing

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#312]
The sim has been through numerous changes since the initial dev test, and it would be great if @arouinfar and possible other design team members could take it for a test drive before we request dev.2.

The latest version is published here:
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.62/phet/wave-interference_en_phet.html

**Comment by arouinfar** [comment]
@samreid dev.62 has the green light from me. :)

Assigning @kathy-phet and @ariel-phet if they'd also like to take a look.

**Comment by ariel-phet** [comment]
@samreid I have looked over the sim, and with @arouinfar comments this issue can be closed.
