### ISSUE TITLE
Design team testing for dev.65

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#318]
As a precursor to QA testing in #317, it would be nice for the design team to take a closer look at the latest version:

https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.65/phet/wave-interference_en_phet.html

This has the following recent changes: 
https://github.com/phetsims/wave-interference/issues/316
https://github.com/phetsims/wave-interference/issues/315

@arouinfar already reviewed a recent version, and signed off on subsequent changes.  So @ariel-phet and @kathy-phet it would be great for you to take a look.

**Comment by samreid** [comment]
I also published dev.66 and opened a QA issue.  If you are going to test, please use https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.66/phet/wave-interference_en_phet.html

**Comment by ariel-phet** [comment]
Played a fair bit, overall things are looking good. Closing
