### ISSUE TITLE
Wave clears after some time

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#319]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/264
When a wave stops, the background returns to its default state following after the last wave.  However, often that wave disappears between 1/4 and 3/4 of the way through the screen.  This gives the appearance of the screen being reset in a sense, rather abruptly.  Appears in water (top and side), sound, and light, on both the Waves and Interference screens (Slit screen handles turning off the wave differently).  Seems to occur more noticeably the longer the wave has been going.
**Steps to reproduce:**
1. Go to the Waves screen (easier to distinguish with one wave rather than two)
2. Start a continuous wave of any kind
3. Wait until the first wave has left the screen.  You can wait longer for possibly more effect
4. Turn off the continuous wave and wait

**Screenshots:**
https://drive.google.com/file/d/1oj5stbflK4Gu9GUfh58HQ9HzZH-Cuh0v/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.66/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.66 2019-01-22 02:30:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
This is not the desired behavior @KatieWoe. I'm seeing the same thing on macOS 10.13.16/latest Chrome. Occasionally, the lattice will immediately clear when the source is turned off -- I saw this happen pretty often for light. 

However, this is somewhat new, as the behavior was correct when I originally verified it on master. It looks like dev.65 and dev.64 are behaving the same as dev.66

**Comment by KatieWoe** [comment]
I just checked master and it has the problem @arouinfar

**Comment by arouinfar** [comment]
Thanks @KatieWoe, but what I meant is that when I verified it on master some time ago, this issue didn't exist. However, master now is not the same as master was then. I was hoping to help @samreid nail down a time frame where the problem was introduced.

**Comment by samreid** [comment]
I don't feel like I have a deep understanding of the problem, but after committing the change above I am unable to create the buggy symptom.  @arouinfar and @KatieWoe can you please test on phettest/master?

**Comment by arouinfar** [comment]
Master looks good to me @samreid.

**Comment by samreid** [comment]
@KatieWoe reported in https://github.com/phetsims/wave-interference/issues/322#issuecomment-457729922

> May not be connected, but also saw some variant of #319. If you have the continuous wave going with Both particles and switch to pulse and fire a pulse, end of the continuous wave disappears too soon.

**Comment by samreid** [comment]
In the commit, I simplified the pruning logic and expanded the base set of deltas to 10.  If the user taps rapidly on the continuous wave on/off button, you can still create incorrect behavior, but we previously determined this is acceptable.
