### ISSUE TITLE
Reset does not change sound display

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#321]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/264
When the orange reset button is pressed the setting in sound for "wave, particle, or both" does not reset.  If the sim was on particle or both before the reset and a wave was propagating, switching back to sound will show the particles behaving for a moment as if still effected by a wave.
**Steps to reproduce:**
1. Refresh sim and go to the wave screen or interference screen
2. Go to sound scene
3. Switch to both scene
4. Start a sound wave
5. As wave is going, hit orange reset button
6. Return to sound scene

**Screenshots:**
https://drive.google.com/file/d/1vyumbU-qZRQ_rmWY0caHPF3UZV0ON-SZ/view?usp=sharing

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.66/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.66 2019-01-22 02:30:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Good catch @KatieWoe. The ResetAllButton should always take the sim back to its startup state.

**Comment by KatieWoe** [comment]
Looks good on master @samreid

**Comment by samreid** [comment]
Thanks, closing.
