### ISSUE TITLE
When amplitude is large water can go above faucet

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#323]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/264
Likely small and may not be easily solvable.  When water is in side view the water splash can be high enough to go over the faucet.  This can appear a bit odd.
**Steps to reproduce:**
1. Go to Wave Screen, Water side view scene
2. Adjust the Amplitude to be max
3. Start waves

**Screenshots:**
![splashabovefaucet](https://user-images.githubusercontent.com/41024075/51571299-0c623580-1e5f-11e9-8dfe-4b51e4f83a73.jpg)

Troubleshooting information (do not edit):

<details>

Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.66/phet/wave-interference_en_phet.html
Version: 1.0.0-dev.66 2019-01-22 02:30:43 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@samreid I'll go ahead and defer this for 1.0, but I think we should explore this option for 2.0:

> reduce the amplitude scaling back to 100% and compensate by recalibrating other factors such as the wave brightness factors and light intensity screen + graph scale factors

**Comment by samreid** [comment]
Self-assigned for initial investigation.

**Comment by samreid** [comment]
If we like the rest of the calibration, perhaps this could be adjusted by simply changing the scale factor for the "side view" water height.  @arouinfar do you think that could work?  It could save a lot of time over re-tuning brightness/intensity screen/graph/etc.

**Comment by arouinfar** [comment]
> If we like the rest of the calibration, perhaps this could be adjusted by simply changing the scale factor for the "side view" water height.

@samreid that sounds like a great idea! Let's give it a try.

**Comment by arouinfar** [comment]
> @arouinfar is acceptable, or do we need to keep up the wave scale out to the right? Another alternative would be just to rescale the wave values in the vicinity of the source--not globally.

@samreid I think it will be acceptable. After all, earlier dev versions didn't extend above the faucet in side-view (for example, [dev.55](https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.55/phet/wave-interference_en_phet.html)). I'm not sure we want to disproportionally scale the amplitudes, so I'd prefer to stick to the global approach. 

Can you push this change to master so I can test it out?

**Comment by samreid** [comment]
Pushed to master, please review on phettest.

**Comment by arouinfar** [comment]
Looks good in master @samreid!

**Comment by samreid** [comment]
Thanks, closing.
