### ISSUE TITLE
Timer sometimes "shivers" when changing numbers

### ISSUE THREAD

**Issue by rea-laura** [phetsims/wave-interference#324]
<b>Test Device</b>

Jordan

<b>Operating System</b>

MacOS 10.14.2

<b>Browser</b>

Chrome 71.0.3578.98

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/264:
Timer numbers occasionally shiver. This happens consistently when it changes to certain numbers - for example, 5, 8, 10, and 13.

<b>Steps to Reproduce</b>

1) open sim and go to "waves" page
2) select and drag timer tool onto the page. Place anywhere.
3) press start on timer. Watch for slight shivers as the seconds change.

<b>Visuals</b>

![kapture 2019-01-22 at 16 26 04](https://user-images.githubusercontent.com/44005544/51572587-2bfb5d00-1e63-11e9-8049-99f712f808a9.gif)

**Comment by arouinfar** [comment]
Nice observation @rea-laura. In https://github.com/phetsims/wave-interference/issues/239, we decided to use a monospaced font (Lucida Console) for the TimerNode so the numbers wouldn't shift. From the screenshot, it looks like the test device may not have that font, and so it's using the Arial fallback. I don't think there's anything in particular that we can do here. @samreid if you agree, please close.

**Comment by samreid** [comment]
In #239 we identified that there are other monospace fonts we can use, such as Courier, but it seemed the design team preferred Arial to Courier.  Therefore it seems appropriate to close this issue.

@arouinfar or @ariel-phet do you recommend further discussion or work here?

**Comment by arouinfar** [comment]
@samreid I think the team consensus was that Courier is a bit too strongly serifed and looks typewriter-y, which didn't look great in the TimerNode. The shifting digits aren't particularly harmful, so I think the Lucida Console/Arial combination is good enough.
