### ISSUE TITLE
Hard to select positions on the slider

### ISSUE THREAD

**Issue by rea-laura** [phetsims/wave-interference#325]
<b>Test Device</b>

Chadwick

<b>Operating System</b>

Chrome OS 71.0.3578.127

<b>Browser</b>

Chrome 71.0.3578.127

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/264:

It is sometimes hard to click directly on a location on the slider to move the slider there. The slider pointer area seems so thin that it is difficult to get the cursor on it. 

<b>Steps to Reproduce</b>

1) open sim
2) go to any page from home screen
3) try to move the slider by clicking a location on the slider so it moves directly there. It is difficult to get the cursor to change to a hand because the slider pointer area is so small.

<b>Visuals</b>

Apologies for terrible quality of gif...
![my video gif](https://user-images.githubusercontent.com/44005544/51622782-96101280-1ef4-11e9-97a0-60221d977a28.gif)

**Comment by samreid** [comment]
In https://github.com/phetsims/wave-interference/issues/148#issuecomment-423396629 it was requested that the slider track height be 1 pixel.  @arouinfar do you want to increase the slider track heights, or increase their pointer areas?  SUN/SliderTrack doesn't currently have support for increasing pointer area, but we could investigate it.

**Comment by arouinfar** [comment]
Thanks @rea-laura. 

@samreid there's not exactly extra vertical space to go around, especially given the oddities in Chromebook layout described in #326. I don't think we should increase the height of the slider track. So long as the slider thumbs and tweakers are easily clickable/touchable (which they are), it's not really a usability concern, either.
