### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#328]
As pointed out in https://github.com/phetsims/QA/issues/267, this sim needs screenshots for 1.0.

**Comment by arouinfar** [comment]
Screenshots for 1.0 have been committed. 

I am reserving alt3 for the Diffraction screen, which will be included in version 2.0.  Leaving this issue open, but marking `status:on-hold` until we near 2.0.

**Comment by arouinfar** [comment]
According to @phet-steele:
>just upload those screenshots. As long as they have the same name, github will be smart and replace the old one with the new

I followed his advice, and the above commit appears to have done the trick. Screenshots are ready for 1.0 @samreid.

**Comment by samreid** [comment]
We published 1.0 with screenshots, so I suppose this issue can be closed.
