### ISSUE TITLE
Sound particles temporarily smear when using renderer: 'webgl'

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#330]
From https://github.com/phetsims/wave-interference/issues/322#issuecomment-457728933

@KatieWoe said:

> We also saw what the odd flash I saw with @ariel-phet when switching from wave to particle was.  If the sim is paused when you do this, you see this:
![3e3443c1-bdf1-4e2b-a8af-1bb317e961b6](https://user-images.githubusercontent.com/41024075/51773000-b08bec80-20aa-11e9-80ad-9c9b91182ac9.png)

**Comment by samreid** [comment]
In the conversation in https://github.com/phetsims/wave-interference/issues/322#issuecomment-457769622 @KatieWoe and @ariel-phet indicated that this bug isn't critical to fix before publication.

**Comment by samreid** [comment]
I reproduced this problem on Chrome with this change:

```
Index: js/waves/view/WavesScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/waves/view/WavesScreenView.js	(revision 62ff50340c46be3abb6ff5e571d0ee881a627468)
+++ js/waves/view/WavesScreenView.js	(date 1548558613000)
@@ -405,7 +405,7 @@
 
         // Too much garbage on firefox, so only opt in to WebGL for mobile safari (where it is needed most)
         // and where the garbage doesn't seem to slow it down much.
-        const useWebgl = Util.isWebGLSupported && phet.chipper.queryParameters.webgl && platform.mobileSafari;
+        const useWebgl = true;
         const node = useWebgl ?
                      new SoundParticleImageLayer( model, this.waveAreaNode.bounds, { center: this.waveAreaNode.center } ) :
                      new SoundParticleCanvasLayer( model, this.waveAreaNode.bounds, { center: this.waveAreaNode.center } );
```

1. Choose "Sound" scene
2. Let it animate a bit.
3. Pause the sim
4. Select "Particles"

@jonathanolson is best qualified to help understand what is happening here.  @jonathanolson any ideas?

**Comment by jonathanolson** [comment]
Not sure quite yet, but it definitely looks like something is preventing the gl.clear from happening, so it is just drawing on top of what was there before.

**Comment by KatieWoe** [comment]
Noting this in https://github.com/phetsims/QA/issues/511

**Comment by arouinfar** [comment]
This issue is pretty stale. I recommend we either close as wont-fix, or reassign to @jonathanolson/@samreid if it's worth digging into the gl.clear issue. I'm fine with closing, but I'll let @ariel-phet make that call.

**Comment by samreid** [comment]
We saw another issue in Natural Selection where the first webgl render was missed, I wonder if it could be related?

**Comment by ariel-phet** [comment]
I think closing as `wontfix` is the correct call
