### ISSUE TITLE
Moving amplitude to 0 repeatedly results in waves being deleted, buggy-looking waves

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/wave-interference#333]
For https://github.com/phetsims/QA/issues/274. Seen on multiple devices. Propagating waves can be "deleted" by moving amplitude to 0 repeatedly.

![issue](https://user-images.githubusercontent.com/31285590/51939589-15a65180-23cd-11e9-93fd-5528c3869bec.gif)

**Comment by samreid** [comment]
Setting the wave amplitude to zero has the same effect on the temporal mask as turning off the wave generator.  Hence it suffers from the same buggy behavior as described in https://github.com/phetsims/wave-interference/issues/319#issuecomment-458324396.  I'm not sure how this could be addressed, leaving assigned to @arouinfar and @ariel-phet to discuss and prioritize.

**Comment by ariel-phet** [comment]
Deferring for now, we will reevaluate after 1.0. However, it seems like the action required to cause this bugginess is not pedagogically productive anyhow, so we might just leave as is.

**Comment by KatieWoe** [comment]
Something I noticed in https://github.com/phetsims/QA/issues/424.  When you let the wave go normally after this, it continues to look pixelated.
Before bug:
![beforejiggle](https://user-images.githubusercontent.com/41024075/64558850-1c515b80-d302-11e9-896f-5547cb9d4238.png)

After bug:
![afterjiggle](https://user-images.githubusercontent.com/41024075/64558860-22dfd300-d302-11e9-8299-186a0f20aa28.png)

**Comment by samreid** [comment]
Without moving to a fully analytic model, I'm not sure how I would address the above problem.  @arouinfar or @ariel-phet do you want any investigation on this before publication?  @KatieWoe how long does the pixellation last before it dissipates?

**Comment by KatieWoe** [comment]
It really only stops when you change the wave, such as the frequency.  It might dissipate eventually, but it didn't seem to while I watched.

**Comment by arouinfar** [comment]
@pixelzoom @ariel-phet the pixelation only seems to occur after pretty harshly scrubbing the amplitude slider. Gradual/less frequent changes in amplitude don't lead to noticeable noise/pixellation in the lattice. Given @samreid's assessment in https://github.com/phetsims/wave-interference/issues/333#issuecomment-530576785 and the fact that the initiating behavior is more of an edge case (and not pedagogically useful), I'm fine with continuing to defer this issue. I'd also be fine with closing this as `type:wontfix`, but I'll defer to @ariel-phet.

**Comment by pixelzoom** [comment]
I hadn't previously been involved with this issue (that I can recall), so I'm unsubscribing.  Let me know if you need feedback from me.

**Comment by arouinfar** [comment]
Sorry, Chris! I tagged the wrong dev. 🙈

**Comment by ariel-phet** [comment]
@arouinfar @samreid I think I am going to go with `wontfix` -- scrubbing the amplitude in this way is just not a use case we need to support, and it seems like addressing it would be difficult and/or very expensive.
