### ISSUE TITLE
QA credits should be alphabetical

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#334]
From slack:

Kathryn Woessner [3:43 PM]
Not sure if there's an issue for this, so: QA for all add (if not there already): Steele Dalton, Megan Lai, Liam Mulhall, Laura Rea, Jacob Romero, Katie Woessner, and Kelly Wurtz
Credits

Sam Reid [3:44 PM]
Checking…
Got it.  It is in this order: Katie Woessner, Steele Dalton, Megan Lai, Liam Mulhall, Laura Rea, Jacob Romero, Kelly Wurtz.  Is that OK?

Kathryn Woessner [3:45 PM]
It should be alphabetical
So I should be just before kelly

**Comment by arouinfar** [comment]
@samreid while you're in the credits, can you make sure the other categories are also alphabetized?

**Comment by samreid** [comment]
I thought the policy was to put the current lead first, then others alphabetical.  Here's the current values:

```js
  const simOptions = {
    credits: {
      leadDesign: 'Noah Podolefsky, Amy Rouinfar',
      softwareDevelopment: 'Sam Reid',
      team: 'Wendy Adams, Diana L\u00f3pez Tavares, Ariel Paul, Kathy Perkins, Katie Woessner',
      qualityAssurance: 'Katie Woessner, Steele Dalton, Megan Lai, Liam Mulhall, Laura Rea, Jacob Romero, Kelly Wurtz',
      graphicArts: 'Cheryl McCutchan'
    }
  };
```

Let me know what changes you recommend.

**Comment by arouinfar** [comment]
@samreid looks like lead design credits are a bit all over the place. Some put HTML5 lead first, some alphabetize, and some specify codebase in parentheses after the name. Leaving things alphabetical seems reasonable to me.

**Comment by samreid** [comment]
> I thought the policy was to put the current lead first, then others alphabetical. 

According to CreditsNode.js this convention apparently applies to design and software development only: https://github.com/phetsims/joist/blob/4768ca48781f7c92aedbeb7656a98d09ec2a0426/js/CreditsNode.js#L62-L103

I'll alphabetize QA.

**Comment by samreid** [comment]
> @samreid looks like lead design credits are a bit all over the place. Some put HTML5 lead first, some alphabetize, and some specify codebase in parentheses after the name. Leaving things alphabetical seems reasonable to me.

I'd prefer to list @arouinfar first in lead design, since she is the lead designer *for this version*.  However, I will not do so until cleared by @ariel-phet or @arouinfar.  Let me know if that's OK.

**Comment by samreid** [comment]
> @samreid while you're in the credits, can you make sure the other categories are also alphabetized?

It looks like team was already alphabetical.

**Comment by ariel-phet** [comment]
@samreid yes, please put @arouinfar first in lead design

**Comment by samreid** [comment]
> It looks like "team" category was already alphabetical.

My mistake, it looks like `Diana L\u00f3pez Tavares` should be alphabetized on T rather than L.  I'll push shortly.

**Comment by samreid** [comment]
OK that's pushed.  Since credits changes (this issue) and icon changes (#335) were the only changes since RC.1, I decided to publish these changes as RC.2.  @arouinfar or @ariel-phet do you want to briefly check the credits and icon changes?
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-rc.2/phet/wave-interference_en_phet.html

Anything else before this is published to the PhET website?

**Comment by arouinfar** [comment]
Well, I briefly went down the rabbit hole of figuring how one should alphabetize double surnames. The Chicago Style Manual says that in the absence of a hyphen, a double last name would be alphabetized by the 2nd last name (Tavares). However, APA style says that double last names should always be alphabetized by the first last name (López), regardless of whether it has a hyphen or starts with something like "de".  This seems like it's more of a matter of convention for a particular professional organization, rather than an actual rule of the English language.

Personally, I would leave it alphabetized as López, as it looks a bit weird to go form Perkins to López.

**Comment by samreid** [comment]
In the commit, I rearranged the credits, here is RC.3 that can be used for verification.
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-rc.3/phet/wave-interference_en_phet.html

Anything else before Wave Interference 1.0 is published to the PhET website?

Also, the Area Model suite has other occurrences where López Tavares is alphabetized as T in the credits.  Should we create an issue to address those?  It wouldn't take long.

```
graphicArts: 'Mariah Hermsmeyer, Amanda McGarry, Diana L\u00f3pez Tavares'
```

**Comment by ariel-phet** [comment]
@samreid that is Diana's full name, so no reason not to alphabetize that way. Alphabetizing the credits list is of very minor concern.

**Comment by samreid** [comment]
Instructions unclear.  Do you want alphabetized as "T" or "L"?  Do you want me to change this and publish RC.4?  Anything else before publishing Wave Interference?

**Comment by ariel-phet** [comment]
@samreid credits fine as is in RC.3. Please go ahead and publish

**Comment by samreid** [comment]
Thanks, I'll close and publish.  Up to @arouinfar if she wants to do anything for Area Model.
