### ISSUE TITLE
Slits screen icon should have plane wave

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#335]
For https://github.com/phetsims/QA/issues/274.

@KatieWoe noticed that the screen icon has a spherical wave approaching the barrier. It would be more appropriate to show a plane wave, so I've updated the assets.

@samreid you can find the updated assets in the [sim design folder](https://drive.google.com/drive/u/0/folders/0B6CMwxdP0NGYdWdmeGo0QVhvMUk) on Drive.

**Comment by samreid** [comment]
I committed the new icon and pushed to 1.0 branch.  I also merged to master so it can be tested on phettest.  @arouinfar do you mind reviewing on phettest?

**Comment by arouinfar** [comment]
👍
