### ISSUE TITLE
"3rd party libraries" and "thanks to" are not correct 

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#339]
@ariel-phet pointed out that the "3rd party libraries" and "thanks to" are not correct for Wave Interference.  A third-party-report step may need to be run again.

![image](https://user-images.githubusercontent.com/679486/52079597-2aaced00-2553-11e9-812f-0ee7494c7601.png)

**Comment by samreid** [comment]
@mattpen or @jonathanolson do you know what step fills in those parts on the website?  I'm not sure how to fix this.

**Comment by samreid** [comment]
Elevating priority so that our sponsor's names will be there when they look.

**Comment by samreid** [comment]
@arouinfar is this something that can be input through the administration interface?

**Comment by samreid** [comment]
The third-party-licenses.md file was updated during deploy in this commit: https://github.com/phetsims/sherpa/commit/590adc76c52948798d313fbf129d7b938ccd4bb1

**Comment by arouinfar** [comment]
@samreid I can edit the "Third-party Libraries" and "Thanks To" fields directly in the administration interface. However, I'm pretty sure third-party libraries should automatically populate. I'm not sure if manually adding them would end up in duplicated results.

For "Thanks to", I'm happy to add acknowledgements for STROBE and/or Google.org. There's not currently a corresponding "thanks" section in the credits, so not sure how they should be credited. (See [pendulum-lab-main.js](https://github.com/phetsims/pendulum-lab/blob/master/js/pendulum-lab-main.js#L27) as an example.)

**Comment by arouinfar** [comment]
On Slack:

> Amy Rouinfar [2:41 PM]
How should STROBE be credited in “Thanks to”? I can think of a few options:
STROBE
STROBE NSF Science and Technology Center
STROBE NSF Science and Technology Center on Real-Time Functional Imaging
>
>Ariel Paul [2:50 PM]
I think the second one would be best

I added STROBE NSF Science and Technology Center to the "Thanks To" section of the sim page, but @samreid should probably add them to the sim credits too. @kathy-phet said that Google.org acknowledgement was not necessary.

**Comment by samreid** [comment]
Like this?

![image](https://user-images.githubusercontent.com/679486/52088721-e711ad80-2569-11e9-8ed3-00ada69456e4.png)

**Comment by samreid** [comment]
The pendulum lab example has a sentence.  Do you want something more like "Thanks to STROBE NSF Science and Technology Center for their support"?

**Comment by mattpen** [comment]
> However, I'm pretty sure third-party libraries should automatically populate. 

Yes, they should.  I'll run that step manually tonight.  This could be avoided by completing phetsims/perennial#106

**Comment by arouinfar** [comment]
@samreid let's go with "Thanks to STROBE NSF Science and Technology Center for their support".

Looks like the 3rd-party libraries have been populated on the sim page, so unassigning @mattpen @jonathanolson.

**Comment by arouinfar** [comment]
Thanks @samreid. On second thought, perhaps we should use the more verbose version of STROBE's name, as we did in the email announcement. Let's also include a period at the end of the sentence. Can you update the text to the following:

"Thanks to the STROBE NSF Science and Technology Center on Real-Time Functional Imaging for their support."

@ariel-phet interfaces with the folks at STROBE, so his call on whether this merits an immediate maintenance release or not.

**Comment by samreid** [comment]
Text updated on 1.0 and master, @arouinfar please review on phettest (make sure line break is OK).

**Comment by arouinfar** [comment]
@samreid line break is fine, but it might look a bit better to put the break between "Imaging" and "for", so the second line has a bit more text. That's a pretty nit-picky suggestion, so up to you.

**Comment by samreid** [comment]
We do not have control over the positioning of the line breaks, but a shorter sentence probably wouldn't incur a line break.  @arouinfar any thoughts or changes before maintenance release?

**Comment by arouinfar** [comment]
> We do not have control over the positioning of the line breaks, but a shorter sentence probably wouldn't incur a line break.

Understood @samreid. I think it's better to use STROBE's full name when acknowledging them in the credits, so the line break can stay where it is.

**Comment by samreid** [comment]
I published an RC here:
https://phet-dev.colorado.edu/html/wave-interference/1.0.1-rc.2/phet/wave-interference_en_phet.html

The only change in the maintenance branch of the wave-interference repo since 1.0 is the credits "thanks" change, but it would be good to have someone else spot check the credits change and make sure nothing unexpected happened.  @arouinfar or @ariel-phet or @KatieWoe can you run a quick sanity test before I run the production publication step?

**Comment by arouinfar** [comment]
@samreid the credits dialog looks good. I lightly tested each screen, and nothing seems disturbed. If the only delta since 1.0 is the edits to the credits, I don't think we need to be worried about further testing.

**Comment by samreid** [comment]
This change is published as 1.0.1, closing.
