### ISSUE TITLE
Changing source frequency causes artifacts on the lattice 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#34]
For #31 

Reported in Unfuddle Ticket [#2657](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2657)
> When changing the frequency of the source in wave-interference 1.09, numerical high-frequency artifacts are introduced into the lattice.  At the Jan 6 developer meeting, Mike Dubson said he ran into a similar problem in resonance and was able to solve it by modulating the phase as the frequency was changed.  He said his approach would probably work for wave-interference too.

@samreid perhaps this is something you should consider for HTML5?

**Comment by samreid** [comment]
I implemented that several months ago and it is working nicely.
