### ISSUE TITLE
SoundParticleCanvasLayer.js and SoundParticleImageLayer.js have copied code

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#341]
@pixelzoom pointed out that SoundParticleCanvasLayer.js and SoundParticleImageLayer.js have copied code, they should be refactored to share code so we don't accidentally end up with a situation where things look different on one platform.

**Comment by pixelzoom** [comment]
Consider encapsulating the look of sound particles in a new `SoundParticleNode`, similar to `GAS_PROPERTIES/ParticleNode`.

**Comment by samreid** [comment]
Proposed fix committed, @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
👍 Closing.
