### ISSUE TITLE
StepButton can enable/disable itself

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#342]
Noted while doing something similar in Gas Properties.

In TimeControls.js:

```js
      const stepButton = new StepButton( {
        ...
      } );

      // Only enable the step button when the model is paused.
      model.isRunningProperty.link( isRunning => {stepButton.enabled = !isRunning;} );
```

The listener for `model.isRunningProperty` is unnecessary.  StepButton is capable of observing `model.isRunningProperty` itself:

```js
const stepButton = new StepButton( {
   isPlayingProperty: model.isRunningProperty
   ...
} );

**Comment by pixelzoom** [comment]
See also https://github.com/phetsims/scenery-phet/issues/466.

**Comment by samreid** [comment]
Implemented and tested, and it seems to be working nicely.  I think it's safe to close, but @pixelzoom feel free to reopen/double check if you wish.
