### ISSUE TITLE
User suggestion: Speaker option

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/wave-interference#343]
> I love the new wave interference Phet simulation and assigned it to my students last week.  The light wave patterns are clearly visible as are the water wave patterns and students can totally get the interference patterns created.  However, it would be GREAT if there was a speaker option for the sound wave generator so they could HEAR the difference between constructive and destructive interference patterns.   I've seen this tool in other sims you have created.

**Comment by arouinfar** [comment]
@oliver-phet adding sound is a feature we've considered, but deferred for 1.0, see #80. I'll move this suggestion to that issue.
