### ISSUE TITLE
check phet.chipper.queryParameters.webgl first

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#351]
Non web-gl sims can experience a pause on MacBook due to GPU switching, see https://github.com/phetsims/scenery/issues/621

In WaveScreenView:

```js
const useWebgl = Util.isWebGLSupported && phet.chipper.queryParameters.webgl && platform.mobileSafari;
```

You need to check `phet.chipper.queryParameters.webgl` first if you want to prevent `Util.isWebGLSupported`, which is the scenery test that causes the GPU switching.

**Comment by pixelzoom** [comment]
You might also want to check `platform.mobileSafari` before doing `Util.isWebGLSupported`.

**Comment by samreid** [comment]
Proposed fix committed.  Not sure how this issue overlaps with https://github.com/phetsims/scenery/issues/621, perhaps it is not covered in that issue because this sim does use webgl (at least for some platforms).  This seemed straightforward, but wouldn't hurt for @pixelzoom to double check, if you have a moment.

**Comment by samreid** [comment]
I also noted that Chrome now requires high perf gpu even for the google homepage.  This seems different than before.  Some notes over here: https://apple.stackexchange.com/questions/124996/stop-chrome-from-switching-to-dedicated-gpu

**Comment by pixelzoom** [comment]
https://github.com/phetsims/wave-interference/commit/948d5500149f161a12eb354fd207390b18f1d719 inspected, looks good to me.  I'm not familiar with where this was an issue in Wave Interference, so didn't test.   Feel free to close if nothing else to do.
