### ISSUE TITLE
Update to use new NumberControl API

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#352]
In https://github.com/phetsims/scenery-phet/issues/451 the NumberControl API was changed, and the Slits screen control panel went from looking like this:

![image](https://user-images.githubusercontent.com/679486/54504240-6aa81380-48f8-11e9-82a1-1151528605af.png)

to looking like this:

![image](https://user-images.githubusercontent.com/679486/54504261-87444b80-48f8-11e9-8d5b-4de558d2b9d5.png)

This blocks publication because it is an unintentional design change.  I'm not sure why it was missed as part of https://github.com/phetsims/scenery-phet/issues/451 or if that suggests other sims may have also been missed.

**Comment by samreid** [comment]
This looks fixed, but it would be great if @arouinfar could compare phettest to 1.0 and make sure I didn't miss anything.

**Comment by arouinfar** [comment]
I compared master and 1.0, and the NumberControls look like a perfect match.
