### ISSUE TITLE
What should the default wavelength be for the diffraction screen?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#353]
The default value for screens 1-3 is the center of the frequency spectrum, which is 511nm.  

![image](https://user-images.githubusercontent.com/679486/54570080-d3e46100-49a2-11e9-8a4b-6a8eb020274a.png)

The design doc specifies 550nm, which is a round number but is a little more washed out and noticeably different than the other screens:
![image](https://user-images.githubusercontent.com/679486/54570101-e8285e00-49a2-11e9-9e7e-c1616e7e98ca.png)

Or we could go with 510nm, which sounds rounder than 511nm but is pretty close?

What do you recommend?

**Comment by arouinfar** [comment]
Let's go with 511 nm @samreid. I'm not sure where that 550 nm came from, maybe just a mistake on my part.

**Comment by samreid** [comment]
OK thanks, the code already has 511nm, closing.
