### ISSUE TITLE
How should we implement the case where the aperture width is much larger than the wavelength?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#354]
The design doc said:

> We would like for the diameter range to extend beyond the diffractive limit (a ~ 𝛌). This mockup is idealized, so there will likely be some edge effects in the screen.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/679486/54577476-9cd17800-49c1-11e9-9a75-f76f9fb8ac02.png">

At a recent design meeting, I asked how this might be implemented, and we agreed to see how the existing FFT algorithm would handle it, then we could decide whether additional modifications are necessary.

I finished implementing correct model units for the Ellipse scene, and by default it looks like this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/679486/54577624-1ff2ce00-49c2-11e9-84d1-8fc7abd2e364.png">

At the max diameter value of 8000nm, the result looks like this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/679486/54577665-40bb2380-49c2-11e9-9d47-847f7344cb65.png">

@arouinfar can we please discuss how to proceed?

**Comment by samreid** [comment]
@kathy-phet reviewed the behavior yesterday and said it might be acceptable.  I indicated that the implementation will be simplest if we do not need to add an extra postprocessing step for this part.  It seems like it warrants further discussion.

**Comment by arouinfar** [comment]
@samreid I think this would be most productively discussed in a design meeting once @ariel-phet and I are back. Assuming everyone will be in town, let's plan on putting this sim on the 4/4 design meeting docket.

At first glance, the behavior seems reasonable, but  when I open the full-size screenshot in a new tab, the fringe effects become pretty obvious. I'm sure there is some balance between choice of FFT algorithm and performance, etc. but that might be easiest to discuss in design meeting.

Unassigning myself for now, adding to the design meeting agenda, and tagging for design meeting.

**Comment by samreid** [comment]
After implementing #355, there are many fewer artifacts, especially for the ellipse scene.  We can also tune the "blurring" of the aperture if that helps.

**Comment by samreid** [comment]
@ariel-phet suggested cross-blending (fading) the diffraction pattern with the shape of the aperture when a>>Lambda.

@samreid will experiment with when the Airy disk breaks down to determine the point for a>>lambda.
@ariel-phet said maybe 2000nm or 4000nm for 500nm light, we could start blending over to the aperture pattern.

@ariel-phet will look into it further and report back.

**Comment by samreid** [comment]
Blending for a cross-fade leaves an odd intermediate state:

![image](https://user-images.githubusercontent.com/679486/56145491-9e12a800-5f61-11e9-82db-3789a80dd590.png)

**Comment by samreid** [comment]
I created a dev version to demonstrate the cross-fade approach.  I'd like to get feedback on this before going further on this issue.  I created a dev version which is only set up for "Ellipse" scene, please do not select other scenes.  I'm asking in part because the intermediate state like https://github.com/phetsims/wave-interference/issues/354#issuecomment-483302547 seemed odd
https://phet-dev.colorado.edu/html/wave-interference/1.1.0-dev.4/phet/wave-interference_en_phet.html?screens=4

@arouinfar and @ariel-phet can you please review it and let me know if the cross-fade approach seems reasonable?

**Comment by ariel-phet** [comment]
related to #360, we will want to address that issue before revisiting this one

**Comment by arouinfar** [comment]
Marking as `status:on-hold` and reassigning to @samreid for review once #370 has been addressed.

**Comment by samreid** [comment]
As discussed in https://github.com/phetsims/wave-interference/issues/370, we will not go out of the FFT range, closing.
