### ISSUE TITLE
Create a Wave Interference variant where each screen is a different wave type

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#356]
From my notes from Thursday's status meeting:

* We would like to create a basic waves sim, with one screen for each scene.
* I could start on that without too much more design work.
* New repo "waves" or "Waves: Basics"--email with @arouinfar to come up with a name.
* It would be good to get started on this.

This idea is also mentioned in the design meeting notes from February 19, 2019.

I'd like to finalize the sim name before creating the repo.  But I can start prototyping it in the wave-interference repo (perhaps with query parameters) before we create the repo.

**Comment by samreid** [comment]
Is this supposed to be based on the "waves" screen of Wave Interference, with neither slits nor multiple source?

**Comment by arouinfar** [comment]
@samreid there hasn't been any design work beyond the one brainstorming meeting.

The sim would only include the Waves screen of Wave Interference. Instead of three scenes (one for each wave type), we would have three screens -- Water, Sound, and Light. I would say a first pass at implementation would be to split the Waves screen into these three separate screens, but we would really need to have more design discussions before taking things any further.

**Comment by samreid** [comment]
In the preceding commit, I created a rough draft for the simulation, you can see it on phettest at:
http://phettest.colorado.edu/wave-interference/wave-interference_en.html?ea&brand=phet&mediumScreens

I'll create issues for some follow-up work/questions.

**Comment by samreid** [comment]
The main work is done, I noted 2 issues above.  Reassigning to @arouinfar for other feedback on this rough draft.

**Comment by arouinfar** [comment]
Thanks @samreid! Could you publish this as a dev version instead? The VPN is super sluggish here.

**Comment by samreid** [comment]
I'm happy to create a new dev version, but suffering from the problem described in https://github.com/phetsims/special-ops/issues/133, so cannot easily create dev versions at the moment.  I'll keep you posted.

**Comment by samreid** [comment]
@zepumph kindly created one here:
https://phet-dev.colorado.edu/html/wave-interference/1.1.0-dev.1/phet/wave-interference_en_phet.html?mediumScreens

**Comment by arouinfar** [comment]
Thanks @zepumph!

@samreid everything's looking good. I don't have any further suggestions for now, but this will be useful when discussing the big picture in design meeting.

**Comment by samreid** [comment]
Other than the screen icons, we need to address the patterns on the light screen accumulator (would prefer no interference pattern).

@samreid will also publish a dev version for review.

**Comment by samreid** [comment]
Here's an initial dev version:
https://phet-dev.colorado.edu/html/waves-intro/1.0.0-dev.1/phet/waves-intro_en_phet.html

@arouinfar anything else for this issue?

**Comment by arouinfar** [comment]
> @arouinfar anything else for this issue?

Don't think so! I'll go ahead and close, thanks.
