### ISSUE TITLE
Screen icons for the "one medium per screen" sim

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#358]
As part of https://github.com/phetsims/wave-interference/issues/356 we will need icons for the screens.  Currently it looks like this:

![image](https://user-images.githubusercontent.com/679486/54932685-d6821180-4ee0-11e9-8df8-f81e476e43e1.png)

**Comment by arouinfar** [comment]
A few ideas to mock up:
- Scene icons from Wave Interference
- Each source emitting a wave
- More iconic view of the screens, e.g. water drop, music note

**Comment by arouinfar** [comment]
I moved this issue to the waves-intro repo, see link above. Closing.
