### ISSUE TITLE
Should we eliminate the separator in the control panel?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#359]
As part of https://github.com/phetsims/wave-interference/issues/356 I'm wondering if we should eliminate the separator in the control panel.

![image](https://user-images.githubusercontent.com/679486/54932516-8c992b80-4ee0-11e9-8e63-9748607a858a.png)

![image](https://user-images.githubusercontent.com/679486/54932540-94f16680-4ee0-11e9-80a8-057ceea0f1ac.png)

![image](https://user-images.githubusercontent.com/679486/54932555-9d49a180-4ee0-11e9-91ba-a2decc76392b.png)

**Comment by arouinfar** [comment]
@samreid I think the separator line helps keep the sliders and other UI controls separate. For water especially, I think the line draws attention to the check box, which could be overlooked. Another option would be to separate the controls into two separate panels, but I think that would look pretty odd for water, which just has the one checkbox. 

If you'd like to discuss further in design meeting @samreid, please go ahead and tag it .

**Comment by samreid** [comment]
My initial instinct was this looked odd, but I agree there are good reasons to keep it.  Let's close this issue.
