### ISSUE TITLE
Diffraction Screen number control stepSize should not be 1

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#363]
Diffraction Screen number control stepSize should not be 1.  For instance, in the square scene, the step size is 1, but the range is 400-8000 so you have to hit step many times before seeing any change.

**Comment by samreid** [comment]
@arouinfar can you please recommend step sizes for the controls? (For any controls that aren't already as desired).

**Comment by arouinfar** [comment]
@samreid I think we actually do want the tweaker size to be 1, so apertures can be tuned to match the wavelength. We can use `constrainValue` to make the thumb snap in larger steps.

## Circle
Diameter
* Range: 200-8000 nm
* Default: 500 nm
* constrainValue: 50 nm (This is still a LOT of steps, but I want users to be able to tune the aperture size to the ballpark of the wavelength without using the tweakers.)

Eccentricity
* Range: 0-0.99
* Default: 0
* constrainValue: 0.05

## Square
Width & Height should match Diameter specs for Circle scene.

## Circle + Diamond
Circle Diameter & Diamond Side Length
* Range: 200-1000 nm
* Default: 500 nm
* constrainValue: 20 nm

## Lattice
Specified in https://github.com/phetsims/wave-interference/issues/364#issuecomment-481009146

## Waving Girl
Height
* Range:  200-1000 nm
* Default: 500 nm
* constrainValue: 20 nm

Rotation
* Range: 0-360*
* Default 0*
* constrainValue: 30*

**Comment by samreid** [comment]
Ranges, defaults, deltas and constrainValues should be better now, @arouinfar can you please double check on phettest?

**Comment by arouinfar** [comment]
Looks great @samreid!
