### ISSUE TITLE
Fix range for disorder scene controls

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#364]
From https://github.com/phetsims/wave-interference/issues/139#issuecomment-476728172

>The design doc shows lattice spacing 0->1000nm, should this be more like 1000->200nm? Or make it more qualitative?

200-1000 sounds like a much more reasonable range, so let's give that a try. I likely copied and renamed one of the other NumberControls in the mockups, without fixing a range.

**Comment by samreid** [comment]
I set the range to be 200nm-1000nm and set the default value to be the midpoint.  Note this is more compressed than the previous version.  @arouinfar, is this what you had in mind?

**Comment by arouinfar** [comment]
@samreid let's try these values. 

Circle Diameter
* Range: 100-500 nm
* Default: 300 nm
* constrainValue: 10 nm

Lattice Spacing
* Range: 500-1500 nm
* Default: 1000 nm
* constrainValue: 50 nm

**Comment by arouinfar** [comment]
Since Disorder is purely qualitative, I don't think it needs a NumberControl. Can you instead make it a traditional slider with 4 tick marks? The range would still be "None" to "Lots".

**Comment by samreid** [comment]
I updated the ranges and removed the readout from the disorder control.  To keep the disorder control looking unified with the other controls, I left it as a `DiffractionNumberControl`, so it would line up and be easy to position correctly.  It would be a bit more work to center the title, let me know if I should take that step.

![image](https://user-images.githubusercontent.com/679486/55759765-7bd7d200-5a17-11e9-820e-56842fd5ddc2.png)

**Comment by arouinfar** [comment]
@samreid the ranges are looking good to me! I think the tweakers should still keep a step size of 1, but the thumb snappiness feels good.

> To keep the disorder control looking unified with the other controls, I left it as a `DiffractionNumberControl`, so it would line up and be easy to position correctly. 

That sounds reasonable to me. I think the Disorder slider looks nice.

**Comment by samreid** [comment]
> I think the tweakers should still keep a step size of 1, but the thumb snappiness feels good.

I forgot the `delta` and `constrainValue` vary independently--https://github.com/phetsims/wave-interference/issues/363#issuecomment-481031114 helped me remember.  I'll change the `constrainValues` as specified above.

**Comment by samreid** [comment]
Ranges, defaults, deltas and constrainValues should be better now, @arouinfar can you please double check on phettest?

**Comment by arouinfar** [comment]
Looks good @samreid, thanks!
