### ISSUE TITLE
Wave chart jumps when going across an undefined value

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#366]
It looks like this:

![image](https://user-images.githubusercontent.com/679486/55672733-ae3cd000-585b-11e9-8128-fe3778f302db.png)

and it could be solved by https://github.com/phetsims/griddle/issues/33

**Comment by samreid** [comment]
I added support for no-value values in https://github.com/phetsims/griddle/issues/33 and it looks like this:

![image](https://user-images.githubusercontent.com/679486/55677647-cb4bc000-58a8-11e9-8be5-23a6f0100386.png)

@arouinfar can you please check this behavior on phettest and close if it seems OK to you?

**Comment by arouinfar** [comment]
The behavior in master is generally looking pretty good @samreid!

I noticed that the vertical position of the dot doesn't reset when the probe encounters "no value".  Instead, it remembers the last value it read. I think it would look a bit more natural if the dot moved back to zero.
![image](https://user-images.githubusercontent.com/8419308/55747464-8edba980-59f9-11e9-85b7-fc9e9a771330.png)


If the amplitude is off-scale, the dot will disappear completely when the probe is moved off the lattice.
![image](https://user-images.githubusercontent.com/8419308/55747292-255b9b00-59f9-11e9-9fa5-cd993a062805.png)

I was also able to lose the dot in this situation, where the probe was moved through a high-amplitude region (near source point) as it was dragged off of the lattice.
![image](https://user-images.githubusercontent.com/8419308/55747421-7075ae00-59f9-11e9-8d7d-c7e037902678.png)

**Comment by samreid** [comment]
Proposed fix committed, @arouinfar can you please review?

**Comment by arouinfar** [comment]
Looks great @samreid!

**Comment by samreid** [comment]
Since this will be released in upcoming deploy and there is no further work necessary, nor clients requesting this feature, it seems good to close this issue.
