### ISSUE TITLE
Waving Girl height should scale, not squish

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#367]
Noticed in https://github.com/phetsims/wave-interference/issues/363

In the Waving Girl scene, reducing the height squishes the image:
![image](https://user-images.githubusercontent.com/8419308/55761081-5d73d580-5a1b-11e9-88d4-b413c3c0442b.png)

Instead, we want to proportionally scale the entire image.
![image](https://user-images.githubusercontent.com/8419308/55761375-51d4de80-5a1c-11e9-810d-cddf90a83469.png)

**Comment by samreid** [comment]
Committed the proposed fix, @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
Looks good @samreid!
