### ISSUE TITLE
Investigate aliasing in the aperture view

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#368]
@ariel-phet pointed out the aperture view is somewhat aliased.  We should look into that and see if it can be improved.  The rectangular scene is no problem, but the circles, diamond and waving girl are problematic.  @ariel-phet said it's not the most important feature, but I'll investigate and report back.

**Comment by samreid** [comment]
Proposed fix committed, @ariel-phet can you please review on phettest and provide feedback?

**Comment by ariel-phet** [comment]
All looking much cleaner. Closing
