### ISSUE TITLE
Adjustment to credits to include STROBE award number

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/wave-interference#369]
@samreid Ellen from STROBE wrote the following:

> If possible, could you include the grant award number in the credit section of the PhET? The following text is preferred, but as long as the award number is there, I believe that is fine. 
> 
> "This material is based upon work supported by the National Science Foundation under STROBE Grant No. DMR 1548924. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation."

Can we make this adjustment in the "Thanks" section? They also asked if a logo could be included but I am pretty sure that is not possible within the "Thanks" section (unless that is already possible we do not need to pursue including a logo).

I have made the change to the credits on the website already, please make this change to the sim on master, so it will be included when we publish the diffraction screen. A maintenance release is not necessary for this change, it will just be included upon the republication.

**Comment by samreid** [comment]
> They also asked if a logo could be included but I am pretty sure that is not possible within the "Thanks" section (unless that is already possible we do not need to pursue including a logo).

I searched CreditsNode and AboutDialog for logo/image/picture and didn't see anything like that.

**Comment by samreid** [comment]
There is an existing string in the "Thanks" that says:

> Thanks to the STROBE NSF Science and Technology Center on Real-Time Functional Imaging for their support.

It is unclear whether to append or replace.  I looked at the credits in https://phet.colorado.edu/en/simulation/wave-interference and it looks like it was replaced, so I'll do a replacement as well, but let me know if you want to open with the "Thanks to the STROBE NSF Science and Technology Center on Real-Time Functional Imaging for their support." sentence.

**Comment by samreid** [comment]
I updated the "thanks" section of the about dialog credits, @ariel-phet can you please review it on phettest and let me know if you recommend any changes?

**Comment by ariel-phet** [comment]
@samreid looks good. Yes, this was intended to replace, not append.
