### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#371]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Arrows at the ends of sliders could have slightly larger pointer areas

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56322746-21c9c180-6127-11e9-99a1-6bcedc6a5210.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56322747-21c9c180-6127-11e9-83a7-cf2c9d157a48.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56322748-21c9c180-6127-11e9-8974-bbc09c459c68.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/56322749-22625800-6127-11e9-838f-552187901437.png)
![Image from iOS (5)](https://user-images.githubusercontent.com/41024075/56322750-22625800-6127-11e9-889e-ada9e3e4d17a.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/41024075/56322751-22625800-6127-11e9-8ba6-22fb2fed2758.png)
![Image from iOS (7)](https://user-images.githubusercontent.com/41024075/56322752-22625800-6127-11e9-9a12-5fadc77becfd.png)
![Image from iOS (8)](https://user-images.githubusercontent.com/41024075/56322753-22625800-6127-11e9-968d-45454d02fa92.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56322754-22625800-6127-11e9-93f8-617568216b77.png)

**Comment by arouinfar** [comment]
@samreid  asymmetric dilation of NumberControl tweakers was added in https://github.com/phetsims/scenery-phet/issues/489. Here's a mockup of updated touch areas in green, which would apply to all tweakers.

![image](https://user-images.githubusercontent.com/8419308/56323066-fa272900-6127-11e9-964d-90e6d9b662db.png)

**Comment by samreid** [comment]
I expanded touch areas for NumberControl arrowButtons in the commit.  It will be simplest if we can use the same dilation constants for each NumberControl in the sim, even though they don't align with the containers exactly in every case.  @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
> It will be simplest if we can use the same dilation constants for each NumberControl in the sim, even though they don't align with the containers exactly in every case.

That seems reasonable to me @samreid.

The updated touch areas look good, but I'll wait to close until I can test it out on my phone when I'm on campus tomorrow.

**Comment by arouinfar** [comment]
Testing on my phone, I didn't have any missed tweaker hits on master, but definitely noticed a few in the app. The expanded touch areas are working nicely!
