### ISSUE TITLE
Water Screen: Play a water drop sound when water hits

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#374]
From yesterdays sonification design meeting, we would like to play a water drop sound when the water drop hits.

**Comment by samreid** [comment]
I'm using PitchedPopGenerator as a placeholder until we have better audio effects for this part.  Assigning to @Ashton-Morris to work on better sound effects.

**Comment by Ashton-Morris** [comment]
I have sent some water drop sounds

**Comment by samreid** [comment]
From this week's meeting:

Ashton will record other water drop variants and we will randomize between them. The variation should be pretty subtle.

**Comment by samreid** [comment]
We reviewed the current sound effects for water drops and love it, closing.
