### ISSUE TITLE
Updates to slider ranges, defaults, constrainValue

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#383]
Due to the changes in #370, the ranges, defaults, and constrainValues specified in https://github.com/phetsims/wave-interference/issues/363#issuecomment-481031114 will need some updating.

Circle Diameter, Square Width/Height, Waving Girl Height should have the same values
* Range 0.04-0.40 mm
* Default: 0.10 mm
* constrainValue: 0.02 mm
* tweaker: 0.1 mm

The other sliders are still looking good.

**Comment by samreid** [comment]
Updated in the commit, @arouinfar can you please review? Close if all is well.

**Comment by arouinfar** [comment]
@samreid the updates are all looking good.

In reviewing the changes, I noticed a few more things that need updating.
- [ ] Square, Circle & Square, and Lattice scenes - units still need to be updated to mm
- [ ] Circle & Square scene - update tweakers to 0.01  mm

**Comment by samreid** [comment]
Proposed fixes pushed, @arouinfar can you please take a look?

**Comment by arouinfar** [comment]
Looks good @samreid
