### ISSUE TITLE
Deal with interference between sound beats and tone

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#388]
From this week's sonification meeting:

JB: Could do audio ducking for the speaker sound clip when sine wave oscillator is playing.
AP: What about another checkbox to turn the speaker sound clip on/off?
??: What about turning off the speaker sound clip completely when the sine wave oscillator is on.

Consensus: We'll try ducking first, if that isn't nice enough, we'll turn it off completely.

**Comment by samreid** [comment]
I added ducking above and will mark this issue for review in design meeting.

**Comment by samreid** [comment]
From the Jan 21, 2020 design meeting:

KP: Let’s duck the membrane sound even more when the pitch is on.  KP: Play tone should duck all other sounds, including the wave detector probes and the position chart.  AR: That’s my vote too.

Marking for #465

**Comment by samreid** [comment]
@arouinfar or @kathy-phet did you intend that even transient sounds, such as button presses and checkbox presses would be ducked?  Or just the continuous sounds like the wave detector probes?

**Comment by samreid** [comment]
I added ducking for the wave meter node.  To duck the rest of the audio subsystem would require changes to tambo which @jbphet should be involved with, if we decide to duck everything.  Otherwise this is ready for review.

**Comment by emily-phet** [comment]
I would strongly recommend not ducking everything (e.g., not the basic UI sounds). Just like the general behavior of the reset all is standardized, it would be nice to standardize that the UI sounds are subtle to start with, and shouldn't need to be ducked.

**Comment by emily-phet** [comment]
In this version https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.14/phet/waves-intro_en_phet.html the ducking for the sound screen sounds great to me.

**Comment by samreid** [comment]
Self-unassigning based on the remarks above, noting that we have one other ducking issue open which is #476.  Also leaving assigned for other reviewers to double check before closing.

**Comment by samreid** [comment]
At today's design meeting we reviewed it and decided it sounds nice, closing.
