### ISSUE TITLE
Should we have sound for when the screen icon buttons are pressed?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#389]
At this week's sonification meeting, we asked:

> Should we have sound for when the screen icon buttons are pressed?

We decided it should be discussed with @emily-phet

**Comment by emily-phet** [comment]
Sure - but perhaps just use the generic 'push button' sound brought up in a separate issue. 

Also - I agree with all the issues on creating a standard default sound for radio buttons, push buttons, etc. I would suggest selecting something that sounds reasonable from what @Ashton-Morris and @jbphet propose. While it's desirable to select something we won't change going forward, I would suggest not laboring long on this decision. Happy to discuss this further if there are questions.

**Comment by Ashton-Morris** [comment]
Yes. We decided on a screen selection and a home screen selection sound.
