### ISSUE TITLE
For the tools, add pick-up drop-off sounds

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#390]
AM: Sounds for the tools in the top-right toolbox?
	> Let's try the same pick-up/drop sound as in friction
	> But it should be discussed with EM

**Comment by emily-phet** [comment]
I would suggest a less strong sound for pick-up/drop in Waves. In BASE and Friction etc., the object being picked up is the main thing. We want that to sound salient and important. In something like Waves, I think we want the sound to provide confirmation of the action, but not sound as important. Maybe something more neutral, slightly lower volume, than friction would be good. Maybe using a timbre something in the ballpark of the combobox sound in Molarity (just a thought - @Ashton-Morris and @jbphet will likely have great ideas here).

**Comment by samreid** [comment]
@jbphet says there are some standard sounds in the tambo demo which may work.  We'll try the second clip.

**Comment by samreid** [comment]
Update from Jan 21, 2020 meeting:

JB: It is missing sounds for taking things out of the toolbox and putting them back in the toolbox.  See the ruler in inverse square law common.

Marking for https://github.com/phetsims/wave-interference/issues/465

**Comment by samreid** [comment]
Added in the commits, closing.
