### ISSUE TITLE
Sound for rotating the wave view

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#391]
AM: Do you want a rotation sound for the Top/Side buttons?
	KP: I could imagine something like that.  Not sure what it would sound like exactly.

**Comment by Ashton-Morris** [comment]
We had a conversation and decided to use a regular radio button for that.

**Comment by samreid** [comment]
Thanks, it therefore seems like this issue can be closed.  Please reopen if more work is needed here.
