### ISSUE TITLE
Should the sound wave tone and corresponding checkbox appear in Wave Interference 2.0?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#392]
We are developing the sound wave tone and "Play Tone" checkbox as part of the Waves Intro sim, but I don't recall if we discussed adding it to Wave Interference itself.  @arouinfar @kathy-phet @ariel-phet what do you recommend?

**Comment by kathy-phet** [comment]
Yes, that would be good.

Kathy

Sent from my iPhone

On May 7, 2019, at 8:31 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #392<https://github.com/phetsims/wave-interference/issues/392> to @kathy-phet<https://github.com/kathy-phet>.

**Comment by arouinfar** [comment]
Agreed with @kathy-phet. We should include Play Tone in Wave Interference, but I think it can wait until 2.0.

**Comment by ariel-phet** [comment]
@kathy-phet  decision works for me.

**Comment by samreid** [comment]
@kathy-phet and @arouinfar: should the "Play Tone" button appear only on the "Waves" screen, or also on the "Interference" and "Slits" sceens?

**Comment by arouinfar** [comment]
I think we'd only want "Play Tone" on the Waves screen. 

For Interference and Slits, we'd need some sort of microphone-like probe to place in the lattice. Playing a single tone on these screens would be problematic, since the interference pattern would alter the sound. I think such a tool would be beyond the scope of Wave Interference, anyway.

**Comment by samreid** [comment]
Working on this, I've noted the problem that the sound tone plays on other scenes.  We will need to associate it with a more specific node to get it to enable/disable correctly.

**Comment by samreid** [comment]
I fixed the problem in the preceding comment and enabled the sine wave oscillator tone and control for Wave Interference's "Waves" screen.  @arouinfar can you please test Wave Interference and Waves Intro to make sure the tone and its control are behaving as desired?

**Comment by arouinfar** [comment]
@samreid looks good in `waves-intro` and `wave-interference`.

**Comment by samreid** [comment]
Excellent, thanks for testing, closing.
