### ISSUE TITLE
The diffraction pattern is too dim at low and high wavelengths

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#395]
As @ariel-phet pointed out: `VisibleColor.wavelengthToColor` turns down the intensity at the upper and lower wavelengths, resulting in difficult-to-see diffraction patterns.  This is problematic because we would like to depict that high frequency light has more ripples in the Airy disk, but when the frequency is too high the light is dim so it seems like are less ripples in the Airy disk:

![image](https://user-images.githubusercontent.com/679486/57425650-44f10980-71d9-11e9-8179-aecc4661c140.png)

There is a term in the `wavelengthToColor` table that reduces intensity at high and low wavelengths.  When we removed that factor, the colors had a better brightness still with a reasonable hue:

![image](https://user-images.githubusercontent.com/679486/57425713-8b466880-71d9-11e9-8785-9393ea9748d8.png)

So we would like to use the intensity=1 values for the light table for the diffraction view.

Here's a picture of the original spectrum:
![image](https://user-images.githubusercontent.com/679486/57425758-c5176f00-71d9-11e9-8e23-8a8a42df3b57.png)

And the intensity=1 spectrum:
![image](https://user-images.githubusercontent.com/679486/57425785-e4160100-71d9-11e9-9613-ead4952d6b33.png)

Our plan is to use the intensity = 1 spectrum only for the diffraction views (not for wavelength control or for the incident/transmitted beam views).  Self-assigning for initial investigation.

**Comment by samreid** [comment]
@pixelzoom I'd like to adapt VisibleColor.js so it is possible to get the `intensity=1` colors.  Perhaps we should create two tables, and specify which one we want with an option to `wavelengthToColor`?  How should we proceed?  Would you like to take the lead on this?

**Comment by pixelzoom** [comment]
Please clarify, what are "the intensity=1 colors"?   And if it's a different table, why not implement in a different class?

**Comment by pixelzoom** [comment]
OK, I think I understand.  How about an option that determines whether `wavelengthToColor` reduces intensity at high and low wavelengths?

**Comment by samreid** [comment]
That sounds perfect!

**Comment by pixelzoom** [comment]
Alrighty.  I don't have any time to work on this, so assigning back to @samreid.  If you also don't have time, feel free to unassign.

**Comment by samreid** [comment]
The preceding commit adds a `reduceIntensityAtExtrema` option to `VisibleColor.wavelengthToColor`.  @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
I reviewed the changes to VisibleColor.  I'm guessing that sims are generally unlikely to use both  `reduceIntensityAtExtrema: true` and `reduceIntensityAtExtrema: false`.   But `REDUCED_INTENSITY_COLOR_TABLE` and `FULL_INTENSITY_COLOR_TABLE` are both created eagerly, and they have length 401.   This seems like a waste of memory.  Perhaps they should be created on demand.  And if that causes a responsiveness problem in some sim, then that sim can make a call to (e.g) `colorToWavelength` early in the startup process to force initialization of the needed table.

The end result in Wave Interference should be reviewed by the designer.

**Comment by samreid** [comment]
I measured that each table takes around 282kb, creating them lazily seems reasonable as long as it doesn't incur a wait time at an inopportune time (during interaction).  I'll commit a proposal for lazy tables momentarily.

**Comment by samreid** [comment]
Did you have something like this in mind?

**Comment by pixelzoom** [comment]
@samreid said:
> ... as long as it doesn't incur a wait time at an inopportune time (during interaction)

In https://github.com/phetsims/wave-interference/issues/395#issuecomment-493548123, I suggested:
> And if that causes a responsiveness problem in some sim, then that sim can make a call to (e.g) `colorToWavelength` early in the startup process to force initialization of the needed table.

@samreid asked:
> Did you have something like this in mind?

I'm not following. Did this comment belong in a different issue?

**Comment by pixelzoom** [comment]
On-demand implementation in https://github.com/phetsims/scenery-phet/commit/79ae2b46d7e3585d070760020369cabd28b767a8 looks good.

**Comment by samreid** [comment]
> And if that causes a responsiveness problem in some sim, then that sim can make a call to (e.g) colorToWavelength early in the startup process to force initialization of the needed table.

Sounds good.

> I'm not following. Did this comment belong in a different issue?

I meant to say:

Did you have something like this commit https://github.com/phetsims/scenery-phet/commit/79ae2b46d7e3585d070760020369cabd28b767a8 in mind?

Can this issue be closed?

**Comment by pixelzoom** [comment]
> The end result in Wave Interference should be reviewed by the designer.

Up to you whether that needs to happen.

**Comment by samreid** [comment]
@ariel-phet can you please review the behavior in master?  The diffraction patterns should now be using intensity=1 and everywhere else should remain at the reduced intensities at extreme wavelengths.

**Comment by ariel-phet** [comment]
All looks good to me! Closing
