### ISSUE TITLE
Update Diffraction screen icon

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#397]
The icon used for the Diffraction screen is a stand-in created early in development, but no longer matches the look of the sim. I've mocked up a few alternatives. (Side note: the black stroke was added so icon bounds are more apparent, but will be removed before integration since the stroke is now handled in joist.)

1. ![screen_icons_Diffraction](https://user-images.githubusercontent.com/8419308/57640937-eb8a3100-7570-11e9-9c94-a7cda1044ed5.png)
2. ![screen_icons-06](https://user-images.githubusercontent.com/8419308/57640939-eb8a3100-7570-11e9-9b80-cbc0eeb5d250.png)
3. ![screen_icons-05](https://user-images.githubusercontent.com/8419308/57640938-eb8a3100-7570-11e9-8707-a6e6d239b368.png)

I think option (1) looks the cleanest, but does give away some information. However the diffraction pattern is revealed immediately when opening the screen, anyway. Option (3) is closest to the current icon, with the current beam path. In this context, the layering of the aperture above the beam just looks odd, which is why I removed it in option (2).

@samreid @ariel-phet any thoughts on these options, or suggestions for alternatives?

**Comment by samreid** [comment]
(1) looks great to me.  Do you think the Airy disk will be too small/aliased for the navigation bar icon size? 
 If so, should it be iconified more?

**Comment by arouinfar** [comment]
> (1) looks great to me. Do you think the Airy disk will be too small/aliased for the navigation bar icon size?

Possibly... good point @samreid.

> If so, should it be iconified more?

I had used a screenshot, but I decided to use a gradient to mimic the diffraction pattern. While not perfectly accurate, I don't think it looks too bad. Here are some mockups at true icon/navbar size. If we decide to go with option (1), the less detailed iconified version is probably the way to go.

<img src="https://user-images.githubusercontent.com/8419308/57647231-a8838a00-757f-11e9-8364-99c29074bea4.png" width=373>
<img src="https://user-images.githubusercontent.com/8419308/57647231-a8838a00-757f-11e9-8364-99c29074bea4.png" width=101>

<img src="https://user-images.githubusercontent.com/8419308/57652210-4aa96f00-758c-11e9-9503-b1c6539857e7.png" width=373>
<img src="https://user-images.githubusercontent.com/8419308/57652210-4aa96f00-758c-11e9-9503-b1c6539857e7.png" width=101>

**Comment by ariel-phet** [comment]
@arouinfar I think the hollywood-ed version of option (1) is great (it is an icon after all)

**Comment by arouinfar** [comment]
Thanks @ariel-phet!

@samreid here are the assets for the updated icon
[diffraction_screen_icon.zip](https://github.com/phetsims/wave-interference/files/3179407/diffraction_screen_icon.zip)

**Comment by samreid** [comment]
Thanks, I updated the icons in the commit. @arouinfar can you please review on phettest?  Close if all is well.

**Comment by arouinfar** [comment]
Looks great, thanks @samreid!
