### ISSUE TITLE
Review NGSS regarding period and energy

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#40]
Notes from Jan 4, 2018 design meeting:

* Do we want to support the relationship between frequency and period? Could have 2 sliders -- update period slider would move thumb on frequency slider. 
* Do we show period? Or do we require it to be measured?
* Review NGSS to see what it has to say about period

@arouinfar can you please look into this and let me know your thoughts?

**Comment by arouinfar** [comment]
@samreid thanks for following up. I added the [relevant standards](https://docs.google.com/document/d/1Lr5A7LG8PyrTHD5tC0Ux4IP9nF7XrE-bZTyRIc7Yc2A/edit#heading=h.omh49itn0px) to the design doc, and they do not reference wave period, only frequency. 

Given that period is not mentioned in the standards, and hasn't been a user request, I don't think we need to add any period-related features.
