### ISSUE TITLE
Wavelength slider thumb goes beyond bounds of slider

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/wave-interference#401]
For https://github.com/phetsims/QA/issues/322.

If you look closely, you can see the little box that shows you what color your wavelength is actually goes beyond the bounds of the slider. This happens on both sides of the slider. Happens in the other screens as well. Also happens in published version. Should it go beyond?

![Screen Shot 2019-05-24 at 3 57 41 PM](https://user-images.githubusercontent.com/31285590/58358783-ac47c400-7e3d-11e9-83e9-b83e9f853d6b.png)

**Comment by samreid** [comment]
If my understanding is correct, the window of that thumb is more than a pixel wide, and since the center of the thumb can go to the edge of the spectrum, it overlaps a little.  @arouinfar or @ariel-phet is this your understanding as well?  Anything we should do about this for short or long term?

**Comment by arouinfar** [comment]
Nice attention to detail @lmulhall-phet.

> If my understanding is correct, the window of that thumb is more than a pixel wide, and since the center of the thumb can go to the edge of the spectrum, it extends beyond the edge a little. @arouinfar or @ariel-phet is this your understanding as well? Anything we should do about this for short or long term?

That's also my understanding @samreid. I think this is just an unavoidable byproduct of the design of SpectrumSlider, and I don't think there's anything that needs to be done here.
