### ISSUE TITLE
Lines in color slider

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/wave-interference#402]
For https://github.com/phetsims/QA/issues/322. There are lines visible in the color sliders. The lines are more prominent on macOS, but they are there on Windows.

2.0.0-dev.1:
![Screen Shot 2019-05-24 at 4 21 31 PM](https://user-images.githubusercontent.com/31285590/58359296-f16cf580-7e3f-11e9-975b-750a6e5f3675.png)

Published version:
![Screen Shot 2019-05-24 at 4 21 13 PM](https://user-images.githubusercontent.com/31285590/58359300-f6ca4000-7e3f-11e9-8e3f-6be816b307fa.png)

Do we want the lines or is this a regression?

**Comment by arouinfar** [comment]
Looks pretty awful in latest macOS/Chrome.

![image](https://user-images.githubusercontent.com/8419308/58359509-0eee8f00-7e41-11e9-9703-051b2dd67cc1.png)

However, the slider looked fine in [1.1.0-dev.5](https://phet-dev.colorado.edu/html/wave-interference/1.1.0-dev.5/phet/wave-interference_all_phet.html) (version just prior to 2.0.0-dev.1)
![image](https://user-images.githubusercontent.com/8419308/58359547-38a7b600-7e41-11e9-9b94-b64921db3457.png)

**Comment by KatieWoe** [comment]
Shows up with less severity in Windows 10 chrome:
![lessbutstillthere](https://user-images.githubusercontent.com/41024075/58359951-3ba3a600-7e43-11e9-928a-7de34f21c520.png)

**Comment by KatieWoe** [comment]
May be connected to https://github.com/phetsims/blackbody-spectrum/issues/95

**Comment by samreid** [comment]
And likewise https://github.com/phetsims/scenery-phet/issues/500

**Comment by pixelzoom** [comment]
I'm guessing that you picked up phetsims/scenery-phet#500 while work was in progress.  Please confirm.

**Comment by pixelzoom** [comment]
I see no evidence of this problem in master, so you almost certainly picked up intermediate work and hit this problem: https://github.com/phetsims/scenery-phet/issues/500#issuecomment-495409067

I'm not sure how we avoid this kind of thing in the future - the "in-progress" label was removed, and any work in progress might impact any sim.   But it wouldn't hurt to ask on Slack before publishing something that will be tested by QA.

**Comment by pixelzoom** [comment]
... and I think it's safe to simply close this issue, after confirming for yourself.

**Comment by samreid** [comment]
I do not see the problem in master at the moment, closing.
