### ISSUE TITLE
Long strings push wavelength box into slit box

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/wave-interference#404]
For https://github.com/phetsims/QA/issues/322. Apologies for not using correct terminology.

I'm not sure if you've had a chance to look over the 4th screen for internationalization issues. Here's what `stringTest=double` looks like right now:

![Screen Shot 2019-05-24 at 4 50 55 PM](https://user-images.githubusercontent.com/31285590/58360182-9984bd80-7e44-11e9-8b01-f45dba288cde.png)

Looks worse with `stringTest=long`.

I haven't seen any issues with screens 1-3.

**Comment by samreid** [comment]
I'll work on the i18n of the wavelength slider after #396 is complete, thanks!

**Comment by samreid** [comment]
Thanks for reporting this @lmulhall-phet. I addressed it in the commit.  Can you or @KatieWoe or @arouinfar please review/test?

**Comment by KatieWoe** [comment]
Looks good to me @samreid

**Comment by arouinfar** [comment]
Looks good @samreid, thanks!
