### ISSUE TITLE
Same setup produces different results in Safari/Chrome

### ISSUE THREAD

**Issue by etwa4650** [phetsims/wave-interference#405]
for https://github.com/phetsims/QA/issues/322
<b>Test Device</b>
Jordan

<b>Operating System</b>
MAC OS 10.14.5

  <b>Browser</b>

Chrome/Safari

  <b>Problem Description</b>

With the same exact inputs, the resulting image looks different in different browsers, and behaves differently when rotated.

  <b>Steps to Reproduce</b>

  1: On both Chrome and Safari, go to the "Diffraction" screen
  2: Set Wavelength to 695nm
  3: Set Height to 0.08 mm
  4: Set the diffraction cutout as the girl logo
  5: Set the rotation to 90 degrees
  6: Rotate freely to view different behavior in each browser

  <b>Visuals</b>

  This is my view for Safari:
![Screen Shot 2019-05-28 at 10 35 17 AM](https://user-images.githubusercontent.com/26493147/58495546-ff1ec580-8134-11e9-8715-bae7cc1cde37.png)

This is my view for Chrome:
![Screen Shot 2019-05-28 at 10 35 00 AM](https://user-images.githubusercontent.com/26493147/58495567-0fcf3b80-8135-11e9-9b76-03b1ef2d5ae2.png)

And I linked a screen recording the of the different behavior during rotation below.
The image seems to change more dramatically on Safari

https://drive.google.com/open?id=1vURGuvxAkxGQ3inKT30KM3LAe2UobDeZ

**Comment by KatieWoe** [comment]
I did a quick check on Win 10.  Firefox and Edge both act more like safari.

**Comment by KatieWoe** [comment]
It looks like chrome is fading towards the edges more.  Not sure which is correct behavior.

**Comment by samreid** [comment]
The fft is giving different results on chrome and safari.  Here is the diagonal:

![image](https://user-images.githubusercontent.com/679486/59639910-c19ccf00-9119-11e9-8f29-70ab6e42ee9c.png)

```
Index: js/diffraction/model/DiffractionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/diffraction/model/DiffractionModel.js	(revision edab1c43150138e82715f99f4a6abc5e0a02af0e)
+++ js/diffraction/model/DiffractionModel.js	(date 1560808994000)
@@ -64,7 +64,7 @@
       ];
 
       // @public - selected aperture type, which is in essence the "scene" for this screen.
-      this.sceneProperty = new Property( this.ellipseScene, {
+      this.sceneProperty = new Property( this.wavingGirlScene, {
         validValues: this.scenes
       } );
 
@@ -146,6 +146,7 @@
     // which now contains frequency (ωx, ωy ) = (0, 0), moves to the center of the image. And you probably want to
     // display pixel values proportional to log(magnitude) of each complex number (this looks more interesting than just
     // magnitude). For color images, do the above to each of the three channels (R, G, and B) independently.
+    const diag = [];
 
     for ( let row = 0; row < MATRIX_DIMENSION; row++ ) {
       for ( let col = 0; col < MATRIX_DIMENSION; col++ ) {
@@ -155,8 +156,12 @@
           ( col + MATRIX_DIMENSION / 2 ) % MATRIX_DIMENSION
         );
         SHIFTED_MAGNITUDES[ destination ] = Math.sqrt( REAL_PART[ source ] * REAL_PART[ source ] + IMAGINARY_PART[ source ] * IMAGINARY_PART[ source ] );
+        if ( row === col ) {
+          diag.push( SHIFTED_MAGNITUDES[ destination ] );
+        }
       }
     }
+    console.log( diag.join( '\n' ) );
 
     // get the largest magnitude.  Spread operator Math.max( ...arr ) did not have good performance characteristics
     // so we compute this manually.
```

**Comment by samreid** [comment]
The bit reversal tables and cosine/sine tables are coming up the same on chrome and safari.

**Comment by samreid** [comment]
The inputs to the FFT are different:

![image](https://user-images.githubusercontent.com/679486/59641401-9799db80-911e-11e9-9ee8-170042377d0d.png)

**Comment by samreid** [comment]
If I use this code:

```
      context.mozImageSmoothingEnabled = false;
      context.webkitImageSmoothingEnabled = false;
      context.msImageSmoothingEnabled = false;
      context.imageSmoothingEnabled = false;
```

Then the number of differences goes from hundreds to just 3:

![image](https://user-images.githubusercontent.com/679486/59641754-dbd9ab80-911f-11e9-8a88-a21f73e2c3e0.png)

And chrome and safari look pretty much the same.

**Comment by samreid** [comment]
Note that disabling image smoothing may lead to more aliasing in the images in the aperture view, a problem we tried to address in https://github.com/phetsims/wave-interference/issues/368

**Comment by samreid** [comment]
In the above commit, I turn off smoothing for the FFT inputs, but leave on the smoothing for antialiasing in the view.  Results now look similar in testing default values on chrome and safari.  @KatieWoe or @etwa4650, can you please test?  Close if all is well.

**Comment by KatieWoe** [comment]
Behavior seems to be the same now.  Will do more thorough check in next test
