### ISSUE TITLE
Interviews on the Diffraction Screen

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#409]
In https://github.com/phetsims/wave-interference/issues/372 @ariel-phet said:

> we need to do some interviews on the diffraction screen

@arouinfar are any of the issues mentioned in https://github.com/phetsims/wave-interference/issues?q=is%3Aissue+is%3Aopen+label%3Awave-interference%3A2.0 blocking for interviews?  If not, please feel free to proceed at your convenience.

**Comment by arouinfar** [comment]
@samreid @ariel-phet none of those issues are blocking. I have three interviews scheduled for today and tomorrow. I was planning to use dev.2 with `?diffractionScaleFactor=2.5`, but it might be handy to have that rolled into a dev.3. @samreid if you have some time, can you publish a new dev version?

**Comment by arouinfar** [comment]
I've done two interviews, with a 3rd lined up for tomorrow morning. So far, I don't have any design tweaks to suggest, but will open an issue should anything arise in the 3rd interview. 

I'll go ahead and close this issue.
