### ISSUE TITLE
Show wave combination on wave detector tool?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#41]
Notes from January 4, 2018 design meeting:

> Could show source 1, source 2, and combined wave on the wave detector tool. The three waves would be superimposed and share the same zero.

In order to track the waves independently, I would need to change the model architecture to have 3 lattices instead of 1.  This would only be applicable to the 2nd screen (two sources).  Are we going to investigate this?

**Comment by arouinfar** [comment]
@samreid I don't think we will show the combined wave in the tool, but I think this is definitely something we should discuss in design meeting. I already had the wave detector tool design on the agenda for tomorrow, so I've added this issue as well.

**Comment by samreid** [comment]
If we use the analytical model for waves as described in #59, then it would be trivial to show the components that sum to form the net wave.

**Comment by arouinfar** [comment]
This is beyond the scope of this sim, and would better serve goals for constructive/destructive interference, which could be the focus of a different sim.
