### ISSUE TITLE
Should the "Diffraction" screen be published as a standalone sim?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#413]
The Diffraction screen seems to be rich enough to warrant its own simulation, and it is easy to envision use cases that would want to focus on diffraction without the scaffolding of the preceding screens.  I don't recall if we have discussed it before, but thought it would be good to chat about.

@arouinfar @kathy-phet @ariel-phet thoughts?

**Comment by ariel-phet** [comment]
My vote would be no -- I do think spin off sims can be pretty nice, but I do not think a separate sim is warranted in this case.

I think a good contrast is our decision on Diffusion:

1. Diffusion (although using a similar model to the rest of gas properties) felt a bit "buried" as a screen. If someone were looking for a sim purely on diffusion, the would be unlikely to necessarily think that it would be included in "Gas Properties" - but Diffraction is very much an interference effect. Diffraction patterns are sometimes referred to as "interference patterns"

2. I agree this screen is quite rich, but it feels a bit unscaffolded on its own. The Diffusion sim for instance stands on its own pretty well, whereas I think if we want to make a Diffraction sim we would need at least an additional screen to help scaffold the understanding.

3. So, if we do want to pursue a stand alone diffraction sim at some point (which would be reasonable IMO) I think it would take some design and development effort to have an intro screen or two, perhaps starting with double slit diffraction and a more theoretical model than the one used in Wave Interference. I actually think such a model would not be so hard to implement (I am envisioning something where the light pattern changes instantly, there is no propagation).

**Comment by arouinfar** [comment]
My vote would also be no, for the reasons that @ariel-phet so nicely articulated in https://github.com/phetsims/wave-interference/issues/413#issuecomment-512046435.

**Comment by samreid** [comment]
Thanks for your comments, closing.
