### ISSUE TITLE
Should Waves Intro: Light Screen have a "Screen" feature?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#416]
We left the "Screen" feature in Wave Interference Screen 1 since it scaffolds up to showing interference patterns in the later screen.  But in Waves Intro, the light "Screen" doesn't really lead to anything.  I wonder if it should be removed for Waves Intro.  @arouinfar have we discussed this before?  What is your recommendation?

**Comment by arouinfar** [comment]
@samreid we should keep the screen in Waves Intro. Another purpose it serves is to show the perceived color, as it's possible that some students may expect the light will flicker based on the alternating colors in the lattice.
