### ISSUE TITLE
Inconsistent slider button sizes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#420]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
chrome
**Problem description**
For https://github.com/phetsims/QA/issues/389
The arrows that adjust the sliders become small on the diameter slider, but not the eccentricity slider, when doubling strings on the Diffraction screen.  Smaller buttons seem to be what occur in other parts of the sim.

**Visuals**
![buttonsizes](https://user-images.githubusercontent.com/41024075/62380015-7db52c00-b505-11e9-9abb-f791a9da46b5.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Wave Interference‬:‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-dev.7/phet/wave-interference_en_phet.html?stringTest=double
Version: 2.0.0-dev.7 2019-07-30 22:17:13 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@samreid is it possible to always maintain tweaker size, like the Eccentricity slider? The small tweaker buttons seem a bit problematic.

**Comment by samreid** [comment]
Good catch @KatieWoe.  The problem was introduced by https://github.com/phetsims/scenery-phet/issues/513 where we set the tweaker button size to match the size of the number display.  In this case, the large text has made the number display shorter, so the arrow buttons have shrunken too.  This problem will impact every sim with NumberControl.  Not sure what's the best solution--for now I'll reopen https://github.com/phetsims/scenery-phet/issues/513 for discussion.

**Comment by KatieWoe** [comment]
Probably moot at this point, but it does happen to a degree even without the string tests:
![sizeisdifferent](https://user-images.githubusercontent.com/41024075/62491400-01cb1600-b789-11e9-933e-06e5bf6c989d.png)

**Comment by samreid** [comment]
I pushed a proposed fix in https://github.com/phetsims/scenery-phet/issues/513 and it's up for review.

**Comment by samreid** [comment]
The fix in https://github.com/phetsims/scenery-phet/issues/513 has been code reviewed.  @KatieWoe can you please test it in master?  Close if all is well.  Also note #422 which we will handle separately.

**Comment by KatieWoe** [comment]
Looks good in master
