### ISSUE TITLE
NumberControls are vertically mis-aligned when maxWidth restricts their heights differently

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#422]
From https://github.com/phetsims/wave-interference/issues/418#issuecomment-518733487

With longer-than-english strings, the heights of boxes are different and the vertical alignment can be off by a little bit:

![image](https://user-images.githubusercontent.com/679486/62555809-d4d23e00-b830-11e9-9543-c4190231d216.png)

@arouinfar or @ariel-phet do you want to spend any time on this before publication?  Also tagging @KatieWoe so she's aware of this problem.

UPDATE: Linking back to https://github.com/phetsims/QA/issues/389

**Comment by ariel-phet** [comment]
@samreid given that this is a common code component that recently got work, yes, it seems we should spend some time as this would be a general issue I think (probably not noticed before since we often do not have multiple number controls in a horizontal row like this) but I believe some planned components in CCK AC have this arrangement, so best to deal with sooner than later.

**Comment by samreid** [comment]
@jonathanolson can you suggest an implementation strategy for this problem?

**Comment by samreid** [comment]
Two possibilities I considered: 
1. Use `AlignBox` to track component sizes and make sure they match up.  This would lead to very complicated client-side code and require knowledge of all the layouts of different NumberControls and/or requirement for client to selectively pass AlignBoxes to the right places.
2. Reserve a vertical "footprint" shrinkable parts of NumberControl via struts or equivalent, based on the unscaled height of components.  But do we want to always do this, or make it an option?

Also, it seems unlikely this problem is isolated to NumberControl.  

I'd be comfortable applying solution (2) to Wave Interference, but this issue would feel incomplete without discussion with @jonathanolson and/or a discussion of how this problem may manifest and be addressed elsewhere.  This is one of the last issues before Wave Interference can go to RC, so I'll elevate the priority.

**Comment by samreid** [comment]
At today's meeting @pixelzoom suggested aligning to the bottom.  I asked if that was general enough, @ariel-phet said it is acceptable.  I'll proceed.

**Comment by samreid** [comment]
This looks acceptable to me, I'll commit

![image](https://user-images.githubusercontent.com/679486/62733692-5fa76a00-b9e4-11e9-9bc9-154019c0ce23.png)

**Comment by samreid** [comment]
Fixed in commit, @arouinfar or @ariel-phet or @KatieWoe can you please review?  Close if all is well.

**Comment by arouinfar** [comment]
Looks good to me @samreid

**Comment by samreid** [comment]
Thanks @arouinfar, closing.
