### ISSUE TITLE
Are the tones right?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#423]
For https://github.com/phetsims/QA/issues/389
The Play Tones sound doesn't seem quite right to me, but I may be doing something wrong.
If you go to sound and use the default frequency (in the middle), and calculate the hz frequency using the timer, you get about 376 hz.  However, the sound that plays seems rather different than that tone.
https://drive.google.com/file/d/1Ux4wMKboR-EBmlvz0G_d0GsHq20ecGlR/view?usp=sharing

**Comment by samreid** [comment]
I measured one wavefront and got 2.99ms on the timer, using the "step" button to get to the next peak.  This works out to be 1/0.00299 = 
334.44816053511704 Hz.  I tried 330Hz in https://www.szynalski.com/tone-generator/ and it sounded about the same pitch as the sim.  I think the largest source of error in this measurement is getting the timer stopped at about the right time.

**Comment by arouinfar** [comment]
At the default frequency I measured the time for 3 complete cycles, and got 9.04 ms, which corresponds to 332 Hz. The actual value is 330 Hz, so I'd say there's pretty good agreement.

> I think the largest source of error in this measurement is getting the timer stopped at about the right time.

Absolutely. I find that pausing the sim, starting the source & timer, and then stepping through to be the most accurate way to collect data, but it's still not perfect.
