### ISSUE TITLE
Sim won't open in IE

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#424]
For https://github.com/phetsims/QA/issues/389
The main sim won't load in IE.
Error in console:
``` SCRIPT438: Object doesn't support property or method 'ellipse' ```

**Comment by samreid** [comment]
The problem is happening around this part:

![image](https://user-images.githubusercontent.com/679486/62591902-658b3700-b88e-11e9-9688-304b7165cca9.png)

**Comment by samreid** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/ellipse, `context.ellipse` is not supported on IE.  I'll look for another solution.

**Comment by samreid** [comment]
Proposed fix committed and checks out OK on my IE11 on bootcamp.  I tested this new dev version https://phet-dev.colorado.edu/html/wave-interference/2.0.0-dev.10/phet/ .  @KatieWoe can you please verify on that or on phettest?

**Comment by KatieWoe** [comment]
Dev test opens alright
