### ISSUE TITLE
IE Play Tone checkbox does nothing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#425]
For https://github.com/phetsims/QA/issues/389, both sims
The only thing the Play Tone checkbox does is play a sound.  Since Tambo isn't supported in IE, this means that this function doesn't work there.  Leaving a checkbox that has no use/effect on this platform.
Edit: Changed tandem to tambo.  Sorry

**Comment by arouinfar** [comment]
After chatting with @KatieWoe, I think I understand this issue. Tambo is not supported in IE (https://github.com/phetsims/tambo/issues/6) and as a result, we decided to remove the sound icon from the navbar (https://github.com/phetsims/tambo/issues/32). However, Wave Interference and Waves Intro have a sound behind a checkbox. In IE, there is no sound support in the sim, but the checkbox remains.

@samreid can you detect if the user is on IE and remove the Play Tone checkbox?

**Comment by samreid** [comment]
I removed it and published a dev version in https://phet-dev.colorado.edu/html/wave-interference/2.0.0-dev.11/phet/ which checks out OK on my IE on bootcamp.  @KatieWoe can you please verify using dev.11 or master?  Close if all is well.

**Comment by KatieWoe** [comment]
Looks good in the dev version.  Should be noted that this would also apply to the basics sim
