### ISSUE TITLE
Screenshot for Wave Interference 2.0

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#427]
The next publication has a new screen and hence will need a new screenshot.  The steps to create the screenshot are described here: https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots

@KatieWoe @arouinfar @ariel-phet who should create the screenshot?  What should the screenshot depict?

**Comment by KatieWoe** [comment]
It can either be the same situations as before, with the new nav bar, or it can be changed/one added to show the new screen.  @arouinfar let me know which you prefer.

**Comment by ariel-phet** [comment]
@KatieWoe please just copy the current screenshot situation, but including the new nav bar

**Comment by arouinfar** [comment]
@KatieWoe please also add this screenshot as alt3:

![Wave Interference screenshot](https://user-images.githubusercontent.com/8419308/62969391-66f6bb00-bdca-11e9-9785-543e52f3dc2e.png)

**Comment by KatieWoe** [comment]
Here are the screenshots.  @arouinfar please approve.
![wave-interference-screenshot](https://user-images.githubusercontent.com/41024075/63182373-ae21bd80-c00f-11e9-9225-c2ada347fa4d.png)
![wave-interference-screenshot-alt1](https://user-images.githubusercontent.com/41024075/63182375-ae21bd80-c00f-11e9-83f2-3b6af1417453.png)
![wave-interference-screenshot-alt2](https://user-images.githubusercontent.com/41024075/63182376-ae21bd80-c00f-11e9-9c5c-e3c0ea468461.png)
![wave-interference-screenshot-alt3](https://user-images.githubusercontent.com/41024075/63182377-ae21bd80-c00f-11e9-8c4a-2190f7658841.png)

**Comment by KatieWoe** [comment]
Above commits should take care of it.  @arouinfar let me know if you need any changes.  If not, this can be closed.

**Comment by arouinfar** [comment]
Looks good, thanks @KatieWoe!
