### ISSUE TITLE
Units for water scene

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#43]
According to http://hyperphysics.phy-astr.gsu.edu/hbase/watwav.html
the velocity of idealized ocean waves is:
```js
var depth = function(lambda,v){return lambda/2/Math.PI*Math.atanh(2*Math.PI*v*v/g/lambda);}
```
For the Java version, I measured lambda = 5.57E-2m, and v=5.57E-2/2.07m/s, giving  a depth of 0.0073cm.

@arouinfar can you please double check my math?  If it checks out, should we revise the timer or size of the wave pool or frequency values to give a more realistic wave speed or depth?

**Comment by arouinfar** [comment]
I estimated the wavelength of water at the default frequency to be ~5cm (nodes at 2 cm & 7 cm).
![image](https://user-images.githubusercontent.com/8419308/39497362-38821052-4d60-11e8-9543-fedf760678c7.png)

Measuring mid-trough to mid-trough on the wave itself results in roughly the same wavelength
![image](https://user-images.githubusercontent.com/8419308/39497427-8a4b92b4-4d60-11e8-8153-a02329e85bda.png)

To measure speed, I timed a node in the graph moving 5 cm, which took 1.87 s.

Using the equation from the linked page, I solved for d.
![image](https://user-images.githubusercontent.com/8419308/39497822-3ff7f692-4d62-11e8-9566-7d3b5e8cb5c8.png)

Plugging 0.05 for lambda, and (0.05/1.87) for speed gives me the same depth as @samreid, 0.00073 cm.

![image](https://user-images.githubusercontent.com/8419308/39497840-4e19a8d8-4d62-11e8-9649-fa447213401f.png)

@samreid the math checks out. However, I think the bigger question is whether or not we are trying to model ocean waves. 

I had thought of the sim as recreating a ripple tank, so I looked at the specs for some ripple tanks being sold for classroom use.
https://www.a3bs.com/ripple-tank-pm02-1017591-u219101-3b-scientific,p_835_25744.html
https://www.fishersci.com/shop/products/full-sized-ripple-tank-2/p-2377624
https://www.pasco.com/prodCompare/ripple-tank-system/index.cfm


The oscillation frequencies were reported to be a variable 1-50 or 1-60 Hz. The typical dimensions appear to be ~35-45 cm, and quite shallow. One had a reported tank depth of 1 cm, but I couldn't find the exact figure for others. 

I'm not sure that students will be calculating wave depth, and it's not really one of the learning goals. I'm also not particularly convinced that the equation for wave depth is even valid in the sim, given the attenuation of the amplitude.

At this point, I think the dimensions chosen for the water scene seem appropriate to me @samreid.

**Comment by samreid** [comment]
Leaving assigned to myself to make sure the HTML5 water units are on par with the Java units.

**Comment by samreid** [comment]
Here are my water units notes from a recent meeting:

Water could go to a lower frequency where it doesn't even interfere.  One drop every 2-3 seconds. 
> another note said "Min frequency of ~0.5 Hz."
> Shouldn’t be able to see interference pattern at min frequency.

**Comment by arouinfar** [comment]
@samreid the suggestion of ~0.5 Hz is a rough guess of a reasonable minimum. Anything in that ballpark would be acceptable.

**Comment by samreid** [comment]
@arouinfar I refined the units and ranges for the water scene, can you please review on phettest and let me know if you have any recommendations?

**Comment by arouinfar** [comment]
@samreid units are looking good. The minimum frequency isn't ideal for interference, but I think that's okay, so long as the default is large enough for interference to be observed (which it is).
