### ISSUE TITLE
Play Tone not reset

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#430]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/405
The Play Tone checkbox is not reset by the orange reset button.
**Steps to reproduce**
1. Go to a screen or scene with the play tone checkbox
2. Note it is unselected by default
3. Select it
4. Reset using the orange button (if for main sim, this can be in any of the three scenes)
5. Re-navigate to the checkbox if needed
5. Notice the box is still checked.

**Visuals**
![playtonenotreset](https://user-images.githubusercontent.com/41024075/63193291-55abe980-c02a-11e9-9481-284031919c2e.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-rc.1/phet/wave-interference_all_phet.html
Version: 2.0.0-rc.1 2019-08-13 21:08:49 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Fix committed to master.  I will need to push it to the wave-interference 2.0 branch.  Also, the chipper-2.0 documentation says I need to create a branch named like waves-intro-1.0 branch for this, but I'm wondering if I could/should just leverage the exact same branch for next waves-intro publication?

**Comment by samreid** [comment]
Chris Malley 4:51 PM
For derivate sims, I have not created a branch of the parent sim dependency.

Sam Reid 4:51 PM
OK sounds good.  Do I need to jump through any hoops to make that work, or just have the parent branch checked out when building the derivate?

Chris Malley 4:55 PM
Something like:

```
cd perennial
grunt checkout-target --repo=waves-intro --target=1.0
cd wave-interference 
git checkout —branch=2.0
cd waves-intro
grunt
// test build here
cp build/phet/dependencies.json .
git add dependencies.json
git commit -m ${{MESSAGE}}
git push origin 1.0
```

**Comment by KatieWoe** [comment]
Looks good in new rc
