### ISSUE TITLE
None and Lots not translated

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#432]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/405
The "None" and "Lots" strings that describe disorder in the diffraction screen are not translatable.
**Steps to reproduce**
1. Set any string test
2. Go to the diffraction screen
3. Select the grid of circles scene
4. Look at the disorder slider

**Visuals**
![noneandlotsnottranslated](https://user-images.githubusercontent.com/41024075/63197728-cf95a000-c035-11e9-92b9-a135ad8ad142.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-rc.1/phet/wave-interference_all_phet.html?stringTest=long
Version: 2.0.0-rc.1 2019-08-13 21:08:49 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Fix committed to master, will need to be cherry-picked to the RC branch.

**Comment by KatieWoe** [comment]
Looks good in the new rc.
