### ISSUE TITLE
Should the timer be above the reset button in z-ordering?

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/wave-interference#434]
For https://github.com/phetsims/QA/issues/405. I looked through the repo and I didn't see any similar issues, so if there is one, feel free to close this one.

I'm wondering if the timer should be above (in front of) the reset button.

![Screen Shot 2019-08-18 at 10 50 15 AM](https://user-images.githubusercontent.com/31285590/63219160-07702500-c1a7-11e9-8c66-7ebd1079ac9c.png)

Seems to happen in all screens with a timer in both Wave Interference and Waves Intro.

**Comment by samreid** [comment]
This is a new problem, not in the published version.

**Comment by samreid** [comment]
Fixed in master and will need to be cherry-picked to the branch for next RC

**Comment by arouinfar** [comment]
I thought we generally had a (likely unwritten) rule about keeping `ResetAllButton` on top of everything else? Might be worth checking in with #dev-public, if we haven't already. Thoughts @samreid?

I don't really have a strong opinion when it comes to this issue. If a user occludes the `ResetAllButton` by moving a tool in front of the button, they can just move the tool out of the way.

**Comment by samreid** [comment]
@pixelzoom said:

> In general, fixed-position UI components are typically behind moveable UI components.

**Comment by KatieWoe** [comment]
This seems fixed in the new rc.  Before closing, I had a related z-ordering question.  Should an object being picked up and moved be moved to the front?  I think we did something similar in gas properties.  @arouinfar?
![zorderbetweenmovement](https://user-images.githubusercontent.com/41024075/64439688-cc676000-d087-11e9-8fa8-94a945cbc111.gif)

**Comment by arouinfar** [comment]
@KatieWoe, yes the active tool generally pops to the front.

@samreid can you adjust the z-ordering of the tools so that the active one pops to the front?

**Comment by samreid** [comment]
Thanks, I opened #450 about moving tools to the front.  This issue can be closed.
