### ISSUE TITLE
Wave is stopped if started during a pulse

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#437]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/405 (both).  Occurs in published version as well.
If you make a pulse, switch to continuous while it makes the wave, and immediately hit the wave button, it will only do one wave then turn off.
**Steps to reproduce**
1. Go to a water scene with one wave and side view (easiest to see)
2. Go to pulse and start a pulse
3. The moment you do 2), switch to continuous wave and hit the button

**Visuals**
![waterisweird](https://user-images.githubusercontent.com/41024075/63294115-ca7b5f80-c286-11e9-8464-305e1af61f00.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.0.0-rc.3/phet/waves-intro_all_phet.html
Version: 1.0.0-rc.3 2019-08-13 22:16:34 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@ariel-phet I don't see a need for students to mix continuous and pulse, so I like the suggestion to clear the lattice when switching between these modes. @samreid can you move forward with this suggestion?

**Comment by samreid** [comment]
I tried calling `lattice.clear()` when the user changes between continuous and pulse, but that did not resolve the problem.  I found that there is another model property called `pulseFiringProperty` which is responsible for this buggy behavior.  

So next I tried: when changing between continuous and pulse, two things would happen:
(1) `lattice.clear()`
(2) `pulseFiringProperty.value = false`

And that appears to have resolved the problem.  However, I noticed that (1) is not a necessary part of this solution.  I tried removing (1) and using (2) only and it did not exhibit the bug.  In my opinion, just addressing this with (2) and not clearing all the water drops and the lattice area seems a little more natural and user-friendly, so I'd like I'll commit that first for feedback.  However, if for any reason this solution feels incomplete or if you want to add the `lattice.clear()` that would be very easy to add.  Commit on the way!

**Comment by samreid** [comment]
@arouinfar or @ariel-phet can you please review the preceding comment and test the behavior in master?  Let me know in particular if clearing the `pulseFiringProperty` is sufficient, or if you also have a reason for wanting to clear out any existing water drops or waves in the lattice.  Also, this is the last issue to discuss before I can prepare RC.2.

**Comment by arouinfar** [comment]
> However, I noticed that (1) is not a necessary part of this solution. I tried removing (1) and using (2) only and it did not exhibit the bug. In my opinion, just addressing this with (2) and not clearing all the water drops and the lattice area seems a little more natural and user-friendly, so I'd like I'll commit that first for feedback.

Thanks @samreid. I would agree that (2) on its own does look a bit more natural. I haven't noticed any side effects, and the original issue appears to have been addressed.

**Comment by ariel-phet** [comment]
@samreid also look good on master to me.

**Comment by samreid** [comment]
Thanks, I'll cherry pick it to the RC branch and it can be tested in RC.2.

**Comment by KatieWoe** [comment]
Looks good in the new rc.  Will reopen if a problem crops up
