### ISSUE TITLE
Pointer Area on Play Tone

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#438]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/405 (both)
There is no pointer area for Play Tone, though there is for similar strings such as Graph just above it.  This means that you can click much further out on Graph to activate that box than you can for Play Tone.  Not major, but an inconsistency.
**Steps to reproduce**
1. Set showPointerAreas
2. Go to a sound scene with one speaker
3. Examine Graph and Play Tone below it

**Visuals**
![pointerareasofplaytones](https://user-images.githubusercontent.com/41024075/63299385-e553d100-c292-11e9-801b-b288167ab619.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-rc.1/phet/wave-interference_all_phet.html?showPointerAreas
Version: 2.0.0-rc.1 2019-08-13 21:08:49 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@samreid please update Play Tone's pointerAreas to match Graph.

**Comment by samreid** [comment]
In https://github.com/phetsims/sun/issues/399#issuecomment-439482289 @pixelzoom said:

> Doing this on a sim-by-sim basis is not recommended - it increases the time/cost for every sim, and makes it much more difficult to test/maintain/modify. If alignment is a requirement, PhET should incur the cost of handling it uniformly in common code.

I'm not sure everyone is aware of that conversation, or whether there is a consensus for that issue.  I recommend further discussion before additional work along these lines.

**Comment by samreid** [comment]
> Checkboxes span the panel width, but radio buttons don't? I don't think the absence of an "established pattern" justifies that.

I investigated expanding the touch area to the right for the radio buttons, but could not find a way to do it without modifying or breaking encapsulation of VerticalAquaRadioButtonGroup.  Hence I will recommend avoiding work on this for RC.2.  The next best checkpoint if/when we proceed with this would probably be in coordination with https://github.com/phetsims/sun/issues/399

**Comment by KatieWoe** [comment]
Looks good in new rc
