### ISSUE TITLE
All particles change behavior when frequency changes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#439]
**Test device**
Dell and Jordan
**Operating System**
Win 10 and Mac 10.14
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/405 (both) and published.
When the frequency of the sound wave is changed, the particles that are currently part of older waves also drastically change their behavior, though there doesn't seem to be a reason for this.
**Steps to reproduce**
1. Go to a single sound wave scene
2. Select the Both scene
3. Set the frequency low and start the waves
4. When the waves fill up the play area turn the frequency up quickly and observe the particles compared to the waves
5. When the high frequency waves fill up the play area turn the frequency down quickly and observe the particles compared to the waves

**Visuals**
https://drive.google.com/file/d/1WoGXkcdZ0nPN9EmBdKw03htttTYSOIHd/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.0.0-rc.3/phet/waves-intro_all_phet.html
Version: 1.0.0-rc.3 2019-08-13 22:16:34 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Good find @KatieWoe. It looks the particles reset their positions when the frequency was cranked up. Here, the particles on the right side of the lattice exhibit the random background motion and no longer correspond to the wavefronts. @samreid can you investigate?

<img width="632" alt="Screen Shot 2019-08-22 at 10 26 41 AM" src="https://user-images.githubusercontent.com/8419308/63532298-9c389280-c4c7-11e9-8bd0-19fc0a032008.png">

**Comment by arouinfar** [comment]
Thanks @samreid. 

It sounds like what we're seeing here is a limitation of the particle model. The particle model supports a single frequency, so changing the frequency will lead to misalignment between the particles and the wavefronts at the previous frequency(ies). 

@ariel-phet is this something you'd be okay with deferring? This behavior certainly isn't ideal, but given the goals of the particle view, I think it's acceptable. I would also update the Teacher Tips to explain this limitation.

**Comment by ariel-phet** [comment]
@arouinfar I am fining deferring, the waves catch up pretty quickly. It is a bit odd, but really the main learning goal here (as you point out implicitly) is that dense particles (high pressure) correspond to crest in the wave view. Moderate speed changes to the frequency basically look fine.

@arouinfar I think you could put in the teacher tips and close as `wontfix` or defer, I will let you make that call.

**Comment by arouinfar** [comment]
The Teacher Tips have been updated, closing as `wontfix`.
