### ISSUE TITLE
Pointer area for wavelength slider smaller than pointer area for other sliders in the sim

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/wave-interference#442]
**Test device**
Windows 7 Laptop
**Operating System**
Windows 7 Professional v. 6.1
**Browser**
Chrome
**Problem description**
From https://github.com/phetsims/QA/issues/424

The sliders for wavelength on the diffraction screen have a smaller pointer area than that which is found on other sliders in the simulation.
**Steps to reproduce**
1. Enter query ?showPointerAreas into the sim url
2. Enter the "Diffraction" screen
**Visuals**
![2019-9-5PointerAreaWavInterf](https://user-images.githubusercontent.com/54685448/64390881-cf207180-d003-11e9-8beb-96bfb8618d43.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Wave Interference‬
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-rc.2/phet/wave-interference_all_phet.html?showPointerAreas
Version: 2.0.0-rc.2 2019-09-04 01:17:25 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Language: en-US
Window: 1366x576
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment]
Good find @loganbraywork.

@samreid can you horizontally dilate the Wavelength tweakers, as was done for other NumberControls.

**Comment by samreid** [comment]
Some notes as I investigate this:

1. This only affects Wave Interference and would not require a new RC for Waves Intro
2. I made an overlay of the touch areas, and the large one is about 15-20% larger

![image](https://user-images.githubusercontent.com/679486/64463292-baee7a00-d0c0-11e9-8da1-b0f4bdae977f.png)

**Comment by samreid** [comment]
If we use the same dimensions (horizontal and vertical) as the other number controls, it impinges somewhat on the slider track:

![image](https://user-images.githubusercontent.com/679486/64463400-1f113e00-d0c1-11e9-8f63-99d2ac2fc4d6.png)

**Comment by samreid** [comment]
I factored out the horizontal part, and reduced the vertical part and now it looks like this:

![image](https://user-images.githubusercontent.com/679486/64463563-b1b1dd00-d0c1-11e9-994e-249780f71b73.png)

I'll commit to master.

**Comment by samreid** [comment]
This is fixed in master, if/when we cherry pick it to the RC branch, it will require 2 cherry-picks.

**Comment by KatieWoe** [comment]
Looks good in the new rc
