### ISSUE TITLE
Intensity window expands

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#444]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/424
When strings are long, the intensity graph in the light screens expands and makes the page look cramped.  Occurs in published version.

**Visuals**
![seemsclose](https://user-images.githubusercontent.com/41024075/64456850-680bc700-d0ae-11e9-85e3-dd53ed6120a8.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/wave-interference/2.0.0-rc.2/phet/wave-interference_all_phet.html?stringTest=long
Version: 2.0.0-rc.2 2019-09-04 01:17:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. 

@samreid looks like the layout issues would be resolved if the Intensity panel didn't expand.

**Comment by samreid** [comment]
This will likely be solved by reducing the maxWidth on the intensity panel text.  I also noted that with stringTest=double, it isn't quite long enough to be a problem:

![image](https://user-images.githubusercontent.com/679486/64464264-8e3c6180-d0c4-11e9-9c43-b36197934e0d.png)

**Comment by samreid** [comment]
Fixed and ready for cherry pick.

**Comment by KatieWoe** [comment]
Looks good in the new rc
