### ISSUE TITLE
Frequency and Amplitude Reset Before Play Tone

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#445]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox (and others)
**Problem description**
For https://github.com/phetsims/QA/issues/424
When you have Play Tone on and a non default frequency and/or amplitude, hitting reset all will briefly produce a sound for the default setting.  Very minor.
**Steps to reproduce**
1. Go to a sound screen/scene with one speaker
2. Turn on Play Tone
3. Turn amplitude to zero (can be done with any frequency or amplitude change, but this is easiest to see)
4. Turn on wave
5. Hit reset all

**Visuals**
https://drive.google.com/file/d/1p3Mxd_3LjRTfNSkKm-N6GGByletocsmt/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.0.0-rc.4/phet/waves-intro_all_phet.html
Version: 1.0.0-rc.4 2019-09-04 22:21:00 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Nice find @KatieWoe. 

This looks like a bug to me @samreid, though I would agree it's pretty minor.

**Comment by samreid** [comment]
The commit fixes the problem on my machine, should be ready for cherry picking and testing.

**Comment by KatieWoe** [comment]
Sounds good in the two rcs.
