### ISSUE TITLE
Wave detector does not reset in toolbox

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#446]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/424
When the measuring tape and timer are returned to the tool box they are reset to their original states.  However, if you use the wave detector, put it in the toolbox, and then pull it out it will still be scrolling through the previous readings.  Occurs in published.
From Slack:
> Kathryn Woessner:office: 10:27 AM
> I noticed that putting the tools back in the tool box resets all of the tools but the Wave Detector tool.  Is that expected/ok?
> Amy Rouinfar 10:29 AM
> That looks weird to me. I would reset the Wave Detector too.
> Sam Reid 10:29 AM
> Sounds good, may I please have an issue?

**Steps to reproduce**
1. Go to a screen with the toolbox
2. Pull out all three tools
3. Lengthen the tape measure, start the timer, and set the wave detector to collecting data
4. Put all three back in the box
5. Quickly pull all three back out again

**Visuals**
https://drive.google.com/file/d/1h2rmwNkuYNUDzTya57uKcpgUr8aDg9l4/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.0.0-rc.4/phet/waves-intro_all_phet.html
Version: 1.0.0-rc.4 2019-09-04 22:21:00 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Fixed and ready for testing or cherry-pick.

**Comment by KatieWoe** [comment]
Looks good in the rcs
