### ISSUE TITLE
should ToolboxPanel use allowTouchSnag:true ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#455]
While working on https://github.com/phetsims/scenery/issues/999, I noticed that `ToolboxPanel` is the only client of `DragListener.createForwardingListener` that is using `allowTouchSnag: false`.   In that issue, we changed the default to `allowTouchSnag: true`, and I changed `ToolboxPanel` accordingly to:

```js
    node.addInputListener( DragListener.createForwardingListener( forwardingListener, {
      allowTouchSnag: false
    } ) );
```

I'm guessing that this was an oversight, because `ToolboxPanel` is similar to other UI components that use `allowTouchSnag: true`.    If it's not an oversight, please document why `allowTouchSnag: false` is appropriate in this case.

**Comment by samreid** [comment]
Fixed, closing.
