### ISSUE TITLE
How should the cube be colored when rotating light?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#46]
The color of the rotation cube is based on the frequency of the light (with a darker shade for one side of the cube).  However, when the light hasn't yet been turned on, or has partially propagated across the screen, it could look incorrect.  This movie shows what it looks like if you rotate red light that hasn't propagated yet:

![rotate-cube](https://user-images.githubusercontent.com/679486/40011180-3f77d212-5764-11e8-86b7-8e9dc5caa5cc.gif)

Is this OK or should we make changes?

**Comment by arouinfar** [comment]
@samreid it think it's fine to use the frequency slider to color the cube. After all, it's what we did in Java. I don't think we need to be worried about the cases where light hasn't (fully) propagated. I made a note in the Interview Notes section of the design doc to be on the lookout for confusion. We can revisit if there are serious issues that arise in the interviews, but closing for now.
