### ISSUE TITLE
incorrect order of merge args

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#460]
As noted in https://github.com/phetsims/phet-info/issues/121#issuecomment-549057504...

The order of args to `merge` in `WAVE_INTERFERENCE/DiffractionNumberControl` creates a potential maintenance problem.

```js
      const mergedOptions = merge( {
        sliderOptions: {
          majorTicks: [ {
            value: property.range.min,
            label: new WaveInterferenceText( property.range.min.toFixed( 2 ) )
          }, {
            value: property.range.max,
            label: new WaveInterferenceText( property.range.max.toFixed( 2 ) )
          } ]
        }
      }, options, WaveInterferenceConstants.NUMBER_CONTROL_OPTIONS );
```

Client-specified `options` correctly override `DiffractionNumberControl` defaults option values. But `NUMBER_CONTROL_OPTIONS` overrides `options` and `DiffractionNumberControl` defaults. So any change to `NUMBER_CONTROL_OPTIONS` could change default and/or client-specified behavior of `DiffractionNumberControl`.

In general, `merge` args should be ordered from least to most specific. So the above should be:

```js
      const mergedOptions = merge( {}, WaveInterferenceConstants.NUMBER_CONTROL_OPTIONS, {
        sliderOptions: {
          majorTicks: [ {
            value: property.range.min,
            label: new WaveInterferenceText( property.range.min.toFixed( 2 ) )
          }, {
            value: property.range.max,
            label: new WaveInterferenceText( property.range.max.toFixed( 2 ) )
          } ]
        }
      }, options );
```
<br>

Note that the first arg is `{}` to prevent modification of `NUMBER_CONTROL_OPTIONS`.

**Comment by samreid** [comment]
Thanks!  I verified that the proposed code has the same resultant options as the previous code and committed.  

This also let me remove this comment:
```js
      // Normally we would like to specify options last, however, at the time of writing, there is a problem that
      // https://github.com/phetsims/phet-info/issues/91#issuecomment-474008231 where all merge arguments are mutated
      // except the last one, hence we specify the shared value last.
```

Closing.
