### ISSUE TITLE
Prepare a version for upcoming usage with Hillside

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#462]
At yesterday's meeting, we decided to publish a dev version for Brett to use with Hillside on Thursday Nov 14, 2019.  I'll strip the debug derivatives from the positional chart, and remove the sonification from the positional chart, which is still in development in https://github.com/phetsims/wave-interference/issues/457

I don't know whether I'll have time to add the single-shepherd's tone with filter frequency modulation in time for usage.

**Comment by samreid** [comment]
I removed the position graph derivatives and sonification and published https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.7/phet/waves-intro_en_phet.html, please test thoroughly before classroom usage.  Also, recall you can append ?screens=1 to the URL to restrict the sim to the water screen.  Please let me know if there's anything else I can help with here.

**Comment by BLFiedler** [comment]
Looks good from my investigations. Let's leave the issue up until next week in case there is an update we want to bring by to the kids.

**Comment by BLFiedler** [comment]
I forgot to say this during the sound meeting, but if there's time, I can possibly have the kids specifically provide feedback tomorrow on the graph sounds you're working on, @samreid .  If you have something worth creating a version for?

Otherwise, maybe that is a good topic for the sharing day on Dec 5th?

**Comment by samreid** [comment]
Here's a version that uses the "single shepard tone + oscillating filter frequency", please test it for yourself and determine whether it is suitable for your usage:
https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.8/phet/waves-intro_en_phet.html

**Comment by samreid** [comment]
I wonder how it would sound if we used one tone per peak, but not using Shepard tones for those.
