### ISSUE TITLE
Sound effects checkbox overlaps with Screen checkbox when Light radio button is selected

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/wave-interference#463]
**Test device**
Windows 7 laptop
**Operating System**
Windows 7 
**Browser**
Chrome 78.0.3904.97
**Problem description**
Appears on master, accidentally discovered when testing for sounds.

When on the Slits or Interference screens, if the Light radio button is selected then the "sound effects" checkbox appears and is overlapped by the "screen" checkbox.
**Steps to reproduce**
1. Go to either the Slits or Interference screens
2. Select the Light radio button
**Visuals**
The following takes place on the Interference screen
![2019-11-12SndBttnWvIntMstr](https://user-images.githubusercontent.com/54685448/68801525-7d0a5680-0619-11ea-828a-cd58daf44b63.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Wave Interference‬
URL: http://phettest.colorado.edu/wave-interference/wave-interference_en.html?ea&brand=phet
Version: 2.1.0-dev.0 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Language: en-US
Window: 1366x625
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
Thanks @loganbraywork, I corrected that problem in the above commit.  Can you please verify the fix on phettest?  Please close if all is well.

**Comment by samreid** [comment]
I checked that this still behaves correctly, and it will be re-tested by QA in the next RC, so it seems safe to close.
