### ISSUE TITLE
Improvements and additions to sonification

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#465]
During our Tuesday Jan 21 Waves Intro sonification meeting, we agreed we would like to make some improvements and additions to the sonification, then move to interviews, dev testing and publication.  This will be without screen reader/a11y design or implementation.  I'll open issues for each of the proposed items.

I indicated to @arouinfar that this could be ready around Feb 6, 2020, so marking as high priority.

**Comment by samreid** [comment]
@emily-phet indicated it would be nice to have a design meeting about this on Thursday.  I'll notify the slack channel Tuesday morning, but also mentioning it to @ariel-phet now in case it helps.

**Comment by samreid** [comment]
This is ready for review in https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.12/phet/waves-intro_en_phet.html

**Comment by samreid** [comment]
I requested design time on the slack design channel.

**Comment by emily-phet** [comment]
During the meeting (Thursday?) I'd like to create a list of:
- sounds we have consensus on that we want to publish the sim with
- sounds for which there are open questions around 
- sounds that will not be included in the next publication.

**Comment by samreid** [comment]
This version un-sonifies the in WaveAreaGraphNode, see https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.13/phet/waves-intro_en_phet.html

**Comment by samreid** [comment]
The following issues came up during Thursday's design meeting:

**Comment by emily-phet** [comment]
@samreid - can this one be closed? It seems like we've moved beyond what was discussed Jan. 21, and new feedback is being put into individual issues.

**Comment by samreid** [comment]
Thanks @emily-phet, closing.
