### ISSUE TITLE
Play/pause in the timer does not have a sound

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#466]
For #465 

Play/pause in the timer does not have a sound.  

JB: Check the standard play/pause button.

**Comment by samreid** [comment]
The simulation already has a Play/Pause button at the bottom center of the screen which pauses/plays the entire simulation.  It seems we should use a different sound for the play/pause on the Stopwatch which only play/pauses the stopwatch.  @arouinfar @emily-phet @Ashton-Morris can you please recommend how to proceed?

**Comment by arouinfar** [comment]
@samreid I think the buttons on the StopwatchNode should use the standard button sounds, not the play/pause sound used in the TimeControlNode.

**Comment by samreid** [comment]
Fixed, closing.
