### ISSUE TITLE
User suggestion: phase offset between the two sources

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/wave-interference#472]
> I found a java version of this type of simulation (by Juan M. Aguirregabiria) that has a phase offset between the two sources as a parameter.  I find that this is very useful to point out to students that interference patterns are driven by other factors besides the source spacing and wavelength.  Any chance this could be added to your nice simulation?

**Comment by samreid** [comment]
@arouinfar can you please advise for this issue?

**Comment by arouinfar** [comment]
Locking the two sources to be in phase was a deliberate design decision.

If we wanted to make this change, I think the control would need to adjust the phase relatively (e.g. 1/4 or 1/2 cycle offset). However, I do think this goes beyond the scope of the learning goals and I suspect the resulting interference pattern would be incredibly hard to interpret. Closing.
