### ISSUE TITLE
Volume balancing

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#473]
From #465, the sim needs overall volume balancing.  @emily-phet indicated this should be done in coordination with @Ashton-Morris, and should be done after all other features are basically working.  On hold until then.

This may be accomplish in part by making sure the sounds are assigned to the right "groups" or "classes".

**Comment by emily-phet** [comment]
@samreid I discussed this with @Ashton-Morris on Slack, and he's going to start working on this.

**Comment by emily-phet** [comment]
@Ashton-Morris - is this done? We might want to leave this open until it's finalized.

**Comment by Ashton-Morris** [comment]
@emily-phet Sorry I don't know git hub etiquette yet. I did the balance the audio levels and thought that was the scope of this issue. 

We did not adjust any frequency of clicking sounds. I wasn't a part of that conversation so I am not sure what was said, but I did adjust the volume of them.

**Comment by emily-phet** [comment]
Thanks @Ashton-Morris - no worries! Once @jbphet returns, let's all take a listen to the latest (perhaps in a design meeting next week?) and double-check if there are any tweaks that come out of that discussion. It's good to leave this open, as a breadcrumb for all about what's happening here until we're 100% sure it's all set and we're ready to move on to the next step towards publication.

**Comment by samreid** [comment]
Assigning to @arouinfar and @emily-phet to review the volume balancing.  @ariel-phet would you also like to review?

**Comment by samreid** [comment]
I also made further improvements today as part of https://github.com/phetsims/wave-interference/issues/474

**Comment by samreid** [comment]
@arouinfar says that everything except the sounds for WaveMeterNode seemed well balanced.  There is a separate issue for this, see #482
The rest of the team is okay with the balance levels.  Closing.

**Comment by arouinfar** [comment]
@samreid I'm noticing that the home screen and navbar sounds are really loud relative to other common UI sounds in master. In https://github.com/phetsims/wave-interference/issues/474#issuecomment-588608347 you classified common component sounds as `user-interface`, could you include the homescreen/navbar sounds in this group?

**Comment by emily-phet** [comment]
Just a note re volume balancing - during yesterday's meeting there was one or two things it seemed @ariel-phet and @arouinfar were going to discuss with Ashton. I suggest we collect recommendations for all volume balancing challenges, and you all include that in the conversation with @Ashton-Morris. 

@Ashton-Morris needs to weigh in on any final volume balancing - there are nuanced details that we as non-sound designers won't attend to. The relative salience is one factor - which is an important one and exactly what we need to weigh in on for @Ashton-Morris! - but there are others, including consistency of volume levels across all sims and many more than are beyond my expertise.

**Comment by samreid** [comment]
> @samreid I'm noticing that the home screen and navbar sounds are really loud relative to other common UI sounds in master. In #474 (comment) you classified common component sounds as user-interface, could you include the homescreen/navbar sounds in this group?

That was likely corrected in https://github.com/phetsims/wave-interference/issues/483.  @arouinfar can you please be aware of that in testing #483?

Leaving assigned to @Ashton-Morris to check the levels again.  Please be aware of the other open issues which relate to this.

**Comment by arouinfar** [comment]
> Just a note re volume balancing - during yesterday's meeting there was one or two things it seemed @ariel-phet and @arouinfar were going to discuss with Ashton. 

During the last design meeting I thought the balancing was appropriate, but the overall volume was low so I opened #483. I believe @ariel-phet was going to work with Ashton on the slider click sound, which happened in #484.

@samreid I don't have any further suggestions for volume balancing. Things generally seem good -- WaveMeterNode volume will be boosted (#482), pedagogical sounds are louder than UI sounds (https://github.com/phetsims/wave-interference/issues/474#issuecomment-588608347), and slider clicks are somewhat quieter than other UI sounds (#474).

Not sure how many sound issues are still out for final review, but I think once everything's settled, it would be good for @Ashton-Morris's final volume balancing review. Assigning to @samreid to decide when we're ready for that.

**Comment by samreid** [comment]
On hold until #490 is complete.

**Comment by samreid** [comment]
From https://github.com/phetsims/wave-interference/issues/490#issuecomment-599682513, 

> After the above commits, all of the searches for "outputLevel" and "duck" in the wave-interference js/ directory are relevant and documented.

**Comment by samreid** [comment]
This issue may be ready for @Ashton-Morris, but please note there are other open issues that may impact the balancing.

**Comment by Ashton-Morris** [comment]
@samreid I just pulled and listened for the new squishy button but did not hear it. Is it in this version?

**Comment by samreid** [comment]
The sim should be using 008.mp3.  Is it possible your browser is caching it?  Let's touch base on slack if that doesn't resolve it.

**Comment by Ashton-Morris** [comment]
I finished the latest round of mixing, lets discuss whats next in todays UI sound meeting @emily-phet

**Comment by emily-phet** [comment]
I think the latest volume balancing is great! I think there slider click sounds need to be decreased, but that is pending outcomes of https://github.com/phetsims/wave-interference/issues/484.

Once the other issues are addressed, I think we'll need a final volume balancing review, and then we'll be good to go.

**Comment by emily-phet** [comment]
@samreid not sure if the labels should be changed for this issue...so assigning back to you just in case.

**Comment by samreid** [comment]
Thanks, I'll place it on hold until the rest of the issues are closed.

**Comment by emily-phet** [comment]
Please give a final listen to the latest sim on phettest. We'd like to finalize this sim asap, so please keep this in mind as you listen. 

Please share your thoughts (good to go, or something else) in this comment, and check your name off when you're done. (@Ashton-Morris and @jbphet have already reviewed)

- [ ] @samreid 
- [ ] @kathy-phet 
- [ ] @arouinfar 
- [x] @jbphet 
- [x] @Ashton-Morris 

 If you have questions, concerns, or topics you'd like to discuss, please note that we'll request an upcoming Thursday design meeting time to discuss.

**Comment by arouinfar** [comment]
Overall, I think master is sounding great. I tested with speakers at 50% max volume, speakers at 100%, and headphones at 50%. In all cases, I could hear all of the sounds, and I thought they were appropriately balanced. 

The only exception was the volume of the sound associated with the lighter probe. I find it practically impossible to hear unless using headphones. Compared the darker probe, it sounds much quieter. I know some of this is likely an illusion and work was done in https://github.com/phetsims/wave-interference/issues/485 to normalize the probe sounds, but it sounds off to me. The volume of the darker probe sounds spot on, so perhaps we can boost the lighter probe so it sounds a bit more similar (even if that means undoing the normalization).

**Comment by ariel-phet** [comment]
I definitely agree with @arouinfar that the lighter grey probe sounds too quiet to my ear and not in proportion to the darker grey probe.

I would also say that on my system (which has a subwoofer), the "Sound" screen bassy sound effect of the wave sounds good, but I think the ducking that is induced when I put in the probes is a bit much. When I take the probes out there is a very obvious difference in volume and it feels more like the probes have somehow affected the wave itself. I think either the actual volume of the wave could be turned down a bit or the ducking effect reduced a bit. However, on a system without a subwoofer this may be a non issue.

**Comment by samreid** [comment]
I reviewed this on the built-in speakers of a 2016 15" MacBook Pro, I set the volume to around 40% and overall it sounds really great!  Two minor points:

If our goal was to purposefully make the water drop, speaker membrane and light sound effect louder than the button/checkbox sound effects, then we have achieved that goal.  But to me, that doesn't make it easier to pick up on them or learn from them, it just makes them more annoying.  I think the sim would sound better if those sounds were reduced around 20%.  I'm happy to be outvoted on this topic if we have research or interview data telling us we have to have these physics sounds at a higher volume than the other UI sounds, or others have had a different experience.

For my setup, the light probe sounds well calibrated (placed in the center of the wave area) but the dark probe sounds like it should be reduced by around 20% to match it.  This differs from what @ariel-phet and @arouinfar recommended above--to increase the light probe volume accordingly.  I guess the answer to this would depend on what we decide for the preceding paragraph.

**Comment by samreid** [comment]
Here's a recent dev version for discussion:
https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.20/phet/waves-intro_en_phet.html

**Comment by samreid** [comment]
We reviewed this at today's design meeting:

@arouinfar recommends: The lighter probe should have its volume increased.

@jbphet recommends to reduce the water drop sounds by 10%
@kathy-phet says the water drops should be louder than the other button-y sounds.

@jbphet recommends to reduce the speaker membrane sound by 20%

**Comment by samreid** [comment]
For after the meeting: 
The lighter probe should have its volume increased. Try to make them sound the same volume at the same spot.

**Comment by samreid** [comment]
Patch from design meeting:

```diff
Index: js/common/view/WaveMeterNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/WaveMeterNode.js	(revision bd73d7c797c2dd2b6807ade5412ba91cb55d43c7)
+++ js/common/view/WaveMeterNode.js	(date 1589491081511)
@@ -241,7 +241,11 @@
             // Set the main volume.  If the sound clip wasn't playing, set the sound immediately to correct an audio
             // blip when the probe enters the play area.  If the sound clip was playing, use a longer time constant
             // to eliminate clipping, scratching sounds when dragging the probes quickly
-            soundClip.setOutputLevel( duckFactor * ( model.isRunningProperty.value ? outputLevel * volumeProperty.value : 0 ), soundClip.isPlaying ? 0.03 : 0.0 );
+            const index = soundClip.myIndex;
+            const scaleFactor = index === 0 ? 1.0 : 2.0;
+            const myOutputLevel = scaleFactor * duckFactor * ( model.isRunningProperty.value ? outputLevel * volumeProperty.value : 0 );
+            console.log( myOutputLevel );
+            soundClip.setOutputLevel( myOutputLevel, soundClip.isPlaying ? 0.03 : 0.0 );
 
             // Work around a bug in Tambo that results in audio played even when outputLevel is 0.0
             if ( !soundClip.isPlaying ) { // TODO: playing a soundclip with outputLevel 0 plays something
@@ -311,19 +315,16 @@
     const waveMeterSound1VolumeProperty = new Property( 0.1 );
     const waveMeterSound2VolumeProperty = new Property( 0.05 );
 
-    const sounds1 = sounds.map( sound => {
-      return new SoundClip( sound, {
-        loop: true,
-        trimSilence: false
-      } );
-    } );
-
-    const sounds2 = sounds.map( sound => {
-      return new SoundClip( sound, {
+    const mapSound = sound => {
+      const soundClip = new SoundClip( sound, {
         loop: true,
         trimSilence: false
       } );
-    } );
+      soundClip.myIndex = sounds.indexOf( sound );
+      return soundClip;
+    };
+    const sounds1 = sounds.map( mapSound );
+    const sounds2 = sounds.map( mapSound );
 
     const series1PlayingProperty = new BooleanProperty( false );
     const series2PlayingProperty = new BooleanProperty( false );
```

**Comment by samreid** [comment]
On second thought, it seems we the audio files should also be balanced, in case we decide to use them in another context.

**Comment by samreid** [comment]
Since all aspects of this issue have been addressed aside from the wave meter probe sound normalizing, let's move that to a separate issue and close this parent issue.

**Comment by samreid** [comment]
I reopened https://github.com/phetsims/wave-interference/issues/485 and will close this issue
