### ISSUE TITLE
Turn down the volume on slider clicks.

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#474]
From #465 and related to #473, the slider clicks are too loud.

AP: The slider ratchet sounds are irritating for me. 
AR: It's appropriate for John Travoltage, but not fitting for these sliders.
EM: It's currently very loud.  
AP: Maybe it will be better when volume balanced.

EM: We wanted something "neutral" here, so it won't catch your attention too much.

**Comment by emily-phet** [comment]
Also regarding the slider clicker sounds, it was brought up that for wavelength slider on the "Light" screen, @arouinfar and @ariel-phet felt it would be better for there to be more clicks, to feel more 'continuous' since the visual display for that slider is different from other screens. 
@arouinfar @ariel-phet please weigh in if I'm recalling this incorrectly.

**Comment by samreid** [comment]
@Ashton-Morris was this addressed during #473 ?

**Comment by emily-phet** [comment]
@samreid @Ashton-Morris I think in this version - https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.14/phet/waves-intro_en_phet.html all of the common UI sounds can be turned down. At least from my setup (speakers on my laptop), the clicker sounds, pick up/drop tool sounds, etc. are all louder than the water drop sound, graph tool sound, etc. It needs to be reversed...you should barely notice the common UI sounds when volume is at moderate. 

I believe these common UI sounds may be categorized together in the code, and perhaps their loudness can be tuned as a whole set (not needing to be done individually).

**Comment by samreid** [comment]
I categorized appropriate sounds as `user-interface` and adjusted the volume.  @emily-phet can you please review on phettest?

**Comment by arouinfar** [comment]
@samreid I think master's definitely an improvement!

**Comment by arouinfar** [comment]
@samreid I think you may have inadvertently classified the wave detector as a `user-interface` element. It sounds a bit quieter in master compared to dev.14.

**Comment by samreid** [comment]
@kathy-phet said: One click sounds a reasonable volume, but since these come in bursts, they should be reduced further.  

@samreid asked: What number should I aim for? 
@kathy-phet: Let's check.

**Comment by samreid** [comment]
I cut it in half in the commit, but this cannot be reviewed until https://github.com/phetsims/wave-interference/issues/483 is addressed.

**Comment by samreid** [comment]
OK #483 has a proposed fix and is up for review.  @kathy-phet or @arouinfar can you please check the slider click volume?  Also, please be aware the sound effect itself changed as part of #484.  Marking high priority in case this should be done before interviews.

**Comment by kathy-phet** [comment]
Seems like a "softer" less "cheerpy" sound to me.

**Comment by arouinfar** [comment]
@samreid I like the updated slider sound and its volume in master.

**Comment by ariel-phet** [comment]
Definitely an improvement!

**Comment by emily-phet** [comment]
Closing this issue, and continuing slider UI sound-related discussion in https://github.com/phetsims/wave-interference/issues/484.
