### ISSUE TITLE
The wavelength slider sonification should sound more continuous

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#475]
From #465, the wavelength slider sounds too "discrete", we are wondering if it should have more frequent ratchet clicks?

> AP: The wavelength slider needs more frequent clicks.
> Wavelength slider clicks problematic -- should sound more continuous

EM: JB has strategies for tuning the slider tick sounds.
SR: I may need to wait for JB's help for that.

**Comment by emily-phet** [comment]
My interpretation of what was said is that the "Light" screen, @arouinfar and @ariel-phet felt it would be better for there to be more clicks, to feel more 'continuous' since the visual display for that slider is different from other screens. I didn't interpret this as being for all frequency sliders.
@arouinfar @ariel-phet please weigh in if I'm recalling this incorrectly.

**Comment by samreid** [comment]
In my opinion, the best way to hear the continuous nature of the wavelength slider is to turn on the "sound effect" checkbox. This causes an immediate pitch-based auditory feedback which is continuous and matches the wavelength of the light.  

Adding "more clicks" to the slider will make it sound more noisy, I don't know that students will interpret that as sounding more "continuous".  And why would we want to signify that the wavelength is somehow "more continuous" than the amplitude and frequency sliders?  They are all equally continuous.

Maybe what we were picking up on during the meeting was that the other sliders have tickmarks and natural points for sonification ratchet clicks, but the wavelength slider looks different--so maybe it should sound different.

What if we try playing the "sound effect" sound when dragging the wavelength slider, and omit its ratchet sounds altogether?  (I'm not sure how difficult that would be to implement, but wanted to get agreement on a direction before working on this implementation).

**Comment by samreid** [comment]
For completeness, I decided to try out the "more frequent clicks" anyways.  I'm surprised that it does sound a bit "more continuous".  Anyways, we should discuss what's best here.  I'll mark for review and discussion at next meeting.

**Comment by samreid** [comment]
During today's design meeting:

@arouinfar said: Since the spectrum slider looks more continuous, it seems like it needs different sounds.  The more frequent clicks sound good.

@samreid says: what about just the "sound effect" sound while dragging
@kathy-phet replies: that seems overwhelming and unwarranted.  The more frequent clicks sound good.  They are still a bit loud for now.

**Comment by jbphet** [comment]
We agreed the current sound is acceptable for interviews.  @Ashton Morris and @ariel-phet will look into a better sound effect in https://github.com/phetsims/tambo/issues/94.

**Comment by ashton** [comment]
Hi, I think you've been citing the wrong Ashton recently hahah
