### ISSUE TITLE
Change "Step Forward" button sound to the softer version

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/wave-interference#478]
The step forward button in Waves Intro is too harsh and should be replaced by the more subtle one used in the Tambo test page. 

@samreid [Example can be heard in this sim](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-soundDesignProto01.3/phet/molecules-and-light_en_phet.html?supportsSound)

**Comment by samreid** [comment]
I used the same sound as in that sim, @Ashton-Morris please review on phettest and close if all is well.

**Comment by samreid** [comment]
We reviewed this in today's meeting and agreed it sounds good, closing.
