### ISSUE TITLE
Remove the wave source button depress (or pop up) sound when the single wave option is chosen

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/wave-interference#479]
When you are testing the sound with the single wave option chosen you hear the button pop up which is very distracting from the learning goals of focusing on the wave. 

Also when you press the reset button you can also hear the Wave Source button depress.

If you can remove the sound from playing in those two instances it would be preferable. Alternatively it could just never play a sound when the button is depressing or popping up.

**Comment by emily-phet** [comment]
@samreid - I totally agree with @Ashton-Morris, the pop-up sound needs to not happen for the single wave button.

For the reset button - no other sounds should ever play, except for the single reset sound. (nice catch @Ashton-Morris)

**Comment by samreid** [comment]
The best way to implement this would be if `RoundStickyToggleButton` had the same level of sound support that `RoundPushButton` has.

**Comment by samreid** [comment]
I followed the example in `RoundPushButton` and applied it in `RoundStickyToggleButton`.  As far as I can tell it has the same sound as requested for this sim.  It also fixes the auto-play problems on reset and switching modes.  @jbphet can you please review this change?

**Comment by samreid** [comment]
We reviewed this and agreed it sounds good, closing.
