### ISSUE TITLE
Normalize the wave detector sounds

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#485]
From https://github.com/phetsims/wave-interference/issues/482#issuecomment-595975149 @arouinfar said:

> One thing I'm noticing is that the darker probe generally seems softer/lower volume than the lighter probe. Am I imagining things, or do you hear it too?

**Comment by samreid** [comment]
For me, the darker probe sounds more "full". But I looked at the waveforms and they don't appear to have the same normalization:

![image](https://user-images.githubusercontent.com/679486/76129420-a3873f80-5fc4-11ea-9664-593d5329dd5e.png)

@Ashton-Morris can you take a look?

The files are:

https://github.com/phetsims/wave-interference/blob/38fcb7b7e4cfbb4e31280c524c7a1c656dd9f1d6/sounds/windy-tone-for-meter-loop-rate-75-pitch-matched-fixed.mp3

https://github.com/phetsims/wave-interference/blob/38fcb7b7e4cfbb4e31280c524c7a1c656dd9f1d6/sounds/220hz-saturated-sine-playback-rate-75.mp3

**Comment by Ashton-Morris** [comment]
@samreid When you have a sound that has a lot of high end noise (harpsichord strike) vs a clean low end sound (low sine wave tone) the one with high end sound will sound louder in more situations even if you lower it to the same exact levels. It has more character and stands out more and I think the human ear is tuned to pick up more on those frequencies.

So it's realistically just as effective to boost the bass one or lower the windy tone one as it is to create more files. 

You can do it which ever way is easiest. These are normalized at -1db

[220hz-saturated-sine-playback-rate-75-norm.mp3](https://drive.google.com/open?id=1viU794bC0uwhcQei3k3DaAMzGIEwwlwt)
[windy-tone-for-meter-loop-rate-75-pitch-matched-fixed-norm.mp3](https://drive.google.com/open?id=1KiER01uHQ1ksaWc0rPO2AxMoCvJGYuzp)

**Comment by samreid** [comment]
Thanks @Ashton-Morris, I used the normalized files in the commit.  @arouinfar can you please review?

**Comment by samreid** [comment]
Here's the visual depiction of the new files from audacity:

![image](https://user-images.githubusercontent.com/679486/76546627-74a01c00-6451-11ea-8c6d-1964313a65bd.png)

**Comment by emily-phet** [comment]
If normalized files are now in use, then we can adjust the difference in perceived volume in final sound mastering step.

**Comment by samreid** [comment]
From https://github.com/phetsims/wave-interference/issues/473#issuecomment-628892946

> The lighter probe should have its volume increased. Try to make them sound the same volume at the same spot.

The light probe is the "smooth" one and the dark one sounds more like a "saw".

**Comment by samreid** [comment]
Reducing the saw tone by -19dB sounds like it makes them the same in the sim.  I'll commit this, then we will need to boost both sounds in the sim.

**Comment by samreid** [comment]
According to https://www.silisoftware.com/tools/db.php this corresponds to a 8.912509381337454x increase in amplitude, so I'll multiply that accordingly.

**Comment by samreid** [comment]
OK I've boosted the light probe by 19dB=8.9 amplitude, and it sounds well-matched to me.  I published a dev version here:
https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.21/phet/waves-intro_en_phet.html

@Ashton-Morris @arouinfar @ariel-phet can you please test this version and report on the wave meter probe normalization?

**Comment by arouinfar** [comment]
I tested with headphones at 50% volume and I found the light probe to be very overpowering. I experimented with the multiplier locally, and something like 1.2 sounds better to me.

**Comment by samreid** [comment]
Does the light probe sound the same volume as the dark probe?  If not, how much louder would you say it is?  Are you saying that the light probe should be reduced from 8.9 to 1.2, leaving the dark probe the same volume?

**Comment by samreid** [comment]
On my Macbook Pro speakers, they sound well-balanced, but using my external speakers it sounds like the light probe is 40-60% louder than the dark probe.

**Comment by samreid** [comment]
Let's take the following steps:

1. re-balance the light probe using my external speakers
2. add a query parameter for adjusting its volume
3. share a dev version with the waves intro sonification team and find the best tuning for that parameter.

**Comment by arouinfar** [comment]
> Does the light probe sound the same volume as the dark probe? If not, how much louder would you say it is? 

No, not at all. The light probe sounds significantly louder to the point that I really cannot bear to listen to it if it is close to the source. (Testing with headphones, volume 50%.)

The probes sound fairly balanced to me in this configuration, despite the amplitudes being very different.
![image](https://user-images.githubusercontent.com/8419308/83426906-1bf77400-a3ed-11ea-90ed-c4697fb3bc2e.png)

> Are you saying that the light probe should be reduced from 8.9 to 1.2, leaving the dark probe the same volume?

I changed the multiplier introduced in https://github.com/phetsims/wave-interference/commit/1d6d1cea4f016472c23306fcfafc3bd71a04db70 to 1.2. If I understand things correctly, it only affects the lighter probe. The dark probe sounds appropriate to me.

> Let's take the following steps

Sounds like a good plan @samreid. I'll unassign myself for now.

**Comment by samreid** [comment]
Here's a dev version with the rebalanced value of 0.42:

https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.22/phet/waves-intro_en_phet.html?lightProbeVolumeAmplitude=0.42

Please test and let me know what value you recommend.

**Comment by samreid** [comment]
> I changed the multiplier introduced in 1d6d1ce to 1.2. If I understand things correctly, it only affects the lighter probe. 

That value in the code is applied to both dark and light probes.

**Comment by Ashton-Morris** [comment]
I feel like the volume levels of the meter reader sound balanced

**Comment by arouinfar** [comment]
@samreid the rebalanced version sounds much better to me.

**Comment by samreid** [comment]
Thanks, I removed the query parameter.  Closing.
