### ISSUE TITLE
The water drops should be quieter and "ducked" when the wave detector is playing

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#488]
From today's meeting:  The water drops should be quieter and "ducked" when the wave detector is playing.  Also, make it easy to adjust these levels because @Ashton-Morris will likely need to fine-tune everything as part of overall normalization, see #473

**Comment by samreid** [comment]
Fixed in the commit, @kathy-phet can you please review on phettest and close if all is well?

**Comment by emily-phet** [comment]
I checked that the water droplets "duck" when wave meter tool active. It does so. Exact sound level adjustments in progress, with multiple sound-level issues open on that. Closing this issue, as I think the central point of it was to get the water droplet sound to duck.
