### ISSUE TITLE
Are we moving the toolbox?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#49]
A note from a prior meeting said:

> Wait to hear from Amy about moving continuous/pulse toolbox, etc. Proposed to: Move toolbox below the lower-left corner of the sim. Pulse/Continuous waves screen only.

Here is a subsequent slack conversation:

> Sam Reid [9:25 AM]
> Hi Amy, I have notes from a while back that say we were considering (a) to move the toolbox to the lower left of the sim, and (b) the “Pulse/Continuous” buttons would be on the wave screen only.  Are we still doing those?  Once we’ve eliminated the “slit position” slider, there will be more room on the right so maybe there is no longer a need to move the toolbox?  Also, it would be a little extra work to implement “pulse” for the plane wave, so I wanted to confirm whether we want that or not.
> 
> Amy Rouinfar [9:31 AM]
> (a) and (b) are correct, but I hadn’t had a chance to update the mockups. However, I agree that after removing the barrier location slider, there will definitely be more room for the toolbox. (edited)
Today I’m pretty busy with the candidate and other design meetings, but I plan to spend time updating Wave Interference next Monday.
>
> Sam Reid [9:38 AM]
> Got it, thanks!
> 
> Amy Rouinfar [9:38 AM]
> I’ll ping you when I update the doc

In my opinion, now that we've removed the "slit position" slider, there is enough room to leave the toolbox at the top right for all screens.  Reassigned to @arouinfar to decide on a plan.

**Comment by arouinfar** [comment]
@samreid I'm still in the process of cleaning up the mockups (will update design doc this afternoon), but the toolbox will remain in the upper right corner.
