### ISSUE TITLE
Sound: Edit Wave Meter A to have less harmonics or high end

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/wave-interference#493]
How does this sound @emily-phet 

[How does this sound?](https://drive.google.com/open?id=1L0B7lulOb-il90hgrF5Cik4d0856-U-C)

[This is the current one](https://drive.google.com/open?id=1KiER01uHQ1ksaWc0rPO2AxMoCvJGYuzp)

**Comment by emily-phet** [comment]
@Ashton-Morris - Yes, this is an improvement! Let's go with this one, but have it as the sound for the "second" wave meter (dark grey, I think).

**Comment by Ashton-Morris** [comment]
@samreid Can you replace the current wave meter sound with this one above.

**Comment by emily-phet** [comment]
@samreid - and swap the sounds played for the wave probes.

**Comment by samreid** [comment]
I switched to the "less harmonics" sound and swapped the probe sounds.  @emily-phet and @Ashton-Morris please review.

**Comment by emily-phet** [comment]
Sounds great!
