### ISSUE TITLE
wave meter colors - better contrast

### ISSUE THREAD

**Issue by michAtEl** [phetsims/wave-interference#494]
Hi,

I captured a video with the simulation wave-interference. Unfortunately, I could not see the light gray plot in the wave meter because there is not enough contrast between the background (white) and the plot (light grey). I would prefer colors like red and dark grey for the meters and the plots.
I think this could also be an issue when you are using this simulation with a projector.

Michael

**Comment by arouinfar** [comment]
Thanks @michAtEl. We will be handling this request in #498. Closing.
