### ISSUE TITLE
Gain being set quite high for light beam sound effect

### ISSUE THREAD

**Issue by jbphet** [phetsims/wave-interference#495]
While investigating some odd sound behavior seen in this sim (see https://github.com/phetsims/tambo/issues/74), I noticed that the gain level for `lightBeamLoopSoundClip` is being set from 0 to 2.5.  Unless the sound source is known to be very quiet, this is a bit risky, since it can result in peak sound levels that exceed 1 dBFS, which can cause clipping on some systems.  I would suggest keeping gain settings between 0 and 1.  If the sound file is particularly quiet, it can be amplified.  We generally try to set sound files to have a peak value of -1 dBFS.

**Comment by samreid** [comment]
I normalized the mp3 in audacity, then recalibrated the gain level accordingly.  @jbphet would you like to review?

**Comment by jbphet** [comment]
Looks great, thanks.  Closing.
