### ISSUE TITLE
No pointer area box on "Sound Effect" button, seems inconsistent with other buttons having pointer area boxes

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/wave-interference#501]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v.1903

**Browser**

Chrome Version 86.0.4240.75

**Problem description**

For https://github.com/phetsims/QA/issues/511

There is no pointer area box on the Sound Effect button in the Light screen. This seems inconsistent with other pointer area boxes on other screens, which include Play Tone specifically on the Sound screen.

**Steps to reproduce**

1. Add ?showPointerAreas query parameter
2. Navigate to Light screen

**Visuals**

![2020-10-14WavesIntroShowPointerAreaSoundEffect](https://user-images.githubusercontent.com/54685448/96040980-5dcb0900-0e28-11eb-9328-90e42637144e.PNG)

<details><summary><b>Sound Screen for comparison</b> </summary>

![2020-10-14WavesIntroShowPointerAreaPlayTone](https://user-images.githubusercontent.com/54685448/96041254-c1553680-0e28-11eb-8fc6-018b9b56ee0f.PNG)

</details>

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.24/phet/waves-intro_all_phet.html?showPointerAreas
Version: 1.1.0-dev.24 2020-10-13 16:44:23 UTC
Features missing: applicationcache, generatedcontent, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Language: en-US
Window: 1536x754
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
I centralized the pointer area code and applied it to the light sound effect checkbox, @loganbraywork or @arouinfar please review and close if all is well.

**Comment by arouinfar** [comment]
👍
