### ISSUE TITLE
Speaker flashes when first used on Firefox

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/wave-interference#502]
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v.1903

**Browser**

Firefox 81.0.2 (64-bit)

**Problem description**

For https://github.com/phetsims/QA/issues/511

On the Sound Screen, when the Speaker is activated for the first time it flashes white. This seems to only occur in Firefox, and only on the first use of the Speaker in the sim. 

**Steps to reproduce**

1. Refresh the page if the Speaker had already been used
2. Interact with the Speaker
3. Refresh page and repeat to view again

**Visuals**

![2020-10-14WavesIntroFlashingSpeakerFirefox](https://user-images.githubusercontent.com/54685448/96047677-b99a8f80-0e32-11eb-8acf-ccaada6cacd4.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.24/phet/waves-intro_all_phet.html
Version: 1.1.0-dev.24 2020-10-13 16:44:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Language: en-US
Window: 1536x750
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
I was not able to reproduce this problem on macOS 10.15.7 running Firefox 82.0.2 (64-bit) and https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.24/phet/waves-intro_all_phet.html

**Comment by samreid** [comment]
Testing on Windows 10 Home 19041.572 running Firefox 82.0.1 I see a delayed appearance, then rapid flickering on first use.  After updating to 82.0.2, I see rapid flickering on first use.

**Comment by samreid** [comment]
@jonathanolson recommended testing with `renderer: 'canvas'` and that seems to be working well and without side-effects.  I published a dev version here which can be used for testing: https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.25/phet/waves-intro_en_phet.html

@loganbraywork can you please test in dev.25?  Close if all is well.

**Comment by loganbraywork** [comment]
Seems fixed, was not able to reproduce in https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.25/phet/waves-intro_en_phet.html
