### ISSUE TITLE
Waves no longer appear properly at high frequencies

### ISSUE THREAD

**Issue by DevonQui** [phetsims/wave-interference#503]
**Test device**
MacBook Pro

**Operating System**
Catalina 10.15.1

**Browser**
Safari

**Problem description**
This is for https://github.com/phetsims/QA/issues/511
For the light and sound wave simulations, the waves will begin to stick together at the wave origin when the wave frequency is high. Fortunately, I was unable to produce this in the Water Wave simulation although the visuals might be considered a little strange at high frequencies. 

**Steps to reproduce**
1. Open the simulation
2. Click on the Sound (or Light) section of the simulation
3. Make sure you have the automatic wave generator on (left-side right underneath the wave generator)
4. Click on the green button on the wave generator to get the waves started
5. Begin to repeatedly and quickly click the green button and observe how the waves stick together at the origin.

**Visuals**
https://drive.google.com/file/d/1PUQCvshi46zIAjvQEtjLT1aZqZA0GVOr/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.1.0-dev.24/phet/waves-intro_all_phet.html
Version: 1.1.0-dev.24 2020-10-13 16:44:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Language: en-US
Window: 1260x720
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Noting that this happens in the published sim as well. It also only happens from using the continuous wave setting, as the pulse button is disabled when pressed until a full wave has been created.

**Comment by samreid** [comment]
I believe we discussed this problem as part of https://github.com/phetsims/wave-interference/issues/316#issuecomment-454458763 and were aware that it was a disadvantage of the temporal masking approach.  @arouinfar or @ariel-phet do you have a clearer recollection?  How do you wish to proceed?

**Comment by arouinfar** [comment]
If I remember correctly, the temporal masking was introduced to smooth out the graph data, intensity plot, and wave meter plots. Some concessions had to be made for reasonable performance for typically lower-performing devices. If the behavior is only present during interactions that are not pedagogically useful, such as rapidly scrubbing sliders or mashing the on/off button, then it's not an issue.

**Comment by ariel-phet** [comment]
@DevonQui thanks for identifying this issue, but yes, considering the compromises we have had to make for the sim to function well, coupled with this behavior not being pedagogically useful we will close as `wontfix`
