### ISSUE TITLE
Minor regression in pulse icon RoundButton size

### ISSUE THREAD

**Issue by zepumph** [phetsims/wave-interference#505]
Over in https://github.com/phetsims/sun/issues/657, RoundButton began to scale down its content when the specified radius option couldn't support it. I was able to cover every case I found expect for in wave interference.  When you swap scene selection buttons, an icon appears on the laser/faucet that looks like a pulse or a wave of some sort. That is slightly smaller since __.

@samreid would you please take a look. It is very small, but it is a change in a sim that I am not responsible for. Just a bit smaller on master now. 

Before:
![image](https://user-images.githubusercontent.com/6856943/97520978-6277dd00-1951-11eb-9cc4-9b7200274aa0.png)

Now:
![image](https://user-images.githubusercontent.com/6856943/97520973-60158300-1951-11eb-8562-30fe0c43bd97.png)

**Comment by samreid** [comment]
This seems OK to me, thanks!  Closing.
