### ISSUE TITLE
TimeControlNode changes?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#506]
From https://github.com/phetsims/QA/issues/572#issuecomment-719880346.  It's unlikely that this is related to sun button changes, and more likely related to changes to TimeControlNode.

@ariel-phet noted that TimeControlNode layout and sizing differs between published and master. If this is a know (or acceptable) regression, that's fine.

Wave Interference published (2.0.2):
![WI-published](https://user-images.githubusercontent.com/4051174/97770961-bcb5a100-1afd-11eb-8b64-2347365296b8.PNG)

Wave Interference master:
![WI-mater](https://user-images.githubusercontent.com/4051174/97770962-c17a5500-1afd-11eb-9753-355a1c1d573b.PNG)

@ariel-phet said:
> As you can see the spacing between the play and step button has changed, and the radio buttons have grown a bit larger in comparison to the text, to my eye the step button is also slightly smaller. Not sure if some of this is sim specific or not

The change in "look" of disabled buttons is OK for now. It's due to sun buttons now using opacity instead of grayscale to denote "disabled".

**Comment by samreid** [comment]
This change is likely due to conversion to use TimeControlNode (and its defaults).  That seems reasonable to me, but please reopen if changes are recommended.
