### ISSUE TITLE
Publish Waves Intro with Sonification and Basic Keyboard Support

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#509]
Issue for milestone https://github.com/phetsims/wave-interference/milestone/1

**Comment by samreid** [comment]
I linked the QA issue above

**Comment by samreid** [comment]
I cherry picked the fixes for
https://github.com/phetsims/wave-interference/issues/510
https://github.com/phetsims/wave-interference/issues/516
https://github.com/phetsims/wave-interference/issues/513

**Comment by samreid** [comment]
RC.4 completed indicating all known issues resolved and no new issues discovered.  I'll proceed with publication.

**Comment by samreid** [comment]
I published the production version of 1.1.0 on the main site: https://phet.colorado.edu/en/simulation/waves-intro

@arouinfar or @emily-phet do we need to update the description or other metadata?

**Comment by arouinfar** [comment]
I tagged the sim with Sound & Sonification and @BLFiedler uploaded the Sound Features video. I don't think there's any other metadata that needs to be updated, so closing.
