### ISSUE TITLE
iPad sim crashes and restarts

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-interference#515]
For https://github.com/phetsims/QA/issues/580.
On iPad 6th gen, iPadOS 14.3 Safari, the Waves Intro sim crashed and reloaded after several minutes of use. The sim had the `?stringTest= rtl` and it happened on the sound screen when switching to the particle view. This sort of thing was more common with older iOS and older devices, but hasn't happened on up-to-date devices often. I only saw it once while testing.

**Comment by samreid** [comment]
I fuzzed "manually" on the iPad 7 for 80 seconds and did not see any problems. I turned on ?fuzz on the iPad and it ran for 3 minutes without crashing.  Perhaps we should consider this a "sighting" and reopen if we hear more reports of this problem.  Closing.
