### ISSUE TITLE
The wave inspector tool handles long strings differently now too, and it looks a bit odd

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#516]
From https://github.com/phetsims/wave-interference/issues/513#issuecomment-759611876

I also noticed that the wave inspector tool handles long strings differently now too, and it looks a bit odd.
Now:
<img width="321" alt="nowview" src="https://user-images.githubusercontent.com/41024075/104489284-afe90b00-558c-11eb-8b2b-3fad2fdef2c3.png">
Published:
<img width="227" alt="thenview" src="https://user-images.githubusercontent.com/41024075/104489303-b4adbf00-558c-11eb-940d-20a3d45b91da.png">

**Comment by samreid** [comment]
Proposed fix pushed to master.  If it seems good, please reassign to me and I'll cherry pick into the release branch.

**Comment by KatieWoe** [comment]
Tool looks good on master.

**Comment by samreid** [comment]
OK I'll mark as ready for QA for testing in the next RC, as a reminder to cherry-pick.

**Comment by KatieWoe** [comment]
looks good in rc.4
