### ISSUE TITLE
Sliders slightly misaligned with long strings

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/wave-interference#517]
### Test Device

MacBook Air

### Operating System

macOS 11.2

### Browser

Safari 14.0.3

### Problem Description

For https://github.com/phetsims/QA/issues/603. While verifying https://github.com/phetsims/wave-interference/issues/513, I noticed that the alignment of the sliders is ever so slightly off with long strings. See screenshots. Only documenting because QA policy is to over-document, not under-document.

### Screenshots

Reasonably aligned:
![reasonably-aligned](https://user-images.githubusercontent.com/60749003/107832230-22483900-6d4d-11eb-9ec2-d503e2c89403.png)

Misaligned:
![misaligned](https://user-images.githubusercontent.com/60749003/107832250-2d9b6480-6d4d-11eb-8020-295cae775760.png)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.1.0-rc.4/phet/waves-intro_all_phet.html
Version: 1.1.0-rc.4 2021-01-30 00:05:35 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
Language: en-us
Window: 1440x820
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by samreid** [comment]
Thanks for the report @liam-mulhall, this problem is akin to https://github.com/phetsims/wave-interference/issues/433 and will likely be dealt with in the same way--that is, with a long term solution in https://github.com/phetsims/sun/issues/48, closing.
