### ISSUE TITLE
No sound when clicking on a slider track

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#519]
Noted while working on https://github.com/phetsims/fourier-making-waves/issues/56.

Sounds occur when dragging the slider.  But there is no sound when you click on the track.  And that's a standard feature of Slider.   Is this an oversight?

**Comment by arouinfar** [comment]
As of https://github.com/phetsims/sun/issues/697, sliders now have an API for sounds. Clicking on the slider track produces a sound, so closing.
