### ISSUE TITLE
Misleading "click" naming in WaveInterferenceSlider.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#520]
Noted while working on phetsims/fourier-making-waves#56, because I was told to use WaveInterferenceSlider.js as an example.

In WaveInterferenceSlider.js

```js
const MIN_INTER_CLICK_TIME = ( 1 / 60 * 1000 ) * 2; // min time between clicks, in milliseconds, empirically determined
...
    // Keep track of the last time a sound was played so that we don't play too often
    let timeOfLastClick = 0;
```

Naming is really confusing here. If this did have something to do with "clicks", it would be better to call it "press", because click is mouse specific.  And in fact it has nothing to do with click or press.  It's the time between drag events. 

Consider renaming for the benefit of future readers/maintainers.

**Comment by samreid** [comment]
I believe the clicks refer to the clicking sound that is made as you move across the slider tick marks.  I'll update the documentation accordingly.

**Comment by samreid** [comment]
I updated the documentation, but couldn't think of a superior variable name.  @pixelzoom what do you recommend?

**Comment by pixelzoom** [comment]
Doc in https://github.com/phetsims/wave-interference/commit/409e3b5d3fbdad8971308284a0074a4961f0e42e looks OK.

 https://github.com/phetsims/ratio-and-proportion/commit/e0bf77f4b61941340b6a84dc9e54d7e7ac93020e looks unrelated to this issue, probably an accidental commit.

Closing.

**Comment by samreid** [comment]
In https://github.com/phetsims/ratio-and-proportion/commit/e0bf77f4b61941340b6a84dc9e54d7e7ac93020e I noticed a copy/pasted version of the bad documentation, so I updated it at the same time.
