### ISSUE TITLE
Value for MIN_INTER_CLICK_TIME

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#522]
In WaveInterferenceSlider.js:

```
const MIN_INTER_CLICK_TIME = ( 1 / 60 * 1000 ) * 2; // min time between clicking sounds, in milliseconds, empirically determined
```

Consider reducing this to a value.  Or at least explain the 4 magic numbers that you're using.

**Comment by samreid** [comment]
I simplified the constants, closing.
