### ISSUE TITLE
in-sim credit and the sim-page credit do not match.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/wave-interference#525]
In https://github.com/phetsims/fourier-making-waves/issues/208#issuecomment-942776878, @kathy-phet said:

> @arouinfar - I noticed that the in-sim credit and the sim-page credit for Wave Interference are different. Do you recall why?

**Comment by samreid** [comment]
I fixed it in master, but the shas are too old to cherry pick automatically (merge conflicts), so I'll do manual commits instead.

**Comment by arouinfar** [comment]
@samreid looks good in the RC's.

**Comment by arouinfar** [comment]
This was blocked by a character limit in the "Thanks to" field, but it was expanded in https://github.com/phetsims/website/issues/1280. The full text is now up on the wave-interference and waves-intro sim pages.
