### ISSUE TITLE
Should we remove the "Amplitude" Slider from the Interference and Slits screens?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#56]
At this week's meeting, it was proposed that we remove the "Amplitude" Slider from the Interference and Slits screens, but leave it on the first (Waves) screen.

We can get to the learning goals about what amplitude means on the first screen, but it doesn't seem too valuable to turn down the amplitude on the 2nd and 3rd screens (essentially it makes it more difficult to see the diffraction patterns).

@kathy-phet what do you think?

**Comment by arouinfar** [comment]
@kathy-phet gave the okay to remove the Amplitude slider from the Interference and Slits screens.

**Comment by samreid** [comment]
Fixed, can you please take a look on phettest?

**Comment by arouinfar** [comment]
Looks good @samreid!
