### ISSUE TITLE
iOS: ObservableArray: duplicates are not allowed

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#57]
I got a rudimentary WebGL renderer for the lattice working and wanted to test it on iOS.  However, I'm receiving an error "duplicates are not allowed" on any touch event:

![image](https://user-images.githubusercontent.com/679486/40316974-3ba1f806-5cdd-11e8-9862-abc13cb31ad2.png)

Co-assigning to @jonathanolson in case he has seen something like this.

**Comment by samreid** [comment]
I commented out the part of ObservableArray that errors on a duplicate item, and it seems to be working OK.

**Comment by jonathanolson** [comment]
Looks like I likely broke touch interaction in Scenery. I'll investigate and figure it out.

**Comment by samreid** [comment]
Pulled and tested built version on iPad2, seems to be working now, thanks @jonathanolson, closing.
