### ISSUE TITLE
Would it be better to use an analytical model?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#59]
In discussion with @jonathanolson yesterday, we realized that it may be possible to code an analytical model (as opposed to the discrete lattice-based approximation we used in Java and have been using until now in JS).  For instance, given the single point source and and its amplitude values as a function of time, you can compute the wave value at every point in space at a given time, without needing to approximate the wave equation on a time-evolved discrete lattice.  For multiple point sources, the value at any point at any time is the sum of contributions from the sources.  The incoming plane wave is already somewhat "analytical" in that we are setting its value based on position and time.  It is unclear to me how to model the slits--perhaps an array of in-phase point sources in each slit (Huygen's principle)?

Currently we support a large damping region and around the border of the lattice in order to minimize reflections at the edge for the lattice-based approach.  An analytical model would inherently avoid any border reflections without any additional effort.  The diffraction patterns would be clearer and less noisy.

Also, an analytical model would simplify a messy part of the simulation that requires us to map back and forth between the physical coordinate frame and the lattice coordinate frame.

We haven't planned for this in the design, but using an analytical model would make it trivial to show how wave sources sum to create the net wave (in the graphs).

An analytical model may only be possible now because of simplifications we've made in the sim design, for instance, if we had barrier at an angle, or barriers that users could move and create reflections dynamically, we would need to use an "emergent" model, but as far as I know all of the features we have designed for support for this version of Wave Interference *may* be able to use an analytical solution.

Questions:
* How fast can we run the analytical model, and at what resolution?  
* Will we run it in WebGL for showing the wave at a high resolution, and in JS for getting values for the charts?  (In #3 @jonathanolson and I explored faster approaches for reading values from WebGL textures.)

@jonathanolson recommended that we discuss the approach with someone more familiar with this area of physics.  I'll tag @arouinfar @ariel-phet and @kathy-phet for discussion, but it may also be valuable to discuss with Mike Dubson--or maybe we should reach out to others with expertise in this area?

Also tagging @jonathanolson to review this description and correct/add anything I've missed.

**Comment by kathy-phet** [comment]
Thanks for the brainstorming,Sam. The slits seem tricky and problematic because they are dynamic in width and location and because they are only point sources in one direction.

Can you please clarify is there an outward facing issue you are trying to address with this approach? Is it the iPad 2 performance? Do you expect this to be more performant? Is there a blocking issue with the current approach that came up?

Sent from my iPhone

On May 26, 2018, at 7:21 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #59<https://github.com/phetsims/wave-interference/issues/59> to @kathy-phet<https://github.com/kathy-phet>.

**Comment by samreid** [comment]
> The slits seem tricky and problematic because they are dynamic in width and location and because they are only point sources in one direction.

We could use logic like "if x < slitLocation.x then planeWave else analyticalModel".  We also clear the wave when the slits move, so that simplifies things.  We could also simplify things by clearing the wave when the slits resize (though it could be possible to capture slit width as a function of time in the analytical model).

> Can you please clarify is there an outward facing issue you are trying to address with this approach? Is it the iPad 2 performance? Do you expect this to be more performant? Is there a blocking issue with the current approach that came up?

The lattice model worked acceptably for Java and it will work equally well in JS.  We originally identified the analytical model as a performance improvement, then realized it would also eliminate reflections/noise at the edges.  It will also yield smoother (less noisy) charts and interference patterns.  Depending on what resolution we can attain, it could yield a smoother wave view as well. 
 Currently, the wave looks like this (for the interpolated WebGL version)
![image](https://user-images.githubusercontent.com/679486/40577195-be4c2120-60be-11e8-9157-7dc29740cfe4.png)

Also, I haven't checked that d sin (theta) = m lambda for the lattice model--hopefully it checks out (and we are not in a near field approximation or have other issues preventing that), but the analytical model would be more likely to yield this pattern.

Internally, it would simplify the logic that requires us to map back and forth between physical coordinate frames and abstract lattice frames.  It is unclear how much performance benefit we may attain with this approach--but we know we will be able to avoid a lot of work that is being done on the lattice in attempt to minimize reflections near the edges.

There is no blocking issue with the existing lattice-based approach, and @jonathanolson and I identified many possibilities for improving its performance and are planning to proceed with that.  However, we wanted to identify if the analytical model would be superior to the lattice-based approach for the life of the sim.

**Comment by samreid** [comment]
In my opinion, a prototype + profiling will be the best way to understand how fast we could run the analytical model--but before going to that step we should discuss if there are any physics reasons we know that *won't* work or is not worth investigation.

**Comment by kathy-phet** [comment]
Mike and Martin are you best first sources on thinking about the physics issues of this approach.

Sent from my iPhone

On May 26, 2018, at 8:42 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


In my opinion, a prototype + profiling will be the best way to understand how fast we could run the analytical model--but before going to that step we should discuss if there are any physics reasons we know that won't work or is not worth investigation.

**Comment by samreid** [comment]
I sent email to Mike and Martin along these lines:

We are struggling with a problem in the development of our "Wave Interference" simulation we thought you could help with.  For reference, here is the Java version:
https://phet.colorado.edu/en/simulation/wave-interference

And the latest development version of the HTML5 port:
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.12/phet/wave-interference_en_phet.html

Until now, we have been using the discrete 2d wave equation like described here: http://www.mtnmath.com/whatth/node47.html which amounts to updating cells on a lattice according to:
f(x,y,t+1) = v^2(f(x+1,y,t) + f(x-1,y,t) + f(x,y+1,t) + f(x,y-1,t) -4f(x,y,t)) - f(x,y,t-1) + 2f(x,y,t)

We also have hacks like an overall damping term and extra cells around the edge of the lattice in order to damp reflections near the edges (to simulate an infinite pool) and minimize noise.

We are wondering what you think about moving to an analytical model (not based on local neighbors in the lattice), where we compute the wave value at a given point f(x,y,t) as a function of the emitters. For instance, in the case of a single emitter and wave speed v, we would have something like f(x,y,t) = g(t-v/d) where g is a function only of the emitter (amplitude, phase, frequency) and d is the distance from x,y to the emitter.  For multiple emitters, it would be something like f(x,y,t) = g(t-v/d1) + g(t-v/d2) + ...

The hope is that this approach will give us better performance/resolution and more control over dealing with reflections, noise and decay (both in the wave area and in the charts and readouts).

We wanted to discuss it with you before going any further:

1. Does this approach sound feasible for our simulation?  Would it be preferable to the lattice-based approach?
2. How will we model the slits?  Would it work to approximate an array of point sources over the face of the slits?  Or is there a more principled way to compute that part (an integral)?  Note that in the HTML5 version we model the incoming wave as a plane wave rather than a point source--we could use one model to the left of the slits and another model to the right of the slits.

**Comment by samreid** [comment]
See parent issue https://github.com/phetsims/wave-interference/issues/60

**Comment by arouinfar** [comment]
@samreid once you hear back from Mike and Martin, it would be good to discuss this in design meeting (unless you decide not to move forward with an analytical model). Unassigning myself for now.

**Comment by samreid** [comment]
Some notes from @veillette on slack:

Martin Veillette [1:18 PM]
Hello Sam, I received your email about wave-interference.

Sam Reid [1:19 PM]
Hi there!
Good to see you on slack!


Martin Veillette [1:20 PM]
I'm still mulling over my response. The approach you suggested would work very well on Waves and Interference screens. It would have the advantage that you can choose your discretizing unit scale differently for the graph and the canvas.

Martin Veillette [1:26 PM]
The only worry then is the Slits screen and I don't have an answer yet about the approach you suggested (namely approximating the face of the slits as an array of point sources). The question is then how many such point sources do you need, and I need a bit more time to give you the answer. I can check it in mathematica to see how many points is "good enough".

Sam Reid [1:26 PM]
Can we integrate over the aperture?

Martin Veillette [1:26 PM]
No
You could integrate over the aperture and then add up these results for multiple slits, that would give you a good result but only in the far regime, that is the Fraunhofer limit.
The far regime is when the screen is very far away from the slits.

Sam Reid [1:30 PM]
understood

Martin Veillette [1:31 PM]
The near-field diffraction, is called Fresnel diffraction and the math is nasty and not analytical. You would need the near field result for the canvas field.
But if you do want to show the results for screen intensity (in Slits Tab)  the result of summing two slits in the Fraunhofer limit would work very well.

Sam Reid [1:36 PM]
To me, it’s important that the wave area and slits view (and charts) are perfectly in sync.  So I would want to use the same model for both.
(For instance, I wouldn’t use neighbor-based propagation in the wave area, then analytical model for screen pattern). (edited)

Martin Veillette [1:38 PM]
Yes I agree with you that you would want only one model. For your information, the litmus test of the approach you suggested will be if you can reproduce the same result for a very wide slit at very high frequency.

Sam Reid [1:38 PM]
Would it help us if we could limit the slit width to be something like 2x wavelength?

Martin Veillette [1:39 PM]
For the calculation, yes, but as an educator, I would prefer if you do not.

Sam Reid [1:42 PM]
That makes sense, should I wait for you to test in Mathematica?
If we can run it in the GPU, then we may be able to sum many points over the aperture
Also, if you look at the animated GIF on https://en.wikipedia.org/wiki/Huygens%E2%80%93Fresnel_principle notice how the amplitude fades out as theta goes from 0 to 90 degrees.  How do we model that?

Martin Veillette [1:52 PM]
That would come out automatically by the destructive interference of multiple point sources. Not that the effect is more prominent when the width of the slits is large with respect to the wavelength. No special math tricks though.

Sam Reid [1:52 PM]
Ah, I see

Martin Veillette [1:52 PM]
I'll make sure to model this behavior as well.

Sam Reid [1:53 PM]
Did you mean “not that” or “note that”?

Martin Veillette [1:53 PM]
Note that

Sam Reid [1:53 PM]
Great, thanks

Martin Veillette [1:54 PM]
I'll try these edge cases in Mathematica and try to find the number of sources needed to get to a  10% and 1% accuracy.

Sam Reid [1:55 PM]
Good luck and keep me posted!  I’m going to archive this conversation on https://github.com/phetsims/wave-interference/issues/59 (edited)

**Comment by veillette** [comment]
I look at modeling the wave interference as a superposition of wavelets, all of them equally spaced across a slit.  To prototype it, I used mathematica to easily calculate the intensity profile by summing over a finite number of point sources.  
We know that if we have an infinite number of wavelet sources across the slits, this should reproduced faithfully the underlying physics. The question is then to find out what is the minimum number of needed sources for a given accuracy.  

The answer is many. 

Since the wavelength sets the scale of the waves, the rule of thumb that the separation between the sources, $\Deltax$ should be only a fraction of the wavelength, $ \Deltax= \lambda /N$ where $N$ is positive number.  So for a slit of width D, the number of sources needed be D*N/\lambda.

It turns out that if we want an accuracy of about 1% than we need N to be about 500. 
Essentially, for a point are far away for the sources, the amplitude contributions of each source point is positive, negative, etc, ,so that the converge is poor. .   

And even 1% is not necessarily a good job since the equidistant separation  of the sources lead to an artifact where the sources interference destructively or constructively due to the evenness of their separation. This leads to a small ripple in the intensity profile that is present even for the untrained eye.

I'll post picture of the mathematica simulation.

**Comment by veillette** [comment]
```
omega = 1; 
lambda = 1;
stepNumber = 100;
a = 2;

F[x_, y_, x0_, y0_, t_] := 
 Cos[2*Pi*Sqrt[(x - x0)^2 + (y - y0)^2]/lambda - omega* t]/
  Sqrt[(x - x0)^2 + (y - y0)^2]

A = DensityPlot[
  Sum[F[x, y, 0, y0, 0], {y0, -a, a, lambda/stepNumber }], {x, 0, 
   20}, {y, -10, 10}, PlotPoints -> 30, Mesh -> 20]

```
stepNumber is the number of sources per unit wavelength. In this case the single slit goes from y=-a=-2 to y=a=2. The wavelength is 1 and there are 400 sources. 
![image](https://user-images.githubusercontent.com/7633344/40863734-eb526a08-65be-11e8-9c54-2300d6681dc9.png)

Although it looks superficially good ( Mathematica color scheme renders the high intensity white.) it becomes apparent that what should be a simple diffraction from a single slit contains additional additional interference component.   

For instance at a distance x=10 and plotting amplitude from -20 to 20 shows:

![image](https://user-images.githubusercontent.com/7633344/40864382-9a1c1d66-65c1-11e8-9f1b-23bc85a3f987.png)

 The approximation is very inadequate. and shows this additional ripples, (truthfully, we are not in the farwaway regime yet so the predicted model doesn't quite apply, nevertheless it shows that this is a non starter.

**Comment by kathy-phet** [comment]
Thanks for your evaluation, Martin!

**Comment by samreid** [comment]
Martin, thanks for taking a careful look at this.  I just want to verify one thing before closing the issue--I can see the discrepancy between the N=400 analytical model and the true model, but I want to confirm that the discrete wave equation/lattice strategy is better.

**Comment by samreid** [comment]
We'll move forward with the lattice solution for now, closing.
