### ISSUE TITLE
Add single/double slit and controls

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#6]
@ariel-phet said:

> I think there are some features you could certainly continue adding that will clearly be included like a single and double slit with adjustable parameters. 

Do you imagine scene selection buttons to choose between none/single/double slits?  Then sliders to adjust the spacing/width?  Or will we have grab handles on the apertures to manipulate them directly?

**Comment by ariel-phet** [comment]
I think we had basically decided the 3 initial screens would be something like "single source" "Double source" "Slits" so, yes, on the "slits" screen I would imagine single and double slit scene selection. I don't see none as a useful option to begin with. 

My instinct for slits controls would be sliders (as in the original sim) for 2 main reasons:
1. Likely better for occlusion
2. the scale of the size of the slits and separation is important, so having a readout of the parameters is helpful, sliders do a nice job as acting as both a readout and control, and allow nice quick exploration.

**Comment by ariel-phet** [comment]
@arouinfar thoughts on the above?

**Comment by arouinfar** [comment]
Agreed with @ariel-phet -- we'll likely break the screens into single source, double source, and slits. However, we've also discussed the possibility of each screen having three scenes, one for each context (water, sound, light). I don't think that single slit and double slit would technically be scenes, but they should behave like radio options. We don't need a "none" option for slits, since the first two screens would act as "none". 

I also prefer slider controls for controlling the slit width and separation for the reasons @ariel-phet has outlined.

**Comment by samreid** [comment]
What should the screens be named?

https://github.com/phetsims/wave-interference/issues/6#issuecomment-335927164 suggested: 

**"single source" "Double source" "Slits"**

Some other possibilities:
**"Waves" "Interference" "Double Slit"**
**"Intro" "Two Waves" "Two Slits"**
**"One Source" "Two Sources" "Slits"**

I can always change names later but it is good to take a "best guess" as I am starting out.  @arouinfar and @ariel-phet thoughts?

**Comment by arouinfar** [comment]
Great suggestions @samreid! I really like
1. Waves 
2. Interference
3. Slits 
4. Diffraction

I think "Waves" and "Interference" both sound exciting while being descriptive. The first screen serves as an introduction to waves and wave properties. The 2nd screen will be the first introduction to interference (unless we allow the wall on the 1st screen). "Slits" is more inclusive of both single-slit and double-slit interference, so I prefer it over "Double Slit" or "Two Slits".

**Comment by ariel-phet** [comment]
I like that order - Waves, Interference, Slits, Diffraction

**Comment by samreid** [comment]
We've designed screen order and controls in the Slits screens, closing.
