### ISSUE TITLE
Optimize the Canvas View

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#61]
From #60: Work on optimizing canvas view (based on putImageData and no allocations, no blend, no color allocations).  See Charges and Fields for an example of `putImageData`.

**Comment by samreid** [comment]
I implemented using `putImageData` but am unable to resize the CanvasNode.  `setScale` called from elsewhere seems to have no effect.  Will I need to create another internal canvas like `ElectricPotentialCanvasNode.directCanvas`?

**Comment by samreid** [comment]
I saw a huge amount of time in the profiler taken by the following:

![image](https://user-images.githubusercontent.com/679486/40628302-693927a4-6281-11e8-9f16-a4fa20faeeab.png)

Perhaps a bug in the profiler?  I haven't seen anything like this before, but I'm inclined to get rid of those setters and see what happens.

**Comment by samreid** [comment]
I commented out the setters and saw:
![image](https://user-images.githubusercontent.com/679486/40628350-bcbd9a86-6281-11e8-9ce3-84f9c1883ad6.png)

Does this mean it's spending a lot of time in this function, and not sure where to annotate it?

**Comment by samreid** [comment]
By scaling up the canvas, I get smoothing like this:

![image](https://user-images.githubusercontent.com/679486/40629200-d3b84466-6286-11e8-8107-4b90669bed5c.png)

In my opinion, better than the pixellated one but not quite as good as the WebGL interpolated one.

**Comment by samreid** [comment]
I pushed the optimized LatticeCanvasNode, @jonathanolson do you have time to skim the change set?

**Comment by samreid** [comment]
Fun fact: with this change, the iPad2 is running at 11fps (same speed as using WebGL renderer in prior test.)

**Comment by jonathanolson** [comment]
Changeset looks good to me.
