### ISSUE TITLE
Make sure no extra CPU/Memory is spent on Bounds calculations

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#63]
From #60: We probably need to put preventFit: true on the charts.  We may also in places need to extend Path and override computeShapeBounds to return a fixed bounds.  We will know this is working when we no longer see bounds time spent in the profiler.  This is closely related to #62

**Comment by samreid** [comment]
I put `preventFit: true` in Node.js, then built with `grunt --mangle=false` and still seeing entries like this in the profiler:

![image](https://user-images.githubusercontent.com/679486/40630651-7cc60e76-6291-11e8-9ce1-6e20da26a4b7.png)

@jonathanolson I could use your help or at least some more direction on this part.

**Comment by jonathanolson** [comment]
Hmm, it looks like you have a bounds listener that needs to get updated, so it's still forcing validation?

The Display.popupDebug() view should probably help figure out where your bounds listeners are, or you can track _boundsEventCount down the tree (checking locations that change). May want to check layout containers, etc.

**Comment by samreid** [comment]
I tried `popupDebug` and chrome reported 

> http://localhost/scenery/js/display/Display.js?bust=1527558946367:1523 Not allowed to navigate top frame to data URL: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Chtml%20lang%3D%22en%22%3E%3Chead%3E%3Ctitle%3EScenery%20Debug%20Snapshot%3C%2Ftitle%3E%3C%2Fhead%3E%3Cbody%20style%3D%22font-size%3A%2012px%3B%22%3E%3Cdiv%20style%3D%22font-weight%3A%20bold%3B%20font-size%3A%20120%25%3B%20margin-top%3A%205px%3B%22%3EDisplay%20Summary...

**Comment by samreid** [comment]
I console.logged the html and viewed it.  It has 122 occurrences of boundsListen.

**Comment by samreid** [comment]
After the above commit, validateBounds is down to 2% or so.  Pretty nice!  @jonathanolson can you review and see if I'm doing this correctly, and if there's anything else to do for this issue?

**Comment by jonathanolson** [comment]
Do you set the localBounds correctly later? Can you guarantee that those localBounds contain all of the actual bounds being drawn?

**Comment by samreid** [comment]
Re-self-assigning to remind me to reach out to @jonathanolson for discussion.

**Comment by samreid** [comment]
I leveraged the clip area bounds for the two dynamic charts and removed the bounds limitation for the other cases.  iPad Air is getting 60fps with all charts turned on.  This seems sufficient to close the issue, closing.
