### ISSUE TITLE
Switch to EventTimer for model steps.  

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#65]
From #60, we need to change the fixed time step of 1/60 to use EventTimer so it will run at the same speed on slow platforms.  Could leverage time/model interpolation if needed, but hopefully not!

**Comment by samreid** [comment]
I noticed when I changed the renderer from canvas to webgl in #48, the wavelength changed.  I did not expect this--it seems there was a bug somewhere.  Hopefully EventTimer would be a part of resolving this.

**Comment by samreid** [comment]
Commit pushed above, @jonathanolson am I barking up the right tree?

**Comment by samreid** [comment]
Running at 60Hz on the iPad2 drops the frame rate to 2fps, and there is a strobe effect for the wave (looks like it is going backwards).

**Comment by samreid** [comment]
Putting the rate to 20Hz gets the wave speed to match between desktop chrome and iPad2, even though the iPad2 is only getting 10fps.

**Comment by samreid** [comment]
@jonathanolson will we need to perform similar interpolation for the readings in the charts?

**Comment by jonathanolson** [comment]
> @jonathanolson will we need to perform similar interpolation for the readings in the charts?

Presumably yes, so the jerkiness doesn't show up there also.

**Comment by samreid** [comment]
Remaining work noted in #81, closing.
