### ISSUE TITLE
The canvas jitters when paused

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#67]
Now that we are using EventTimer, interpolation and canvas, the simulation jitters when paused:

![pulse](https://user-images.githubusercontent.com/679486/41245353-130a0c92-6d65-11e8-87c0-a103a60a8bf4.gif)

Not sure which part is causing it.  Any guesses @jonathanolson?

**Comment by jonathanolson** [comment]
Not sure at all, let me know if collaboration would help. Presumably the model and interpolation ratio don't change at all, so the Canvas would be fed the same information and display the same thing.

**Comment by samreid** [comment]
Thanks, I'll take an initial look and report back if I need assistance.

**Comment by samreid** [comment]
Fixed in e1bd5c51436cd7c9b6f9c59b29e4a738708f5a02, closing.
