### ISSUE TITLE
Prepare and deliver a stable demo version for STROBE before Sept 24

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/wave-interference#69]
@samreid @arouinfar the STROBE site visit is Sept 24-25. It would be good to have a stable "demo" for this visit. The sim certainly does not need to be fully functional, but we should probably make clear what is working and what is not to the STROBE team, and even consider hiding a screen if we feel it is too buggy or such. There is no major pressure from this issue, just tagging you both so you are aware.

Tess (who coordinates the education efforts) wrote:

> Thanks for the follow-up! Yes, the NSF has a site visit every year for STROBE. This year it will be here at CU Boulder, September 24-25. We typically have the education and research thrust leads present on the first day, focusing on the highlights from the Annual Report (the reports are due August 15). We encourage all STROBE collaborators and members to attend the presentations on the first day, but the second day is limited to the STROBE leadership and the site visit team. At this time, I do not think we will have PhET members present at the site visit, but we will highlight the Wave Sim, as well as the Berkeley Vis Tool, if there's some prototype to share by September.

**Comment by samreid** [comment]
I noticed in the comments above that the reports are due August 15.  Do you want to include the version we prepared for https://github.com/phetsims/wave-interference/issues/73 ?

**Comment by ariel-phet** [comment]
@samreid, I already included that version in the report, so thanks for getting that stable.

**Comment by samreid** [comment]
Anything else to do for this issue before it can be closed?

**Comment by ariel-phet** [comment]
I think we can close.
