### ISSUE TITLE
Labels and vertical gridlines for light

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#72]
If I keep the same vertical gridlines as for water and sounds, the light scene has odd spacing for the labels:

![image](https://user-images.githubusercontent.com/679486/41617422-ab15716c-73bd-11e8-8d28-c0f7e071e767.png)

You can test the latest version here:
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.13/phet/wave-interference_en_phet.html

Would you like to have the grid lines at different locations for the light scene, perhaps every 500nm?

**Comment by arouinfar** [comment]
@samreid I've been mocking up the viewing window as 5000 nm x 5000 nm, so I'm not quite sure why it's at 3789 nm.

![image](https://user-images.githubusercontent.com/8419308/41622006-8a8de786-73cb-11e8-89b3-fad6d0398988.png)

**Comment by samreid** [comment]
Thanks @arouinfar, it has been corrected in the aforementioned commit, closing.
