### ISSUE TITLE
Prepare a dev version for July 31

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#73]
We would like to prepare a report for google.org with a stable version.  Report is due July 31 so we would like to have a stable version in advance so it can be tested.

**Comment by samreid** [comment]
It would be great to get planes waves working for this.

**Comment by samreid** [comment]
@ariel-phet and @arouinfar can you please review https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.18/phet/wave-interference_en_phet.html and let me know what is essential to change/fix before our July 31 deadline?  I have a vacation between now and then, so I won't have a lot of time.

**Comment by arouinfar** [comment]
@samreid dev.18 seems pretty stable to me! I think we could probably share this version with google.org, but I think it would be good to also have @ariel-phet and/or @kathy-phet's sign-off.

I noticed that the wave vibrates when the sim is paused, which isn't ideal for sharing, but I realize that may take more time to address than we have.

The artwork is still a work-in-progress, but I think it's fine to share with google.org as-is.

There are a few other design tweaks that it would be nice to make, if time allows, though not critical.
* #56 - Remove Amplitude slider from Interference and Slits
* #53 - Adding time-scale information above viewing window
* #26 - Barrier and graph z-ordering

**Comment by samreid** [comment]
@arouinfar I published a new dev version here with numerous recent improvements:
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.21/phet/wave-interference_en_phet.html

Can you please check it out and see if it is reasonable for our reports?

**Comment by arouinfar** [comment]
@samreid dev.21 is looking nice! The issues above would be nice to address (though not critical) before the delivering to google.org, if time allows.

**Comment by samreid** [comment]
I published with https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.22/phet/wave-interference_en_phet.html which includes the fix for #84 and the proposed (unreviewed fix) for #86.  @arouinfar can you please test it out?

**Comment by arouinfar** [comment]
@samreid looks good to me!

**Comment by samreid** [comment]
Thanks, I'll send it along to @kathy-phet and close this issue.
