### ISSUE TITLE
Check the accuracy of d sin(θ) = mλ and document how to easily check it in the future

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#74]
For the ideal case double slit interference, maxima occur at d sin(θ) = mλ, where:

d is the distance between the centers of the slits
theta is the angle from the line between the slits
m=0,1,2,3,...
lambda is the wavelength

**Comment by samreid** [comment]
I pushed a version of the simulation that shows d sin(θ) = mλ  and d sin(θ) = (m+1/2)λ.  Here are some results:

![image](https://user-images.githubusercontent.com/679486/44609731-359a6f00-a7b6-11e8-91bc-9d05a5cf0a14.png)

![image](https://user-images.githubusercontent.com/679486/44609755-54006a80-a7b6-11e8-8d74-8cd5dbb56fa4.png)

![image](https://user-images.githubusercontent.com/679486/44609773-6a0e2b00-a7b6-11e8-8629-bf7c3a14596a.png)

![image](https://user-images.githubusercontent.com/679486/44609807-81e5af00-a7b6-11e8-817f-b503a00e7ae2.png)

I've noted this in the documentation.  @arouinfar can you take a look on phettest with `?dev` or maybe it is `&dev` and let me know your thoughts?

**Comment by arouinfar** [comment]
The `?dev` overlay for 2-slit interference is really handy! I wonder if it should be its own query parameter that we could share with teachers in the production version.

The double-slit interference is behaving nicely and the physics looks correct to me.

For the single slit, I have not been able to produce an interference pattern. Have you had any luck with that @samreid?

**Comment by samreid** [comment]
@arouinfar is this single slit diffraction?

![image](https://user-images.githubusercontent.com/679486/44961058-a6810b80-aec7-11e8-91f1-b42d62047675.png)

**Comment by arouinfar** [comment]
Yes, that's what I was looking for @samreid! Reducing the wavelength definitely does the trick. I was originally testing with red light. 

One thing I'm noticing is that there doesn't appear to be a true minimum between the primary and secondary maxima. It's more apparent when the wavelength is a bit larger.
![image](https://user-images.githubusercontent.com/8419308/45119126-b98a1a80-b117-11e8-9229-918b2846ae2f.png)

Do you have any thoughts about this @samreid?

**Comment by samreid** [comment]
I searched a bit more and found a better node here:

![image](https://user-images.githubusercontent.com/679486/45130945-19001e80-b148-11e8-9e23-908529da25c8.png)

Perhaps noise and near-field effects are obscuring this physics.  I don't know if single slit diffraction is a primary learning goal for this simulation, or if we should add a "dev" style overlay for single sit angles.  What do you recommend?

**Comment by samreid** [comment]
Labeled for design meeting to see what else remains for this issue.

**Comment by samreid** [comment]
The 2nd order maxima for single slit diffraction has a magnitude much smaller than the central (1st order) maximum:

https://en.wikipedia.org/wiki/Diffraction#Single-slit_diffraction
![image](https://user-images.githubusercontent.com/679486/45171509-cf531a80-b1bf-11e8-894a-2450ca74e9e8.png)

**Comment by arouinfar** [comment]
@samreid correct, but there should be regions of zero intensity between the maxima. The screenshots in https://github.com/phetsims/wave-interference/issues/74#issuecomment-417962167 and https://github.com/phetsims/wave-interference/issues/74#issuecomment-418871145 don't have very clear minima.

**Comment by samreid** [comment]
> Perhaps noise and near-field effects are obscuring this physics.

Another possibility is interference from reflections at the boundaries of the lattice (which we haven't been able to eliminate completely).

**Comment by samreid** [comment]
We'll take the time to quantitatively check the single slit equation with an overlay.

**Comment by samreid** [comment]
Outstanding work tracked in aforementioned issues, closing.
