### ISSUE TITLE
The barrier jumps when grabbed

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#75]
I'm using DragListener like so:

```js
    this.addInputListener( new DragListener( {

      // TODO: with this line, the barrier jumps a bit on drag, but without it, it is off by hundreds of pixels
      // TODO: work with @jonathanolson to figure out how to resolve this

      // TODO: AR will mock up a handle, such as a lollipop beneath the barrier.
      applyOffset: false,
      locationProperty: model.barrierLocationProperty,
      transform: this.modelViewTransform
    } ) );
```

But when the barrier is grabbed, it jumps to the side.  @jonathanolson can you help?

**Comment by samreid** [comment]
![movie](https://user-images.githubusercontent.com/679486/42114407-39585278-7bac-11e8-9f6f-c7ddd2de5216.gif)

**Comment by samreid** [comment]
In the preceding commit, I removed a workaround that was offsetting the barrier by a cell to try to compensate for the drag handler issue.  The problem is a bit more pronounced now--what would be best is to drag based on deltas, not absolute location, and that's what I could use help with.

**Comment by jonathanolson** [comment]
Maybe this would be good to collaborate on? I'm not sure why applyOffset is false, and working together would be the most helpful to resolve this.

**Comment by samreid** [comment]
On hold until I schedule a meeting to collaborate with @jonathanolson.

**Comment by samreid** [comment]
Fixed with @jonathanolson's help, closing.
