### ISSUE TITLE
Should DoubleHeadedArrowWithBarsNode be moved to scenery-phet?

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#79]
While working on #78, I wondered if DoubleHeadedArrowWithBarsNode should be moved to common code.  It renders the double headed arrow with bars for the scale representation, such as:

![image](https://user-images.githubusercontent.com/679486/42720691-77cee754-86e9-11e8-8d6e-641a2deb41d1.png)

@ariel-phet or @arouinfar any suggestions whether this will be used in other sims, or should just be defined for this sim?

**Comment by andrealin** [comment]
There is a similar type in graphing-lines (already published), called DimensionalArrowNode.js

**Comment by arouinfar** [comment]
@samreid I've also used this same scale bar in [Coulomb's Law](https://bayes.colorado.edu/dev/html/coulombs-law/1.0.0-dev.17/phet/coulombs-law_en_phet.html).

**Comment by arouinfar** [comment]
Ack, I accidentally hit enter. @samreid please disregard until I edit my previous comment and delete this one.

**Comment by pixelzoom** [comment]
Why so many options? Isn't it advantageous to standardize on what dimensional arrows look like?  The type of tip (solid vs stroked) seems particularly gratuitous.

**Comment by samreid** [comment]
For the record, the critical feature in Wave Interference was to be able to precisely control the distance between the centers of the bars at the end of the arrowheads.

**Comment by samreid** [comment]
@arouinfar says "scale indicator" arrows should usually be filled--they are small arrows and look better as filled instead of open arrows.

@kathy-phet points out that in some places, the arrows will need to be lined (open).

Dashed vs solid line between arrowheads is an important feature to keep.

**Comment by samreid** [comment]
We may discuss on Thursday the possibility of ES6 code in common repos, see https://github.com/phetsims/wave-interference/issues/24#issuecomment-414791935

**Comment by pixelzoom** [comment]
Are we discussing because there's an ES6 implementation of this that needs to be moved to common code? I didn't think we even had the requirements nailed down yet.

**Comment by samreid** [comment]
> Are we discussing because there's an ES6 implementation of this that needs to be moved to common code? I didn't think we even had the requirements nailed down yet.

We are still working on the requirements, but since ScrollingChartNode uses DoubleHeadedArrowNode this conversation pertains: https://github.com/phetsims/wave-interference/issues/24#issuecomment-414791935

**Comment by samreid** [comment]
It seems the important part is being able to set one or more bars at the right centered locations, then being able to position arrows based on the locations of the bars.

Also, in Masses and Springs, this bar is not centered on its reference line:

![image](https://user-images.githubusercontent.com/679486/44628928-30e4d080-a906-11e8-8a59-2e950839820d.png)

**Comment by samreid** [comment]
A type definition like https://github.com/phetsims/wave-interference/blob/f116b8b2d3f1aa7731d3866fe5d796916734e9bc/js/common/view/DoubleHeadedArrowWithBarsNode.js is inflexible.  It is hard-coded to use Line and ArrowNode, and has a clumsy way to pass options through to those type.  A dependency-injection approach would be much more flexible (where the nodes are passed in instead of created by DoubleHeadedArrowWithBarsNode) provides clients with full generality.  However, a dependency-injection approach reveals that the logic provided by DoubleHeadedArrowWithBarsNode is trivial: space two nodes and put another between them.  I don't think we need to factor out an implementation for this, and we should leave it to our design teams to encourage consistent design for this kind of component.

For example, see the change in ScrollingChartNode.js in the preceding commit.  It is clearer how the options pass through to the Line and ArrowNode types, and only adds a 3 lines of code to get full generality and clarity (and we are able to eliminate 66 lines of DoubleHeadedArrowWithBarsNode.js).

Another way of phrasing this issue: we have had many discussions about how to properly pass through options to subcomponents.  The idea proposed here is to pass through the subcomponent itself instead of passing through options and hardcoding a type to be instantiated.

Since this logic is applicable elsewhere, I'm inclined to discuss this at developer meeting.  In particular, it will be important to decide where to draw the line: when should we use this pattern?

**Comment by samreid** [comment]
Self-assigning to clean up and close this issue and open a separate issue for discussion about dependency injection.

**Comment by pixelzoom** [comment]
As a less awkward name for this, how about DimensionalArrows?

**Comment by samreid** [comment]
This comment https://github.com/phetsims/wave-interference/issues/79#issuecomment-416045828 argues that we do not need a type for this.  I'm planning to close this issue and open a new issue for developer meeting discussion about using dependency injection in cases like this.

**Comment by pixelzoom** [comment]
Got it.

**Comment by samreid** [comment]
I created a new issue for discussion, closing this one since Wave Interference is all set.
