### ISSUE TITLE
FFT performance on iPad is poor

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#8]
At 256x256 the diffraction FFT and rendering is very slow on iPad2 (several seconds) and realtime updates while dragging the slider are not possible.  It may be possible to run this computation on the GPU to improve performance, but it would likely take several weeks to port the FFT to run in WebGL (if it is possible at all).  We can cut the resolution to 128x128 on iPad, but I expect that will look pretty blurry and may still have inadequate performance.

@ariel-phet how would you like to proceed?

**Comment by ariel-phet** [comment]
@samreid would it be possible to have a "mode" we use on certain platforms were the update is not realtime? As we discussed before the update happens on release of the slider (so moving the slider turns the diffraction pattern blank and a then the new diffraction pattern comes into place when the slider is released)

It would be good to verify if this is also an issue on iPad Air. At some point, likely after next summer there is a good chance we will be dropping iPad2 support anyhow.

**Comment by samreid** [comment]
@ariel-phet said it is probably we will drop iPad2 support in the summer.  We would go to whatever minimum hardware could run iOS 10 (whether iPad mini, etc)

**Comment by samreid** [comment]
We discussed iPad2 support yesterday, it seems our website is <1% iOS9 and our iOS app is <10% iOS9 (if I heard that correctly).

**Comment by samreid** [comment]
Labeled for design meeting to discuss performance.  I'll bring an iPad2.  @arouinfar or @ariel-phet would you like to bring an iPad 4+ ?

**Comment by arouinfar** [comment]
@samreid I can bring an iPad Air.

**Comment by samreid** [comment]
During our review, performance on the iPad air was low.  I'm seeing around 4fps while dragging a slider on this screen.  Some possibilities:

1. Reduce the size of the canvas
2. Could we hollywood an algorithm that would look as correct but run faster?

It seems we should investigate the canvas size first.

**Comment by samreid** [comment]
If we end up hollywooding many-slit diffraction in #9, will we also want to hollywood the other apertures as well?

**Comment by samreid** [comment]
I tried running the same FFT algorithm at 128x128 (previously was 256x256) and it got around 22fps on iPad Air for squares and 9fps for circles.  In my opinion, this seemed responsive enough for squares.  

To test the hypothesis that the extra time was spent in rendering the secondary circle canvas, I omitted the calls that painted it to the secondary (displayed) canvas, but the frame rate remained at 10fps.  This suggests the extra time is being spent in evaluations of the gaussian function across the lattice.

Instead of creating a gaussian and evaluating FFT, we could just try evaluating the Airy function directly for the circle case.  Perhaps I should investigate that in case it is easy, though we wouldn't be able to reuse that logic for the "blob" case.  Will the blob case have free parameters?

@arouinfar @ariel-phet any thoughts before I get too far into this?

**Comment by samreid** [comment]
I estimated 2-4 hours to test the Airy disk using a 3rd party library.  We'll investigate, but if it doesn't work, that's OK. 

We'll start with radius only (only 1 control for circle--no ellipse).

**Comment by samreid** [comment]
I wrote on slack: 

Sam Reid [8:38 AM]
For Wave Interference, I would like to use the Bessel function to show diffraction for the circular aperture.  I saw this library https://github.com/SheetJS/bessel which is open source listed as Apache 2.0.  Is that compatible with our licensing?  Or is there a better way to evaluate or approximate the bessel function?

**Comment by samreid** [comment]
Also, I wonder if it would be possible to just use an Airy Disk raster and stretch it, instead of dynamically computing it each time?  The same could be possible for rectangles.  This would give great performance as well as having a simpler implementation (as long as it is accurate).

**Comment by samreid** [comment]
Reviewing the existing implementation of FFT for rectangles, it seems scaling would work OK.  I'm planning to investigate this.

**Comment by samreid** [comment]
I published a version that shows scaled (fast) and fft (slow) results side by side.  They look qualitatively similar:
![image](https://user-images.githubusercontent.com/679486/46448520-7e91fb80-c744-11e8-9a6a-72662b8ef0c8.png)

**Comment by samreid** [comment]
@arouinfar I'd like to continue investigating this avenue for the circular aperture, but can you please check the preceding dev link to make sure it seems reasonable to you?

**Comment by samreid** [comment]
Generating a circular aperture at 20 and scaling to 4 loses a lot of the dynamics:
![image](https://user-images.githubusercontent.com/679486/46451011-899f5880-c751-11e8-96f5-a3796a32ca51.png)

I'll test restricting the range to 10

**Comment by arouinfar** [comment]
@samreid I'm not sure I follow your last few comments. Can we chat about this for a few minutes sometime tomorrow?

**Comment by samreid** [comment]
In discussion with @arouinfar, we decided that scaling images seems like a reasonable approach.  We will need a design meeting to determine the ranges and whether we will need snapshots at multiple resolutions.

**Comment by samreid** [comment]
By the same token, for the asymmetric or symmetric shapes, we may be able to use an image or a set of images rather than computing FFTs on the client machine.  I'll plan to leave the FFT code in, in case we used that for generating images, but we won't plan on running this on client machines.

**Comment by samreid** [comment]
iPad Air 2 running a built version with ?screens=4 is currently giving 35fps for circle/square scenes.  6fps for the circle-diamond scene.  6fps for the lattice disorder scene.  16fps for the waving girl scene.

We moved to a faster FFT implementation in #346 which likely explains most of these speed-ups.  Based on design considerations, we will not be able to use image processing to simulate the FFTs.  However, I noted the improved speed for the waving girl compared to the circle-diamond and lattice disorder scene.  It will be possible to use the canvas approach from the waving girl scene for the other scenes.  I will open a new issue for investigation of that.
