### ISSUE TITLE
Add audible sound to the simulation

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#80]
From https://github.com/phetsims/wave-interference/issues/42#issuecomment-406598296

The Java version has audible sound.  It seems like a good idea to add audible sound to this simulation, but we haven't discussed that much yet.

May 17, 2018

> If we follow Java design, sound will play tones -- discrete range would sound very strange.

A reason to discuss this issue now is because it pertains to the units we choose for the sound scene.  @arouinfar any thoughts?

**Comment by samreid** [comment]
Sam Reid [12:39 PM]
Good day sir!

I am working on getting the scale correct for Wave Interference and would like to know what is a good range of pitches for the sonification.
For instance, I think we were planning on A4=440Hz as a lower bound, but what do you think will sound good from a pitch perspective?
We are picturing just a sine wave

John Blanco [12:42 PM]
Decent, yes.  We don't have good guidelines yet, but I've also done things starting an octave lower, i.e. 220 Hz, to get more range, and it seemed to work okay.  So if you need it, you can try that.

Sam Reid [12:43 PM]
How high should we go?

John Blanco [12:44 PM]
It depends on how long the tone will play.  Sine waves start to sound annoying pretty quickly, and the higher it goes the more that is felt.  How about we start with an upper bound around 2k, and go from there.

**Comment by samreid** [comment]
Following https://pages.mtu.edu/~suits/notefreqs.html, here are the corresponding wavelengths in cm:

A3 | 220.00 | 156.82
A6 | 1760.00 | 19.60

**Comment by samreid** [comment]
Maybe a good corresponding wave area would be 1000cm?  Or 500cm?

**Comment by arouinfar** [comment]
@samreid after seeing the screenshot in https://github.com/phetsims/wave-interference/issues/42#issuecomment-406598296, I've realized that I've clearly made an error when deciding the scale bar would represent 10 cm.

I think a range of A3-A6 could have some scaling issues at the extremes. A range of A3-A5 (880 Hz, 39.2 cm) would allow for quadrupling f, but is easier to deal with scale-wise. I would recommend a wave area of 500 cm, with a scale bar of 50 cm.

@samreid we should probably have a discussion about adding audio to the sound scene before you start implementation. It would be good to make sure we're all on the same page, as well as iron out the goals.

**Comment by samreid** [comment]
We selected the units for the sound scene in #42.

@ariel-phet and @arouinfar pointed out that we should only have sound in screen 1 (no interference) or should have a movable microphone.

@ariel-phet said OK to leave audio out of the sim for version 1, we can visit it in the future for sonification, a11y, etc.

If we use microphone, we could use a "sinusoidal regression" to determine the amplitude/frequency, or maybe take the frequency from the sources.  Also important not to regress while moving the mic, since it will be "noisy".

We'll defer for now, we can decide when we get closer to publication.

**Comment by arouinfar** [comment]
In #343 @oliver-phet reported a related user request:

> I love the new wave interference Phet simulation and assigned it to my students last week. The light wave patterns are clearly visible as are the water wave patterns and students can totally get the interference patterns created. However, it would be GREAT if there was a speaker option for the sound wave generator so they could HEAR the difference between constructive and destructive interference patterns. I've seen this tool in other sims you have created.

**Comment by samreid** [comment]
Labeling for meeting:design to see if we want this feature for 2.0

**Comment by samreid** [comment]
We have begun sonification instrumentation in other issues.  The only facet of this issue not captured elsewhere is:

> However, it would be GREAT if there was a speaker option for the sound wave generator so they could HEAR the difference between constructive and destructive interference patterns. I've seen this tool in other sims you have created.

I'll open a specific issue for that.
