### ISSUE TITLE
Use EventTimer interpolation for the charts

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#81]
From #65, we need to use interpolation for the charts.

**Comment by jonathanolson** [comment]
Is the behavior of the sim different (say, on Chrome on a good desktop) if you replace a `step( dt ) ` with `_.times( 10, () => step( dt / 10 ) )`? (If you run 10 smaller steps, presumably it just uses more CPU and shouldn't change the behavior of the sim)

**Comment by samreid** [comment]
I went all the way out to `_.times( 1000000, () => this.eventTimer.step( dt/1000000 ));` in WavesScreenModel.step and the behavior was the same.  Closing.
