### ISSUE TITLE
Reduce size of play/pause/next frame by 25%

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#82]
The barrier drag handle added in #76 is pretty tight with play/pause.
![image](https://user-images.githubusercontent.com/8419308/43179494-832a72e4-8f90-11e8-9766-ced9508ff235.png)

The playback controls are actually quite large. Compare to, Pendulum Lab, for example:
![image](https://user-images.githubusercontent.com/8419308/43179509-92650e72-8f90-11e8-8cf7-0febe4929c5d.png)

@samreid can you reduce the size of play/pause and next frame by 25%?

**Comment by samreid** [comment]
@arouinfar, I reduced the size to 0.75, can you please review on phettest?

**Comment by arouinfar** [comment]
Looks great, thanks!
