### ISSUE TITLE
Pulse button releases multiple pulses at a time

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#84]
Observed in dev.21, but was behaving normally in dev.18. Would be good to fix before delivering to google.org #73.

When pressing the button on the wave source, it stays depressed and releases ~6 pulses before turning itself off. Seems like the timing on the momentary button is off. @samreid can you investigate?

**Comment by samreid** [comment]
Good catch @arouinfar, this bug was introduced during #77 and should be fixed after the pushed commits above.  Can you please review on phettest?

**Comment by arouinfar** [comment]
Looks good!
