### ISSUE TITLE
Increase width of TimerNode so it can handle an additional digit

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#85]
TimerNode cannot handle times larger than 99.99, which seems a bit too small. @samreid can you increase the width so it can support another digit? This is not critical for the google.org report.
![image](https://user-images.githubusercontent.com/8419308/43231822-38d3a990-902b-11e8-840f-069ce86add62.png)

**Comment by samreid** [comment]
I added an option that allows you to specify `maxValue`, so it currently looks like this at its max value:

![image](https://user-images.githubusercontent.com/679486/43922745-d8475136-9bdc-11e8-9a42-64b4b5caedac.png)


We'll be discussing other TimerNode layout issues in https://github.com/phetsims/wave-interference/issues/94 and https://github.com/phetsims/wave-interference/issues/45, closing this one.
