### ISSUE TITLE
Wave Detector reads outside of viewing window

### ISSUE THREAD

**Issue by arouinfar** [phetsims/wave-interference#86]
The probes are reading way beyond the visible boundaries of the wave.

![image](https://user-images.githubusercontent.com/8419308/43231674-946c8eda-902a-11e8-9bf3-e88b3e4f9cec.png)

**Comment by arouinfar** [comment]
@samreid this would be nice to address for #73, if time allows.

**Comment by arouinfar** [comment]
Thanks @samreid. I think a reasonable constraint would be to require the center-point of the probe to overlap with the viewing window.

The top and left boundaries are looking good (probe reads until the halfway point), but the bottom and right boundaries are a bit off (probe doesn't require much overlap to read).
![image](https://user-images.githubusercontent.com/8419308/43410663-e477c936-93e4-11e8-8b72-24f1caab6fab.png)
![image](https://user-images.githubusercontent.com/8419308/43410735-28841a08-93e5-11e8-8e6e-1133a95fd7f3.png)

**Comment by samreid** [comment]
Thanks, there was an extra cell included in the bottom and right edge, I removed it in the preceding commit, can you please review?

**Comment by samreid** [comment]
I published a dev version with the proposed fix: https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.22/phet/wave-interference_en_phet.html

@arouinfar can you please test it out?

**Comment by arouinfar** [comment]
👍
