### ISSUE TITLE
It is difficult to see 0-value nodes

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#89]
Even searching a rather large window, it is difficult to find a spot that has a true zero.  For instance:

![image](https://user-images.githubusercontent.com/679486/43610870-a807e42c-9664-11e8-9fe4-409b7c63333b.png)

This may be due to the granular nature of the lattice.  

@kathy-phet suggested adding a `?dev` overlay that shows the true values for d sin (theta) = m lambda.  I was concerned about that working in the near field, and that even if it did show us the theoretical minimum for the wave, we would still see oscillation due to the nature of the lattice.

For waves like in the screenshot above, it seems like averaging over a spatial and/or temporal window might help.

@arouinfar or @ariel-phet any other ideas about how to proceed?

**Comment by ariel-phet** [comment]
@samreid I actually do not think this is an issue. If you look at the following case, it is quite close to zero, I think you really need to look in the farfield.

![zero](https://user-images.githubusercontent.com/4051174/43654490-9e6d1a46-9708-11e8-81db-f8026b7902c0.PNG)

**Comment by ariel-phet** [comment]
In addition, moving the spherical staring point further to the left (closer to the source) I think will help

**Comment by arouinfar** [comment]
@samreid @kathy-phet, I tend to agree with @ariel-phet on this one. The behavior seems reasonable along the nodes, so long as there is a bit of distance from the sources.

![image](https://user-images.githubusercontent.com/8419308/43744780-f1b1b012-9998-11e8-8229-e7da811f3c9d.png)

> For waves like in the screenshot above, it seems like averaging over a spatial and/or temporal window might help.

@samreid I'm a bit hesitant when it comes to tinkering with the model, because the sim isn't technically wrong.

> In addition, moving the spherical staring point further to the left (closer to the source) I think will help

Agreed @ariel-phet. I believe we decided to move the starting point a bit further to the left a few design meetings ago.

**Comment by kathy-phet** [comment]
OK. I do find it pretty hard to get the node to be that flat. (I'll show you next time we are together, maybe its harder on my machine for some reason, or maybe I am just bad at it).

**Comment by samreid** [comment]
@ariel-phet recommendation is to defer for 1.0, @kathy-phet said that sounds reasonable.  

@samreid said it would only take 1-2 hours to try a spatial sampling/averaging window, which might "wash out" these effects and show a better zero.

Perhaps we'll revisit when we are closer to publication?

**Comment by arouinfar** [comment]
I should probably say something about this in the Teacher Tips, so adding `design:teaching-resources`. I'll untag once it comes time for a general Teacher Tips issue.

**Comment by samreid** [comment]
In https://github.com/phetsims/wave-interference/issues/74#issuecomment-415893775 I created a `?dev` overlay that shows the theoretical minima/maxima.  Putting on hold until https://github.com/phetsims/wave-interference/issues/96 is addressed, then we can re-evaluate.

**Comment by samreid** [comment]
@arouinfar can you please advise for this issue?  Can it be closed?

**Comment by arouinfar** [comment]
Yes, let's close this one @samreid.
