### ISSUE TITLE
Choppy or irregular behavior in the lattice and wave detector plot

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#90]
@kathy-phet reported choppy/irregular behavior in the lattice and wave detector.  She reported that the problem is difficult to reproduce, but may be correlated to whether the computer is doing other CPU intensive tasks.  @arouinfar or @ariel-phet have you seen anything like this?  Should we run it past QA to see if they can replicate something like that?

**Comment by arouinfar** [comment]
@samreid this is not something I've encountered on my machine (Mid 2014 MacBook Pro running macOS 10.13.6). @ariel-phet have you run into any choppy behavior?

**Comment by ariel-phet** [comment]
All looking pretty good for now. Closing.
