### ISSUE TITLE
Move the source on the lattice to the left

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#96]
From https://github.com/phetsims/wave-interference/issues/89 we would like the lattice source to be further to the left.

**Comment by samreid** [comment]
The previous value was 10 cells from the edge, I moved it to 4 cells from the edge.  This is close to the edge but far enough away that you can see the wave is circular.

@arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
I think it looks quite nice @samreid! 

I know @ariel-phet had some thoughts about the source point, so I think it'd be good to quickly review this issue in design meeting to get a :+1: from other team members.

**Comment by samreid** [comment]
@ariel-phet recommends 1 more cell to the left.  I'll do so and run it past the design team.

**Comment by samreid** [comment]
I moved the water drops and emitter location another cell to the left and published a dev version:
https://phet-dev.colorado.edu/html/wave-interference/1.0.0-dev.25/phet/wave-interference_en_phet.html

Note the hose location was not updated and will not be updated until we have new artwork, see https://github.com/phetsims/wave-interference/issues/104.  @arouinfar @kathy-phet @ariel-phet can you please review and comment?

**Comment by ariel-phet** [comment]
@samreid The wave still looks obviously spherical to me. It looks to me like it could go even another cell left. Basically as long as the wave looks just a hair over hemispherical at the left side I think we are in good shape of giving the impression of a spherical wave.

**Comment by kathy-phet** [comment]
I think it is in a good place right now. I looked at how much it shifted from the last time, and if it shifted that far over again, I think it would be too far and the drop would start to crowd the left hand side with very little negative space there for the drop. And would get to see less of the sphere part of the wave. So I am in favor of leaving it here.

**Comment by arouinfar** [comment]
I agree with @kathy-phet. The wave is still looking nice and spherical, but I think moving it an extra cell to the left may be taking it a bit too far. 

4 cells:
![image](https://user-images.githubusercontent.com/8419308/45061707-e9c3b180-b062-11e8-9a10-329bf84983df.png)


3 cells:
![image](https://user-images.githubusercontent.com/8419308/45061718-f2b48300-b062-11e8-93e0-0cf01abec85d.png)




Let's leave it at 3 cells @samreid.
