### ISSUE TITLE
Finalize the design for the diffraction screen

### ISSUE THREAD

**Issue by samreid** [phetsims/wave-interference#99]
See also #7 and #9, @arouinfar can you please review the status of the diffraction screen and work on completing the design, or identifying what remains to be done?

**Comment by samreid** [comment]
Cross labeling for design meeting in case that's the best place to discuss it.

**Comment by samreid** [comment]
I'll be moving notes from https://github.com/phetsims/wave-interference/issues/7 to here and closing https://github.com/phetsims/wave-interference/issues/7.

- [ ] hard edge on bottom left image instead of showing gaussian there (but do show it in top left image). Even though we will still use gaussian for the model.
- [ ] Start with a circle where you just change the radius. Maybe we can get rid of the ellipse?
- [ ] slider by the laser to set wavelength, visible region only.  This can be implemented by tuning the aperture in the model but leaving the view aperture fixed.  
- [ ] show scale, perhaps between or below the squares

I'm not sure about the accuracy of several of these. For the first item, I don't know why we would show the gaussian in the top left image.  The ellipse in the current version works well in my opinion, matches nicely with the rectangle, and you can still reach learning goals of circle radii.

**Comment by samreid** [comment]
@arouinfar can you please check in on the status of this issue and the design of the diffraction screen?

**Comment by arouinfar** [comment]
The design for the diffraction screen has been discussed in a few design meetings now, and the design is specified in the design doc. Now that #139 has been addressed, I don't think there is anything outstanding that would require this issue to remain open.
